### ISSUE TITLE
Zip task can't copy files into different directories

### ISSUE THREAD

**Issue by otros-systems** [gradle/kotlin-dsl#1008]
When using zip task, all files are packed into last directory configured with `into`

My zip task: https://github.com/otros-systems/gradle-kotlindsl-ziptask/blob/master/build.gradle.kts

```
tasks {
    // Use the native JUnit support of Gradle.
    "appdist"(Zip::class) {
        baseName = "AppDist"
        val baseDir = "$baseName-$version"

        into("lib").from(project.configurations.runtime)

        into(baseDir)
                .from(project.file("src/dist/otherFiles"))
                .from(project.file("src/dist/scriptsWin"))
                .from(file("src/dist/scriptsUnix")) { fileMode = 755 }
        
    }.dependsOn("jar")
}
```
If I put `into("lib").from(project.configurations.runtime)` after `into(baseDir)`, all files will be in `lib` folder.

### Expected Behavior

Files are copied into specified directories

### Current Behavior

When using zip task, all files are packed into last directory configured with `into`

### Steps to Reproduce (for bugs)

clone repo: https://github.com/otros-systems/gradle-kotlindsl-ziptask
run: ` ./gradlew appdist; unzip -t build/distributions/AppDist-1.1.zip`

```
➜  gradle-kotlindsl-ziptask git:(master) ✗ ./gradlew appdist; unzip -t build/distributions/AppDist-1.1.zip 

BUILD SUCCESSFUL in 0s
3 actionable tasks: 3 up-to-date
Archive:  build/distributions/AppDist-1.1.zip
    testing: AppDist-1.1/             OK
    testing: AppDist-1.1/guava-26.0-jre.jar   OK            => All jars should be in ./lib folder
    testing: AppDist-1.1/jsr305-3.0.2.jar   OK
    testing: AppDist-1.1/checker-qual-2.5.2.jar   OK
    testing: AppDist-1.1/error_prone_annotations-2.1.3.jar   OK
    testing: AppDist-1.1/j2objc-annotations-1.1.jar   OK
    testing: AppDist-1.1/animal-sniffer-annotations-1.14.jar   OK
    testing: AppDist-1.1/logback.xml   OK
    testing: AppDist-1.1/app.bat      OK
    testing: AppDist-1.1/app.sh       OK

```

### Your Environment

 * Build scan URL:  https://scans.gradle.com/s/2qfdbg342wa6o/

**Comment by StefMa** [comment]
I tested it with the Groovy DSL too.
Same behavior.
I don' think it is a Kotlin DSL issue.

Beside of that.
Who says that you can use multiple `into`?

**Comment by eskatos** [comment]
@StefMa is right!

Please use the [Gradle Forums](https://discuss.gradle.org/) for general questions.
