### ISSUE TITLE
Projects with mixed Groovy and Kotlin scripts are cumbersome and error prone to set up

### ISSUE THREAD

**Issue by ldaley** [gradle/kotlin-dsl#1022]
### Expected Behavior

Users should be able to rename a _project_ build script to have the .kts extension and things just work.

### Current Behavior

Users need to opt in to Kotlin for project build scripts via settings, which is cumbersome and error prone. 

### Context

At best, everyone is going to need to solve this boilerplate problem themselves. At worst, many users are going to probe the filesystem for this, which is a performance killer.

**Comment by eskatos** [comment]
@ldaley there's no opt-in in settings to enable the use of `.gradle.kts` scripts

Are you referring to the case where a build diverges from the default project script name and then one need to distinguish Groovy and Kotlin scripts explicitly? Like in https://github.com/gradle/gradle/blob/dd3e28584484fe44ca19f9d25b794d464aef800c/settings.gradle.kts#L110-L184

**Comment by ldaley** [comment]
IIUC, Gradle will use `build.gradle` unless you tell it to use something else (like `build.gradle.kts`). This means that there has to be logic somewhere to know whether a project's script is Kotlin or not. People are going to do this “dynamically” and probe for the existence of files, which is slow.

**Comment by JLLeitschuh** [comment]
@ldaley If you have a `build.gradle.kts` file, gradle will automatically pick that up without needing to specify the build file in a `settings.gradle` file.
It used to be the case you needed to opt-in, but those days are far behind us.

**Comment by eskatos** [comment]
After discussing this with @ldaley we understood it was an issue about some testing environment on his end. The Gradle Kotlin DSL is doing the right thing. Closing as invalid.
