### ISSUE TITLE
ObjectFactory should be able to instantiate types with a no-arg ctor and no @Inject annotation

### ISSUE THREAD

**Issue by JLLeitschuh** [gradle/kotlin-dsl#1028]
If I want to use the `ObjectFactory` to create an instance of a kotlin object, I need a single noarg constructor annotated with `@Inject`.

For classes where I want properties to be in the constructor of the object this requires you to jump though extra hoops like the following:
```kotlin
open class CustomPasswordCredentials
constructor(
    @get:Internal
    private var user: String? = null,
    @get:Internal
    var pass: String? = null
) : PasswordCredentials {

    @Inject // I shouldn't need to specify an additional constructor like this
    constructor(): this(null, null)

    override fun setUsername(userName: String?) {
        user = userName
    }

    @Input
    override fun getUsername(): String? {
        return user
    }

    @Input
    override fun getPassword(): String? {
        return pass
    }

    override fun setPassword(password: String?) {
        pass = password
    }
}
```

Kotlin 1.0.6 introduced the `kotlin-noarg` plugin that allows you have entities annotated with some annotations to automatically have the noarg constructor get generated allowing them to be used by a DI framework like the one Gradle utilizes.

**Comment by eskatos** [comment]
This opens the question of what annotation to use to trigger the `kotlin-noarg` compiler plugin, what would be its meaning, use etc.. ?

`kotlin-dsl plugin should apply the kotlin-noarg plugin` isn't the solution, just that wouldn't be enough. Could you please rephrase the issue title so it's more about what than how?

**Comment by JLLeitschuh** [comment]
@eskatos Is that a bit better now?

**Comment by eskatos** [comment]
@JLLeitschuh 💯 thanks!

**Comment by eskatos** [comment]
A more general solution might be to allow Gradle to instantiate types without the `@Inject` annotation. If that was the case your sample type could be fixed adding `@JvmOverloads` to the ctor.

Something like that would work:
- unless there's an `@Inject` annotation, use the no-arg constructor
- if there's a single `@Inject` annotation, use the annotated constructor
- in any other case, fail

**Comment by eskatos** [comment]
Issue moved to [gradle/gradle #7645](https://github.com/gradle/gradle/issues/7645) via [**ZenHub**](https://www.zenhub.com/)
