### ISSUE TITLE
Effective Java Point 1: factory methods instead of constructors (*Scope classes)

### ISSUE THREAD

**Issue by JLLeitschuh** [gradle/kotlin-dsl#1030]
## The Problem

By exposing constructors in the API you are coupling API consumers to creating new instances of objects.

There are several places across the Kotlin DSL API where constructors are exposed in the public API instead of static factory methods.

For example:
```kotlin
/**
 * Receiver for [NamedDomainObjectContainer] configuration blocks.
 */
class NamedDomainObjectContainerScope<T : Any>(
    private val container: NamedDomainObjectContainer<T>
) : NamedDomainObjectContainer<T> by container, PolymorphicDomainObjectContainer<T> {
    // ...
```

Even though you haven't exposed an API coupling to the constructor, you've exposed a binary coupling to the constructor call.

If you want to convert the `NamedDomainObjectContainerScope` to an interface, you can't because that would be a binary API breaking change.

## The Fix

Expose `invoke` methods on companion objects instead.
The API looks exactly the same, (as if a new object were being created), but you have prevented the coupling to the constructors in your consumers code.

```kotlin
/**
 * Receiver for [NamedDomainObjectContainer] configuration blocks.
 */
class NamedDomainObjectContainerScope<T : Any>
private constructor(
    private val container: NamedDomainObjectContainer<T>
) : NamedDomainObjectContainer<T> by container, PolymorphicDomainObjectContainer<T> {
    companion object {
        operator fun invoke(container: NamedDomainObjectContainer<T>) = 
            NamedDomainObjectContainerScope(container)
    }
```

With this simple change any plugin's code is no longer tied to the `init` bytecode instruction expecting a new object to be constructed.

If you need to later change `NamedDomainObjectContainerScope` to an interface, you can do so easily by simply leaving the `companion object` on the interface.

**Comment by eskatos** [comment]
Done in #1180
