### ISSUE TITLE
Gradle 4.10-rc1 can't resolve dependency kotlin-scripting-compiler-embeddable

### ISSUE THREAD

**Issue by tagantroy** [gradle/kotlin-dsl#1033]
After upgrade to Gradle 4.10-rc1 i faced with this problem while gradle sync:
```
Execution failed for task ':buildSrc:compileKotlin'.
> Could not resolve all files for configuration ':buildSrc:kotlinCompilerPluginClasspath'.
   > Could not find org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:1.2.60.
     Searched in the following locations: file:/Users/ivan.balaksha/.gradle/caches/4.10-rc-1/embedded-kotlin-repo-1.2.60-2/repo/org/jetbrains/kotlin/kotlin-scripting-compiler-embeddable/1.2.60/kotlin-scripting-compiler-embeddable-1.2.60.jar
     Required by:
         project :buildSrc
   > Could not find org.jetbrains.kotlin:kotlin-sam-with-receiver:1.2.60.
     Required by:
         project :buildSrc
```
Link to demo project: https://github.com/Malinskiy/marathon/pull/84

**Comment by eskatos** [comment]
With Kotlin 1.2.60, the Kotlin Gradle Plugin driving the kotlin compiler requires extra dependencies that aren't required by Gradle Kotlin DSL scripts alone and aren't embedded into Gradle.

This can be fixed by adding a repository that contains Kotlin compiler dependencies:
```kotlin
repositories {
    jcenter()
}
```
In your case it should go into `./buildSrc/build.gradle.kts`

**Comment by tagantroy** [comment]
@eskatos thank you. Solved.

**Comment by AlexCzar** [comment]
I think this should be added to release notes. Just wasted half an hour on on troubleshooting and then found this issue.

**Comment by Asad-Khan-Aasanjobs** [comment]
Thanks, @eskatos 
I seem to have missed this part when reading about upgrading to Gradle 4.10

**Comment by wuchengithub** [comment]
> With Kotlin 1.2.60, the Kotlin Gradle Plugin driving the kotlin compiler requires extra dependencies that aren't required by Gradle Kotlin DSL scripts alone and aren't embedded into Gradle.
> 
> This can be fixed by adding a repository that contains Kotlin compiler dependencies:
> 
> ```kotlin
> repositories {
>     jcenter()
> }
> ```
> 
> In your case it should go into `./buildSrc/build.gradle.kts`

big big big help!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by ellykits** [comment]
cool thanks a lot!

**Comment by jcornaz** [comment]
Thank you very much @eskatos. Please write it down in the documentation.

**Comment by eskatos** [comment]
@jcornaz it is documented here https://docs.gradle.org/current/userguide/kotlin_dsl.html#sec:kotlin-dsl_plugin

**Comment by hereisderek** [comment]
> With Kotlin 1.2.60, the Kotlin Gradle Plugin driving the kotlin compiler requires extra dependencies that aren't required by Gradle Kotlin DSL scripts alone and aren't embedded into Gradle.
> 
> This can be fixed by adding a repository that contains Kotlin compiler dependencies:
> 
> ```kotlin
> repositories {
>     jcenter()
> }
> ```
> 
> In your case it should go into `./buildSrc/build.gradle.kts`

I have added the line but still get the error

https://github.com/hereisderek/android-util/tree/f06b5b9b4ae859e61b8d27b7e099a12d770a5377
