### ISSUE TITLE
1.0.0-rc-3: Missing NamedDomainObjectContainer.registering(action) overload

### ISSUE THREAD

**Issue by mkobit** [gradle/kotlin-dsl#1042]
```kotlin
val a by configurations.registering
```

works but

```kotlin
val a by configurations.registering {
}
```

does not.

### Current Behavior

Have to declare, then configure:

```kotlin
val a by configurations.registering
a.configure {
}
```

### Context

Migrating plugin to lazy configuration APIs

### Your Environment

Gradle `4.10-rc-2`

**Comment by eskatos** [comment]
Closing as fixed in https://github.com/gradle/kotlin-dsl/pull/1116
