### ISSUE TITLE
Allow module substitution for plugin resolution in the plugins block

### ISSUE THREAD

**Issue by fuzzyweapon** [gradle/kotlin-dsl#1043]
There are probably many ways to solve this use case and I can see the summary for this issue being problematic, so I will just describe the use-case.

I'd like to develop plugins locally within a composite build using the plugins block to apply them (and apply them to another included project in that composite build) without requiring developers to manually execute some kind of plugin publishing task.

### Expected Behavior

I'd like to be able to build+publish modules that the plugins block relies upon before included builds that use them are evaluated.  Module substitution for plugin resolution would be one way I think to approach solving this, but it might not be the best way. (please see current behavior section for more comprehensive introduction to our scenario)

### Current Behavior

When using the plugins block, those plugins need to be published before other included builds in the composite build are evaluated in the configuration phase.  In my testing, aside from requiring an extra first-time setup type task, the developer can run into some edge-cases during development where it isn't apparent to those not maintaining build scripts how they should handle it.  There are other confusing gotchas and brittleness (that is required to be introduced).  For instance, let's say I accept the brittleness introduced by creating said task that builds and publishes.  Well, after running this task upon setting up their dev environment, anyone making changes to a plugin will not be able to simply have build for the composite project depend on this task.  Why?  Because in this scenario, Gradle will evaluate all included builds for the composite project first, meaning that included build that uses the plugin will use the last one built still in the local repo, and then on the /next/ run of build, it should resolve to the newly built and published version of the plugin.  This is awkward.

The other way to develop plugins in composite builds is to add the plugin module to the classpath in the buildscript dependencies block.  This triggers Gradle to trigger these modules to be rebuilt before evaluating downstream projects that use it.  Great!  All problems solved?  The problem with this, is in Kotlin DSL, we then lose all the things that make Kotlin DSL great (type-safety, IDE exploration, etc).  This has the extra problem that one of the included build projects that applies one of these plugins can no longer be built as a separate project.

Attempts to marry the two strategies with existing features lead to not knowing really whether Gradle is using one method or another transparently, and the idea that it could use one or the other is inherently problematic.

### Context

We need this functionality to smooth out the experience of setting up and working with a gradle dev environment.  We're developing an open source library that will be used in many organizations.  We do not intend to publish artifacts or opinionated build plugins to an opinionated environment (aka, we don't want to require companies and individuals that use this to consume our library artifact from a public or intranet server that our specs dictate and we don't believe that our opinionated build plugins belong as public gradle distributions) for the foreseeable future.  We want this to be as plug-and-play as possible while not relying on any infrastructure dependencies or forcing the developers to have much knowledge of the build code/structure.

Composite builds make sense for this scenario in which we as library developers are often working in a demo project and making iterative changes in the library and allow downstream projects to locally build and consume the library.  We also need to be able to use plugins for some of our tasks due to some chicken-egg scenarios with things like a homegrown texturepacking library having dependencies on modules in another included build project.

We want the type-safety of Kotlin DSL plugins, local development of plugins and libraries, and the ability to develop those independently or together without any gotchas or strange workflow changes.

### Steps to Reproduce (for bugs)

Not relevant.

### Your Environment

 * Build scan URL: 
Not relevant.

**Comment by fuzzyweapon** [comment]
I realize the reason the plugins block uses the published plugin metadata to help resolve the way those artifacts are published...and that, as far as I remember, the plugins use a different type of resolution so this isn't trivial.

**Comment by eskatos** [comment]
Hi Julia,
Thank you for this well put issue.
Plugin resolution via the `plugins {}` block [doesn't work out of the box](https://github.com/gradle/gradle-native/issues/522) across included build yet.
However, you can already work around it using the `pluginManagement {}` block in a settings script as demonstrated in the WIP [included build-logic](https://github.com/gradle/kotlin-dsl/pull/1037/files#diff-1a865325d4bcf975b6a9f7f5d7075a8e) sample.
HTH

**Comment by JLLeitschuh** [comment]
@fuzzyweapon This totally captures some of the issues that I had with how we ended up having to setup our examples for my plugin [ktlint-gradle](https://github.com/JLLeitschuh/ktlint-gradle).

I'm going to add @Tapchicoma to this conversation as well because he's had some experience with this same issue.

**Comment by fuzzyweapon** [comment]
@eskatos Thanks.  Yeah, I'm using that for build script plugins where possible.  Still requires us to force consumers to maintain esoteric (to them) blocks of plugin management in their settings files for composite builds (which will be every build and that can get very boiler-plateish really quick).  The good thing is that code shouldn't change often. :)

@JLLeitschuh 
Since you're applying a build script plugin, you should be able to mitigate having to use configure<> and the old apply style by directing consumers to use pluginmanagement, but I agree, it isn't ideal.  Most consumers would rather do whatever looks easiest when they get started, especially when they are unaware of the benefits of using `plugins {}`.  Personally, I plan on not even providing them documentation on how to use the old style so unless they really know what they are doing with kotlin dsl and gradle, they don't go that route. >__> ;)

For those looking at this issue, one way I relieve the boilerplate between lots of included builds (or conditionally included builds for those who are more developing an environment for devs to load various parts of a larger behemoth project in), is to use a script plugin for the pluginmanagement.

Since we've been restricted to using one of those block recently per settings file though, that might not be ideal anymore if consumers need to add their own repos and plugin resolution rules to it, and I haven't tested that scenario yet.

**Comment by eskatos** [comment]
This is https://github.com/gradle/gradle/issues/2528, closing as duplicate
