### ISSUE TITLE
`buildSrc-plugin` sample is broken with 1.0-RC

### ISSUE THREAD

**Issue by bigdaz** [gradle/kotlin-dsl#1050]
The [`buildSrc-plugin`](https://github.com/gradle/kotlin-dsl/tree/master/samples/buildSrc-plugin) sample hasn't been updated for breaking changes in 1.0-RC-3.

- Need to use `create("greet-plugin")` due to changes to `String` invoke on container
- Need to add `jcenter` repository

**Comment by StefMa** [comment]
The develop branch is up to date.
See also this commit
https://github.com/gradle/kotlin-dsl/commit/cadf2ad7d45c99fa3f70e03e976f46de726080e4

**Comment by bigdaz** [comment]
Thanks. I wasn't aware that changes for RCs were not being merged into `master`.
