### ISSUE TITLE
dslAccessors created for sourceSets prevent application of NamedDomainObjectContainerScope

### ISSUE THREAD

**Issue by ramonwirsch** [gradle/kotlin-dsl#1052]
After the latest change from ```java.sourceSets``` to ```sourceSets```,
NamedDomainObjectContainerScope kotlin extension is no longer applied, leading to the requirement of 
```
(sourceSets) {
   "sourceSet" {
   }
}
```

The DSL Accessors generated include the call with configure-lambda and thereby prevent kotlin from using its previous 
```
NamedDomainObjectContainer<T>> C.invoke(configuration)
```
wrapper.

If the choice is between either having to use java.sourceSets directly or having to wrap sourceSets in parentheses, in my opinion, explaining to people where the parentheses come from is much harder...

Ideally the generated DSL Accessor would either apply the wrapper itself or would only provide the getter, so that the existing automatic wrapping still works.

Tested with Gradle 4.10-rc-2 & kotlin-dsl 1.0-rc-3

**Comment by eskatos** [comment]
Thanks for the issue @ramonwirsch 
This is #1120 
Closing as duplicate
