### ISSUE TITLE
[Feature Request] Generate Extension Functions for additional Android buildtypes

### ISSUE THREAD

**Issue by runningcode** [gradle/kotlin-dsl#1053]
I would like to kindly request the ability for the kotlin-dsl to generate `DependencyHandler` extension functions for additional build types.

For example:
```
android {
    buildTypes {
        getByName("debug") {
            isCrunchPngs = true
        }
        create("foo") {
            isDebuggable = false
        }
    }
}
```

In the above buildscript, the kotlin dsl generates the following extension function in the DependencyHandler for the debug BuildType.
```
fun DependencyHandler.`debugImplementation`(dependencyNotation: Any): Dependency? =
    add("debugImplementation", dependencyNotation)
```

Would it be possible to generate the following extension for the foo buildtype?
```
fun DependencyHandler.`fooImplementation`(dependencyNotation: Any): Dependency? =
    add("fooImplementation", dependencyNotation)
```

Is this technically possible? Are there limitations? If not, I would be glad to help out with the implementation, could you point me in the right direction?

Cheers!

**Comment by eskatos** [comment]
Thanks for the issue @runningcode.

Type-safe accessors in project build scripts, kotlin extensions really, get generated right before evaluating the script body. In other words they don't get generated for model elements created in the script body itself. See https://docs.gradle.org/5.0-rc-1/userguide/kotlin_dsl.html#sec:configuring_plugins

If you move the creation of your `"foo"` build type up, either in a plugin applied using the `plugins {}` block in that script, or in a parent project injecting configuration, then it'll exist before evaluating the script body and you'll get the type-safe accessors for the `fooImplementation` configuration.
