### ISSUE TITLE
closureOf action should be  T.() -> V instead of  T.() -> kotlin.Unit

### ISSUE THREAD

**Issue by gortiz** [gradle/kotlin-dsl#1054]
Some groovy plugins are configured using closures. This is why the kotlin-dsl has functions like closureOf and delegateClosureOf. Usually this closures are used to configure the receiver object, but there are cases where they are used like regular functions and should return a value.

In these cases, current closureOf (and delegateClosureOf) auxiliary functions cannot be used as it receives an action whose signature is T.() -> kotlin.Unit and therefore there is no way to specify the value the closure should return.

### Expected Behavior
closureOf and delegateClosureOf should receive an action like  T.() -> V or there should be another similar auxiliary functions that make it easy to create closures that return something.

### Current Behavior
closureOf and delegateClosureOf receives an action that cannot specify the returned value.

### Context
One example of this requirement is the excelent [Axion Release Plugin](https://axion-release-plugin.readthedocs.io/en/latest/configuration/version.html#incrementing), which uses the result of a closure to get the next release version.
To be able to specify the closure, I have to do something like that:

`
KotlinClosure1<Receiver, Value>({my code that returns a Value}, null, null)
`

**Comment by gortiz** [comment]
If you are ok with that, I can prepare a PR.

**Comment by eskatos** [comment]
Thanks for the report @gortiz. We agree that the proposed api could make sense, except that we can no longer break the api. FWIW, `KotlinClosure1` already provides that exact capability.

We would be willing to accept PRs with new Closure interoperability functions for new use cases.
