### ISSUE TITLE
Cross-configuration of buildscript throws an exception

### ISSUE THREAD

**Issue by ingokegel** [gradle/kotlin-dsl#1057]
With the build script `build.gradle.kts`

    allprojects {
        buildscript {
            dependencies {
                classpath("commons-io:commons-io:2.6")
            }
        }
    }

an invocation of 

    gradle

fails with the error message

    Cannot change dependencies of configuration ':classpath' after it has been resolved.

The same build script named  `build.gradle` works as expected with the Groovy DSL.

In the above example, you could simply remove the `allprojects` call to make it work for the root project. However, cross-configuration of buildscript in multi-module projects is not possible with the Gradle Kotlin DSL.

**Comment by ljacomet** [comment]
My own testing of this script using the Groovy DSL fails on Gradle 4.9. Which version did you test with?

Anyway, you should not rely on this behavior. Resolving the buildscript `classpath` configuration is required to interpret projects themselves, so this pattern is wrong and should not be used.

**Comment by ingokegel** [comment]
Works for me with gradle 4.9 and the Groovy DSL and I use this pattern in several of my projects. Do you get the same error message as with the Kotlin DSL?

>Resolving the buildscript classpath configuration is required to interpret projects themselves, so this 
>pattern is wrong and should not be used.

Why is this wrong? The root project can configure the classpath for subprojects. This has always worked this way and I don't see what the Kotlin DSL changes in this respect.

**Comment by ljacomet** [comment]
I do get the same error.

Your example uses `allprojects` not `subprojects`, but your explanation hints at the later. The former does not work for me and should not as I explained. The later does work indeed in Groovy DSL and can make sense.
Isn't that the issue in our different interpretation? If yes, can you update the original issue description?

**Comment by ingokegel** [comment]
Thank you, that helped. When using `subprojects`, cross-configuration of `buildscript` also works with the Kotlin DSL, it's just the root project that behaves differently. In the Groovy DSL, you could modify it, but it had no effect, with the Kotlin DSL it throws an exception, which is actually better.
