### ISSUE TITLE
[Question] Adds an implementation dependency only to the “free” product flavour in Kotlin DSL

### ISSUE THREAD

**Issue by nksaroj** [gradle/kotlin-dsl#1058]
I am in process of migrating our Groovy based scripts to Kotlin. 
I have been able to get most of done except not sure how to add a dependency for a particular flavour. This is how looks like in Kotlin DSL so far but not sure why the freeImplementation("bar:2.2.8") is not working.
````
 productFlavors {
    create("free") {
         ...
         ...
    }
    create("paid") {
        ...
        ...
    }
}

dependencies {

    implementation("foo:1.2.0")

    // This is not working when migrated to Kotlin DSL
    freeImplementation("bar:2.2.8")

    //Below was the code in Groovy which was working fine earlier 
    //freeImplementation "bar:2.2.8"

}

**Comment by bamboo** [comment]
Hi @nksaroj,

Assuming the `freeImplementation` configuration is registered dynamically, as a side-effect of the `create("free")` call, it needs to be brought into scope explicitly before dependencies can be declared:

```kotlin
val freeImplementation by configurations
dependencies {
    freeImplementation("bar:2.2.8")
}
```
Alternatively, a string literal can be used to denote a dynamic configuration:
```kotlin
dependencies {
    "freeImplementation"("bar:2.2.8")
}
```
Does that answer your question?

**Comment by nksaroj** [comment]
@bamboo Thank you very much. You saved my day :)

**Comment by StefMa** [comment]
Hey @bamboo 
a maybe dumb question about this.
Is it planned to support dynamically added configurations in some way? 🤔 
Or is is "impossible"?

I ask also because someone have requested this [feature here](https://github.com/gradle/kotlin-dsl/issues/1053).
