### ISSUE TITLE
KT-26387 - IntelliJ IDEA plugin ignores script template argument `-XXLanguage:+SamConversionForKotlinFunctions`

### ISSUE THREAD

**Issue by bamboo** [gradle/kotlin-dsl#1064]
https://youtrack.jetbrains.com/issue/KT-26387

**Comment by GFriedrich** [comment]
Just used the last unofficial 1.2.70 EAP and seems to work there too (https://teamcity.jetbrains.com/viewLog.html?buildId=1585200&tab=artifacts).
Let's hope jetbrains releases 1.2.70 rather soonish because currently it blocks me from using 4.10 properly.

**Comment by GFriedrich** [comment]
First RC for 1.2.70 is ready - see https://github.com/JetBrains/kotlin/releases/tag/v1.2.70-eap-40 and https://plugins.jetbrains.com/plugin/6954-kotlin

**Comment by GFriedrich** [comment]
The plugin for Kotlin 1.2.70 just has been released and it's working for me. :tada:

**Comment by eskatos** [comment]
Closing as fixed in 1.2.70
