### ISSUE TITLE
Apply method in settings script is ambiguous since 1.0-RC

### ISSUE THREAD

**Issue by ingokegel** [gradle/kotlin-dsl#1066]
In a `settings.gradle.kts` script

    apply {
        plugin<MySettingsPlugin>()
    }

used to work before 1.0-RC. Now, with Kotlin SAM conversion, the methods `fun apply(configuration: ObjectConfigurationAction.() -> Unit)`  and `apply(action: Action<in ObjectConfigurationAction>)` make this call ambiguous, so it has to be written as 

    apply (Action {
        plugin<MySettingsPlugin>()
    })

I would suggest removing `fun apply(configuration: ObjectConfigurationAction.() -> Unit)`  from the settings script API.

**Comment by bamboo** [comment]
Thanks for the report!

**Comment by bamboo** [comment]
Fixed by #1069
