### ISSUE TITLE
Accessing script top-level members from inline task type constructor fails at runtime

### ISSUE THREAD

**Issue by eskatos** [gradle/kotlin-dsl#1068]
@StefMa commented on [Mon Aug 27 2018](https://github.com/gradle/gradle/issues/6530)

I noticed that my build script failed if I have the following task:
```kotlin
open class ATask : DefaultTask() {

    @TaskAction
    fun xx() {
        println(buildDir)
    }
}

// It does not care if we use `create` or `register`
tasks.create("crash", ATask::class.java)
```

Gradle reports with this example:
> The constructor for class [] should be annotated with @Inject

If I add a `@Inject` constructor it failed with a `ArrayIndexOutOfBoundsException`.

The reason is that we try to access the `buildDir` inside a `(Default)Task`. 
The `getBuildDir()` method is part of `Project` **not** of a `DefaultTask`. It seems that the IDE can't resolve it correctly but Gradle fails at runtime.

According to @eskatos it is maybe related to the way Gradle instantiate tasks.
He posted a example in Slack which works:
```
println(Foo())
class Foo { init { println(buildDir) } }
```
[See Slack](https://gradle-community.slack.com/archives/CA7UM03V3/p1535375382000100?thread_ts=1535360843.000100&cid=CA7UM03V3)

### Expected Behavior
The best behavior I expect is that the IDE reports me that I can't access top-level members inside a "closed" class. 
**Or** it should work and Gradle does not fail 🙃 

### Current Behavior
It failed :/

### Your Environment
Gradle 4.10-rc-3 (but effects also 4.9)
IntelliJ IDEA 2018.2.2 (Community Edition)
Build #IC-182.4129.33, built on August 21, 2018
JRE: 1.8.0_152-release-1248-b8 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6

**Comment by eskatos** [comment]
It can be reproduced with a Java plugin:
```java
public class FooPlugin implements Plugin<Project> {

    public class FooTask extends DefaultTask {
        @TaskAction
        public void foo() {
            System.out.println("foo!");
        }
    }

    @Override
    public void apply(Project project) {
        project.getTasks().register("foo", FooTask.class);
    }
}
```

```
* What went wrong:
A problem occurred configuring project ':'.
> Could not create task ':foo'.
   > Could not create task of type 'FooTask'.
      > The constructor for class foo.FooPlugin$FooTask_Decorated should be annotated with @Inject.
```

**Comment by eskatos** [comment]
Closing as superseded by https://github.com/gradle/gradle/issues/7644

**Comment by mkobit** [comment]
I ran into this too, and I thought it was because `println(buildDir)` was getting `buildDir` from the `project.buildDir` from the script and then it was not able to be constructed.
