### ISSUE TITLE
Model rule

### ISSUE THREAD

**Issue by luengnat** [gradle/kotlin-dsl#1071]
I noticed that https://docs.gradle.org/current/userguide/software_model.html mentioned that 

```Rule based configuration will be deprecated. New plugins should not use this concept.```

what do we need to use to replace that? "model" does not seem to support in Kotlin

**Comment by eskatos** [comment]
@luengnat, please see https://github.com/gradle/kotlin-dsl/issues/935

Closing as duplicate
