### ISSUE TITLE
Ambiguous "apply"-method in settings.gradle.kts

### ISSUE THREAD

**Issue by GFriedrich** [gradle/kotlin-dsl#1074]
Using apply in settings.gradle.kts with Kotlin DSL 1.0-RC3 results in compiler error mentioning ambiguous method usage.

### Expected Behavior
Using an apply block in settings.gradle.kts should simply work.

### Current Behavior
Currently I need to use a lambda type to make the call unambiguous.

### Steps to Reproduce (for bugs)
Simply use `apply { }` in the settings.gradle.kts
The compiler will complain that it's an ambiguous call.

### Solution
As far as I can see is that the [KotlinSettingsScript class](https://github.com/gradle/kotlin-dsl/blob/master/subprojects/provider/src/main/kotlin/org/gradle/kotlin/dsl/KotlinSettingsScript.kt#L96) implements both apply methods.
Now that Kotlin DSL uses SAM conversion, only the latter one is needed.

**Comment by thc202** [comment]
Seems to be a duplicate of #1066.

**Comment by GFriedrich** [comment]
Argh - I checked the master branch. I always forget that this repository uses a different branching model than the Gradle repository itself.
Nevermind...
