### ISSUE TITLE
Set the develop branch as default

### ISSUE THREAD

**Issue by StefMa** [gradle/kotlin-dsl#1075]
There are a lot of issues which get opened because users take a look into the `master` branch (which is currently the default branch in github) instead of the `develop` branch (which most of the time include the fix already).

I would suggest that you make the `develop` branch the default branch so that `github.com/gradle/kotlin-dsl` directly points to that branch, instead of the probably outdated `master` branch.

I don't know if there is already something planned internally. But that suggestions above is something what I would recommend (and is the easiest solution currently).
Another solution would be to follow the same branching model like **gradle/gradle** does. 

### Expected Behavior
Users should be easier find the **current** implementation of something.

### Current Behavior
Users tend to open issues/ask questions because the look at an outdated code.

**Comment by GFriedrich** [comment]
#921 ... but thanks @StefMa - I guess you created the ticket because of me :smile:

**Comment by bamboo** [comment]
Thanks for the suggestion and rationale @StefMa.

Our main motivation to keep `master` as the default branch was to  increase the usefulness of the published samples with the policy that the samples displayed by default should always work with the latest public version of Gradle.

We are considering to revisit that policy and make things more consistent with `gradle/gradle`.

**Comment by eskatos** [comment]
Superseded by #1232
