### ISSUE TITLE
Gradle should accept Kotlin lambdas as a lazy construct for e.g. files

### ISSUE THREAD

**Issue by eskatos** [gradle/kotlin-dsl#1077]
### Expected Behavior

```kotlin
val srcDir = file("src")
val collection = layout.files({ srcDir.listFiles() })
println(collection.files)
```

### Current Behavior
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':foo'.
> Cannot convert the provided notation to a File or URI: () -> kotlin.Array<(out) java.io.File!>!.
```

### Context
See https://docs.gradle.org/current/userguide/working_with_files.html#example_implementing_a_file_collection

The file notation conversion unpacks Groovy Closures, one can expect it to also unpack Kotlin lambdas. This applies to many other APIs, see e.g. https://docs.gradle.org/current/userguide/working_with_files.html#sec:specifying_multiple_files

### Your Environment
Gradle 4.10

**Comment by eskatos** [comment]
The file notation conversion also unpacks `Provider<T>`s. This allows the following:

```kotlin
val srcDir = file("src")
val collection = layout.files(provider { srcDir.listFiles() })
println(collection.files)
```

**Comment by eskatos** [comment]
What makes this confusing is that the complete error message:
```
* What went wrong:
Cannot convert the provided notation to a File or URI: () -> kotlin.Array<(out) java.io.File!>!.
The following types/formats are supported:
  - A String or CharSequence path, for example 'src/main/java' or '/usr/include'.
  - A String or CharSequence URI, for example 'file:/usr/include'.
  - A File instance.
  - A Path instance.
  - A Directory instance.
  - A RegularFile instance.
  - A URI or URL instance.
```
doesn't mention `Callable` nor `Provider` nor collections or arrays.

**Comment by JLLeitschuh** [comment]
@eskatos The error message also doesn't mention that it can accept collections of any of those items as well.

**Comment by eskatos** [comment]
Done in https://github.com/gradle/gradle/pull/7739 and https://github.com/gradle/gradle/pull/7966
