### ISSUE TITLE
[Help Needed] org.gradle.api.plugins.UnknownPluginException

### ISSUE THREAD

**Issue by nksaroj** [gradle/kotlin-dsl#1080]
I am getting the following error while running the build in our internal CI Server.

> org.gradle.api.plugins.UnknownPluginException: Plugin [id: 'org.gradle.kotlin.kotlin-dsl', version: '0.18.1'] was not found in any of the following sources:
> 
> - Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
> - Plugin Repositories (could not resolve plugin artifact 'org.gradle.kotlin.kotlin-dsl:org.gradle.kotlin.kotlin-dsl.gradle.plugin:0.18.1')
>   Searched in the following repositories:
>     Gradle Central Plugin Repository
> 

app/buildSrc/build.gradle.kts
Below is the code in build.gradle.kts
```
plugins {
    `kotlin-dsl`
}
```
Even though I tried to include the repositories above or below the plugins didnt make any difference.

```
plugins {
    `kotlin-dsl`
}
repositories {
      maven("https://ci.mycompany.com/jcenter")
}
```

**Comment by GFriedrich** [comment]
I guess you're behind a company proxy and can therefore not access the repositories. But as you have your own repository you were already on the right track: To tell Gradle where to search for plugins you've to use the pluginManagement block. See also at: [https://docs.gradle.org/current/userguide/plugins.html#sec:plugin_management](https://docs.gradle.org/current/userguide/plugins.html#sec:plugin_management)
Additionally make sure that your repository is syncing/proxing the repository from https://plugins.gradle.org/m2/ as the plugins are only available from there.

**Comment by nksaroj** [comment]
Thanks @GFriedrich I will post this in other forum.
Yes we cycle and sync regularly. Even I am sure it's already exist in our repo. But no luck.

**Comment by nksaroj** [comment]
I had to add pluginManagement to the settings.gradle

```
pluginManagement {
       repositories {
                  maven("https://ci.mycompany.com/jcenter")
               }
}
```
