### ISSUE TITLE
Using the `build-scan` property extension should apply the same build-scan plugin version as running with --scan

### ISSUE THREAD

**Issue by eskatos** [gradle/kotlin-dsl#1083]
### Expected Behavior
```kotlin
plugins {
    `build-scan`
}
```
should apply the same version of the build scan plugin as running with `--scan`.

### Current Behavior
It uses the version from the `gradleApi()` dependency used at `gradle/kotlin-dsl` compilation time because the version comes from a constant that gets inlined in the bytecode.

This should be changed to a method call.

**Comment by bamboo** [comment]
Resolved by #1085
