### ISSUE TITLE
Cannot set a repository to get plugin from

### ISSUE THREAD

**Issue by yayaa** [gradle/kotlin-dsl#1089]
I would like to be able to set a different repository path so that `kotlin-dsl` is accessed through that. We are working in a restricted network access and we proxy all maven dependencies through our internal nexus. I would like to be able to set our internal repository to get `kotlin-dsl` retrieved from.

### Expected Behavior
Set a repository for buildSrc so that when we apply the plugin it checks the source through the given repository.

### Current Behavior
There is no way to set a repository to redirect where `kotlin-dsl` will be downloaded. Tried the following approach;

```kotlin
buildscript {
    repositories {
        maven(url = "internal nexus url")
    }
}

plugins {
    `kotlin-dsl`
}
```

It ignores the repository and still tries to download from `https://plugins.gradle.org/m2/org/gradle/kotlin`

```
Error resolving plugin [id: 'org.gradle.kotlin.kotlin-dsl', version: '0.13.1']
> Could not resolve all dependencies for configuration 'detachedConfiguration1'.
   > Could not determine artifacts for org.gradle.kotlin.kotlin-dsl:org.gradle.kotlin.kotlin-dsl.gradle.plugin:0.13.1
      > Could not get resource 'https://plugins.gradle.org/m2/org/gradle/kotlin/kotlin-dsl/org.gradle.kotlin.kotlin-dsl.gradle.plugin/0.13.1/org.gradle.kotlin.kotlin-dsl.gradle.plugin-0.13.1.jar'.
         > Could not HEAD 'https://plugins.gradle.org/m2/org/gradle/kotlin/kotlin-dsl/org.gradle.kotlin.kotlin-dsl.gradle.plugin/0.13.1/org.gradle.kotlin.kotlin-dsl.gradle.plugin-0.13.1.jar'.
            > Remote host closed connection during handshake
```

### Context
This issue basically blocks us to use `kotlin-dsl` at all.

**Comment by eskatos** [comment]
Hi @yayaa,

Repositories for the `plugins {}` block are declared in your settings file, see https://docs.gradle.org/current/userguide/plugins.html#sec:plugin_management

The following should do:

```kotlin
// settings.gradle.kts
pluginManagement {
    repositories {
        maven(url = "internal nexus url")
        // gradlePluginPortal()
    }
}
```

**Comment by yayaa** [comment]
Hey @eskatos , thank you so much for quick reply!

**Comment by rafaeltoledo** [comment]
Just posting here as I am not able to make this to work. Tested with Gradle 4.10.3, 5.1, and 5.2.

Even with the configuration of `pluginManagement` in the first line of `settings.gradle.kts`, Gradle tries to resolve the `kotlin-dsl` declaration from `buildSrc` in Gradle Central Plugin Repository.

```kotlin
// settings.gradle.kts
pluginManagement {
    repositories {
        maven(url = "https://internalrepo.corp/artifactory")
    }
}
```

```kotlin
// buildSrc/build.gradle.kts
plugins {
    `kotlin-dsl`
}

repositories {
    maven(url = "https://internalrepo.corp/artifactory")
}
```

But the script fails (our CI don't have internet access)
```
Build file '/Users/rdtoledo/Projects/project-android/buildSrc/build.gradle.kts' line: 1

* What went wrong:
Plugin [id: 'org.gradle.kotlin.kotlin-dsl', version: '1.1.3'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'org.gradle.kotlin.kotlin-dsl:org.gradle.kotlin.kotlin-dsl.gradle.plugin:1.1.3')
  Searched in the following repositories:
    Gradle Central Plugin Repository
```

**Comment by rafaeltoledo** [comment]
Exactly! Thank you! :)
