### ISSUE TITLE
tasks.regiser<T>(name) returns NamedDomainObjectProvider instead of TaskProvider

### ISSUE THREAD

**Issue by JLLeitschuh** [gradle/kotlin-dsl#1108]
This is the example code I'm working from:
```kotlin
val sourceJar =
    tasks.register<Jar>("sourceJar") {
        group = LifecycleBasePlugin.BUILD_GROUP
        description = "An archive of the source code"
        classifier = "sources"
        from(java.sourceSets["main"].allSource)
    }
```

### Expected Behavior
`sourceJar` in the example should be of type `TaskProvider<Jar>`

### Current Behavior
`sourceJar` in the example above should not return the less specific type`NamedDomainObjectProvider<Jar>`

### Context

With the addition of the `TaskProvider` API, I'm concerned that future API's will constrain the inputs of lazy task's to only accept `TaskProvider` which will prevent objects created through `tasks.register` to be passed without casting.

### Your Environment

```
------------------------------------------------------------
Gradle 4.10
------------------------------------------------------------

Build time:   2018-08-27 18:35:06 UTC
Revision:     ee3751ed9f2034effc1f0072c2b2ee74b5dce67d

Kotlin DSL:   1.0-rc-3
Kotlin:       1.2.60
Groovy:       2.4.15
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_92 (Oracle Corporation 25.92-b14)
OS:           Mac OS X 10.13.6 x86_64
```

**Comment by StefMa** [comment]
Is that a issue for the Kotlin DSL?
You simply call [this method](https://docs.gradle.org/4.10.1/javadoc/org/gradle/api/tasks/TaskContainer.html#register-java.lang.String-org.gradle.api.Action-) which is a API call from `gradle/gradle`, no? 🤔 

Anyway. The following buildscript gives the correct output:
```
plugins {
  java
}

val sourceJar =
    tasks.register<Jar>("sourceJar") {
        group = LifecycleBasePlugin.BUILD_GROUP
        description = "An archive of the source code"
        classifier = "sources"
        from(sourceSets["main"].allSource)
    }

println(sourceJar)
```
(with Gradle 4.10.1):
```
> Configure project :
provider(task sourceJar, class org.gradle.api.tasks.bundling.Jar)
```

**Comment by JLLeitschuh** [comment]
It's because there's a reified extension function, but not one for `TaskContainer`.

The runtime type is correct, but the compile time type is not.

**Comment by eskatos** [comment]
Closing as fixed in https://github.com/gradle/kotlin-dsl/pull/1116
