### ISSUE TITLE
Unable to activate pre-emptive authentication with Kotlin DSL

### ISSUE THREAD

**Issue by checketts** [gradle/kotlin-dsl#1109]
In https://docs.gradle.org/2.7/release-notes.html#support-for-preemptive-http-authentication it demonstrates that you can tell Gradle to preemptively sent BasicAuth headers.

### Expected Behavior
I should be able to configure the Authentication method

```
repositories {
  maven {
    url = uri("https://my.mavenrepo.com/artifactory/mvn-main")
    authentication {
      basic(BasicAuthentication) // enable preemptive authentication (won't compile)
    }

    credentials {
      username = mavenUser
      password = password
    }
  }

}
```

### Current Behavior
It isn't clear how to enable the BasicAuth preemptive auth mechanism.

### Context
I'm trying to enable auth in the pluginManagement in my `settings.gradle.kts`, and am seeing it misbehave (likely will be opening another issue in that regard)

### Steps to Reproduce (for bugs)
Code sample is above

### Your Environment
I'm using Gradle 4.10.1, on OSX with the included Gradle Kotlin DSL

**Comment by StefMa** [comment]
Kotlin is static typed.
Means you have to use the class there:
```kotlin
basic(BasicAuthentication::class.java) {
}
```
(Maybe `BasicAuthentication::class` works too).

**Comment by eskatos** [comment]
The nightly build of the Gradle user manual now has samples demonstrating this with the Kotlin DSL.
See https://docs.gradle.org/nightly/userguide/repository_types.html#sub:authentication_schemes

Here's your sample translated:
```kotlin
repositories {
    maven {
        url = uri("https://my.mavenrepo.com/artifactory/mvn-main")
        authentication {
            create<BasicAuthentication>("basic")
        }
        credentials {
            username = mavenUser
            password = password
        }
    }
}
```
Closing as answered
