### ISSUE TITLE
BasicAuth repository credentials in pluginManagement block is passed incorrectly to maven server

### ISSUE THREAD

**Issue by checketts** [gradle/kotlin-dsl#1110]
In converting a script to the Kotlin DSL, my plugins and dependencies need to come from an internal Artifactory repository that requires credentials.

To avoid checking credentials into the project they are read from `~/.gradle/gradle.properties`

Here is a sample `settings.gradle.kts`:

```
rootProject.name = "myproject"

val mavenUser: String by settings
val mavenPassword: String by settings

pluginManagement {
  repositories {
    maven {
      url = uri("https://myrepo.com/artifactory/mvn-main")
      credentials {
        username = mavenUser
        password = mavenPassword
      }
    }
  }
}
```

### Expected Behavior
The exact same credentials work for my dependencies and those download fine. I also verified (via println) that the properties are read in correctly in the settings file.

I would expect my plugins to be able to be loaded from the internal repo.

### Current Behavior
Could not HEAD 'https://myrepo.com/artifactory/mvn-main/org/springframework/boot/org.springframework.boot.gradle.plugin/2.0.5.RELEASE/org.springframework.boot.gradle.plugin-2.0.5.RELEASE.jar'. Received status code 403 from server: Forbidden

If I remove the credentials I receive a 401 from the server, so I can see the credentials are being read in. I also can trigger a 403 for my dependencies if I intentionally typo the password for those.

I tried to use a proxy to sniff out the bad header, but I wasn't able to make it work. (happy to try again if anyone has any tips)

### Context
I need pluginManagement to leverage my internal maven repo (with credentials) to finish migrating to the Kotlin DSL.

### Steps to Reproduce (for bugs)
1- Create a repo with basicAuth (https://mymavenrepo.com/ offers free ones) and publish some plugins/deps
2- Create a `~/.gradle/gradle.properties` with properties for the username/password for your repo
3- In `settings.gradle.kts` add lines:

```
rootProject.name = "myproject"

val mavenUser: String by settings //match your properties in ~/.gradle/gradle.properties
val mavenPassword: String by settings

pluginManagement {
  repositories {
    maven {
      url = uri("https://mymavenrepo.com/abcd123")
      credentials {
        username = mavenUser
        password = mavenPassword
      }
    }
  }
}
```
4 - Add a plugin to your plugin block that you could pull from your repo

### Your Environment
Running on Gradle 4.10.1, included Kotlin DSL, Java 8.

**Comment by JLLeitschuh** [comment]
If you print your credentials to the console they look right??

I'm doing something similar and it's working fine for me.

**Comment by checketts** [comment]
@JLLeitschuh Yes, I added `println("creds: u:'$mavenUser' p:'$mavenPassword'")` in my file and the correct values are being printed out.

**Comment by checketts** [comment]
Thanks to the answer in #1109 I was able to get it to pre-emptively send the credentials and inspect the headers sure enough the same header is sent in both cases. So I think this indicates that there is something wonky with my repo. 

Thanks for the help.

**Comment by checketts** [comment]
Eureka! My internal repo isn't mirroring the plugin repo correctly. That didn't matter before because we used the `apply` approach for plugins instead of the `plugins` block.

I can work around it while I wait for the other team to improve their config by manually looking up each plugin based on it's ID (I'll clean that up but for now here is my approach):

```
resolutionStrategy {
      eachPlugin {
        if (requested.id.id == "org.springframework.boot") {
          useModule("org.springframework.boot:spring-boot-gradle-plugin:${requested.version}")
        }
        if (requested.id.id == "io.spring.dependency-management") {
          useModule("io.spring.gradle:dependency-management-plugin:${requested.version}")
        }
        if (requested.id.id == "com.github.ben-manes.versions") {
          useModule("com.github.ben-manes:gradle-versions-plugin:${requested.version}")
        }
        if (requested.id.id == "com.gorylenko.gradle-git-properties") {
          useModule("gradle.plugin.com.gorylenko.gradle-git-properties:gradle-git-properties:${requested.version}")
        }
        if (requested.id.id == "com.avast.gradle.docker-compose") {
          useModule("com.avast.gradle:gradle-docker-compose-plugin:${requested.version}")
        }
        if (requested.id.id == "org.jetbrains.kotlin.jvm") {
          useModule("org.jetbrains.kotlin:kotlin-gradle-plugin:${requested.version}")
        }
        if (requested.id.id == "org.jetbrains.kotlin.plugin.allopen") {
          useModule("org.jetbrains.kotlin:kotlin-allopen:${requested.version}")
        }
        if (requested.id.id == "org.jetbrains.kotlin.plugin.spring") {
          useModule("org.jetbrains.kotlin:kotlin-allopen:${requested.version}")
        }
      }
    }
```
