### ISSUE TITLE
Plugin syntax is inconsistent

### ISSUE THREAD

**Issue by helmbold** [gradle/kotlin-dsl#1127]
Only standard plugins can be used in the `plugins` block:
```kotlin
plugins {
    java
    application
}

apply(plugin = "checkstyle")
```

However, to use a completely different syntax outside of this block (and useful structure element) is strange. I suggest to put the declaration of foreign plugins into the `plugins` block:

```kotlin
plugins {
    java
    application
    plugin(id = "checkstyle")
    plugin(id = "jacoco", version = "1.2.3")
}
```

The `apply` method should be deprecated or removed for this purpose.

**Comment by StefMa** [comment]
> Only standard plugins can be used in the `plugins` ~blog~ block:

That is not true.
Each Plugin which is published to the [Gradle Portal](https://plugins.gradle.org/) can be used inside the `plugins` block.
Beside of that *each* plugin which is not publish to the Gradle Portal can be used inside the `plugins` block with the `pluginMangament` setting in the `settings.gradle[.tks]`. See this documentation for more: https://docs.gradle.org/4.10.2/userguide/plugins.html#sec:plugin_management

> The apply method should be deprecated or removed for this purpose

I think the Kotlin DSL is not a replacement for the Groovy DSL but more an complement.
Beside of that the `apply` method is already declared as `legacy` (see the linked doc).

**Comment by eskatos** [comment]
Closing as won't fix
