### ISSUE TITLE
Update main gradle/kotlin-dsl GitHub page 

### ISSUE THREAD

**Issue by pioterj** [gradle/kotlin-dsl#1134]
We should update the gradle/kotlin-dsl GitHub page before 1.0 release.

Some specific things to do:
* Link to a newer blog post (currently linking to intro post from 2016)
* Link to [the migration guide](https://guides.gradle.org/migrating-build-logic-from-groovy-to-kotlin/)
* Link to [DSL introduction](https://github.com/gradle/kotlin-dsl/issues/277) in the user guide
* Mention of Kotlin samples in the user guide

The content of [getting started page](https://github.com/gradle/kotlin-dsl/tree/master/doc/getting-started) should probably be fully migrated to the user guide and the migration guide.

**Comment by eskatos** [comment]
Done in #1182
