### ISSUE TITLE
baseFeature flag is private in Kotlin DSL

### ISSUE THREAD

**Issue by nksaroj** [gradle/kotlin-dsl#1136]
I am trying to use the feature modules introduced recently to Android.
But when I tried to set the baseFeature it turned to be private and not been able to set the value as "true" .
Any help is appreciated.

https://developer.android.com/topic/google-play-instant/getting-started/feature-plugin
```
android {
    ...
    baseFeature true
    ...
}
```

**Comment by StefMa** [comment]
You have to use the Kotlin DSL - not the Groovy DSL.
Both of them are working for me:
<img width="409" alt="bildschirmfoto 2018-09-25 um 09 30 42" src="https://user-images.githubusercontent.com/10229883/45999379-c4e0be00-c0a5-11e8-9d78-d7704a0b49a4.png">
<img width="403" alt="bildschirmfoto 2018-09-25 um 09 30 55" src="https://user-images.githubusercontent.com/10229883/45999380-c4e0be00-c0a5-11e8-88a8-d93d1a335255.png">
(When I use the `plugins {}` block  it can be `android {}` of course...)
