### ISSUE TITLE
Can't fail build in gradle.taskGraph.whenReady(Action)

### ISSUE THREAD

**Issue by dsvoronin** [gradle/kotlin-dsl#1143]
### Expected Behavior

Following code in build.gradle.kts should fail build in the end of configuration phase:
```kotlin
gradle.taskGraph.whenReady {
    throw GradleException("!!!")
}
```

### Current Behavior

Build successful with any type of exception thrown

same code in groovy fails build as expected
```groovy
gradle.taskGraph.whenReady {
    throw new GradleException("!!!")
}
```

### Context

I'm trying to configure fail fast properties validation for plugin

### Your Environment

I'm using gradle 4.10.1 (also tried with .2 version) 
It's just a sample Android studio project with provided sample added into root build.gradle.kts

**Comment by dsvoronin** [comment]
Yep, `closureOf` variant it works for me (somehow failed when i tried)

**Comment by eskatos** [comment]
Issue moved to [gradle/gradle #6900](https://github.com/gradle/gradle/issues/6900) via [**ZenHub**](https://www.zenhub.com/)
