### ISSUE TITLE
2/3 of the sample build scripts fail

### ISSUE THREAD

**Issue by SeanShubin** [gradle/kotlin-dsl#1144]
I tried building each project in the "samples" directory with the command "gradle build", and got the following results:

### The following 22 projects fail
- ant
- build-cache
- build-scan
- buildSrc-plugin
- composite-builds
- copy
- domain-objects
- extra-properties
- gradle-plugin
- groovy-interop
- hello-android
- hello-js
- kotlin-friendly-groovy-plugin
- maven-publish
- model-rules
- multi-project-with-buildSrc
- precompiled-script-plugin
- project-with-buildSrc
- provider-properties
- source-control
- task-dependencies
- testkit

### The following 11 projects succeed
- code-quality
- hello-coroutines
- hello-kapt
- hello-kotlin
- hello-world
- maven-plugin
- modularity
- multi-kotlin-project-config-injection
- multi-kotlin-project-with-buildSrc
- multi-kotlin-project
- project-properties

### Expected Behavior
I expect to see the line
`BUILD SUCCESSFUL`
as in the hello-world example

### Current Behavior
I see the line
`FAILURE: Build failed with an exception.`
as in the hello-js example
Here is the first error on the hello.js example, see [build-logs.zip](https://github.com/gradle/kotlin-dsl/files/2421007/build-logs.zip) file for full detail.

  Line 03:     val plugin by registering(GradleBuild::class) {
                             ^ Unresolved reference: registering

### Context
I am evaluating the best way to build Kotlin projects, with emphasis on javascript and multiplatform projects.
Kotlin-dsl is appealing because I really like type safety, but it is hard to evaluate this option fairly if I can't get the samples to work.

### Steps to Reproduce (for bugs)
pushd ant ; gradle build > ../../logs/ant.txt 2>&1 ; popd
pushd build-cache ; gradle build > ../../logs/build-cache.txt 2>&1 ; popd
pushd build-scan ; gradle build > ../../logs/build-scan.txt 2>&1 ; popd
pushd buildSrc-plugin ; gradle build > ../../logs/buildSrc-plugin.txt 2>&1 ; popd
pushd code-quality ; gradle build > ../../logs/code-quality.txt 2>&1 ; popd
pushd composite-builds ; gradle build > ../../logs/composite-builds.txt 2>&1 ; popd
pushd copy ; gradle build > ../../logs/copy.txt 2>&1 ; popd
pushd domain-objects ; gradle build > ../../logs/domain-objects.txt 2>&1 ; popd
pushd extra-properties ; gradle build > ../../logs/extra-properties.txt 2>&1 ; popd
pushd gradle-plugin ; gradle build > ../../logs/gradle-plugin.txt 2>&1 ; popd
pushd groovy-interop ; gradle build > ../../logs/groovy-interop.txt 2>&1 ; popd
pushd hello-android ; gradle build > ../../logs/hello-android.txt 2>&1 ; popd
pushd hello-coroutines ; gradle build > ../../logs/hello-coroutines.txt 2>&1 ; popd
pushd hello-js ; gradle build > ../../logs/hello-js.txt 2>&1 ; popd
pushd hello-kapt ; gradle build > ../../logs/hello-kapt.txt 2>&1 ; popd
pushd hello-kotlin ; gradle build > ../../logs/hello-kotlin.txt 2>&1 ; popd
pushd hello-world ; gradle build > ../../logs/hello-world.txt 2>&1 ; popd
pushd kotlin-friendly-groovy-plugin ; gradle build > ../../logs/kotlin-friendly-groovy-plugin.txt 2>&1 ; popd
pushd maven-plugin ; gradle build > ../../logs/maven-plugin.txt 2>&1 ; popd
pushd maven-publish ; gradle build > ../../logs/maven-publish.txt 2>&1 ; popd
pushd model-rules ; gradle build > ../../logs/model-rules.txt 2>&1 ; popd
pushd modularity ; gradle build > ../../logs/modularity.txt 2>&1 ; popd
pushd multi-kotlin-project ; gradle build > ../../logs/multi-kotlin-project.txt 2>&1 ; popd
pushd multi-kotlin-project-config-injection ; gradle build > ../../logs/multi-kotlin-project-config-injection.txt 2>&1 ; popd
pushd multi-kotlin-project-with-buildSrc ; gradle build > ../../logs/multi-kotlin-project-with-buildSrc.txt 2>&1 ; popd
pushd multi-project-with-buildSrc ; gradle build > ../../logs/multi-project-with-buildSrc.txt 2>&1 ; popd
pushd precompiled-script-plugin ; gradle build > ../../logs/precompiled-script-plugin.txt 2>&1 ; popd
pushd project-properties ; gradle build > ../../logs/project-properties.txt 2>&1 ; popd
pushd project-with-buildSrc ; gradle build > ../../logs/project-with-buildSrc.txt 2>&1 ; popd
pushd provider-properties ; gradle build > ../../logs/provider-properties.txt 2>&1 ; popd
pushd source-control ; gradle build > ../../logs/source-control.txt 2>&1 ; popd
pushd task-dependencies ; gradle build > ../../logs/task-dependencies.txt 2>&1 ; popd
pushd testkit ; gradle build > ../../logs/testkit.txt 2>&1 ; popd

### Your Environment
macOS High Sierra
version 10.13.6

**Comment by SeanShubin** [comment]
Ok, thanks.  It also seems I was using gradle 4.9 instead of gradle 4.10, so that fixed most of them.

**Comment by eskatos** [comment]
Closing as answered
