### ISSUE TITLE
Access for ExtensionContainer from any DSL object

### ISSUE THREAD

**Issue by TWiStErRob** [gradle/kotlin-dsl#1154]
Hey, I'm looking for an extension method that gives me `obj.extensions` in Gradle, with signature:
```kotlin
val Any.extensions: ExtensionContainer
```
I was able to write one using Groovy, but I'm looking for a pure Kotlin solution:
https://discuss.gradle.org/t/how-to-access-extensions-on-any-dsl-object-statically/28867

I'm writing this issue, hoping you would add one, as, if it belongs in any project it's this one.

I looked in 1.0-RC11, but no luck.

**Comment by bamboo** [comment]
Here's what such an extension could look like and how it could be used in our own build script:

https://github.com/gradle/kotlin-dsl/commit/ead45655fee383a3e1fb8509ec39b105e87f284d

**Comment by TWiStErRob** [comment]
Thanks Rodrigo 😀!!

Neat trick with `as`; nice improvement with extension property.
Does this mean you will consider adding it to `ExtensionAwareExtensions.kt`?

**Comment by eskatos** [comment]
Closing as won't fix
