### ISSUE TITLE
Script editor dependencies requests pile up when first one takes long

### ISSUE THREAD

**Issue by eskatos** [gradle/kotlin-dsl#1155]
When editing a `.gradle.kts` script the first resolution of dependencies can take a relatively long time. This can be because of downloading dependencies and their sources (including the Gradle sources if using a `-bin` distribution).

Making changes to that script while a resolution request is running is enqueuing new requests:

![image](https://user-images.githubusercontent.com/132773/46273691-dff47780-c556-11e8-91c1-5df723d41079.png)

This doesn't spawn a process per request, they are queued and processed by a single daemon. All those requests will eventually complete but this is disturbing. We should look into ways to mitigate this.

**Comment by bamboo** [comment]
A first step could be to dedupe pending requests.

**Comment by bamboo** [comment]
14d1735b8abd88d7d22684ccc4af22054ba85d4b improves the situation by only handling the most recent request and cancelling older requests for the classpath of the same script.

Requests will still pile up but they will no longer cause unnecessary roundtrips to the daemon so their overhead should be minimal.
