### ISSUE TITLE
Generate accessors for extensions on Tasks

### ISSUE THREAD

**Issue by JLLeitschuh** [gradle/kotlin-dsl#1160]
This might already exist in 5.0. If so, sorry for a duplicate issue.

Extensions should be generated for tasks that have extensions added to them.
For example, the `JacocoTaskExtension` is added to the `Test` task.

### Expected Behavior
```kotlin
plugins {
    jacoco
}
tasks.withType<Test>().configureEach {
    jacoco {
       // configure JacocoTaskExtension
    }
    // ...
```

### Current Behavior
You have to access the extension using the `configure` API.
```kotlin
plugins {
    jacoco
}
tasks.withType<Test>().configureEach {
    extensions.configure(typeOf<JacocoTaskExtension>()) {
       // configure JacocoTaskExtension
    }
    // ...
```
### Context
This will make the API for Kotlin similar to that of Groovy for configuring task extensions.

### Your Environment
```
------------------------------------------------------------
Gradle 4.10.1
------------------------------------------------------------

Build time:   2018-09-12 11:33:27 UTC
Revision:     76c9179ea9bddc32810f9125ad97c3315c544919

Kotlin DSL:   1.0-rc-6
Kotlin:       1.2.61
Groovy:       2.4.15
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_92 (Oracle Corporation 25.92-b14)
OS:           Mac OS X 10.13.6 x86_64

```

**Comment by mkobit** [comment]
Related: https://github.com/gradle/kotlin-dsl/issues/1041

**Comment by eskatos** [comment]
This can't be done currently without defeating task configuration avoidance because we need the task instances to know what extension they have. The Gradle extension model has to be made more static friendly first.

**Comment by eskatos** [comment]
This is #681 
Closing as duplicate
