### ISSUE TITLE
Gradle 5.0 doesn't work (can't find Kotlin deps)

### ISSUE THREAD

**Issue by SUPERCILEX** [gradle/kotlin-dsl#1163]
It looks like Gradle isn't looking on the network:
```
* What went wrong:
A problem occurred configuring project ':buildSrc'.
> Could not resolve all artifacts for configuration ':buildSrc:classpath'.
   > Could not find org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.0-rc-116.
     Searched in the following locations: file:/C:/Users/gojun/.gradle/caches/5.0-milestone-1/embedded-kotlin-repo-1.3.0-rc-116-2/repo/org/jetbrains/kotlin/kotlin-gradle-plugin/1.3.0-rc-116/kotlin-gradle-plugin-1.3.0-rc-116.jar
     Required by:
         project :buildSrc > gradle.plugin.org.gradle.kotlin:gradle-kotlin-dsl-plugins:1.0rc-12
   > Could not find org.jetbrains.kotlin:kotlin-sam-with-receiver:1.3.0-rc-116.
     Searched in the following locations: file:/C:/Users/gojun/.gradle/caches/5.0-milestone-1/embedded-kotlin-repo-1.3.0-rc-116-2/repo/org/jetbrains/kotlin/kotlin-sam-with-receiver/1.3.0-rc-116/kotlin-sam-with-receiver-1.3.0-rc-116.jar
     Required by:
         project :buildSrc > gradle.plugin.org.gradle.kotlin:gradle-kotlin-dsl-plugins:1.0-rc-12
```

**Comment by eskatos** [comment]
@SUPERCILEX, can you share a bit more about this? What is the content of your `buildSrc/build.gradle(.kts)` would help.

Note that Kotlin 1.3.0-rc-116 requires the [kotlin-eap](https://dl.bintray.com/kotlin/kotlin-eap/) repository to be set up. Also see the breaking changes section of the Kotlin DSL release notes about this: https://github.com/gradle/kotlin-dsl/releases/tag/v1.0-RC12#breaking-changes

**Comment by SUPERCILEX** [comment]
But it says the EAP repo will be added automatically. Here's my project: https://github.com/SUPERCILEX/Robot-Scouter. Run `./gradlew setup`

**Comment by eskatos** [comment]
Thanks Alex, I can reproduce.

For the kotlin-eap repo to be added automatically add an empty `buildSrc/settings.gradle.kts` file as instructed in the release notes. Please note that this behaviour will be removed once Kotlin 1.3 GA is available.

**Comment by SUPERCILEX** [comment]
Ohhhhhhhhh, in `buildSrc`, I see. Can I just add the EAP maven manually?

**Comment by eskatos** [comment]
Yes you can

**Comment by SUPERCILEX** [comment]
Confirmed, it works. The release notes should probably be updated to clarify that `buildSrc` needs a `settings.gradle.kts` too for the automatic stuff to work.
