### ISSUE TITLE
Spike faster approach for generating accessors

### ISSUE THREAD

**Issue by bamboo** [gradle/kotlin-dsl#1168]
Compiling the generated accessors is now the main bottleneck in the _first use_ and _buildscript classpath change_ scenarios.

This spike will explore emitting the bytecode for the accessors directly in order to completely avoid the compilation overhead.

The main questions to be answered by the spike are:
 - [ ] is the approach feasible at all?
 - [ ] how much faster can it be?
 - [ ] is the IDE experience negatively impacted in any way?

**Comment by JLLeitschuh** [comment]
Being able to to jump to declarations in the IDE is really nice. I'd rather not lose that.
