### ISSUE TITLE
Android Studio 3.2 can not use kotlin-dsl

### ISSUE THREAD

**Issue by wuchengithub** [gradle/kotlin-dsl#1170]
when i updated Android Studio 3.2 ,kotlin plugin must be higher 1.2.51

my project has a buildSrc module, and i use kotlin-dsl, like this:
file : build.gradle.kts
plugins {
    `kotlin-dsl`
}

but build project failed:
**error message:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.2.51 and higher. Project 'buildSrc' is using version 1.2.21.**

now, i guess kotlin-dsl has kotlin-plugin but version is 1.2.21, can not working at Android Studio 3.2, 
because only supports 1.2.51 and higher, what should i do???

Android Studio 3.2
Gradle 4.6
gradle-plugin 3.2
gradle-kotlin-version 1.2.71

**Comment by StefMa** [comment]
Update Gradle 🙃 
Gradle 4.10 brings the Kotlin DSL version 1.0-RC6 which brings Kotlin 1.2.61.
-> https://github.com/gradle/kotlin-dsl/releases/tag/v1.0-RC6

**Comment by eskatos** [comment]
@wuchengithub that's #1033, closing

**Comment by minchulking91** [comment]
add fallow in build.gradle.kts

repositories {
    jcenter()
}
--- looks like
import org.gradle.kotlin.dsl.`kotlin-dsl`
repositories {
    jcenter()
}
plugins {
    `kotlin-dsl`
}
