### ISSUE TITLE
Are build scripts in the buildSrc preferred over Plugin<Project> classes?

### ISSUE THREAD

**Issue by StefMa** [gradle/kotlin-dsl#1172]
I just saw @eskatos KotlinConf talk especially the [slides here](https://eskatos.github.io/kotlinconf2018-type-safe-build-logic/#/).
There he linked to the its [`kotlinconf18-greetings` repository](https://github.com/eskatos/kotlinconf18-greetings).

Inside the `buildSrc/` there is the [generator.gradle.kts](https://github.com/eskatos/kotlinconf18-greetings/blob/89af339767c58b75e9837de2c5d0b380599c618b/buildSrc/src/main/kotlin/greetings/generator.gradle.kts) which is - basically - a "plugin".
Meaning - it could be also a simple (Kotlin) class which extends `Plugin<Project>`.

Because Gradle 5.0-M1 provides the functionally to apply such scripts inside the `plugins` block I wanted to ask if it **preferred** to write build scripts instead of a class.
Or is it just because of the lack that the `plugins` block can't apply plugin classes from the `buildSrc` dir? 🤔 
And if so - will there be support for this (in the future)? 🤔

**Comment by oehme** [comment]
It's not preferred, it's just less ceremony when you want to do some quick scripting.

**Comment by StefMa** [comment]
OK, thank you.
What about my second question?
Will there be support in the plugins block for classes which implements the
plugin interface in the future?

**Comment by oehme** [comment]
There already is - you just give them an id in buildSrc/build.gradle. Inferring an ID from the class name doesn't sound too enticing :)

**Comment by StefMa** [comment]
Well, that was too easy 😅 

But I created the Plugin-ID manually in the `resources/META-INF/gradle-plugins` dir.
How can I do that directly in the build.gradle file? 🤔 
Do you mean by applying the `java-gradle-plugin`?

**Comment by oehme** [comment]
Exactly.
