### ISSUE TITLE
Plugin authors should be able to unit/integration test Kotlin DSL generated accessors

### ISSUE THREAD

**Issue by JLLeitschuh** [gradle/kotlin-dsl#1178]
As a plugin author, I have no way to unit or integration test my plugin automatically with the Kotlin DSL generated accessors.
This is because, as a plugin author, I can't write tests that utilize the `plugin` block mechanism.
Related: https://github.com/gradle/gradle/issues/2528

It's currently impossible for plugin authors to write unit tests that do something like this:
```kotlin
class SomeTest {
    @Test
    fun `jlink execution`() {
        projectRoot.apply {
            buildKotlinFile().writeText(
                    """
                import org.gradleweaver.plugins.jlink.*
                plugins {
                    id("org.gradleweaver.plugins.simple-jlink") // This isn't allowed
                }
                jlink { // This accessor won't get generated
                    "example" {
                        useMinimalImage()
                        applicationJar = file("test.jar")
                        modules = listOf("java.base") // To avoid calling jdeps on an empty file
                    }
                }
                    """.trimIndent()
            )
           ...
}
```

Instead, plugins are required to add their own extensions in to the script manually by doing something like this:
```kotlin
class SomeTest {
@Test
    fun `jlink execution`() {
        projectRoot.apply {
            buildKotlinFile().writeText(
                """
                import org.gradleweaver.plugins.jlink.*

                buildscript {
                    repositories { maven { setUrl("$testRepositoryPath") } }
                    dependencies {
                        classpath("org.gradleweaver.plugins:simple-jlink:${testProperties["version"]}")
                    }
                }

                apply(plugin = "org.gradleweaver.plugins.simple-jlink")

                tasks.all {}

                jlink {
                    "example" {
                        useMinimalImage()
                        applicationJar = file("test.jar")
                        modules = listOf("java.base") // To avoid calling jdeps on an empty file
                    }
                }

                // We just need to hope that in users plugins extensions like this will automatically get generated
                fun `jlink`(configure: ${JLinkExtension::class.qualifiedName}.() -> Unit): Unit =
                    (this as org.gradle.api.plugins.ExtensionAware).extensions.configure("jlink", configure)
               """.trimIndent()
            )
            ...
}
```

This leaves plugin authors to **_just hope_** that their plugin extensions get generated the way they expect them to.

This same problem exists with the composite build testing solution that I've utilized in other plugins I've written.

Because composite build dependencies can't be substituted in using the `Settings::pluginManagement` block, you have to apply your plugin and hope that the extensions get generated correctly. 

This results in weird samples like this ([taken from here](https://github.com/JLLeitschuh/ktlint-gradle/blob/master/samples/kotlin-ks/build.gradle.kts)):
```kotlin
import org.jlleitschuh.gradle.ktlint.KtlintExtension
import org.jlleitschuh.gradle.ktlint.reporter.ReporterType

plugins {
    application
}

plugins.apply("org.jlleitschuh.gradle.ktlint")
apply {
    plugin("kotlin")
}

// ...

configure<KtlintExtension> {
    verbose.set(true)
    outputToConsole.set(true)
    coloredOutput.set(true)
    reporters.set(setOf(ReporterType.CHECKSTYLE, ReporterType.JSON))
}
```

### Your Environment

```
------------------------------------------------------------
Gradle 4.10.2
------------------------------------------------------------

Build time:   2018-09-19 18:10:15 UTC
Revision:     b4d8d5d170bb4ba516e88d7fe5647e2323d791dd

Kotlin DSL:   1.0-rc-6
Kotlin:       1.2.61
Groovy:       2.4.15
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          10.0.1 ("Oracle Corporation" 10.0.1+10)
OS:           Mac OS X 10.14 x86_64

```

**Comment by mkobit** [comment]
Why isn't this allowed:

```kotlin
plugins {
  id("org.gradleweaver.plugins.simple-jlink") // This isn't allowed
}
```
I do this in my plugins and use [`GradleRunner.withPluginClassPath()`](https://docs.gradle.org/current/javadoc/org/gradle/testkit/runner/GradleRunner.html#withPluginClasspath--) and the [`java-gradle-plugin`](https://docs.gradle.org/current/userguide/java_gradle_plugin.html) and everything seems to work fine for me. 

Is this something specific to composite (from referenced issue above)?

**Comment by JLLeitschuh** [comment]
@eskatos Introduced a bunch of complexity into the `ktlint-gradle` test ecosystem.
For example all of our tests use this function to add the plugin to our test classpath:
https://github.com/JLLeitschuh/ktlint-gradle/blob/master/plugin/src/test/kotlin/org/jlleitschuh/gradle/ktlint/AbstractPluginTest.kt#L19-L28

@eskatos Has the issue that required you to add this block of code been resolved?

> Work around Gradle TestKit limitations in order to allow for compileOnly dependencies
https://github.com/JLLeitschuh/ktlint-gradle/blob/617987c0170b034b941b87ffbe6ea8b86d459a30/plugin/build.gradle.kts#L39-L53

**Comment by tbroyer** [comment]
@JLLeitschuh You can use the plugins DSL in your build, even if you're deploying to a local repository, by using `pluginManagement {}` in the project's settings: https://github.com/tbroyer/gradle-errorprone-plugin/blob/d36cf009776592cd6bed22d49a3265583a3d8d2f/src/test/kotlin/net/ltgt/gradle/errorprone/AbstractPluginIntegrationTest.kt#L41-L62

**Comment by JLLeitschuh** [comment]
I'm going to close this as resolved.
