### ISSUE TITLE
All-open compiler plugin 

### ISSUE THREAD

**Issue by jmfayard** [gradle/kotlin-dsl#1189]
```kt
class MyTask: DefaultTask()

project.tasks.register<MyTask>("myTask")
``` 

This code failed with this exception:

> Could not create task ':myTask'.
> Cannot create a proxy class for final class 'MyTask'.

- Gradle expects all classes to be open
- Kotlin likes to make all classes final. 

Spring had exactly the same problem and JetBrains wrote a compiler plugin for them. Some annotation has to be defined for all classes that Gradle wants to make open, and then we do something like this

```
plugins {
  id "org.jetbrains.kotlin.plugin.allopen" version "1.2.71"
}
allOpen {
    annotation("org.gradle.SomeAnnotation")
}
```

https://kotlinlang.org/docs/reference/compiler-plugins.html

**Comment by eskatos** [comment]
Closing as a duplcate of #390
