### ISSUE TITLE
Migrate to the latest build cache API

### ISSUE THREAD

**Issue by eskatos** [gradle/kotlin-dsl#1193]
Since build caching of compiled script was implemented the build-cache api got better and using `BuildCacheCommandFactory` should simplify the implementation.

**Comment by bamboo** [comment]
Requires a new Gradle distro built from `gradle/gradle@master`.

**Comment by bamboo** [comment]
After further investigation `BuildCacheCommandFactory` doesn't really help making the implementation simpler. 

I'm changing the scope of this issue to be about migrating to the new API only.
