### ISSUE TITLE
Build cache key for Kotlin script compilation is not helpful in build operation descriptions

### ISSUE THREAD

**Issue by big-guy** [gradle/kotlin-dsl#1196]
### Expected Behavior
Build cache operations would look like "regular" build cache operations.

### Current Behavior
Build cache operation description shows the default toString() for a Java object.

### Context
I noticed this in the IDE.
![image](https://user-images.githubusercontent.com/5387972/47186800-ba5dc100-d2ff-11e8-882d-96d90da62037.png)

The reason this works for "Load" is something on the gradle/gradle side.  We should fix this to be more consistent in gradle/gradle, but the quick fix is to implement toString in the same way as `DefaultTaskOutputCachingBuildCacheKey`.

### Steps to Reproduce (for bugs)
Import gradle/gradle and look at the build operations generated for kotlin build scripts.

### Your Environment
This always happens.

**Comment by eskatos** [comment]
Closing as delivered in #1279
