### ISSUE TITLE
Reduce code generation overhead

### ISSUE THREAD

**Issue by bamboo** [gradle/kotlin-dsl#1202]
Each code generator use one separate short-lived IO thread per project which in the worst case (first-use no cache) leads to the creation of at least one thread per project in a multi-project and two for the root project.

Follow up to #1199

**Comment by JLLeitschuh** [comment]
Could coroutines help here?

Also, in my project this will result in something like 70 thread being created, for the core Gradle project, it will be 85 threads.

**Comment by bamboo** [comment]
Implemented by #1245.
