### ISSUE TITLE
Missing: an android migration sample

### ISSUE THREAD

**Issue by jmfayard** [gradle/kotlin-dsl#1208]
### Expected Behavior
Let say I am an android developer (so, using Gradle) but new to the Kotlin DSL.
Given that I go to https://github.com/gradle/kotlin-dsl/blob/master/samples/README.md, I expect to find a realistic sample that would give me an idea of what it would be like if I decide to migrate partially my project to the Kotlin-DSL. There is not such a thing, the information on how I would do that is scattered among different samples.

### Current Behavior

Currently:
- the `hello-android` sample would give me an idea of what it is like to start an android project from scratch
- there are three different projects using a buildSrc but It's not really clear that why I would need that in my use case
- there are other samples with some features I would also benefit from, but likewise it's a bit all over the place

### Suggestion

I would suggest a new android sample that is closer to what could happen in the real world (a partial migration from a real world project)

- that would has both groovy and kotlin modules (since nobody has time to rewrite all its build from scratch)
- with typical build logic extracted to the buildSrc. For android developpers, this means typically extracting the dependencies versions, and the variables we usually write in Groovy for things like compileSdkVersion, .... [example here](https://github.com/jmfayard/gradledemo/blob/master/buildSrc/src/main/kotlin/Config.kt#L21-L27)
- (optional) with a simple plugin to benefits from the Kotlin DSL even if the buildscript is still written in Gradle like https://github.com/jmfayard/gradledemo/commit/896ea008fea9d792d69dad122addc76d09ebce54

This is what I built for myself here, and if you are interested, I could contribute a simpler version of it to the samples directory.

https://github.com/jmfayard/gradledemo

**Comment by StefMa** [comment]
From my point of view you suggest three *complete* different things here:
1. An "more realistic android project" - whatever this means
2. A better explanation what the buildSrc is and how can a developer get value of it
3. How to create a plugin which can help a developer even more

These three things are totally independent topics. At the first place.
Combining each of them into one project could demonstrate how to benefit of "all Gradle features" in general. But that have nothing to do with the Kotlin DSL only.

Whatever. What I want to say is:
Your project helps "advanced Gradle developers". But not "Gradle starters". The would be more confused about all the things happen and why they should use it.

**Comment by jmfayard** [comment]
@StefMa To rephrase: I'm specifically talking about people wondering whether and how to migrate an existing Android project from Groovy to Kotlin. 

Why is this important? 
- because that's a huge number of projects out there
- because android projects tend to have a more complex Gradle configuration (multiples modules, the Android Gradle Plugin has a huge API) 
- because in this case, migration strategy 2. is IMHO much more meaningful than migration strategy 1.

> Migration strategies

> As we’ve seen above, both scripts using the Kotlin DSL and those using the Groovy DSL can participate in the same build. In addition, Gradle plugins from the buildSrc directory, an included build or an external location can be implemented using any JVM language. This makes it possible to migrate a build progressively, piece by piece, without blocking your team.
> Two approaches to migrations stand out:
> 1. Migrating the existing syntax of your build to Kotlin, bit by bit, while retaining the structure — what we call a mechanical migration
> 2. Restructuring your build logic towards Gradle best practices and switching to Kotlin DSL as part of that effort

https://guides.gradle.org/migrating-build-logic-from-groovy-to-kotlin/#migration_strategies

**Comment by StefMa** [comment]
And that sounds a little bit different from that what you initial wrote 🙃 
I agree with you here.
But I would suggest that we shouldn't create a project with a Plugin (most of the Android projects doesn't have this - unfortunately) and use the `buildSrc` only for "easy" things. Like in your example with "shared" versionNumbers of dependencies.

I think nothing could prevent you to create such an sample and create PR here 🙃

**Comment by jmfayard** [comment]
A Gradle Guide is probably better suited for what I have in mind, so closing this in favor of:
https://github.com/gradle/guides/issues/195
