### ISSUE TITLE
After change from gradle to kts, instrumentation test didn't work

### ISSUE THREAD

**Issue by pokk** [gradle/kotlin-dsl#1229]
Yesterday I tried to change gradle to kts in my android project. UI testing worked well before I change.
Is it kts problem or my environment problem? I google a lot but I counldn't find a way to fix it :(

### Current Behavior

UI test didn't work well after I change to kts.

This is from LogCat

<img width="1325" alt="jietu20181102- 14227" src="https://user-images.githubusercontent.com/5198104/47894245-30882900-dea5-11e8-9173-5c7754c9d4e7.png">

This is from Run

```
Client not ready yet..
Started running tests
Test running failed: Instrumentation run failed due to 'Process crashed.'
```

Also It says can't find my test case.

### Context

The test code is like 

```kotlin
@LargeTest
@RunWith(AndroidJUnit4::class)
class FragmentTest {
    @Before
    fun setUp() {
        ActivityScenario.launch(Activity::class.java)
    }

    @Test
    fun initialState() {
		...
    }

    @Test
    fun enableButton() {
		...
    }
```

### Your Environment

my app:gradle is 

```gradle
android {
	...
    defaultConfig {
        ...
        minSdkVersion(21)
        targetSdkVersion(28)
        multiDexEnabled = true
        versionCode = 1
        versionName = "1.0"
        testInstrumentationRunner = "android.support.test.runner.AndroidJUnitRunner"
    }
	...
}
```

I'm using the newest Kotlin DSL version 

```
distributionUrl=https\://services.gradle.org/distributions/gradle-5.0-rc-1-all.zip
```

**Comment by StefMa** [comment]
I'm not hundred percent sure if the AGP (Android Gradle Plugin) works with Gradle 5.0?!
Could check if it works with Gradle 4.10.2?

**Comment by pokk** [comment]
I'm so sorry that I didn't explain clearly. I was using Gradle 4.10.2 in the beginning. It didn't work so I upgrade to Gradle the newest version. But it still doesn't work.

**Comment by eskatos** [comment]
@pokk it's hard to tell what's happening without knowing what AGP version you use or, better, a reproducer project, could you provide that?

**Comment by pokk** [comment]
@eskatos Thank you for the reminder.

```kts
    dependencies {
        val kotlinVersion: String by rootProject.extra

        classpath("com.android.tools.build:gradle:3.2.1")
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion")  // Kotlin version is 1.3.0

        // NOTE: Do not place your application dependencies here; they belong
        //  in the individual module build.gradle files

        classpath("com.google.gms:google-services:4.2.0")  // google-services plugin
        classpath("android.arch.navigation:navigation-safe-args-gradle-plugin:1.0.0-alpha07")
    }
```

I'm using 3.2.1 now. If there's not enough information, please let me know.

**Comment by pokk** [comment]
I feel so sorry. After checked my gradle file and kts file, I found the `testInstrumentationRunner` value are difference.

```gradle
    defaultConfig {
		...
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"  // It's androidx
		...
    }
```

but my kts is

```kts
    defaultConfig {
		...
        testInstrumentationRunner = "android.support.test.runner.AndroidJUnitRunner"  // because I referenced other projects and copied directly.
		...
    }
```

I really feel so sorry and thank you guys for taking your time.

**Comment by eskatos** [comment]
Thanks for getting back to us and glad you got it working!
Closing as invalid
