### ISSUE TITLE
Move gradle/kotlin-dsl into gradle/gradle

### ISSUE THREAD

**Issue by eskatos** [gradle/kotlin-dsl#1232]
The Gradle Kotlin DSL is coupled with Gradle's core, the relationships go both ways. The Kotlin DSL started as a separate repository, it is now time to integrate it closer to Gradle core.

Those cyclic dependencies are the cause of most of the pain one can experience when working on the code base. For example, in order to bring a tiney change in Gradle API or internals to the `gradle/kotlin-dsl` repository it requires a dedicated "snapshot gradle distribution" built from a specially crafted rolling branch to be able to update the wrappers in `gradle/kotlin-dsl`. The other way around, when changing a Gradle API in `gradle/gradle` for which the Kotlin DSL support relies on Kotlin implementation by delegation, one can't write Kotlin DSL tests in `gradle/gradle` until a new release of the Kotlin DSL is integrated into `gradle/gradle`. Those two scenarios happen more often than desirable, this is causing pain to all teams working on Gradle.

We considered two options to fix this situation:
- leverage composite builds
- meld the Kotlin DSL into `gradle/gradle`

We chose the second option to not conflate many goals. Leveraging composite builds would require drastic changes to how the `gradle/gradle` build is organized and extract a lot from it (e.g. fixtures), possibly disturbing developer productivity and failing at releaving the pain. Not talking about the quirks in IDE support for complex composite builds scenarios. Also, there are many other Gradle components that are better candidates for this given they are not as core as the Kotlin DSL, e.g. plugins.

By moving to `gradle/gradle` we'll be able to leverage lots of goodness from the `gradle/gradle` build and tools, from the CI pipeline to custom static code analysis or cross-version TAPI testing.

This will also mean that the Kotlin DSL version will then be the Gradle version. In other words, no more separate versionning, thus lessening a rather frequent confusion. The release process will be simplified as there won't be a separate release for just the Kotlin DSL as a prerequisite for a Gradle release.

**Comment by JLLeitschuh** [comment]
😢 Oh no! As an external contributor, I personally enjoy having this be a separate project. It makes this project far more accessible. The gradle/gradle repo can be an overwhelming beast of a project for any first-time contributor.

It has also allowed me to follow the development of this project specifically without being overwhelmed by the significantly higher number of issues & PR's opened against gradle/gradle.

Would someone from the Gradle team be willing to provide some explanation around this decision? I can imagine that it significantly simplifies the release pipeline.

**Comment by fuzzyweapon** [comment]
I would like to retain the ability to search for issues specific to kotlin-dsl when this is migrated.  I'm sure this is something that is probably already an internal requirement, but just want to throw it out there.

**Comment by eriwen** [comment]
I imagine there will be a #kotlin-dsl label for this @fuzzyweapon. Hope that serves your needs.
