### ISSUE TITLE
Instead of "Avoiding Gradle Kotlin DSL internal APIs", actually hide the APIs

### ISSUE THREAD

**Issue by JLLeitschuh** [gradle/kotlin-dsl#1249]
APIs like `Gradle.serviceOf` are in a weird state where they are "documented private" but this isn't actually enforced by the compiler or a standard convention.

As a user of the Gradle Kotlin DSL, or as developer reviewing a PR with changes to a `build.gradle.kts` file, I should be able to easily ascertain that some Gradle Kotlind DSL API being used is a "Gradle internal API". This is usually easily determined by looking at the import statements. 

Seeing `import org.gradle.api.**.internal.**` is a quick giveaway when looking at code that the imported API shouldn't be being used. Imports like `org.gradle.kotlin.dsl.support.serviceOf` do not conform to what has generally been considered the norm for the Gradle API.

# Proposals to resolve

There are certainly other ways this could probably be resolved, these are the two I've come up with.

### Pros
 - Consistent with the rest of the Gradle API.
### Cons
 - The API is still public from the perspective of the compiler.
 - If there are any inline functions using these API's they can't be moved.
 - A large amount of churn in the code structure.

## Use the Kotlin `internal` access modifier on these APIs
If other components (subprojects) of the Gradle API needs to access these internal APIs, the Gradle Kotlin compiler could take advantage of the `friendPaths` compiler option to allow other sub-projects to access internal API's they normally would be forbidden from accessing.

### Pros
 - These `internal` APIs would be protected at the compiler level, preventing them from accidentally being used.
### Cons
 - Inconsistent with how the rest of the Gradle codebase handles `internal` code.
 - The `friendPaths` compiler option is pretty much completely undocumented. The `KotlinCompile` task doesn't expose a public way of configuring the `friendPaths`.

**Comment by eskatos** [comment]
Dropped for now. Please open an issue on `gradle/gradle` if you feel strongly about it
