### ISSUE TITLE
Is there a way to publish and import extension functions?

### ISSUE THREAD

**Issue by lamba92** [gradle/kotlin-dsl#1253]
A plugin seems an overkill for that.

**Comment by StefMa** [comment]
Which extension functions do you mean?

**Comment by bamboo** [comment]
@lamba92 a regular library of Kotlin functions would do, then you could import it in the usual way using the `buildscript` block of the root project.

**Comment by JLLeitschuh** [comment]
Are you looking for a DSL agnostic way of adding extension functions?

**Comment by JLLeitschuh** [comment]
Related: https://github.com/gradle/gradle/issues/7427

**Comment by lamba92** [comment]
> @lamba92 a regular library of Kotlin functions would do, then you could import it in the usual way using the `buildscript` block of the root project.

I think this should work. Can you show an example?


> Are you looking for a DSL agnostic way of adding extension functions?

I'm talking about writing some commodity extension functions  or just functions and reuse them later.  Like here: https://github.com/Kotlin/kotlin-frontend-plugin/issues/31#issuecomment-430225448
