### ISSUE TITLE
The gradle/kotlin-dsl test suite should pass on Java 11

### ISSUE THREAD

**Issue by eskatos** [gradle/kotlin-dsl#1296]
A couple tests currently fail https://scans.gradle.com/s/i4pqoi47ecmba/tests/failed

One is a cross-version test that tries to run Kotlin 1.2.21 that doesn't support Java 11.
The other one tries to use a Jacoco version that doesn't support Java 11.

Preconditions should be added to the tests.

**Comment by bamboo** [comment]
Fixed in 22afbe002e82097f35e017ecb353524f155c3bdb, d902379b22b1f9be01d47c9d3006090ae8333962 and 54bc0eb7d5886bdc8d868be57c0403029fbc9b69.
