### ISSUE TITLE
Provide helper functions for matching repositories for dependencies

### ISSUE THREAD

**Issue by jmfayard** [gradle/kotlin-dsl#1309]
Gradle 5.1 has added a nice feature to match repositories to dependencies

https://docs.gradle.org/5.1/userguide/declaring_repositories.html#sec::matching_repositories_to_dependencies

But the ergonomics around this API are a bit cumbersome. It seems like Gradle just exposed the internal include/exclude mechanism instead of providing more useful APIs to convey intent

### Expected Behavior

I would like to be able to write something like this:

```kotlin
repositories {
    google()
        .ensureGroups( "io.fabric", "com.crashlytics")
        .ensureGroupsByRegexp("androidx.*", "com.android.*" , "com.google.android.*" )
   mavenCentral()
}
```

### Current Behavior

- Cumbersome syntax
- Implicit side effects that are not very clear.

### Your Environment

 * Gradle 5.1

### Context

This was discussed in the Android Study Group slack channel

https://androidstudygroup.slack.com/archives/C03KKLGC2/p1546896139083100

To solve this problem, I proposed the following extension functions:

```kotlin
// buildSrc/src/main/kotlin/repositories.kt
@file:JvmName("Repositories")

fun MavenArtifactRepository.ensureGroups(vararg group: String): MavenArtifactRepository = apply {
    content {
        for (g in group) {
            includeGroup(g)
        }
    }
}
fun MavenArtifactRepository.ensureGroupsByRegexp(vararg regexp: String): MavenArtifactRepository = apply {
    content {
        for (g in regexp) {
            includeGroupByRegex(g)
        }
    }
}
```

**Comment by StefMa** [comment]
As far as I know the Kotlin DSL is "just another language".
it's intention is **not** to have a "better"/different syntax or any other sugar to the Groovy DSL.

But there are other task you could do:
* Create a ticket in gradle/gradle and complain about the current API. Maybe the team will think about it and change the it.
* Meanwhile you could create your own plugin which brings these extension build in. You could use [these "trick"](https://github.com/gradle/kotlin-dsl/issues/1185) for that.

**Comment by jmfayard** [comment]
Ok, makes sense.
