### ISSUE TITLE
Buildship support

### ISSUE THREAD

**Issue by bamboo** [gradle/kotlin-dsl#131]
Superseded by https://github.com/eclipse/buildship/issues/222

**Comment by pioterj** [comment]
Buildship support will be handled mostly by @donat, right? Is there any work for @bamboo to do on this front other than guidance?

**Comment by donat** [comment]
That is correct, I'm responsible for the Kotlin support in Buildship. I'll need guidance from @bamboo, I don't think that he needs to be deeply involved in this story.

**Comment by eskatos** [comment]
Superseded by https://github.com/eclipse/buildship/issues/222
