### ISSUE TITLE
configurations.classpath.exclude group not working

### ISSUE THREAD

**Issue by ColtonIdle** [gradle/kotlin-dsl#1313]
I'm migrating my Android project slowly but surely to kotlin dsl.

I had a line in the usual root build.gradle file

configurations.classpath.exclude group: 'com.android.tools.external.lombok'

inside of the buildscript { } block. It converted it to this

I tried changing it to

`configurations.classpath.exclude group: "com.android.tools.external.lombok"`

and

`configurations.classpath.exclude(group ="com.android.tools.external.lombok")'

with no luck. 

I tried looking up documentation and questions related to configurations.classpath.exclude kotlin dsl without much luck. I feel like I'm missing something basic here that I'm unfamiliar with. Any help is appreciated.

**Comment by bamboo** [comment]
Hi @ColtonIdle,

Here's the equivalent Kotlin DSL code:

```kotlin
    configurations.classpath {
        exclude(group = "com.android.tools.external.lombok")
    }
```

The main difference compared to the Groovy DSL is that `configurations.classpath` doesn't return the `Configuration` itself but an indirection intended to enable [lazy configuration](https://docs.gradle.org/current/userguide/lazy_configuration.html), also called _configuration avoidance_ in the docs: 
> Note that accessors for elements of containers such as configurations, tasks and sourceSets leverage Gradle’s configuration avoidance APIs. For example, on tasks they are of type TaskProvider<T> and provide a lazy reference and lazy configuration of the underlying task.
From the [Gradle Kotlin DSL Primer](https://docs.gradle.org/5.1/userguide/kotlin_dsl.html#type-safe-accessors).

I hope that answers your question.

**Comment by ColtonIdle** [comment]
@bamboo it does answer my question! Thank you very much!
