### ISSUE TITLE
No main manifest attribute in jar file

### ISSUE THREAD

**Issue by SparrowA** [gradle/kotlin-dsl#1314]
I can't generate jar for my kotlin application.
I have gradle dsl script
```kotlin
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    application
    kotlin("jvm") version "1.3.11"
}

group = "DataCheck"
version = "1.0-SNAPSHOT"

application {
    mainClassName = "com.MainKt"
}

repositories {
    mavenCentral()
}

dependencies {
    compile(kotlin("stdlib-jdk8"))
    implementation(files("lib/SimpleExcelReader.jar"))
}

tasks.withType<Jar> {
    manifest {
        attributes["Main-Class"] = application.mainClassName
    }

    from(configurations.runtime.get().map {if (it.isDirectory) it else zipTree(it)})
}

tasks.withType<KotlinCompile> {
    kotlinOptions.jvmTarget = "1.8"
}
```

And structure of my project:

![image](https://user-images.githubusercontent.com/5427830/51236467-44f7a000-1983-11e9-8c10-a4ca50ad6aec.png)

When I generate jar file, it does not contains correct MANIFEST.MF file:
![image](https://user-images.githubusercontent.com/5427830/51236732-f39be080-1983-11e9-8851-cfd082c019bc.png)

but I expected something like this:
![image](https://user-images.githubusercontent.com/5427830/51236789-1928ea00-1984-11e9-9208-ba567e9251b2.png)

**Comment by StefMa** [comment]
I've just copied your code (more or less) and run `gradle build`. The `build/libs/*.jar` contains the correct Manifest like you expect.

<details>
<summary>build.gradle.kts</summary>

```kotlin
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile
import org.gradle.api.tasks.bundling.Jar

plugins {
  application
  kotlin("jvm") version "1.3.11"
}

group = "DataCheck"
version = "1.0-SNAPSHOT"

application {
  mainClassName = "com.MainKt"
}

repositories {
  mavenCentral()
}

dependencies {
  compile(kotlin("stdlib-jdk8"))
  implementation(files("lib/SimpleExcelReader.jar"))
}

tasks.withType<Jar> {
  manifest {
    attributes["Main-Class"] = application.mainClassName
  }

  from(configurations.runtime.get().map {if (it.isDirectory) it else zipTree(it)})
}

tasks.withType<KotlinCompile> {
  kotlinOptions.jvmTarget = "1.8"
}
```

</details>

Then running
```
gradle build
```
(With Gradle 5.1.1)

The output:
![bildschirmfoto 2019-01-16 um 10 33 21](https://user-images.githubusercontent.com/10229883/51239623-2b058f80-197a-11e9-80b9-0e31cf8e677a.png)

**Comment by voghDev** [comment]
@SparrowA @StefMA could you indicate the Package name inside your main.kt file? or provide a small part of the Main class? could be helpful for me. I'm finding the same error compiling a Kotlin HelloWorld example in console (no IntelliJ, just commands)

**Comment by StefMa** [comment]
@voghDev 
I've just created a sample project here:
[kotlindsl-issue1314.zip](https://github.com/gradle/kotlin-dsl/files/3320515/kotlindsl-issue1314.zip)

Hope this helps...

**Comment by JoeBonifazi** [comment]
I am a noob.  New to java, kotlin, gradle, gradle DSL 
I stumbled upon your post trying to solve my own environment issues.
Your example build.gradle.kts helped me a lot.

I looked at your zip, and your main.kt source.
I am guessing you need
`package mainkt `
as line 1 in your main.kt source file.

**Comment by sylhare** [comment]
I came accross this error. I had to modify the jar task, to manually add the main class in the manifest:

https://stackoverflow.com/a/61372736/7747942
