### ISSUE TITLE
buildSrc/build.gradle.kts cannot resolve references defined in buildSrc/src

### ISSUE THREAD

**Issue by ninrod** [gradle/kotlin-dsl#1320]
### Expected Behavior
The user should be able to reference objects and functions defined in his buildSrc/src/main/kotlin directory.

### Current Behavior
I have a working kotlin dsl gradle build: [kotlin-dsl-gradle-experiment](https://github.com/ninrod/kotlin-dsl-gradle-experiment)

I've written a function in my buildSrc/src/main/kotlin/test.kt file as follows: 

```kotlin
package org.ninrod.backend.build

import java.io.File

fun doWeHaveToUseArtifactory(): Boolean {
    val centos = File("/etc/centos-release").exists()
    val workbench = File("/etc/hostname").readText().trim() == "workbench"
    return centos && workbench
}
```

I'd love to use that function inside my buildSrc/build.gradle.kts instead of duplicating myself in [every kotlin dsl block](https://github.com/ninrod/kotlin-dsl-gradle-experiment/blob/master/buildSrc/build.gradle.kts):

```kotlin
buildscript {
    val artifactory = "http://artifactory/artifactory/gradle"
    fun doWeHaveToUseArtifactory(): Boolean {
        val centos = File("/etc/centos-release").exists()
        val workbench = File("/etc/hostname").readText().trim() == "workbench"
        return centos && workbench
    }
    repositories {
        if (doWeHaveToUseArtifactory()) {
            println("configuring artifactory for plugin repos")
            maven {
                url = uri(artifactory)
            }
        } else {
            println("we are using mavencentral for plugins")
            maven {
                mavenCentral()
                jcenter()
            }
        }
    }
    dependencies {
        if (doWeHaveToUseArtifactory()) {
            println("we are going to add the classpath of the org.jfrog.buildinfo plugin")
            classpath("org.jfrog.buildinfo:build-info-extractor-gradle:4.9.0")
        }
        classpath("gradle.plugin.org.gradle.kotlin:gradle-kotlin-dsl-plugins:1.1.1")
    }
}

apply(plugin = "org.gradle.kotlin.kotlin-dsl")


allprojects {
    repositories {
        val artifactory = "http://artifactory/artifactory/gradle"
        fun doWeHaveToUseArtifactory(): Boolean {
            val centos = File("/etc/centos-release").exists()
            val workbench = File("/etc/hostname").readText().trim() == "workbench"
            return centos && workbench
        }
        if (doWeHaveToUseArtifactory()) {
            maven {
                url = uri(artifactory)
            }
        } else {
            mavenCentral()
            jcenter()
        }
    }
}
```

### Context
this affects all kotlin-dsl users that have to configure interesting/complex behaviour and have to resort to logic which should be reusable.

These actions does not work: 

* importing the function
* referencing by full qualified name

### Steps to Reproduce (for bugs)

simply clone the [kotlin-dsl-gradle-experiment](https://github.com/ninrod/kotlin-dsl-gradle-experiment) and verify the behaviour: 

```sh
$ git clone https://github.com/ninrod/kotlin-dsl-gradle-experiment.git
$ cd kotlin-dsl-gradle-experiment
$ gradle build
# verify that the build works
# now try to change the buildSrc/build.gradle.kts to reuse the function define in buildSrc/src/main/kotlin/test.kt

$ gradle build
# verify that nothing works
```

### Your Environment

------------------------------------------------------------
Gradle 5.1.1
------------------------------------------------------------

Build time:   2019-01-10 23:05:02 UTC
Revision:     3c9abb645fb83932c44e8610642393ad62116807

Kotlin DSL:   1.1.1
Kotlin:       1.3.11
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          1.8.0_192 (Oracle Corporation 25.192-b12)
OS:           Linux 4.9.87-linuxkit-aufs amd64

**Comment by JLLeitschuh** [comment]
You can see a potential way to solve this problem here:

I created a script that I could apply from either context and then call a function that that script exports.

https://github.com/gradle/kotlin-dsl/issues/821#issue-314655076

**Comment by ninrod** [comment]
@JLLeitschuh that's so hacky. So I understand that there is no support yet for code reuse when using the buildSrc strategy, yes?

**Comment by ninrod** [comment]
I understand. I did not quite grasp the workaround though. Do you have a repo somewhere where this strategy is working? for reference purpouses?

**Comment by eskatos** [comment]
Gradle is working as intended wrt the original issue description:

> `buildSrc/build.gradle.kts` cannot resolve references defined in `buildSrc/src`

This is a chicken and egg problem. `buildSrc/build.gradle.kts` contains the build logic that describes how to build the code from `buildSrc/src`, so it cannot depend on what gets built.

Trying to work around that using some dynamic construct won't make things easy.

Now, if you want to share code type-safely between your "`buildSrc` build logic"' and "`buildSrc` sources" you need to extract that code into something new. That new thing is another build, either via a published artifact or a Gradle included build. The recent [webinar on the Kotlin DSL](https://gradle.com/blog/getting-started-with-gradle-kotlin-dsl/) will provide some answers, also see [Integrating Separate Gradle build](https://docs.gradle.org/current/userguide/composite_builds.html) in the user guide.

Please use the Gradle forums for support questions https://discuss.gradle.org/

**Comment by bejibx** [comment]
> Now, if you want to share code type-safely between your "buildSrc build logic"' and "buildSrc sources" you need to extract that code into something new. That new thing is another build, either via a published artifact or a Gradle included build. The recent webinar on the Kotlin DSL will provide some answers, also see Integrating Separate Gradle build in the user guide.

I tried it but sadly got error message “Cannot include build ‘dependenciesDigest’ in build ‘buildSrc’. This is not supported yet.”. I’m using Gradle version 5.4.1
