### ISSUE TITLE
Add support for Kotlin in binary compatibility check

### ISSUE THREAD

**Issue by eskatos** [gradle/kotlin-dsl#1332]
- [x] Add support for Kotlin in AbstractGradleViolationRule.isOverride
- [x] Add support for Kotlin in SinceAnnotationMissingRule
- [x] Assess japicmp behavior over Kotlin bytecode
- [x] Consider using the Kotlin compiler to produce an api jar
    The Kotlin compiler plugin that generates API classes couldn't be used as it works at Kotlin compilation time and can't be used after the fact.

Outcome should be a reasonable best effort check and identified follow ups.

**Comment by eskatos** [comment]
PR https://github.com/gradle/gradle/pull/8895

**Comment by eskatos** [comment]
Identified follow ups

- Kotlin only
  - exclude [Kotlin synthetic private accessors](https://medium.com/@iateyourmic/synthetic-accessors-in-kotlin-a60184afd94e) from the check, like `internal` members
  - add `org.gradle.kotlin.dsl.plugins.dsl.*` to the check
- Both Java and Kotlin
  - consider parameter name changes code as breaking
  - consider nullability change as breaking

**Comment by JLLeitschuh** [comment]
> exclude Kotlin synthetic private accessors from the check, like internal members

You need to ensure you don't exclude methods annotated with the Kotlin annotation `@PublicAPI`

**Comment by eskatos** [comment]
Good point @JLLeitschuh, I assume you meant [`@PublishedApi`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-published-api/index.html)

**Comment by JLLeitschuh** [comment]
Yes, exactly! Thanks.

**Comment by eskatos** [comment]
Another follow up: typealiases used in function signatures aren't handled

**Comment by eskatos** [comment]
Closing as delivered in https://github.com/gradle/gradle/pull/8895
