### ISSUE TITLE
Empty connected tests report

### ISSUE THREAD

**Issue by BulatMukhutdinov** [gradle/kotlin-dsl#1352]
After running 
```
./gradlew connectedAndroidTest 
```
index.html shows empty result
### Expected Behavior
index.html shows the actual result of execution
### Current Behavior
index.html is empty
### Context
you can check it in my sample project https://github.com/BulatMukhutdinov/Sample
run 
```
./gradlew connectedAndroidTest 
```
and check index.html

**Comment by eskatos** [comment]
Please use the Gradle forms for support questions
https://discuss.gradle.org/

**Comment by BulatMukhutdinov** [comment]
But it is not a question. It seems to be a bug in Kotlin DSL

**Comment by eskatos** [comment]
It works for me

![image](https://user-images.githubusercontent.com/132773/56716716-4c290980-673b-11e9-835c-5b8d4c8daa56.png)
