### ISSUE TITLE
KotlinBuildScriptDependenciesResolver should return valid javaHome

### ISSUE THREAD

**Issue by NataliaUkhorskaya** [gradle/kotlin-dsl#1354]
`KotlinBuildScriptDependenciesResolver` should contains `javaHome` in the returned script dependencies. Otherwise  `gradle.kts` scripts can be highlighted with errors if non-java sdk is set as Project SDK in Intellij IDEA

related tiked: https://youtrack.jetbrains.com/issue/KT-21501

### Expected Behavior
`ScriptDependencies.javaHome` is set to some valid value. It can be obtained from `environment` parameter passed into `resolve` method.

### Current Behavior
`javaHome` is null

**Comment by eskatos** [comment]
This will ship in Gradle 5.4

**Comment by eskatos** [comment]
@NataliaUkhorskaya, this shipped in Gradle 5.4
We are seeing some issues with IntelliJ Kotlin plugin 1.3.30 not recognizing JDK types in the script editor:

![image](https://user-images.githubusercontent.com/132773/56199965-31211000-603e-11e9-9de9-86f5557aeae6.png)


Could it be related?

**Comment by JLLeitschuh** [comment]
@eskatos This looks like a Java 10+ issue. I'm guessing you wouldn't see that problem if the language version was set to Java 8. Just a thought.

**Comment by wolfs** [comment]
Using Java 8 in some places makes the problem go away...

**Comment by eskatos** [comment]
The script already uses Java 8 language version.

But yes, if the build is imported using Java 11 then this problem shows up, it doesn't happen if the build was imported using Java 8.

**Comment by eskatos** [comment]
The script already uses Java 8 language version.

But yes, if the build is imported using Java 11 then this problem shows up, it doesn't happen if the build was imported using Java 8.

**Comment by eskatos** [comment]
In my comment above it worked for me importing with Java 8 because both _Gradle
 JVM_ and _Project SDK_ were the same, not demonstrating the problem.

The root problem is that the Kotlin DSL IDEA script editor can't find JDK classes with Gradle 5.4 if Gradle JVM != Project SDK. See https://github.com/gradle/gradle/issues/9195
