### ISSUE TITLE
CPU exploding with trivial line

### ISSUE THREAD

**Issue by celcius112** [gradle/kotlin-dsl#1367]
The trivial line `assertThat(true).isTrue()` from the testing library [assertj](https://github.com/joel-costigliola/assertj-core) freezes my IDE (IntelliJ 2019.1).
 
When using the `kotlin-dsl` plugin the CPU simply explodes with that line, with more than 200% of the processing used on `org.jetbrains.kotlin.types.TypeApproximator`.

The problem can be reproduced with this [project](https://github.com/celcius112/kotlin-perf-test). See the [README](https://github.com/celcius112/kotlin-perf-test/blob/master/README.md) for more details on how to reproduce this problem.

You can find more information on my environment from https://scans.gradle.com/s/ziiye4ahx7faa/. 

I am using **Intellij 2019.1**. I am not opening an issue on Jetbrains because this issue only happens when the kotlin-dsl is present. I am also using Gradle 5.3.1 and the Intellij Kotlin plugin 1.3.21-release-IJ2019.1-3

**Comment by eskatos** [comment]
Please open an issue on IntelliJ Kotlin issue tracker https://youtrack.jetbrains.com/issues/KT

**Comment by mkobit** [comment]
I've been seeing this as well - it looks like @celcius112 opened up an issue at https://youtrack.jetbrains.com/issue/KT-29488
