### ISSUE TITLE
Multi-project build in which a project compiled against a newer version Kotlin depends on a project compiled against an older version of Kotlin 

### ISSUE THREAD

**Issue by bamboo** [gradle/kotlin-dsl#138]
An example would be using a more recent version of Kotlin in a test project (a project that contains the tests for another project).

Support configuring each KotlinCompile task on each subproject separately.

**Comment by bamboo** [comment]
Because of the ClassLoader relationship between root project and subprojects, this will require more thinking.

**Comment by bamboo** [comment]
Consider letting dependency resolution decide what's the correct version of the Kotlin runtime to use for the buildscript classpath by always adding an implicit dependency to the embedded Kotlin runtime version. 

This would require isolating the kotlin compiler from the buildscript classpath / runtime.

**Comment by oehme** [comment]
The Kotlin compiler used for compiling project sources should not be loaded from the `buildscript` classloader. It should be resolved from a plain old `Configuration` in each project that uses Kotlin.

If the Kotlin plugin currently doesn't isolate the compiler, it should be changed to do so. Either by using a URLClassloader to load the compiler or by forking it.

**Comment by bamboo** [comment]
Closing as invalid.
