### ISSUE TITLE
Confusing issue template in gradle/kotlin-dsl and gradle/gradle repositories

### ISSUE THREAD

**Issue by gildor** [gradle/kotlin-dsl#1383]
gradle/kotlin-dsl issue template contains this phrase:

> You may want to use the gradle/gradle issue tracker for issues about the Gradle Kotlin DSL itself

But gradle/gradle issue template has this:

> Please open Kotlin DSL-related issues at https://github.com/gradle/kotlin-dsl/issues

So essentially now there is no valid place for new Kotlin DSL issues, probably gradle/gradle template should be fixed, but I'm not sure

**Comment by eskatos** [comment]
Thanks for the report @gildor!
Fixed in https://github.com/gradle/gradle/commit/f99370710d1e64c19342675d4b7e052f65e3ee89
