### ISSUE TITLE
kotlin-android-extensions not working

### ISSUE THREAD

**Issue by javalue** [gradle/kotlin-dsl#1387]
I want to upgrade android targetsdkversion to 28.
When I impletement **com.google.android.gms:play-services-ads:18.0.0** after synchronization and build, my view can't find in xxxxxx.kt.

error:
xxxxxxx.kt: (100, 25): Unresolved reference. None of the following candidates is applicable because of receiver type mismatch:
public val Activity.tvNickname: TextView! defined in kotlinx.android.synthetic.main.aaa
public val Dialog.tvNickname: TextView! defined in kotlinx.android.synthetic.main.aaa
public val android.app.Fragment.tvNickname: TextView! defined in kotlinx.android.synthetic.main.aaa
public val androidx.fragment.app.Fragment.tvNickname: TextView! defined in kotlinx.android.synthetic.main.aaa

**Comment by eskatos** [comment]
Hi @javalue,
This looks like a Kotlin for Android issue.
You'll have a better chance to get help on the Kotlin issue tracker https://youtrack.jetbrains.com/issues/KT

**Comment by javalue** [comment]
> Hi @javalue,
> This looks like a Kotlin for Android issue.
> You'll have a better chance to get help on the Kotlin issue tracker https://youtrack.jetbrains.com/issues/KT

emmm, i know the reason
is't ok in activity， but not working in fragment, you should import kotlinx.android.synthetic.main.your_fragment**.view**.* focus ".view",
and use view.!!.tv1.text = "123"
however, i don't know why change it to this way?

**Comment by javalue** [comment]
it's just add a view，and find child by the view

**Comment by javalue** [comment]
it's maybe change in org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.0

**Comment by StefMa** [comment]
This has nothing to do with gradles kotlin DSL.
This is an kotlin feature. Questions, issues or feedback should be reported
at https://youtrack.jetbrains.com/issues/KT
