### ISSUE TITLE
Nag user about mixing Kotlin plugin versions in a multi-project build

### ISSUE THREAD

**Issue by bamboo** [gradle/kotlin-dsl#140]
Configuration injection in multi-project builds involving heterogeneous Kotlin version won't be supported and it's important the user is warned to correctly identify the problem (which might surface as a "ClassLoader constraint violation" or "Task not found").

**Comment by bamboo** [comment]
Relates to #138

**Comment by oehme** [comment]
This is a general problem of the [PluginManager](https://github.com/gradle/gradle/blob/66ce4568610da84087566b7607ca8e9dc107df57/subprojects/core/src/main/java/org/gradle/api/internal/plugins/DefaultPluginManager.java#L173) - it only checks for class equality, but not if another class of the same name was loaded in another classloader already. We should add a warning there.

**Comment by bamboo** [comment]
Closing as invalid.
