### ISSUE TITLE
Provide feedback to the user for editor classpath resolution errors

### ISSUE THREAD

**Issue by bamboo** [gradle/kotlin-dsl#151]
The TAPI model should be returned with information about the error even when the classpath cannot be computed as it could happen if the script fails to compile under certain conditions such as #150.

It should instead provide a model describing exactly what went wrong so the user can fix the script and retry.

**Comment by bamboo** [comment]
We should also move any useful information that would help diagnose the problem from the IntelliJ log into the [IntelliJ event log accessible directly in the IDE](https://kotlinlang.slack.com/archives/gradle/p1481827666000340).

**Comment by bamboo** [comment]
Throwing an exception with enough information gathered from the build might be enough.

**Comment by eskatos** [comment]
Closing as delivered in #866
