### ISSUE TITLE
Automatically detect and build Kotlin sources under buildSrc

### ISSUE THREAD

**Issue by bamboo** [gradle/kotlin-dsl#152]
Without requiring an explicit build.grade/build.gradle.kts script to apply the kotlin-gradle-plugin.

The default configuration should include `gradleScriptKotlinApi()` in the compile classpath (see #118).

Currently this is the boilerplate required for Kotlin buildSrc projects:

``` kotlin
            buildscript {
                configure(listOf(repositories, project.repositories)) {
                    gradleScriptKotlin()
                }
                dependencies {
                    classpath(kotlinModule("gradle-plugin"))
                }
            }
            apply {
                plugin("kotlin")
            }
            dependencies {
                compile(gradleScriptKotlinApi())
            }
```

**Comment by oehme** [comment]
The buildscript and apply boilerplate will disappear once we support the plugins DSL. The gradleScriptKotlinApi dependency is completely fine imho.

In fact, I'd rather remove the Groovy plugin from `buildSrc` in the future. Users can decide for themselves which language they want to use.

**Comment by bamboo** [comment]
Considering that we already embedded the Kotlin compiler, we could setup some specialised Kotlin compilation tasks upon detecting the presence of a default Kotlin source folder (`buildSrc/src/main/kotlin` or `buildSrc/src/test/kotlin`) but no Kotlin libraries in the buildscript classpath (meaning the user doesn't want to custom configure Kotlin compilation).

This should account for 80%+ of the Kotlin `buildSrc` scenarios.

**Comment by bamboo** [comment]
Superseded by #394
