### ISSUE TITLE
Fix Gradle integration test on Windows

### ISSUE THREAD

**Issue by bamboo** [gradle/kotlin-dsl#166]
See gradle/gradle@34aacbb93bb03cd21d73cba4f6f6b2f79b04b00a

**Comment by bamboo** [comment]
All Kotlin DSL tests are now enabled and green on Windows.

Follow-up (non critical) work to review the tests still leaking file handles has been recorded as #704.

**Comment by wolfs** [comment]
This issue does not appear to be fixed: See for example: https://builds.gradle.org/viewLog.html?buildId=10802834&tab=buildResultsDiv&buildTypeId=Gradle_Check_Platform_Java8_Oracle_Windows_integTest

**Comment by wolfs** [comment]
Ah, I guess `NestedInputKotlinImplementationTrackingIntegrationTest` still needs a `@LeaksFileHandles` annotation, right?

**Comment by bamboo** [comment]
@wolfs Right.
