### ISSUE TITLE
Script plugins with external dependencies defined in a buildscript block

### ISSUE THREAD

**Issue by bamboo** [gradle/kotlin-dsl#180]
For `*.gradle.kts` files including `Settings` script plugins (`*.settings.gradle.kts`).

**Comment by eskatos** [comment]
This is now done for scripts applied to project and settings.  Remain scripts applied from init scripts. Today you would have to use `initscript {}` in those applied scripts but it should be `buildscript {}` instead. Only the top level init scripts must use `initscript {}`.

**Comment by bamboo** [comment]
Closing as delivered for `Project` and `Settings` script plugins. For init script support see #870.

**Comment by thc202** [comment]
@bamboo or @eskatos should this change also allow applied scripts to apply plugins? (Same set up as described in #814. I didn't find any open issue with this use case, some were closed as duplicate other as superseded, might have missed it though. #425 would address it but not exactly the same and this use case is supported with Groovy).

I'm getting the following error:
```
FAILURE: Build failed with an exception.

* Where:
Script 'publishing-portal.gradle.kts' line: 12

* What went wrong:
Plugin with id 'com.gradle.plugin-publish' not found.
```

when attempting to apply a plugin from an applied script, e.g.:
`build.gradle.kts`
```Kotlin
apply(from = "publishing-portal.gradle.kts")
```

`publishing-portal.gradle.kts`
```Kotlin
buildscript {
    repositories {
        maven {
            url = uri("https://plugins.gradle.org/m2/")
        }
    }
    dependencies {
        classpath ("com.gradle.publish:plugin-publish-plugin:0.9.10")
    }
}

apply(plugin = "com.gradle.plugin-publish")
```

The above works fine if done directly in `build.gradle.kts`.

Versions:
```
------------------------------------------------------------
Gradle 4.8-rc-2
------------------------------------------------------------

Build time:   2018-05-24 09:28:21 UTC
Revision:     0b1824635622a85b201776fc1245b6a40f4a5b22

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          10.0.1 (Oracle Corporation 10.0.1+10-Ubuntu-3ubuntu1)
OS:           Linux 4.15.0-22-generic amd64
```

**Comment by bamboo** [comment]
That sounds like gradle/gradle#1262

**Comment by thc202** [comment]
Thanks! It works fine using the type. (I didn't look into Gradle issue tracker because it works fine with Groovy DSL and I was expecting that to just work in Kotlin DSL.)

**Comment by bamboo** [comment]
> it works fine with Groovy DSL

Hm, it shouldn't, gradle/gradle#1262 is about the Groovy DSL.

In fact I've just converted your repro scripts to the Groovy DSL and got the exact same error.

**Comment by thc202** [comment]
Ouch! Messed up the conversion somewhere... Indeed, in the original Groovy script was using the type as well `apply plugin: com.gradle.publish.PublishPlugin`. Thank you.
