### ISSUE TITLE
Generate extensions taking a `KClass` for methods in the Gradle API taking a `java.lang.Class` 

### ISSUE THREAD

**Issue by bamboo** [gradle/kotlin-dsl#221]
So we can write `project.container(Foo::class)` instead of `project.container(Foo::class.java)`. 

Investigate the possibility of making this a core Kotlin feature (or contribute one via a compiler plugin) just like SAM conversions.

**Comment by JLLeitschuh** [comment]
@eskatos What happened to the thought of making this a compiler plugin?

**Comment by eskatos** [comment]
Closing as delivered in #914
