### ISSUE TITLE
Add kotlin-dsl build scripts support to gradle init

### ISSUE THREAD

**Issue by eskatos** [gradle/kotlin-dsl#253]
gradle init --dsl=kotlin --type java-library
    gradle init --dsl=kotlin --type java-application

**Comment by oehme** [comment]
I think Kotlin is orthogonal to the project type. Consider adding `--script-language`

**Comment by adammurdoch** [comment]
+1000 to considering DSL language used to define the build as a separate concern to the type of software the build produces.

**Comment by adammurdoch** [comment]
I'd use something like `--dsl-language` or `--kotlin-build-scripts` or whatever as the name of the option, rather than `--script-language`, just to make it clear that it affects the build scripts rather than the source files of the software being built.

**Comment by eskatos** [comment]
Issue on the `gradle/gradle` board: https://github.com/gradle/gradle/issues/1673

**Comment by eskatos** [comment]
Upstream PR https://github.com/gradle/gradle/pull/3556
