### ISSUE TITLE
Provide maven(url: String, name: String? = null, ...) shortcut

### ISSUE THREAD

**Issue by sdeleuze** [gradle/kotlin-dsl#256]
Current syntax to specify Maven repositories is not very idiomatic. Providing a regular Kotlin `maven()`function with parameters like `maven(url: String, name: String? = null, ...)` would be more easy to use for end users via autocomplete, positional or named parameters, and would read and write more easily.

Current syntax:
```kotlin
repositories {
  maven { setUrl("...") }
}
````

Proposed syntax:
```kotlin
repositories {
  maven(url = "...") // can be abbreviated to maven("...")
}
```

**Comment by bamboo** [comment]
Alternatively we could add the strongly typed setter `setUrl(URI)` to `MavenArtifactRepository` and then the syntax would be:

```kotlin
maven { url = uri("...") }
```

**Comment by bamboo** [comment]
As a second step we could work with the Kotlin team to introduce the concept of implicit conversion compiler plugins and achieve complete parity with Groovy with the advantage of compile time checking:

```kotlin
maven { url = "..." } // statically checked implicit conversion from String to URI 
```

**Comment by eskatos** [comment]
I like the alternative route a lot.

We should refrain from adding adhoc shortcuts. They are terrible to maintain, they may outnumber us at some point 😄  and they surely will minimize the goodness we could get from a coherent frontend on top of the Gradle API.

**Comment by eskatos** [comment]
Type safe setters have been added to the Gradle API in:
- `MavenArtifactRepository`
- `IvyArtifactRepository`
- `MavenPluginRepository`
- `IvyPluginRepository`

See https://github.com/gradle/gradle/issues/1823

This provides the following:
```kotlin
repositories {
  maven { url = uri("...") }
}
```

Implicit conversions will be addressed in https://github.com/gradle/gradle-script-kotlin/issues/335

**Comment by sdeleuze** [comment]
As commented on gradle#335, I am against introducing implicit conversion to Kotlin, and I still think such shortcut is relevant for such frequently used statement.

**Comment by bamboo** [comment]
We should reconsider this shortcut.
