### ISSUE TITLE
Document how to get kotlin build to interact with ant tasks

### ISSUE THREAD

**Issue by JLLeitschuh** [gradle/kotlin-dsl#259]
One of the thing that gradle promotes is that ant tasks are "First Class Citizens".

How will these ant tasks work in type safe kotlin?

*Example:* I'm not even quite sure where to start in kotlin trying to re-implement [this groovy logic](http://stackoverflow.com/a/35236539/3708426).

**Comment by eskatos** [comment]
This may be of interest: https://github.com/DevCharly/kotlin-ant-dsl

**Comment by JLLeitschuh** [comment]
Do something like put this in the `buildSrc` as a generate sources phase or something. Hmmm... Interesting.

**Comment by eskatos** [comment]
Sample relying on the Groovy Builder introduced in 9ac37c8a33ec8f457a593a75c36a558ff11b5a9d is now available, see https://github.com/gradle/kotlin-dsl/tree/develop/samples/ant

Related commits are 94bd7f0121e03a6631afe0ad5f227fd461a75861 and fc5cd9d444c8917b1e7e9bf828cdd406068c9259.

Closing
