### ISSUE TITLE
How to use a model block in a build.gradle.kts

### ISSUE THREAD

**Issue by baron1405** [gradle/kotlin-dsl#260]
I am in the process of converting my build.gradle files to Kotlin build.gradle.kts files. A number of my build files contain model blocks. I cannot find a way to code these in Kotlin and am concerned that this is a Groovy-only construct. Is there a Kotlin equivalent to the model block?

**Comment by bamboo** [comment]
Hi @baron1405, model blocks won't be supported in gradle-script-kotlin 1.0.

It should be possible to convert model blocks into `RuleSource` classes and apply them explicitly though.

We will consider adding a sample on the next milestone.

**Comment by baron1405** [comment]
Thanks @bamboo for the update and suggestion. I will give a RuleSource class a try.

**Comment by ikzk** [comment]
Anyone can provide info on how to use RuleSource?

**Comment by eskatos** [comment]
@baron1405, @ikzk, please have a look at the `model-rules` sample to see how to apply rule sources in a `.gradle.kts` script: https://github.com/gradle/kotlin-dsl/tree/develop/samples/model-rules

**Comment by bamboo** [comment]
The model block won't be supported but we now we have a sample on how to write model rules.

Closing as _Delivered_.

**Comment by ikovalyov** [comment]
It there a way to specify play version with this approach? All docs have only this example:

```
model {
    components {
        play {
            platform play: '2.5.8', scala: '2.11'
            injectedRoutesGenerator = true
        }
    }
}
```

Thanks.
