### ISSUE TITLE
Design API Reference layout

### ISSUE THREAD

**Issue by bamboo** [gradle/kotlin-dsl#272]
A first version of the API reference is available here: https://gradle.github.io/kotlin-dsl-docs/api/

It uses the default [dokka](https://kotlinlang.org/docs/reference/kotlin-doc.html) style.
It should be using a Gradle style instead.

The documentation is built by this build: https://github.com/gradle/kotlin-dsl-docs
The CSS file for API reference is [here](https://github.com/gradle/kotlin-dsl-docs/blob/master/src/pages/style.css)

**Comment by chaficnajjar** [comment]
I can help with implementing and maintaining the style sheets of the API reference, @bamboo. 

@aweida Do you want to take care of the design of the API reference or would you prefer I just go ahead implementing this and use https://docs.gradle.com and https://docs.gradle.org as reference points?

**Comment by eskatos** [comment]
Thanks @chaficnajjar !

When you start looking at implementation details, feel free to ping us so we can guide you through the documentation build.

**Comment by aweida** [comment]
> @aweida Do you want to take care of the design of the API reference or would you prefer I just go ahead implementing this and use https://docs.gradle.com and https://docs.gradle.org as reference points?

@chaficnajjar yes lets be consistent and follow our current docs
