### ISSUE TITLE
Write User Guide section on DSLs introducing both the Kotlin DSL and the Groovy DSL

### ISSUE THREAD

**Issue by bamboo** [gradle/kotlin-dsl#277]
Including documenting the different configuration patterns in each DSL.

- How to configure project extensions
- How to configure tasks
- How to configure domain object collections
- How to use delegated properties to access the different Gradle model elements
- How to use Gradle properties
- Interoperability with Groovy from Kotlin
  - How to pass Closures to Groovy
  - How to do dynamic dispatching using the `withGroovyBuilder` utility
- Interoperability with Kotlin from Groovy
  - How to access a Kotlin extension member from Groovy
- ...

**Comment by eskatos** [comment]
Closing as delivered in https://docs.gradle.org/5.0-rc-1/userguide/kotlin_dsl.html
Groovy counterpart at https://docs.gradle.org/5.0-rc-1/userguide/groovy_build_script_primer.html
