### ISSUE TITLE
Unify `DependencyHandler` configuration dependency APIs for both extension methods and for the string invocation

### ISSUE THREAD

**Issue by mkobit** [gradle/kotlin-dsl#291]
## Overview

The generated extensions for various configurations have different method signatures than those when using the `String.invoke` and are also not easily visible when coding against them in IntelliJ. This leads to a different user experience when dealing with each type. such as not being able to do `"myConfiguration"("group", "name", "version")`

This issue is a proposal to unify the different dependency handling APIs.

## Per configuration generated extensions methods

For generated extensions methods for configurations like `compile`, there is:

* `compile(dependency: T, dependencyConfiguration: T.() -> kotlin.Unit): T`
* `compile(dependencyNotation: kotlin.Any): org.gradle.api.artifacts.Dependency`
* `compile(group: kotlin.String, name: kotlin.String, version: kotlin.String? = null, configuration: kotlin.String? = null, classifier: kotlin.String? = null, ext: kotlin.String? = null): org.gradle.api.artifacts.ExternalModuleDependency`
* `compile(group: kotlin.String, name: kotlin.String, version: kotlin.String? = null, configuration: kotlin.String? = null, classifier: kotlin.String? = null, ext: kotlin.String? = null, dependencyConfiguration: org.gradle.api.artifacts.ExternalModuleDependency.() -> kotlin.Unit): org.gradle.api.artifacts.ExternalModuleDependency`
* `compile(dependencyNotation: kotlin.String, dependencyConfiguration: org.gradle.api.artifacts.ExternalModuleDependency.() -> kotlin.Unit): org.gradle.api.artifacts.ExternalModuleDependency`

and from IntelliJ it looks like

<img width="1154" alt="compile extension methods on Dependency Handler" src="https://cloud.githubusercontent.com/assets/1447148/23584088/29c31bba-011c-11e7-94e1-1e263f01dc12.png">

## `String.invoke`

For `String.invoke` there is:

* `<T : org.gradle.api.artifacts.ModuleDependency> kotlin.String.invoke(dependency: T, dependencyConfiguration: T.() -> kotlin.Unit): T`
* `String.invoke(dependencyNotation: kotlin.Any): org.gradle.api.artifacts.Dependency`
* `String.invoke(dependencyNotation: kotlin.String, dependencyConfiguration: org.gradle.api.artifacts.ExternalModuleDependency.() -> kotlin.Unit): org.gradle.api.artifacts.ExternalModuleDependency`

and from IntelliJ _Parameter Info_ shortcut

<img width="361" alt="String invocation of adding dependency in dependency handler" src="https://cloud.githubusercontent.com/assets/1447148/23584125/3721ce5e-011d-11e7-83a1-e636ac0e5133.png">

Notice no auto-complete suggested for overloaded methods and odd suggestions for `invoke` parameters

## `Configuration.invoke`

For `Configuration.invoke` there is:

* `<T : org.gradle.api.artifacts.ModuleDependency> org.gradle.api.artifacts.Configuration.invoke(dependency: T, dependencyConfiguration: T.() -> kotlin.Unit): T`
* `Configuration.invoke(dependencyNotation: kotlin.Any): org.gradle.api.artifacts.Dependency`
* `Configuration.invoke(dependencyNotation: kotlin.String, dependencyConfiguration: org.gradle.api.artifacts.ExternalModuleDependency.() -> kotlin.Unit): org.gradle.api.artifacts.ExternalModuleDependency`

and from IntelliJ _Parameter Info_ shortcut

<img width="495" alt="configuration invoke method paramater suggestions" src="https://cloud.githubusercontent.com/assets/1447148/23584171/bbdcfafa-011e-11e7-9b48-370f4c19ede8.png">

Notice no auto-complete suggested for overloaded methods and odd suggestions for `invoke` parameters

## Versions

* IntelliJ 2017.1 Public Preview
* IntelliJ Kotlin Plugin Version: 1.1.0-release-IJ2017.1-1
* GSK https://repo.gradle.org/gradle/dist-snapshots/gradle-script-kotlin-3.5-20170304121428+0000-all.zip

**Comment by eskatos** [comment]
Here are screenshots of IntelliJ suggestions after the fix:

**Per configuration generated extensions methods**

![image](https://user-images.githubusercontent.com/132773/30477645-2d027588-9a0e-11e7-9be4-427a804d6bef.png)

**String.invoke**

![image](https://user-images.githubusercontent.com/132773/30477559-ded6d642-9a0d-11e7-9dd7-c862a5bfdd51.png)

**Configuration.invoke**

![image](https://user-images.githubusercontent.com/132773/30477630-1a39eea4-9a0e-11e7-9900-0f6220480d5b.png)

----
Note that no suggestion for `*.invoke` extensions is provided by IntelliJ when triggering completion at `something(|)` just as on your two screenshots. One can get proper suggestions by triggering completion at `something.inv|` as shown in the screenshots above.

@mkobit I agree this is missing, the same thing happen with `SomeConstructor(|)` or `someMethod(|)`, even in plain Java. I've found some related issue on IntelliJ issue tracker:  [IDEA-93584](https://youtrack.jetbrains.com/issue/IDEA-93584).

**Comment by eskatos** [comment]
@mkobit, thank you very much for the good catch and great report!

The fix will be included in 0.12, closing.

**Comment by mkobit** [comment]
Awesome! Thanks @eskatos !
