### ISSUE TITLE
IntelliJ does not resolve Action<? super T> to (T) -> Unit in large projects

### ISSUE THREAD

**Issue by JLLeitschuh** [gradle/kotlin-dsl#310]
I have a fairly large and complicated build. In the small demo projects this isn't a problem but in large complicated build files this becomes a problem.

Example this is in a subproject of a multi-project build:
```kotlin
configurations.all {
    resolutionStrategy {
        force("org.jetbrains.kotlin:kotlin-stdlib:${rootProject.extra["kotlinVersion"]}")
        force("org.jetbrains.kotlin:kotlin-reflect:${rootProject.extra["kotlinVersion"]}")
        // The latest version of mockito that power mock works with
        // https://github.com/powermock/powermock/wiki/Mockito2_maven
        force("org.mockito:mockito-core:2.4.0")
    }
}
```
Looks like this:
<img width="735" alt="screen shot 2017-03-21 at 3 30 38 pm" src="https://cloud.githubusercontent.com/assets/1323708/24166948/6f51d590-0e4b-11e7-9d90-2fb3ed60c1fd.png">

Another example:
<img width="630" alt="screen shot 2017-03-21 at 3 31 48 pm" src="https://cloud.githubusercontent.com/assets/1323708/24166989/8ce648f2-0e4b-11e7-9794-d5bee6d595d2.png">

Third example:
<img width="765" alt="screen shot 2017-03-21 at 3 33 09 pm" src="https://cloud.githubusercontent.com/assets/1323708/24167055/c24e4c4c-0e4b-11e7-9dd9-a683a663e204.png">

Distribution URL:
```
distributionUrl=https\://repo.gradle.org/gradle/dist-snapshots/gradle-script-kotlin-3.5-20170305000422+0000-all.zip
```
```
IntelliJ IDEA 2017.1
Build #IU-171.3780.95, built on March 20, 2017
Licensed to Plexxi, Inc. / Jonathan Leitschuh
Subscription is active until December 14, 2017
JRE: 1.8.0_112-release-736-b13 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.3
```
Kotlin Plugin Version: `1.1.1-release-IJ217.1-1`

**Comment by bamboo** [comment]
Thanks for the report, @JLLeitschuh . A repro project would really help make sure this is fixed, otherwise I'm going to ask you to try again after #249 is implemented.

**Comment by bamboo** [comment]
@JLLeitschuh is this still happening?

**Comment by JLLeitschuh** [comment]
I'm on vacation this week. I'll double check next week but my recollection is that this has been fixed.

**Comment by eskatos** [comment]
@JLLeitschuh, could you confirm that this has been fixed for you?

**Comment by JLLeitschuh** [comment]
This is no longer a problem with small build scripts. The build I was working on where I had an incredibly long build scripts has been scrapped. If I see it again I'll reopen this issue.
