### ISSUE TITLE
No IDE support out of the box

### ISSUE THREAD

**Issue by dagguh** [gradle/kotlin-dsl#313]
### Steps
1. Clone this repo.
2. Open it in IntelliJ IDEA 2016.3.5:
  a. Open the IDE.
  b. Invoke the `Open...` action.
  c. Choose the checked out directory.
  d. Check `Use auto-import` in the `Import Project From Gradle` dialog.
  e. Press `OK`. 
3. Open `build.gradle.kts`.

### Expectation
> The best IDE and tooling experience possible.

### Reality
![screen shot 2017-03-22 at 15 12 33](https://cloud.githubusercontent.com/assets/1194704/24202226/b9c77090-0f12-11e7-9a6f-5b3353fe4f83.png)
Broken imports. No autocompletion. Unresolved references.

**Comment by bamboo** [comment]
Please describe step 2 in detail.

**Comment by dagguh** [comment]
I updated the description.

**Comment by dagguh** [comment]
I found a workaround. First build the project via CLI, then open it in the IDE.

**Comment by hyysguyang** [comment]
We still can't attache source code  of the script plugin within idea, when access ProjectExtensions.kt,just got this:
```kotlin
// IntelliJ API Decompiler stub source generated from a class file
// Implementation of methods is not available

package org.gradle.script.lang.kotlin

private fun fileCollectionOf(files: kotlin.collections.Collection<java.io.File>, name: kotlin.String): org.gradle.api.file.FileCollection { /* compiled code */ }

public inline fun <reified T : org.gradle.api.Plugin<org.gradle.api.Project>> org.gradle.api.Project.apply(): kotlin.Unit { /* compiled code */ }

public fun org.gradle.api.Project.applyFrom(script: kotlin.Any): kotlin.Unit { /* compiled code */ }
```

**Comment by yoavst** [comment]
Is there any fix to this issue?

**Comment by bamboo** [comment]
This is probably related to some timeout during project import.

Closing as unreproducible.
