### ISSUE TITLE
AbstractCopyTask needs a ::from overload that takes some sort of deferred action

### ISSUE THREAD

**Issue by JLLeitschuh** [gradle/kotlin-dsl#315]
See https://github.com/gradle/gradle/issues/1636

**Comment by eskatos** [comment]
Closing in favor of the upstream issue.

**Comment by JLLeitschuh** [comment]
The fix provided in the issue linked above by @bamboo should probably be documented somewhere. Maybe in the getting started docs in this project perhaps?
