### ISSUE TITLE
Document limitations around plugin application

### ISSUE THREAD

**Issue by pioterj** [gradle/kotlin-dsl#318]
There are some fundamental limitations regarding plugin application that we cannot easily work around in gradle-script-kotlin and will be handled separately. Let's document them and the workarounds in the meantime, for example on https://github.com/gradle/gradle-script-kotlin#limitations. 

- Imperative plugin application, e.g. `apply { plugin("application") }`
    - The need to manually generate accessors, including command-line usage
- Script plugins, e.g. `apply from: 'other.gradle'`
    - Not being able to configure a plugin applied in parent script, which you can do in Groovy

**Comment by bamboo** [comment]
Fixed in https://github.com/gradle/kotlin-dsl/blob/master/doc/getting-started/Configuring-Plugins.md
