### ISSUE TITLE
`configure<ExtensionType> { ... }` and `the<ExtensionType>()` allows generic `ExtensionType`

### ISSUE THREAD

**Issue by bamboo** [gradle/kotlin-dsl#319]
Given an extension [registered under the generic public type](https://github.com/gradle/gradle/blob/408b10a601f95542dbd015f906f197cdd20b1a3f/subprojects/core/src/main/java/org/gradle/api/plugins/ExtensionContainer.java#L67-L67) `NamedDomainObjectContainer<SomeType>`, the following code will configure it:

```kotlin
configure<NamedDomainObjectContainer<SomeType>> {
  val someValue by creating {
    someProperty = 42
  }
}
```

Using [`ExtensionContainer#findByType<T>(TypeOf<T>)`](https://github.com/gradle/gradle/blob/408b10a601f95542dbd015f906f197cdd20b1a3f/subprojects/core/src/main/java/org/gradle/api/plugins/ExtensionContainer.java#L185-L185) under the hood.

**Comment by eskatos** [comment]
Related to #611

**Comment by eskatos** [comment]
Closing as delivered in 245aaea
