### ISSUE TITLE
Support upgrading gradle-kotlin-dsl

### ISSUE THREAD

**Issue by cbeams** [gradle/kotlin-dsl#32]
The goal here is to provide users with a way to upgrade `gradle-script-kotlin` (say) to a new snapshot or to a milestone release newer than the one that shipped with their current Gradle distribution.

Ultimately, this should be a first-class feature in Gradle itself, i.e. the ability to upgrade any module within the distribution without having to upgrade the distribution itself, but in the meantime, a stopgap approach might be to contribute an `upgradeGradleScriptKotlin` task that:
- gets configured via property as to what `gradleScriptKotlinVersion` you want to use
- resolves that version and its deps  (using Gradle’s own resolution mechanism) into `$TMPDIR`
- patch the `gradle-script-kotlin-classpath.properties` file in order to match the Gradle distribution's own set of dependencies (based on dependency resolution rules—see #59 for details)
- interrogates existing `gradle-script-kotlin` classpath properties (from `$GRADLE_HOME/lib/…`)
- creates a diff between the deps in `$TMPDIR` and `$GRADLE_HOME/lib`
- deletes the delta between them
- deletes the existing `gradle-script-kotlin` jar
- copies the contents of `$TMPDIR` => `$GRADLE_HOME/lib`

**Comment by bamboo** [comment]
The upgrade process must also change the version number of the patched distribution to guarantee daemon processes compatible with the original distribution are not reused in the context of the patched one.

**Comment by cbeams** [comment]
We should not tackle this until we have #59 solved, because upgrading the gradle-script-kotlin jar will require patching its `-classpath.properties` file anew. I've updated the description of this issue to reflect the addition of that step
