### ISSUE TITLE
Multi-kotlin-project with buildSrc sample not working in Android Studio

### ISSUE THREAD

**Issue by lwasyl** [gradle/kotlin-dsl#323]
I get following error when trying to sync the project:
> Error:The modules ['buildSrc', 'multi-kotlin-project-with-buildSrc'] point to the same directory in the file system.
> Each module must have a unique path.

This is on Android Studio 2.4 based on IntelliJ 2017.1 EAP. `./gradlew build` works properly.

**Comment by bamboo** [comment]
No longer reproducible with Android Studio 3.0.1 with Kotlin 1.2.20.

```
Android Studio 3.0.1
Build #AI-171.4443003, built on November 9, 2017
JRE: 1.8.0_152-release-915-b08 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6
```
