### ISSUE TITLE
Array reassignment becomes method invocation

### ISSUE THREAD

**Issue by breandan** [gradle/kotlin-dsl#324]
For certain Gradle plugins which use array assignment in their configuration, migrating to gradle-script-kotlin seems to break the DSL style. For example, in the [gradle-intellij-plugin](https://github.com/jetbrains/gradle-intellij-plugin#configuration), replacing `plugins = ['someplugin:version']` from Groovy, with the Kotlin equivalent `plugins = arrayOf("someplugin:version")` currently fails to build with an error: `Val cannot be reassigned`. Instead, GSK expects a method invocation here, where `plugins = ['someplugin:version']` now becomes `setPlugins("someplugin:version")`. In order to preserve DSL similarity, would it be possible to use the former API instead? Thanks!

**Comment by mkobit** [comment]
Ahh, I thought this was just me doing something weird.

The https://github.com/bintray/gradle-bintray-plugin is another example of this with the various `String[]` types  in https://github.com/bintray/gradle-bintray-plugin/blob/master/src/main/groovy/com/jfrog/bintray/gradle/BintrayExtension.groovy#L18-L20

**Comment by mkobit** [comment]
Another impacted area is [`SourceDirectorySet`](https://docs.gradle.org/current/javadoc/org/gradle/api/file/SourceDirectorySet.html)

![screen shot 2017-04-03 at 3 19 38 pm](https://cloud.githubusercontent.com/assets/1447148/24630119/06db2df0-1881-11e7-98f0-5cf635cb4142.png)

**Comment by sureshg** [comment]
Another one is `project.exec`
<img width="318" alt="screen shot 2017-04-08 at 8 56 26 am" src="https://cloud.githubusercontent.com/assets/356994/24830344/48333340-1c39-11e7-89f1-9c6ce0be9a61.png">

**Comment by bamboo** [comment]
This issue is probably caused by Kotlin not recognizing the getter/setter pair as a property, see https://kotlinlang.org/docs/reference/java-interop.html#getters-and-setters for details.
