### ISSUE TITLE
Modularised build scripts cannot resolve kotlin-gradle-plugin classes

### ISSUE THREAD

**Issue by jonathan-yan** [gradle/kotlin-dsl#334]
### Context

I am trying to start using the [_Java Library_](https://docs.gradle.org/current/userguide/java_library_plugin.html) plug-in in _Gradle_ for a _Kotlin_ project. So I started modularising my build scripts so that I only need to define the [work-around](https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_known_issues_compat) once (which in my example is in the _kotlin-library.gradle.kts_ file) to get the _Kotlin_ plug-in to work nicely.

### Expected Behavior

`./gradlew tasks` should be successful.

### Current Behavior

Command fails: `e: .../example-modularity-issue/kotlin-library.gradle.kts:23:28: Unresolved reference: KotlinCompile`.

### Steps to Reproduce

* Example project: [example-modularity-issue.zip](https://github.com/gradle/kotlin-dsl/files/923524/example-modularity-issue.zip)
* Run `./gradlew tasks`

**Comment by bamboo** [comment]
Applied scripts don't see the classpath of the applying script. 

For now the easiest workaround would be organizing build logic under `buildSrc`.
