### ISSUE TITLE
Implicit conversions

### ISSUE THREAD

**Issue by eskatos** [gradle/kotlin-dsl#335]
Some Gradle DSL properties would benefit from implicit type safe conversions.

For example, to define a maven repository one has to:
```kotlin
repositories {
  maven { url = uri("...") }
}
```
The call to `project.uri('...')` converts a `String` to an `URI`.

With implicit conversions one could simply write:
```kotlin
repositories {
  maven { url = "..." }
}
```

One possible way to achieve this could be with implicit conversion compiler plugins, see https://github.com/gradle/gradle-script-kotlin/issues/256#issuecomment-293621429. This would provide complete parity with Groovy with the advantage of compile time checking.

**Comment by JLLeitschuh** [comment]
As it stands right now, this works right now:
```kotlin
repositories {
  maven { setUrl("...") }
}
```
I'm not a fan of this either

**Comment by eskatos** [comment]
Also see #380 (KT-4075)

**Comment by sdeleuze** [comment]
I am not sure I like the idea of introducing implicit conversions to Kotlin ...
