### ISSUE TITLE
Generate accessors for configurations created by applied plugins

### ISSUE THREAD

**Issue by eskatos** [gradle/kotlin-dsl#337]
Today, configurations accessors are only available for plugins applied to the GSK build.
We should enhance the accessors generation to produce extensions for all configurations created by applied plugins.

See #287

**Comment by JLLeitschuh** [comment]
To clarify the goal is to have the `generateGSKAccessors` task would print these out?

Trying to do this at compiler time sounds like trying to solve the halting problem.

**Comment by eskatos** [comment]
@JLLeitschuh yep, this is about moving configuration accessors generation from `gradle-script-kotlin` build time, where we can only do it in an arbitrary and incomplete way, to actual contextual accessors generation. The latter happens either in `:gskGenerateAccessors` task or `:gskProjectAccessors` task or when using `org.gradle.script.lang.kotlin.accessors.auto=true`.

**Comment by JLLeitschuh** [comment]
What does `org.gradle.script.lang.kotlin.accessors.auto=true` do?

**Comment by eskatos** [comment]
@JLLeitschuh see [`0.8.0` release notes](https://github.com/gradle/gradle-script-kotlin/releases/tag/v0.8.0)
