### ISSUE TITLE
Let examples use `distributionUrl=https\://services.gradle.org/distributions/gradle-3.5-all.zip`

### ISSUE THREAD

**Issue by iirekm** [gradle/kotlin-dsl#342]
It seems that at least some of them work with it. 
The current `distributionUrl=https\://repo.gradle.org/gradle/dist-snapshots/gradle-script-kotlin-4.0-20170421144052+0000-all.zip` was a bit measleading for me, and suggested that gradle-script-kotlin works with special customized Gradle 4 distributions, which may be out of question in real projects.

**Comment by bamboo** [comment]
Samples in the `master` branch only use official Gradle versions now, e.g., [samples/hello-world/gradle/wrapper/gradle-wrapper.properties](https://github.com/gradle/kotlin-dsl/blob/master/samples/hello-kotlin/gradle/wrapper/gradle-wrapper.properties).
