### ISSUE TITLE
Provide convenient configuration for SourceSet extensions and conventions

### ISSUE THREAD

**Issue by eskatos** [gradle/kotlin-dsl#343]
One frequent example is configuring source set directories.

In Groovy:
```groovy
sourceSets.main.kotlin.srcDirs += 'src/main/myKotlin'
```

In Kotlin today:
```kotlin
java.sourceSets["main"].withConvention(KotlinSourceSet::class) {
    kotlin.srcDir(file("src/main/myKotlin"))
}

```

Desired solution:
```kotlin
java.sourceSets["main"].kotlin {
    kotlin.srcDirs += file("src/main/myKotlin")
}
```

Alternate (working) solution:
```kotlin
val kotlin: KotlinSourceSet by java.sourceSets["main"].extensions
kotlin.kotlin.srcDirs += file("src/main/myKotlin")
```

**Comment by mkobit** [comment]
My current solution is to define something like this in the build script or in `buildSrc`:

```kotlin
val SourceSet.kotlin: SourceDirectorySet
  get() = (this as HasConvention).convention.getPlugin(KotlinSourceSet::class.java).kotlin
```

Then, you can do something that looks close to Groovy:

```kotlin
java.sourceSets["main"].kotlin.srcDirs += file("src/main/myKotlin")
```

Still using the internal `HasConvention` but a somewhat useful way to make the Kotlin source set configuration a little simpler.

**Comment by bamboo** [comment]
@mkobit That property getter definition can be simplified to `withConvention(KotlinSourceSet::class) { kotlin }`

**Comment by gildor** [comment]
But this solution `java.sourceSets["main"].kotlin` still uses convention under the hood as I understand.
Are there any global solutions for such problem or some recommendations for plugin authors?
Maybe make more sense to move `sourceSets` definition from `java.sourceSets` to `kotlin.sourceSets`, so completely rid of convention.

**Comment by JLLeitschuh** [comment]
Related: https://github.com/gradle/gradle/issues/3191

@oehme Had said that the goal was to stop exposing the concept of `convention`? Isn't this a step in the wrong direction?

**Comment by eskatos** [comment]
@gildor, @JLLeitschuh, the reality is that Gradle core plugins do use `Convention`s. And just like with all already existing extensions/conventions support in the Gradle Kotlin DSL, this issue is both about extensions and conventions, preferring extensions.

**Comment by eskatos** [comment]
I spiked this and it turns out that `SourceSet` (from `gradle-plugins-x.y.z.jar`) currently cannot be class loaded at project schema generation time. Need to figure out how to fix this.

**Comment by JLLeitschuh** [comment]
You want to do this without forcing plugin developers to have to write these extensions themselves I'm assuming.
Good luck man.

**Comment by eskatos** [comment]
Once project schema calculation is moved to the Gradle plugins class loader, it does work.

**Comment by eskatos** [comment]
One thing to note is that most extensions of `SourceSet`s are done via the convention mechanism Today, exposing the convention implementation type.

**Comment by eskatos** [comment]
This is done for source sets extensions.
Conventions on source sets won't be supported as they are being deprecated soon.
The plan is to provide the same functionality via extensions, see https://github.com/gradle/gradle/issues/5377
