### ISSUE TITLE
Polish Android sample

### ISSUE THREAD

**Issue by bamboo** [gradle/kotlin-dsl#351]
Consider providing some extension sugar implicitly.

**Comment by pioterj** [comment]
@bamboo I see that you are already working on it so I moved it to in progress. I noticed because I'm very curious about "providing some extension sugar implicitly" so I wanted to subscribe to updates about this story :)

**Comment by bamboo** [comment]
Thanks, @pioterj  :)

**Comment by bamboo** [comment]
Superseded by #406.
