### ISSUE TITLE
Use delegateProvider to support initialization of delegated extra properties

### ISSUE THREAD

**Issue by ramonwirsch** [gradle/kotlin-dsl#353]
By using the relatively new feature [delegateProvider](http://kotlinlang.org/docs/reference/delegated-properties.html#providing-a-delegate-since-11), the extra property delegates could do initialization.

This could reduce code like:
```
var prop: String by extra
prop = "value"
```

to 
```
var prop: String by extra { "code" }
```
or
```
var prop: String by extra("val")
```

The code for this is quite easy and i can supply it if desired.

**Comment by mkobit** [comment]
Similar to https://github.com/gradle/gradle-script-kotlin/issues/307

**Comment by mkobit** [comment]
I think this can be closed as a duplicate as https://github.com/gradle/kotlin-dsl/issues/307 has been closed and released

**Comment by bamboo** [comment]
Indeed, @mkobit, thanks.

Closing as duplicate.
