### ISSUE TITLE
KT-17770 - Kotlin IntelliJ plugin fails to re-index Gradle script classpath after change to the `plugins` block

### ISSUE THREAD

**Issue by bamboo** [gradle/kotlin-dsl#354]
https://youtrack.jetbrains.com/issue/KT-17770

![IntelliJ-fails-to-re-index](https://cloud.githubusercontent.com/assets/51689/25773975/a985cd44-325d-11e7-8b42-0be39cc30709.gif)

**Comment by superbobry** [comment]
For others having this issue: closing & reopening the project helps.
