### ISSUE TITLE
no main manifest attribute in jar file

### ISSUE THREAD

**Issue by kjkrol** [gradle/kotlin-dsl#369]
As I understand 'Main-Class' attribute of MANIFEST.MF should be set by "application" plugin
application {
    mainClassName = appMainClassName
}

**Comment by kjkrol** [comment]
I found that workaround to solve the issue:

**Comment by renannprado** [comment]
I've just ran into the same issue. I believe that today there's a proper way of doing this, but I can't find how.
It's even possible that this issue has to be reopened.

**Comment by abitofhelp** [comment]
I've snooped and scanned the Internet and cannot find anything but this workaround...  It'd be great to learn if there is an idiomatic way to build the shadowjar with a proper manifest using Kotlin DSL...

**Comment by abitofhelp** [comment]
Here is what I've learned... I don't know whether it is the latest and greatest information, but it works...

`////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// This task must be added to the build.gradle.kts file
// in order to create a shadowjar containing the required information.
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////

tasks.withType<ShadowJar> {
    manifest.attributes.apply {

        /////////////////////////////////////////////////////////////////////////////////////
        // The following attributes apply to the archive/jar file
        // that is being created and not the manifest.
        /////////////////////////////////////////////////////////////////////////////////////

        // A description about the archive/jar being created;
        // I couldn't find it being applied to an archive/jar.
        description = "A simple app to determine how to configure shadowjar with Kotlin DSL in Gradle."

        // The base name of the archive/jar being created
        archiveName = "thearchivename"

        // The directory path for the archive/jar being created
        destinationDir = File("")

        // The extension part of the archive/jar name
        extension = "JAR"

        // The appendix part of the archive/jar name
        appendix = "abc"

        // The classifier part of the archive/jar name
        classifier = "all"

        // The version part of the archive/jar name
        version = "1.0.0"

        ////////////////////////////////////////////////////////////////////////////////////////
        // The following attributes apply to the mainfest for the
        // archive/jar being created.
        ////////////////////////////////////////////////////////////////////////////////////////
        manifest {
            attributes(
                mutableMapOf<String, String>(
                    "Base-Name" to baseName,
                    "Main-Class" to "com.example.Main",
                    "Start-Class" to "",
                    "Implementation-Title" to "I am a title.",
                    "Implementation-Version" to version
                )
            )
        }
    }
}`

**Comment by abitofhelp** [comment]
A slight correction...  The Main-Class needs to have "Kt" appended to the name of the class:

        /////////////////////////////////////////////////////////////////////////////////////////
        // The following attributes apply to the mainfest for the
        // archive/jar being created.
        /////////////////////////////////////////////////////////////////////////////////////////
        manifest {
            attributes(
                mutableMapOf<String, String>(
                    "Base-Name" to baseName,
                    "Main-Class" to "com.abitofhelp.howdy.MainKt",
                    "Start-Class" to "",
                    "Implementation-Title" to "I am a title.",
                    "Implementation-Version" to version
                )
            )
        }

**Comment by sylhare** [comment]
You can have a complete example [here](https://stackoverflow.com/a/61373175/7747942) on how to set up your build.gradle.kts for it to work :)
