### ISSUE TITLE
Cannot configure non-root extension 

### ISSUE THREAD

**Issue by ghost** [gradle/kotlin-dsl#375]
I want to use the App Engine plugin from my build.gradle.kts but cannot access the "tools" extension that is registered.

In groovy script it is accessed like this:

appengine {
  tools {
    // Configure tools path here
  }
}

More details here:

https://discuss.kotlinlang.org/t/gradle-script-kotlin-configure-app-engine-plugin/2830

**Comment by eskatos** [comment]
Duplicate of #457, closing
