### ISSUE TITLE
spring bootRun not producing console logs  with gradle-script-kotlin 0.9.1

### ISSUE THREAD

**Issue by xmlking** [gradle/kotlin-dsl#376]
with gradle-script-kotlin 0.9.1 (20170523130707), no logs are printed to console.
it is working fine with gradle-script-kotlin 0.9.0 (20170518042627)
How to reproduce :
1. checkout  https://github.com/xmlking/reactive-apps
2. run `./gradlew  stream-service:bootRun`

**Working**
> gradle wrapper --gradle-distribution-url https://repo.gradle.org/gradle/dist-snapshots/gradle-script-kotlin-4.0-20170518042627+0000-all.zip

**Not Working**
> gradle wrapper --gradle-distribution-url https://repo.gradle.org/gradle/dist-snapshots/gradle-script-kotlin-4.0-20170523130707+0000-all.zip

**Comment by eskatos** [comment]
Closing as unreproducible
