### ISSUE TITLE
Custom tasks in Kotlin build scripts are automatically `open`

### ISSUE THREAD

**Issue by bamboo** [gradle/kotlin-dsl#378]
Because of Gradle runtime class decorations tasks must be declared `open` in Kotlin.

The [allopen Kotlin plugin](https://kotlinlang.org/docs/reference/compiler-plugins.html#all-open-compiler-plugin) can make it happen automatically.

- `kotlin-dsl` plugin
- script compilation

**Comment by SUPERCILEX** [comment]
I see this keeps being pushed back, but I would love to see it happen for at least classes extending the default task. I know the spring boot people also managed to make it work by looking at annotations.
