### ISSUE TITLE
IDEA-169717: Intellij uses incorrect Gradle version for buildSrc project

### ISSUE THREAD

**Issue by eskatos** [gradle/kotlin-dsl#383]
https://youtrack.jetbrains.com/issue/IDEA-169717

**Comment by bamboo** [comment]
Closing as fixed upstream.

**Comment by JLLeitschuh** [comment]
Glad to see that this finally got resolved. @bamboo Can we pull the `gradle.properties` hack out of the samples now?

**Comment by eskatos** [comment]
Good call @JLLeitschuh!
Done in 0ac7956
