### ISSUE TITLE
KT-23603: IntelliJ does not link buildSrc sources and their usage in build scripts

### ISSUE THREAD

**Issue by eskatos** [gradle/kotlin-dsl#384]
https://youtrack.jetbrains.com/issue/KT-23603

- navigating from build scripts to buildSrc source doesn't work, points to compiled code
- members in buildSrc used in project's build scripts are marked unused
- find usages of buildSrc members doesn't work
- refactoring members in buildSrc doesn't refactor build scripts

Tagged as fixed in 1.3.20

**Comment by eskatos** [comment]
This issue affects both Groovy and Kotlin build scripts.

**Comment by eskatos** [comment]
Just tried with IntelliJ 2017.2.5 and navigating from build scripts to buildSrc source now does work.

Other items listed in the description still do not work.

**Comment by wolfs** [comment]
Navigating from build scripts to buildSrc brings me to compiled code with `2017.3.5`. Is this a regression?

**Comment by bamboo** [comment]
@wolfs What's the buildSrc project layout? Custom `buildSrc` project layouts are not supported yet ( #755).

**Comment by wolfs** [comment]
Yeah, it is a custom `buildSrc` layout.

**Comment by eskatos** [comment]
IDEA-173999 is now fixed in 2018.2 for Groovy scripts.

https://youtrack.jetbrains.com/issue/KT-23603 is for Kotlin scripts.

**Comment by eskatos** [comment]
Required changes to the IDEA platform are done and will be released in 2018.3.

Then other changes are required in the IntelliJ Kotlin Plugin.
The sooner this could be fixed is Kotlin 1.2.70.

**Comment by jivimberg** [comment]
Hi! Intellij marks with red my calls to an extension functions defined in `buildSrc`, and of course I can navigate to them. Yet everything works ok when executing gradle tasks from CLI.

Is this what this issue is describing? or am I missing something.

ps: Not sure what do you mean by custom `buildSrc` layout. I just copied the layout provided in the samples: https://github.com/gradle/kotlin-dsl/blob/master/samples/multi-kotlin-project-with-buildSrc

**Comment by eskatos** [comment]
@jivimberg this doesn't sound like the same issue. Please create a new issue with details about your build, ideally sharing your build or a reproducer ; a screenshot of IJ showing the warning in context would also help.

**Comment by eskatos** [comment]
To clarify my https://github.com/gradle/kotlin-dsl/issues/384#issuecomment-407714112 above: navigating, finding usages, from/to buildSrc from/to scripts works already.

The missing bit is IJ considering scripts when refactoring `buildSrc` code (e.g. rename member).

**Comment by eskatos** [comment]
Closing as fixed in 1.3.20
