### ISSUE TITLE
Plugin portal no longer requires custom protocol

### ISSUE THREAD

**Issue by eskatos** [gradle/kotlin-dsl#389]
By serving plugin marker artifacts so it can be used as a "regular" maven repository.

## Implementation notes
 - [x] Plugin portal serves plugin marker artifacts
 - ~[ ] Gradle consumes plugin portal as a regular maven repository~ (moved to #469)

**Comment by bamboo** [comment]
The Plugin Portal can be consumed via the `maven` protocol now:

```groovy
// settings.gradle
pluginManagement {
  repositories {
     maven { url = 'https://plugins.gradle.org/m2/' }
  }
}
```

**Comment by bamboo** [comment]
Closing as delivered.
