### ISSUE TITLE
Support script debugging

### ISSUE THREAD

**Issue by cbeams** [gradle/kotlin-dsl#39]
In talking with @ligee, basic support for debugging should "already be there", e.g. setting breakpoints, etc. Should just be a matter of passing the correct remote debugging flags to underlying the Gradle process.
- [ ] See what's already possible with debugging
- [ ] Provide feedback to Kotlin team about surfacing first-class support for debugging Gradle build scripts wherever it's missing

**Comment by cbeams** [comment]
I've just re-associated he milestone from 1.0 `M2` to `GA`. It was an accident that the M2 association happened in the first place. We know we want complete debugging support by 1.0 GA, but its priority is not clear enough right now to slate into a particular milestone.

**Comment by mkobit** [comment]
This would be awesome to have - recently, IntelliJ added support to debug Groovy build scripts (see https://www.jetbrains.com/help/idea/gradle.html#debug_gradle) so I'm looking forward to `kotlin-dsl` support.

**Comment by eskatos** [comment]
@mkobit debugging scripts currently works with the caveat that breakpoints on top-level members are ignored, see #1040 and [JT-23526](https://youtrack.jetbrains.com/issue/KT-23526).
