### ISSUE TITLE
kotlin-dsl script compilation and plugin apply the all-open kotlin compiler plugin for Gradle types

### ISSUE THREAD

**Issue by eskatos** [gradle/kotlin-dsl#390]
all-open Gradle types (Task..)

**Comment by eskatos** [comment]
The `allopen` kotlin compiler plugin only allows to use annotations to tag types. See https://kotlinlang.org/docs/reference/compiler-plugins.html

We'll either need to add such an annotation to the Gradle API and targeted types, or, praise for adding support for listing open types in the `allopen` kotlin compiler plugin configuration.

**Comment by jmfayard** [comment]
I was to quick https://github.com/gradle/kotlin-dsl/issues/1189

**Comment by jmfayard** [comment]
More infos about allopen: 

> If the class (or any of its superclasses) is annotated with com.your.Annotation, the class itself and all its members will become open. It even works with meta-annotations:

https://github.com/Kotlin/KEEP/blob/master/proposals/extensions/opening-classes-for-frameworks.md

https://blog.jetbrains.com/kotlin/2016/12/kotlin-1-0-6-is-here/

**Comment by eskatos** [comment]
@jmfayard, it looks great!
It's already too late for 5.0. It's now tentatively scheduled for 5.1.

**Comment by jmfayard** [comment]
Ok thanks Paul !

**Comment by mkobit** [comment]
As an alternative, why doesn't Gradle create proxy classes for `final` classes similar to how ByteBuddy does for Mockito?

**Comment by JLLeitschuh** [comment]
@mkobit I think that that's considered a pretty expensive operation. I'm guessing there are other reasons as well.

**Comment by eskatos** [comment]
A prototype of `allopen` integration is available in the [eskatos/compilation/allopen](https://github.com/gradle/kotlin-dsl/compare/develop...eskatos/compilation/allopen) branch. It's not satisfactory yet in that the compiler plugins api for embedded compiler usage are only available in the maven plugin artifact.

Also see the discussion in https://github.com/gradle/gradle/pull/7971
