### ISSUE TITLE
Migrate several open source project builds

### ISSUE THREAD

**Issue by cbeams** [gradle/kotlin-dsl#40]
The following projects have volunteered to work with us in migrating their builds to `gradle-script-kotlin`:
- [sdeleuze/spring-kotlin](https://github.com/sdeleuze/spring-kotlin)
- [sdeleuze/geospatial-messenger](https://github.com/sdeleuze/geospatial-messenger)

Please add a comment if you run an open source project and you'd like to migrate your existing Groovy-based Gradle build to Gradle Script Kotlin. Feel free to do so as well if you've _already_ partially or completely migrated your build.

**Comment by ingokegel** [comment]
https://github.com/ingokegel/jclasslib

**Comment by DanielThomas** [comment]
I'd be happy to move our nebula-plugins projects. We're allergic to boilerplate though, so most of the usual build script configuration happens via plugin in https://github.com/nebula-plugins/nebula-plugin-plugin. Thought you might find us trying the support you're building for scripts in plugins valuable. 

Incidentally, I migrated one of our plugins to Kotlin already, and except for a case of #8, the conversion with the current API went smoothly - https://github.com/nebula-plugins/gradle-resolution-rules-plugin.

**Comment by bamboo** [comment]
Another project: https://github.com/reactor/projectreactor.io/blob/master/build.gradle.kts

**Comment by Barteks2x** [comment]
I already migrated to gradle script kotlin, it mostly went without issues, with a few exceptions (questions I asked on slack): https://github.com/Barteks2x/CubicChunks/blob/MC_1.11/build.gradle.kts

There are a few things that seem a bit verbose to me so I'm not sure if I did it correctly.

**Comment by elect86** [comment]
It'd be useful to have a guide explaining the steps to take to migrate
