### ISSUE TITLE
Gradle API uses nullability annotations recognized by the Kotlin compiler

### ISSUE THREAD

**Issue by eskatos** [gradle/kotlin-dsl#403]
Gradle currently uses the `org.gradle.api.Nullable` annotation to decorate nullable parameters and method return types.

Moving to annotations recognized by the Kotlin compiler will allow it to automatically generates Java interop so that:
- `@Nonnull java.lang.String => String`
- `@Nullable java.lang.String => String?`

See https://kotlinlang.org/docs/reference/java-interop.html#null-safety-and-platform-types

**Comment by eskatos** [comment]
PR opened: https://github.com/JetBrains/kotlin/pull/1171

**Comment by eskatos** [comment]
Gradle issue: https://github.com/gradle/gradle/issues/2382

**Comment by bamboo** [comment]
👍
