### ISSUE TITLE
`hello-android` sample uses the `plugins` block to apply android and kotlin plugins

### ISSUE THREAD

**Issue by bamboo** [gradle/kotlin-dsl#406]
By using the `pluginManagement` DSL to point to the Google repository.

This will enable removing `gradle/project-schema.json` and relying on jit project accessors instead.

**Comment by jaredsburrows** [comment]
@bamboo Do we have to use the `project-schema.json` still?

**Comment by eskatos** [comment]
This is blocked by the availability of [plugin marker artifacts](https://docs.gradle.org/current/userguide/plugins.html#sec:plugin_markers) published alongside the plugins on the Google repository.

See: https://issuetracker.google.com/issues/64551265

**Comment by eskatos** [comment]
The PR #502 uses a plugin resolution strategy to substitute a plugin request for `id("com.android.application")` by the actual Android Gradle Plugin artifact.

This strategy also works with the upcoming Android Gradle Plugin 3, tested locally.
The only change is that the AGP 3 is not found in JCenter but in the Google maven repo instead.

Once https://issuetracker.google.com/issues/64551265 is fixed and AGP 3 is out we'll have to change the sample accordingly.

**Comment by bamboo** [comment]
@eskatos should we close this one and introduce a new one to track the AGP 3 release?

**Comment by eskatos** [comment]
Validated that importing the sample in Android Studio works ✅ 

See #505 to track AGP 3 release
