### ISSUE TITLE
Existing collection element can be explicitly referenced and configured via delegated property

### ISSUE THREAD

**Issue by bamboo** [gradle/kotlin-dsl#407]
```kotlin
collection {

  // referencing existing with default type
  val existing by getting

  // referencing existing with non default type
  val existing: Foo by getting

  // configuring existing with default type
  val existing by getting {
    property = value
  }

  // configuring existing with non default type
  val existing by getting(Foo::class) {
    fooProperty = value
  }

}
```

**Comment by gildor** [comment]
Will this new syntax work in this case:
```kotlin
 val existing: Foo by getting {
    fooProperty = value
  }

```

**Comment by bamboo** [comment]
Unfortunately not, @gildor.

The reason is that the call to `getting` needs to reveal the type of the element so the receiver of the lambda expression can be typed correctly.

**Comment by gildor** [comment]
Yeah, I see. And `getting<Foo> {}` impossible as well as I understand because requires one more generic argument.
Anyway `val existing by getting(Foo::class)` looks good 👍

**Comment by bamboo** [comment]
Thanks for the feedback, @gildor 👍
