### ISSUE TITLE
KT-18889 Cannot navigate to source of overloaded property setter

### ISSUE THREAD

**Issue by bamboo** [gradle/kotlin-dsl#409]
https://youtrack.jetbrains.com/issue/KT-18889

**Comment by eskatos** [comment]
Could not reproduce with IntelliJ 2017.2.5 & Kotlin 1.1.50

![navigate-to-overloaded-setter](https://user-images.githubusercontent.com/132773/30980863-c0686886-a482-11e7-948f-1c24abefaed0.gif)
