### ISSUE TITLE
KT-18890 Cannot navigate to source of method accepting SAMWithReceiver argument

### ISSUE THREAD

**Issue by bamboo** [gradle/kotlin-dsl#410]
https://youtrack.jetbrains.com/issue/KT-18890

**Comment by eskatos** [comment]
I could not reproduce this with IntelliJ 2017.2.5 & Kotlin 1.1.50

![navigate-to-source](https://user-images.githubusercontent.com/132773/30980567-cb9ebf76-a481-11e7-87b6-94ebc2c1eb10.gif)
