### ISSUE TITLE
configuration issue with alpha version of Android Gradle plugin + kotlin-dsl

### ISSUE THREAD

**Issue by iNoles** [gradle/kotlin-dsl#411]
Here is the sample project: https://github.com/iNoles/hello-android

Android Gradle Plugin 3.0.0-alpha5 requires Gradle 4.1 

compile() doesn't work, but "compile"() works. There is possible issues with latest kotlin-dsl snapshots.

**Comment by jaredsburrows** [comment]
If you look at the samples: https://github.com/gradle/kotlin-dsl/tree/master/samples/hello-android

There is a project schema: https://github.com/gradle/kotlin-dsl/blob/master/samples/hello-android/gradle/project-schema.json

**Comment by iNoles** [comment]
I believe it already has project schema.

**Comment by bamboo** [comment]
Hi @iNoles,

I assume that `project-schema.json` file was copied from another project (possibly `kotlin-dsl/samples/hello-android`).  For that to work, the multi-project structure of both projects would have to be the same.

The recommended way of creating and updating `gradle/project-schema.json` is via the `kotlinDslAccessorsSnapshot` task:

    ./gradlew kotlinDslAccessorsSnapshot

Can you confirm that fixes the issue on your side?

**Comment by iNoles** [comment]
I confirmed it does work now. Thanks!
