### ISSUE TITLE
Improve the plugins DSL 

### ISSUE THREAD

**Issue by eskatos** [gradle/kotlin-dsl#422]

**Comment by jaredsburrows** [comment]
Any description or specific stuff to work on?

**Comment by bamboo** [comment]
Hey @jaredsburrows, we use ZenHub for GitHub to manage our issues. If you install their browser extension and navigate to https://github.com/gradle/kotlin-dsl#boards you will notice this is actually an _Epic_ and see the attached issues.

**Comment by mkobit** [comment]
1 additional request/thought - make the copy/paste snippets included on the plugin portal work in Kotlin DSL as well as they only currently work in Groovy (or add snippets to support however the Kotlin DSL evolves here)

For example, https://plugins.gradle.org/plugin/com.gradle.build-scan has

```groovy
plugins {
  id "com.gradle.build-scan" version "1.8"
}
```

But, has to be changed to:
```kotlin
plugins {
  id("com.gradle.build-scan") version "1.8"
}
```

Would be nice if `infix` was supported for the Id or if the plugin portal had updated with copy/paste snippets for Kotlin DSL.

**Comment by jaredsburrows** [comment]
@bamboo Awesome. Let me try it out.

**Comment by eskatos** [comment]
Thanks for the suggestion @mkobit, I opened #452
