### ISSUE TITLE
Script plugins can use the plugins {} DSL to define their dependencies on builtin plugins

### ISSUE THREAD

**Issue by bamboo** [gradle/kotlin-dsl#425]
**build.gradle.kts**
```kotlin
plugins {
    script("other.gradle.kts")
}
```

**other.gradle.kts**
```kotlin
plugins {
    java
}
```

**Comment by eskatos** [comment]
Once #424 is done, this comes for free for the Kotlin DSL as [the `plugins` block is already evaluated on non-top-level scripts](https://github.com/gradle/kotlin-dsl/blob/cb44112374e36b41732ab390531b8bc29e8de327/provider/src/main/kotlin/org/gradle/kotlin/dsl/provider/KotlinBuildScriptCompiler.kt#L169) ; some adjustments will be necessary for the [Groovy DSL](https://github.com/gradle/gradle/blob/8583d59f51f1ef2cf20c0630738668faa7dd7335/subprojects/core/src/main/java/org/gradle/configuration/DefaultScriptPluginFactory.java#L219-L222) to support this.
