### ISSUE TITLE
Script plugins can use static project extension accessors

### ISSUE THREAD

**Issue by bamboo** [gradle/kotlin-dsl#432]
```kotlin
// plugin.gradle.kts
plugins {
  java
}

java {
  sourceCompatibility = JavaVersion.VERSION_1_7
}
```

## Implementation notes

The plugins must not rely on the global environment in any way because they are going to be applied to a separate, synthetic project which won't share any information with the original.

**Comment by jaredsburrows** [comment]
This will be great :)

**Comment by jaredsburrows** [comment]
@bamboo Is this supported yet?

**Comment by bamboo** [comment]
No, not yet.

**Comment by JLLeitschuh** [comment]
> because they are going to be applied to a separate, synthetic project which won't share any information with the original

Can you explain this a bit better?

**Comment by jaredsburrows** [comment]
Any update on this?
