### ISSUE TITLE
init.gradle defined repositories are ignored in Intellij when editing build.gradle.kts files

### ISSUE THREAD

**Issue by flstaats** [gradle/kotlin-dsl#433]
Our organization uses a shared init.gradle file that centrally manages the initscript, buildscript, and build repositories for our builds behind our firewall as our build.gradle files do not contain repositories blocks (see partial example below).  Our Gradle Groovy-DSL the buildscripts are runable and editable from both command line and Intelij.  However with Gradle Kotlin-DSL the build scripts run from the command line but NOT from within Intellij as Intellij will not download the plugins from the internal repositories.  As a work around we have put the buildscript repository block inside the build.gradle files and Intellij works as expected.  This bug is blocking us from deploying Gradle Kotlin-DSL scripts from withing our firewall.

```
// Known issues with using initscript to set default plugins as of 13-JUL-2017:
//     https://github.com/gradle/gradle/issues/1322
//     https://github.com/gradle/gradle/issues/1370
initscript {
    repositories {
        maven {
            url 'https://nexus.standard.com:8443/nexus/repository/gradle-plugins'
        }
        maven {
            url 'https://nexus.standard.com:8443/nexus/repository/xebialabs'
        }
    }
    dependencies {
        // Dependencies for globally applied initscript apply plugin: go here
    }
    // Apply here
}
allprojects {
    buildscript {
        repositories {
            maven {
                url 'https://nexus.standard.com:8443/nexus/repository/gradle-plugins'
            }
            maven {
                url 'https://nexus.standard.com:8443/nexus/repository/xebialabs'
            }
        }
    }
    repositories {
        maven {
            url 'https://nexus.standard.com:8443/nexus/repository/public'
        }
    }
    dependencies {
        // Dependencies for globally applied buildscript apply plugin: go here
    }
    // Apply here
}
```

**Comment by flstaats** [comment]
This behavior was noted with the latest nightly gradle-kotlin-dsl-4.1-20170712173431+0000-all.zip on Intellij IDEA 2017.2 Build #IC-172.3317.76 using the built in JRE 1.8 & JDK 1.8.121 64-bit on both Windows and Linux.

**Comment by flstaats** [comment]
Using Kotlin Intellij Plugin 1.1.3-release-IJ2017.2-2

**Comment by bamboo** [comment]
Hi @flstaats, I cannot reproduce this problem against the current Kotlin DSL snapshot distribution and IntelliJ 2017.3 with Kotlin 1.2.21:

```
IntelliJ IDEA 2017.3.4 (Community Edition)
Build #IC-173.4548.10, built on January 23, 2018
Kotlin 1.2.21-release-IJ2017.3-1
JRE: 1.8.0_152-release-1024-b11 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.3
```

Please reopen the issue if you are still able to reproduce it.
