### ISSUE TITLE
Extend "by extra" functionality for Gradle properties to pass existing values and other extensions

### ISSUE THREAD

**Issue by flstaats** [gradle/kotlin-dsl#436]
Recently "val myProperty by extra" was extended to take both method() and lambda { "42" } style initializers in the files.

kotlin-dsl\provider\src\main\kotlin\org\gradle\kotlin\dsl\ExtraPropertiesExtensions.kt
kotlin-dsl\provider\src\test\kotlin\org\gradle\kotlin\dsl\ExtraPropertiesExtensionsTest.kt

I have been working on customized version that extends this functionality in four ways and am wondering if a pull request would be appreciated:

1) Optionally passes in the current value of Gradle property so that it can be used in the initialization.  For example this can be used to create default values that are only set if the property is not already set.  Note a cast is required since the default Gradle properties are of type Any?:

```
val myProperty by extra { it as? String? ?: "defaultValue" }
```

Other uses could include updating user provided template properties with additional details at run time.  Or changing the type of a property for example from a string to a boolean using pattern matching.

2) Provides additional extra.default method so that the functionality can be invoked without the extra boilerplate and visual clutter:

```
val myProperty by extra.default { "defaultValue" } // Same behavior as above.
```

3) Provides implicit conversion from String to Boolean values matching /(?i)false/ regex to false and everything else to true.  This allows setting Boolean properties from the command line.

```
// build.gradle
val myProperty by extra.default { false } // Note initializer type is Boolean
```

```
# Command line
./gradlew -PmyProperty # true, similar syntax to Maven profiles
./gradlew -PmyProperty=true # true
./gradlew -PmyProperty=abc # true
./gradlew -PmyProperty=false # false
./gradlew -PmyProperty=False # false
./gradlew # default in build file was false
```

4) Provides logging of final values of properties set with --info level logging.  My implementation also screens any property value who's property name contains /(?i)password/ from logging values to prevent accidental leakage into log files.  This probably would need to be able to be optionally toggled off with another non-default property or system value.

**Comment by JLLeitschuh** [comment]
I think you may be conflating the extra properties plugin with the properties.
One way that this could be achieved is to do something like this:

In `gradle.properties`:
```
myProperty="defaultValue"
```
In your `build.gradle.kts` file:
```kotlin
val myProperty by extra{ property["myProperty"] as String }
```
I think that the behaviour of `-PmyProperty` is that it overrides any configuration that is setup in your `gradle.properties` but I'd want @bamboo or @oehme to confirm this.

**Comment by flstaats** [comment]
I think you are mis-understanding my intent.  My end users use the build script as an example (copy paste when the overhead of a custom plugin is too high) and reasonable defaults are set in the text of the build.gradle.kts script itself.  Users would use either the gradle.properties and/or the -P command line arguments to override only defaults that don't match their needs.

The extra properties associate a strongly typed Kotlen var or val with with a Gradle property.  This is exactly what I want to do, but I also want to add semantics to set default values in the build.script .

hasProperty(): Boolean tells you if the property exists, but additional logic is needed to set a default value.

property() or property[] returns the property but throws an exception if it doesn't exist, not very useful if you are wanting to set default values in the script.

findPropery() returns the value of the property and null if it doesn't exist.

Today I can do something like this:

```val testit by extra(findProperty("testit") ?: "defaultValue")```

or

```val testit by extra { findProperty("testit") ?: "defaultValue" }```

But this violates the don't repeat yourself principle in that the variable name is repeated both in the val declaration and inside the findProperity() as a String value.  It is also visually distracting and doesn't show the intent the script is setting a default value that can be overriden.  I think the following is much clearer without the noise of repeating yourself:

```val testit by extra.default { "defaultValue" }```

Also my modifications allow you to take the user provided value set in gradle.properites and/or -P command line and modify it:

```val testit by extra { "Testit currentValue: ${it}" }```

Which today would require the more verbose:

```val testit by extra { "Testit currentValue: ${findProperty("testit")}" }```

My proposed changes provide additional behavior automatically converting Sting to Boolean if the default value is a Boolean value which I've found very useful.  Also there is some additional logging at the --info level so you can easily debug the final set values at run time.

Finally the proposal is fully backwards compatible with the existing syntax so no code would need to be rewritten if this was implemented.  I've tested the updates as a plugin which I can publish to the plugin portal if anyone is interested, but I really think the changes would be better suited in the core functionality.

**Comment by eskatos** [comment]
Thanks for your thorough proposal @flstaats,
We'll discuss internally the opportunity to include this in the Gradle Kotlin DSL.
Could you either publish your work as a community plugin in the meantime, or as a PR against this very repository, so we have more material to look at?

**Comment by bamboo** [comment]
Thanks for the suggestion, @flstaats. Those ideas are interesting but we think they are better implemented as an external plugin.
