### ISSUE TITLE
Add `Supplier<String>`-esque overloads to org.gradle.api.logging.Logger log methods

### ISSUE THREAD

**Issue by mkobit** [gradle/kotlin-dsl#441]
Mixing String interpolation and `{}` placeholder loggers can be confusing and doesn't always feel Kotlin-esque. Adding in extension methods would be useful for both build scripts and plugin development.

It would be nice to introduce some extension methods similar to https://github.com/MicroUtils/kotlin-logging , with signatures like `fun Logger.error(msg: () -> String)` and `Logger.error(msg: () -> String)` and `fun Logger.error(t: Throwable, msg: () -> String)`. Since [`Logger`](https://docs.gradle.org/4.0.1/javadoc/org/gradle/api/logging/Logger.html) extends the `org.slf4j.Logger`, it could make sense to introduce additional overloads for those methods as well.

If you accept this, I'd like to contribute it!

**Comment by bamboo** [comment]
@mkobit I think that's an interesting idea. We already have [some of those implemented internally](https://github.com/gradle/kotlin-dsl/blob/cb44112374e36b41732ab390531b8bc29e8de327/provider/src/main/kotlin/org/gradle/kotlin/dsl/support/Logger.kt#L29-L28) and we'd gladly accept a patch making them public API with proper documentation.

**Comment by bamboo** [comment]
Those would be better implemented at the Gradle side once the minimum required JVM version is upgraded to Java 8 in Gradle 5. Would you mind opening an issue in `gradle/gradle`?

**Comment by StefMa** [comment]
Wuhu 🎉
Java 8!
