### ISSUE TITLE
Chicken and egg problem with accessors.kt

### ISSUE THREAD

**Issue by dastultz** [gradle/kotlin-dsl#447]
I have a `project-schema.json` file for specifying accessors to be generated to support `build.gradle.kts`. Compilation of `accessors.kt` fails when dependencies are not available.

### Expected Behavior
When I build my project in an environment with no Gradle cache present, the project should download dependencies and compile. Kotlin accessors should resolve as they do when the dependencies are already cached.

### Current Behavior
Compilation of `accessors.kt` fails when it encounters a class that is part of dependency that is not yet available because the build has never run before in order to download the dependency.

### Context
I'm trying to use `project-schema.json` to define accessors so I can use clean syntax such as

```
myplugin {
...
}
```

### Steps to Reproduce (for bugs)
Create a project that relies on a plugin such as
```
apply {
   plugin("myplugin")
}
```
Define `project-schema.json` like so:

```
{
    ":": {
        "conventions": {
            "base": "org.gradle.api.plugins.BasePluginConvention",
            "java": "org.gradle.api.plugins.JavaPluginConvention"
        },
        "extensions": {
            "myplugin": "com.xyz.MyExtension"
        }
    }
}
```

Do configuration in the build file:

```
myplugin {
   ...
}
```

Upon compilation, when the Gradle dependency for the plug in `com.xyz.MyExtension` is not already downloaded and cached, it will fail trying to run `accessors.kt` with something like:

```
e: /root/.gradle/caches/4.0/gradle-script-kotlin-accessors/4m...lm/src/org/gradle/script/lang/kotlin/accessors.kt:85:30: Unresolved reference: xyz
```

### Your Environment

Gradle 4.0

Build time:   2017-06-14 15:11:08 UTC
Revision:     316546a5fcb4e2dfe1d6aa0b73a4e09e8cecb5a5

Groovy:       2.4.11
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_25 (Oracle Corporation 25.25-b02)
OS:           Mac OS X 10.12.6 x86_64

**Comment by bamboo** [comment]
Hi @dastultz,

There's a misunderstanding here with regards to the workflow. One shouldn't create or edit the `project-schema.json` file by hand. The correct workflow with Gradle 4.0.2 is:
 * define the dependencies and apply plugins in your build script (without using any project extensions just yet)
 * execute the `gskGenerateAccessors` task
 * edit the build script with the project extension accessors now available

Also please notice that generating accessors that way is only really needed if you are using plugins that can be applied using the [plugins DSL](https://docs.gradle.org/4.0.2/userguide/plugins.html#sec:plugins_block).

For more details please check the _Type-safe accessors for project extensions and conventions_ section in the [v0.8.0 release notes](https://github.com/gradle/kotlin-dsl/releases/v0.8.0).

As for the compilation error, there's something else going on there since the accessors are only compiled after the build script dependencies have been successfully resolved (and downloaded). In the _Steps to Reproduce_ you haven't mentioned how the dependency on the plugin is declared so I wonder if it's missing in your project?

In case it persists, could you please provide a minimal repro?

**Comment by dastultz** [comment]
Thanks or the quick response, Rodrigo. My plugin dependency is like so:

```
buildscript {
	repositories {
		gradleScriptKotlin()
		ivy {
			...
		}
	}
	dependencies {
		classpath("company:myplugin:1.0.2")
	}
}
```
Thanks for the link to the 0.8.0 release. I had seen that earlier and none of the approaches are working for me. I did run `gskGenerateAccessors` but can't seem to find any place to put the output that works. I pasted it at the bottom of `build.gradle.kts`, at the top, in a file `accessors.kt` under `buildSrc/src`, but never success.

I did edit `project-schema.json` file by hand but after generating it initially. I could not find the web page that I used to generate it, so I edited by hand to address a subproject challenge (I opened and closed another issue related to this). Perhaps the subproject arrangement is part of the problem I'm experiencing here. Here is the [issue](https://github.com/gradle/kotlin-dsl/issues/402). I had 2 identical `project-schema.json` in the root and subproject. I had to duplicate the content of the root file as specified in that issue.

**Comment by eskatos** [comment]
Hi @dastultz,

Like @bamboo said, the `project-schema.json` file is a generated file and is not supposed to be edited by hand.

If you still struggle with this, a reproducer project would help us to understand your problem. Ideally as a minimal example in a github repository.

**Comment by dastultz** [comment]
My efforts to produce an example have failed, in a good way. The description above about how to use `gskGenerateAccessors` has helped me find a flaw in `project-schema.json`. (My root project had an extensions line that was related to the sub project.)

Thanks so much for your help.

**Comment by lampapos** [comment]
@bamboo @dastultz tell me, please, how do you solve a problem from this issue in case of Android project? How do you generate `project-schema.json` if a plugin requires some fields declaration even on just `apply`?

When I try to reproduce steps that you proposed:
> * define the dependencies and apply plugins in your build script (without using any project extensions just yet)
> * execute the `gskGenerateAccessors` task _(for the current Kotlin DSL version we should use `kotlinDslAccessorsSnapshot`, does we?)_
> * edit the build script with the project extension accessors now available

with applied Android Gradle plugin I get an error:
```
> ./gradlew kotlinDslAccessorsSnapshot
Configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'experiment'.
> buildToolsVersion is not specified.
```

Is Android project exceptional case and we should add `gradle/project-schema.json` manually?

There is my `build.gradle.kts`:
```
buildscript {
  dependencies {
    classpath("com.android.tools.build:gradle:2.3.3")
  }

  repositories {
    jcenter()
  }
}

apply {
  plugin("com.android.application")
}
```

**Comment by bamboo** [comment]
Hi @lampapos,

Unfortunately the `com.android.application` plugin demands both `buildToolsVersion` and `compileSdkVersion` to be set before project configuration can succeed.

The workaround is to start with a build script where both properties are configured the old way then generate the accessors.

Start with:

```kotlin
buildscript {
  dependencies {
    classpath("com.android.tools.build:gradle:2.3.3")
  }

  repositories {
    jcenter()
  }
}

apply {
  plugin("com.android.application")
}

// android {
configure<com.android.build.gradle.AppExtension> {
  buildToolsVersion("25.0.0")
  compileSdkVersion(23)
}
```

Then run:

     ./gradlew kotlinDslAccessorsSnapshot

Then replace `configure<...AppExtension>` by `android`.

I hope that helps.

**Comment by lampapos** [comment]
Oh, got it. Thanks a lot!

**Comment by eskatos** [comment]
Just opened https://issuetracker.google.com/issues/66363371 on the Android Gradle Plugin issue tracker as a follow up
