### ISSUE TITLE
How to apply "versions" script in buildscript block?

### ISSUE THREAD

**Issue by jaredsburrows** [gradle/kotlin-dsl#449]
In this repo, I am using `applyFrom` to apply versioning for all plugins and dependencies for my project. (https://github.com/jaredsburrows/android-gif-example/blob/master/build.gradle.kts#L4)

In this PR, https://github.com/gradle/kotlin-dsl/issues/442, I removed `applyFrom` and using `apply from` does not work the same. How can I apply this script before my project is evaluated?

**Comment by jaredsburrows** [comment]
I rather not copy and paste the source like this:
```
fun Project.applyFrom(script: Any) =
  apply { from(script) }
```

And this does not work in the Kotlin DSL like it does in the Groovy DSL:
```
apply { from(rootProject.file("gradle/versions.gradle.kts")) }
```

**Comment by jaredsburrows** [comment]
You can use ` rootProject.apply { }` like:
```
buildscript {
  rootProject.apply { from(rootProject.file("gradle/dependencies.gradle.kts")) }
}
```

**Comment by JLLeitschuh** [comment]
This should be fixed though for groovy parity.
