### ISSUE TITLE
KT-19165: IntelliJ should suggest to reload Gradle projects when Kotlin build scripts change

### ISSUE THREAD

**Issue by eskatos** [gradle/kotlin-dsl#451]
When changing Groovy Gradle build scripts, IntelliJ suggests to reload the Gradle build.

It does not when changing Kotlin Gradle build scripts.

See https://youtrack.jetbrains.com/issue/KT-19165

**Comment by eskatos** [comment]
Marked as fixed upstream and targeted at Kotlin 1.2.40 \o/

**Comment by eskatos** [comment]
Confirmed as fixed in 1.2.40-EAP-16

**Comment by bamboo** [comment]
Closing as fixed upstream.
