### ISSUE TITLE
ModuleDependency setting force/transitive is different than Groovy

### ISSUE THREAD

**Issue by mkobit** [gradle/kotlin-dsl#453]
### Expected Behavior

Should match the `force = true` example from the Groovy examples

### Current Behavior

Must use `isForce = true`

### Context

Was attempting to provide some finer grained dependency setup.

### Steps to Reproduce (for bugs)

1. Set up project with Gradle 4.1
1. Create a `build.gradle.kts` file with the following:
    ```kotlin
    plugins {
      `java-library`
    }

    repositories {
      jcenter()
    }

    configurations {
    }

    dependencies {
      // contrived example
      testImplementation("com.nhaarman:mockito-kotlin:1.5.0") {
        // force = true and transitive = false do not work
        isForce = true
        isTransitive = false
      }
    }
    ```

### Your Environment

* Gradle 4.1

**Comment by bamboo** [comment]
That's standard Kotlin behaviour:

> `Boolean` accessor methods (where the name of the getter starts with `is` and the name of the setter starts with `set`) are represented as properties which have the same name as the getter method.

https://kotlinlang.org/docs/reference/java-interop.html#getters-and-setters

That's exactly the case of `ExternalDependency#isForce()` (https://github.com/gradle/gradle/blob/c8143c9bcf412a2d19053b8c926c7787c1dc8087/subprojects/core/src/main/java/org/gradle/api/artifacts/ExternalDependency.java#L25).

**Comment by mkobit** [comment]
Ah, woops.

Thanks for quick response, going to close.
