### ISSUE TITLE
Provide convenient configuration of nested project extensions and conventions

### ISSUE THREAD

**Issue by bamboo** [gradle/kotlin-dsl#457]
Although a relatively uncommon pattern, project extensions can themselves be extended. 

The Kotlin DSL should provide accessors for all nested extensions found at project schema computation time.

Related forum post: https://discuss.gradle.org/t/make-a-gradle-plugin-compatible-with-kotlin-dsl/23657/3

**Comment by eskatos** [comment]
Here is another example of a plugin using nested extensions: https://github.com/GoogleCloudPlatform/app-gradle-plugin/blob/v1.3.3/src/main/java/com/google/cloud/tools/gradle/appengine/core/AppEngineCorePlugin.java#L67-L76

**Comment by JLLeitschuh** [comment]
The Junit 5 plugin used to do this too before I opened a PR to fix it.
There needs to be a way to make sure that the compiler doesn't complain or blow up about having duplicate extensions if the plugin author has added these helper methods themself.

Example:
https://github.com/junit-team/junit5/blob/master/junit-platform-gradle-plugin/src/main/groovy/org/junit/platform/gradle/plugin/JUnitPlatformExtension.groovy#L100-L102
```groovy
class JUnitPlatformExtension {
	void selectors(Action<SelectorsExtension> closure) {
		closure.execute(getProperty(JUnitPlatformPlugin.SELECTORS_EXTENSION_NAME) as SelectorsExtension)
	}
}
```
And how the extensions are added:
https://github.com/junit-team/junit5/blob/master/junit-platform-gradle-plugin/src/main/groovy/org/junit/platform/gradle/plugin/JUnitPlatformPlugin.groovy#L41

**Comment by NikolayMetchev** [comment]
Is there a workaround for this? Is there ANY way to get the nested extensions? i am trying to use the Jaxb plugin which nests the xjc extensions inside the jaxb extensions (https://github.com/jacobono/gradle-jaxb-plugin). How would I customize the xjc extensions?

**Comment by NikolayMetchev** [comment]
I have managed to figure out the workaround for the Jaxb case but it is a complete hack. If someone has a better workaround let me know. 

Add this method to the script:
`
fun JaxbExtension.xjc(configure: XjcExtension.() -> Unit) {
  val convention: DefaultConvention = this::class.members.find { m -> m.name == "getConvention" }?.call(this) as DefaultConvention
  configure.invoke(convention.getByName("xjc") as XjcExtension)
}
`


Which will then allow you to customize Jaxb as expected:
`
jaxb {
  xjc {
    destinationDir = "src/generated/java"
  }
  xsdDir = projectDir.resolve("src").resolve("xsd").relativeTo(rootDir).toString()
}
`

**Comment by bamboo** [comment]
Hi @NikolayMetchev, 

A simpler workaround would be to cast the outer extension to `ExtensionAware` and extract the extension explicitly as in the following (working) example:

```kotlin
import org.gradle.jacobo.plugins.extension.XjcExtension

plugins {
    id("com.github.jacobono.jaxb") version "1.3.5"
}

jaxb {

    val jaxbExtensions = (this as ExtensionAware).extensions

    val xjc: XjcExtension by jaxbExtensions
    xjc.apply {
        destinationDir = "src/generated/java"
    }

    xsdDir = projectDir.resolve("src").resolve("xsd").relativeTo(rootDir).toString()
}
```

**Comment by NikolayMetchev** [comment]
Thanks @bamboo that is a much better workaround.

**Comment by Xerus2000** [comment]
I think a first step would be to atleast have an extension function as a simple workaround within kotlin-dsl, maybe something like this:

```
fun <T : Any> Any.extensionAware(clazz: KClass<T>, action: T.() -> Unit) = (this as ExtensionAware).extensions.configure(clazz.java, action)
```

**Comment by eskatos** [comment]
Closing as delivered
