### ISSUE TITLE
JacocoPluginExtension::applyTo can not be called from Kotlin

### ISSUE THREAD

**Issue by JLLeitschuh** [gradle/kotlin-dsl#458]
### Expected Behavior

Ability to call:
```kotlin
jacoco {
    applyTo(tasks.matching { name == "junitPlatformTest" } as TaskCollection<*>)
}
```
OR:
```kotlin
jacoco {
    applyTo(tasks.matching { name == "junitPlatformTest" })
}
```
OR:
```kotlin
jacoco {
    applyTo(tasks.getByName("junitPlatformTest") as Task)
}
```
OR:
```kotlin
jacoco {
    applyTo(tasks.getByName("junitPlatformTest"))
}
```

This same problem exists even if you try wrapping the method names in backticks.

### Current Behavior

When calling the `applyTo` with the signature `<T extends Task & JavaForkOptions> void applyTo(TaskCollection tasks)`:
```
e: /Users/jonathanleitschuh/personal/git/shuffleboard/build.gradle.kts:102:13: Type inference failed: Not enough information to infer parameter T in fun <T : Task!> applyTo(tasks: TaskCollection<(raw) Task!>!): Unit where T : JavaForkOptions!
Please specify it explicitly.
```

When calling the `applyTo` with the signature `<T extends Task & JavaForkOptions> void applyTo(final T task)`:
```
> Configure project :
e: /Users/jonathanleitschuh/personal/git/shuffleboard/build.gradle.kts:102:13: None of the following functions can be called with the arguments supplied: 
public open fun <T : Task!> applyTo(task: (???..???)): Unit where T : JavaForkOptions! defined in org.gradle.testing.jacoco.plugins.JacocoPluginExtension
public open fun <T : Task!> applyTo(tasks: TaskCollection<(raw) Task!>!): Unit where T : JavaForkOptions! defined in org.gradle.testing.jacoco.plugins.JacocoPluginExtension
Latest annotated tag is null. This does not match the expected version number pattern.

```

### Context

I'm trying to configure Jacoco to run with Junit 5

### Steps to Reproduce (for bugs)

See above.

### Your Environment

 * Build scan URL: 

Gradle version: `4.1`.

**Comment by JLLeitschuh** [comment]
This is the workaround code that I'm using and I know works:
```
/**
 * Workaround fix for calling [org.gradle.testing.jacoco.plugins.JacocoPluginExtension.applyTo]
 *
 * [Issue details here](https://github.com/gradle/kotlin-dsl/issues/458)
 */
fun org.gradle.testing.jacoco.plugins.JacocoPluginExtension.applyToHelper(task : Task) {
    val method = this::class.java.getMethod("applyTo", Task::class.java)
    method.invoke(this, task)
}
```

**Comment by JLLeitschuh** [comment]
I think that this has been resolved? Not entirely sure. Are you waiting to close this until after there is a Gradle release with this fix?

**Comment by JLLeitschuh** [comment]
In hindsight, this may have simply been my problem, not an issue with the compiler.
However, the type on the collection is wrong.

In my original example this didn't work which is sane because of the compiler:
```kotlin
jacoco {
    applyTo(tasks.getByName("junitPlatformTest") as Task)
}
```
This, on the other hand does work:
```kotlin
jacoco {
    applyTo(tasks.getByName("junitPlatformTest") as JavaExec)
}
```

Similarly, this didn't work:
```kotlin
jacoco {
    applyTo(tasks.matching { name == "junitPlatformTest" } as TaskCollection<*>)
}
```
But this does work:
```kotlin
jacoco {
    applyTo<JavaExec>(tasks.matching { name == "junitPlatformTest" })
}
```

The API in Gradle did need to be updated though. So we did the right thing there.

**Comment by eskatos** [comment]
Thanks @JLLeitschuh for following up!

The Gradle API has not seen any recent changes wrt this issue. I believe it already worked as described in your last comment.

Closing

**Comment by bamboo** [comment]
@eskatos there is a related change pending on Gradle that I intended to follow up on: https://github.com/gradle/gradle/commit/40d09068cf6fb6fbdd0b1ade10f90d4185fc204e

**Comment by eskatos** [comment]
Fixed in upstream Gradle by https://github.com/gradle/gradle/commit/f8f8618490f6592b625ce52c40d76d63ca7c7074

Closing
