### ISSUE TITLE
Multi Android project won't build with Gradle 4.1

### ISSUE THREAD

**Issue by GFriedrich** [gradle/kotlin-dsl#460]
Hi,
after switching from Gradle 4.0.2 to 4.1 I'm not able to build my multi Android project anylonger.
Gradle build scripts and the projects are written with Kotlin.
Gradle complains about not being able to compile the Gradle Kotlin build scripts of the subprojects.
Basically all references are unresolved, e.g. "app\build.gradle.kts:11:5: Unresolved reference: compile"
@bamboo: Maybe you can provide a working sample project for Android with multi project structure.
Thanks a lot in advance.

**Comment by GFriedrich** [comment]
Ah okay ... after fiddling around with the configuration, I found out that the "project-schema.json" was moved with the latest release. (Yes, this is mentioned in the "Misc" section of the changelog, but I would've expected such an information at the top of the changelog...)

Anyhow: Everything is back working.
Appreciate your work in the Kotlin DSL!

**Comment by bamboo** [comment]
Hi @GFriedrich, I'm sorry for your trouble. Following your suggestion I moved the warning about the new location for "project-schema.json" to the top of the [`0.10.1` release notes](https://github.com/gradle/kotlin-dsl/releases/tag/v0.10.1).

Cheers!

**Comment by GFriedrich** [comment]
@bamboo ah, don't worry - sh... happens ;) ... thanks for moving it to the top.

**Comment by hastebrot** [comment]
I had the same problem with `Unresolved reference: compile` and didn't update my kotlin-dsl snapshot since mid-June. It still occurred with a snapshot from today. After I read this issue deleting the existing `project-schema.json` solved the problem for me.
