### ISSUE TITLE
JacocoLimit setMinimum isn't Kotlin friendly

### ISSUE THREAD

**Issue by JLLeitschuh** [gradle/kotlin-dsl#467]
### Expected Behavior
Should be able to use the same syntax to configure `JacocoLimit` as in groovy:
```gradle
violationRules {
    rule {
        limit {
            minimum = 0.5
        }
    }
}
```

### Current Behavior
You need to use (and this requires importing)
```kotlin
tasks.withType<JacocoCoverageVerification>{
    dependsOn(jacocoJunit5TestReport)
    violationRules {
        rule {
            limit {
                minimum = BigDecimal(0.5)
            }
        }
    }
}
```

Even this would be better: `0.5.toBigDecimal()`

### Context
This is a minor inconvenience but it could be made better with an overloaded API for `setMinimum` that takes a `double`

### Your Environment
Gradle version `4.1`.

**Comment by eskatos** [comment]
Thanks for the well written issue @JLLeitschuh.

`BigDecimal` is part of the [implicit imports](https://github.com/gradle/kotlin-dsl/blob/develop/provider/src/main/kotlin/org/gradle/kotlin/dsl/support/ImplicitImports.kt#L40) so you should not have to import it explicitly.

Also see the [`code-quality` sample](https://github.com/gradle/kotlin-dsl/blob/develop/samples/code-quality/build.gradle.kts#L41-L47) that demonstrate exactly this.

Adding a `setMinimum` overload to `JacocoLimit` won't make it much nicer as the corresponding getter/property type will still be of the `BigDecimal` type so you'd have to write:

```kotlin
limit {
    setMinimum(0.5)
}
```

**Comment by jaredsburrows** [comment]
@JLLeitschuh Does `setMinimum` work? If so, can you close this one?

**Comment by JLLeitschuh** [comment]
I mean no, `setMinimum` takes a `BigDecimal`.

**Comment by eskatos** [comment]
Closing as won't fix
