### ISSUE TITLE
plugins.apply(...) not working from IdeaPlugin

### ISSUE THREAD

**Issue by BorzdeG** [gradle/kotlin-dsl#475]
build.gradle:

```
buildscript.repositories { jcenter() }
if (project == rootProject) {
	plugins.apply(IdeaPlugin.class)
	idea.module.downloadSources = false
}
```

execute `./gradlew -b ./build-idea.gradle tasks` - return "IDE tasks" section

build.gradle.kts:

```
buildscript.repositories { jcenter() }
if (project == rootProject) {
	plugins.apply(IdeaPlugin::class.java)
	idea.module.isDownloadSources = false
}
```

execute `./gradlew -b ./build-idea.gradle.kts tasks` - return exception:

```
: $CUT_PROJECT_DIR/build-idea.gradle.kts:4:2: Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
public val PluginDependenciesSpec.idea: PluginDependencySpec defined in org.gradle.kotlin.dsl


FAILURE: Build failed with an exception.
```

working example `build.gradle.kts`:

```
buildscript.repositories { jcenter() }
if (project == rootProject) {
	plugins.apply(JavaPlugin::class.java)
}
```

output `./gradlew -v`:

```
------------------------------------------------------------
Gradle 4.1
------------------------------------------------------------

Build time:   2017-08-07 14:38:48 UTC
Revision:     941559e020f6c357ebb08d5c67acdb858a3defc2

Groovy:       2.4.11
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_152-ea (Oracle Corporation 25.152-b05)
OS:           Mac OS X 10.12.6 x86_64
```

**Comment by bamboo** [comment]
Hi @BorzdeG,

The `idea` static extension accessor is only available when the plugin is applied via the top-level `plugins` block.

When the plugin is applied imperatively, the extension needs to be retrieved explicitly via one of the provided mechanisms:

 1. By type via the `the<ExtensionType>()` utility:

    ```kotlin
     the<IdeaModel>().module.isDownloadSources = false
    ```

 2. By type via the `configure<ExtensionType>() { ... }` utility:

    ```kotlin
     configure<IdeaModel> {
       module.isDownloadSources = false
    }
    ```

  3. By name and type via delegated properties:

     ```kotlin
     val idea: IdeaModel by extensions
     idea.module.isDownloadSources = false
     ```
   4. By copying the static accessor code given by the `./gradlew kotlinDslAccessorsReport | grep idea` command into the script and using it as if the plugin had been applied via the `plugins` block.

**Comment by BorzdeG** [comment]
4.

```
$ ./gradlew kotlinDslAccessorsReport | grep -i idea
 * Retrieves the [idea][org.gradle.plugins.ide.idea.model.IdeaModel] project extension.
val Project.`idea`: org.gradle.plugins.ide.idea.model.IdeaModel get() =
    extensions.getByName("idea") as org.gradle.plugins.ide.idea.model.IdeaModel
 * Configures the [idea][org.gradle.plugins.ide.idea.model.IdeaModel] project extension.
fun Project.`idea`(configure: org.gradle.plugins.ide.idea.model.IdeaModel.() -> Unit): Unit =
    extensions.configure("idea", configure)
```

The problem is that there is no opportunity to apply a plug-in, but not its subsequent configuring.
i.e. how to apply a plug-in only in case of execution of a certain condition?

**Comment by BorzdeG** [comment]
fixed: replaced first `./gradlew -b ./build-idea.gradle.kts tasks` with `./gradlew -b ./build-idea.gradle tasks`
