### ISSUE TITLE
KT-18062 - SamWithReceiver not setup by IntelliJ for .kt files in buildSrc

### ISSUE THREAD

**Issue by eskatos** [gradle/kotlin-dsl#476]
https://youtrack.jetbrains.com/issue/KT-18062#comment=27-2397603

![image](https://user-images.githubusercontent.com/132773/29972265-d74ec822-8f2b-11e7-8a07-d9c47d5eeb93.png)

Also see #373

**Comment by bamboo** [comment]
Can't no longer reproduce with 1.2.20.
