### ISSUE TITLE
Minimize impact of Kotlin dependencies on distribution file size

### ISSUE THREAD

**Issue by cbeams** [gradle/kotlin-dsl#48]
The inclusion of `gradle-script-kotlin` and its transitive dependencies causes the Gradle distribution zip to grow by more than 22 MB, 20 MB of which is due to the `kotlin-compiler-embeddable` jar alone.

There are multiple ways to approach dealing with this, including:
- resolving gradle-script-kotlin and its dependencies on demand into a Gradle distribution instead of packaging them with the distribution up front
- using ProGuard or similar to pare down the Kotlin compiler classes to only those that we actually need (it is unknown whether this would produce any measurable reduction)
- do both of the above

In any case, per our last discussions with JetBrains on this topic, it doesn't sound likely that the file size of the embeddable compiler jar will be reduced any time soon.

**Comment by adammurdoch** [comment]
+1 to resolve and download.

**Comment by jaredsburrows** [comment]
Is this really a problem? Since `kotlin-script` is now shipped with Gradle, this is a one time install.
