### ISSUE TITLE
Add Kotlin and Kotlin-DSL Version to -version print out

### ISSUE THREAD

**Issue by JLLeitschuh** [gradle/kotlin-dsl#481]
Running `./gradlew -version` currently prints out something like this:

```
------------------------------------------------------------
Gradle 4.1
------------------------------------------------------------

Build time:   2017-08-07 14:38:48 UTC
Revision:     941559e020f6c357ebb08d5c67acdb858a3defc2

Groovy:       2.4.11
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_92 (Oracle Corporation 25.92-b14)
OS:           Mac OS X 10.12.6 x86_64
```

### Expected Behavior
If you are using the Gradle Kotlin DSL then you should also see the embeded version of Kotlin being used in your build. Additionally, you should probably also see the version of the Gradle Kotlin DSL JAR being used (assuming that these versions will remain diverged from the normal Gradle version).

### Current Behavior
No information is printed about the kotlin DSL when `./gradlew -version` is run.

### Context
This will help maintainers who want users to report their environment in issues. This will allow maintainers to quickly see what version of Kotlin is being used in the build without having to know what version of Gradle shipped with what version of Kotlin.

### Your Environment
See above.

**Comment by JLLeitschuh** [comment]
@oehme @bamboo would this issue be better against the gradle project? I'd be happy to take a crack at fixing it if someone could point me to the place where the `-version` information is printed.

**Comment by bamboo** [comment]
@JLLeitschuh it's printed here: https://github.com/gradle/gradle/blob/7d1da13df2cdc2406cc95429e70a6828b6d850a5/subprojects/launcher/src/main/java/org/gradle/launcher/cli/CommandLineActionFactory.java#L175

**Comment by JLLeitschuh** [comment]
So, some problems I'm running into as I'm attempting to tackle this one.

The Gradle Kotlin DSL isn't a dependency of the launcher project.
Additionally, Kotlin isn't a dependency of launcher either, if it was I could use `kotlin.KotlinVersion` to pull this information.

Some thoughts that I'm having:
 * Try to read this information from a `externalVersions.properties` that I add as a resource in the launcher project. I'd store `kotlin.version` and `gradle.kotlin-dsl.version` in that file.
 * If the `kotlin-dsl` will be available at runtime I could use some reflection magic to get the class, from there I can do `[someclass].getPackage().getImplementationVersion()` to get the versions.

**Comment by eskatos** [comment]
One thing you should consider is that as of today, `:launcher` must work on Java 5 😞 
So, displaying the Kotlin & Kotlin DSL versions should be lenient.

Kotlin and the Kotlin DSL are available in the launcher classpath at runtime. Reflection might be an option:

```java
private static String kotlinVersions() {
    try {
        ClassLoader loader = CommandLineActionFactory.class.getClassLoader();
        String kotlinVersion = loader.loadClass("kotlin.KotlinVersion").getDeclaredField("CURRENT").get(null).toString();
        String dslVersion = loader.loadClass("org.gradle.kotlin.dsl.GradleDsl").getPackage().getImplementationVersion();
        return "DSL " + dslVersion + " using Kotlin " + kotlinVersion;
    } catch (Throwable ex) {
        return "N/A";
    }
}
```

This does work. But it may not be how we want to do it.

Another option would be to augment `org.gradle.scripts.ScriptingLanguage` so that it provides the information, and the implementation could then be on the Kotlin DSL side.

@bamboo, any thoughts?

**Comment by bamboo** [comment]
I think reflecting on Kotlin libraries on the `:launcher` side would be bad as this is a `kotlin-dsl` dependency and `:launcher` shouldn't know about it.

I also think `org.gradle.scripts.ScriptingLanguage` is not the right place for that information. Another very lightweight SPI similar to `ScriptingLanguage` could be (`VersionInfoProvider`?).

Another idea that comes to mind would be to use well-known  resource files in the classpath as the "SPI", say, any Gradle module that wants to participate in `--version` would include a `META-INF/gradle-module/version-info.(txt|properties)` with the desired output.

**Comment by JLLeitschuh** [comment]
I'm not really certain I understand how you'd want this to be a general solution.

Wouldn't it need to be a file with something like `META-INF/gradle-module-[some-name]/version-info.(txt|properties)`?

Maybe I just don't understand how the `META-INF` directory behaves.

**Comment by eskatos** [comment]
`gradle/gradle`'s `:launcher` classpath at runtime in the client VM doesn't include dynamic modules. Resources from Kotlin DSL jars can't be used there as is.

**Comment by JLLeitschuh** [comment]
@eskatos So would this need to be something that gets encoded in a properties file during gradle build time? The build producing the Gradle release has this information so could encode it in some properties file correct?

**Comment by eskatos** [comment]
@JLLeitschuh The `gradle/gradle` build knows the `gradle-kotlin-dsl` version, but not the Kotlin version directly. I don't feel comfortable with having some logic in the `gradle/gradle` build to infer that.

Instead, the `gradle/kotlin-dsl` jar should embed its version information, say in a properties file. And then the `gradle/gradle` build could load these versions in order to encode them in a way `:launcher` can get to them at runtime.

**Comment by JLLeitschuh** [comment]
Does the launcher have the `kotlin-dsl` JAR somewhere in scope so it can read it?
