### ISSUE TITLE
Applying build scan plugin in both init.d and Kotlin build script fails with unhelpful error message

### ISSUE THREAD

**Issue by pioterj** [gradle/kotlin-dsl#489]
Applying build scan plugin in both `init.d` and Kotlin build script fails with unhelpful error message. Such scenario works in Groovy script where (somewhat surprisingly) `init.d` wins. 

The error message is: `com.gradle.scan.plugin.internal.api.f_Decorated cannot be cast to com.gradle.scan.plugin.internal.api.f`

Reproduced on 4.1 and 4.2-RC1.

Build scan: https://gradle.com/s/xf4rm6krpaztq

## Steps to reproduce:

1) Add the following script to `~/.gradle/init.d` directory:

```
initscript {
    repositories {
        maven {
            url "https://plugins.gradle.org/m2"
        }
    }
    dependencies {
        classpath "com.gradle:build-scan-plugin:1.9"
    }
}

rootProject {
      apply plugin: com.gradle.scan.plugin.BuildScanPlugin
      buildScan {
          publishAlways()
          licenseAgreementUrl = "https://gradle.com/terms-of-service"
          licenseAgree = "yes"
      }
}
```

2) Create a `gradle.kotlin.dsl` file with the following content:

```
plugins {
    `build-scan`
}

buildScan {
    setLicenseAgreementUrl("https://gradle.com/terms-of-service")
    setLicenseAgree("yes")
}
```

3) Run `gradle help`

Build fails with the message `com.gradle.scan.plugin.internal.api.f_Decorated cannot be cast to com.gradle.scan.plugin.internal.api.f`

**Comment by eskatos** [comment]
This happens because when applying the build scan plugin in an init script, the registered `buildScan` extension is defined in the init scripts classloader scope. Then, when configuring the `buildScan` extension in a project script, the type of the extension comes from another classloader, hence the `ClassCastException`.

Here's a workaround that can be used until this gets fixed:

```kotlin
// build.gradle.kts

plugins {
    `build-scan`
}

extensions["buildScan"].withGroovyBuilder {
    "setLicenseAgreementUrl"("https://gradle.com/terms-of-service")
    "setLicenseAgree"("yes")
}
```

**Comment by bamboo** [comment]
Related to #145

**Comment by eskatos** [comment]
Closing in favor of upstream https://github.com/gradle/gradle/issues/4078
