### ISSUE TITLE
Dollar sign in extension/configuration names produce not-compilable project accessors

### ISSUE THREAD

**Issue by eskatos** [gradle/kotlin-dsl#494]
Plugins registering configurations or extensions with a dollar sign (`$`) in their name produce not-compilable project accessors.

### Expected Behavior
Project accessors for configurations or extensions with a `$ ` in their name should just work.

### Current Behavior
Compilation of accessors fail very early: https://scans.gradle.com/s/csbhz2zq3s53k

### Context
I was trying to port the build of a Gradle Guide to use the Kotlin DSL.
It indirectly makes use of the `org.ysb33r.gradletest` that registers a configuration and an extension with `$` in their names: [`GradleRunnerPlugin.groovy`](https://github.com/ysb33r/gradleTest/blob/45f3bb8500178034a4b2cba737a744b227c11f44/src/main/groovy/org/ysb33r/gradle/gradlerunner/GradleRunnerPlugin.groovy#L29-L30)

### Steps to Reproduce (for bugs)
Apply a plugin that registers configurations and extensions with `$` in their name.

### Implementation notes
See https://kotlinlang.org/docs/reference/basic-types.html#string-templates

**Comment by JLLeitschuh** [comment]
That is an amazing edge case that I wouldn't have ever thought of. Totally makes sense though.

Can you have the `'` character in an extension? If so that won't work either as you can't have the `'` character in field or method names but you might in an extension name.

**Comment by eskatos** [comment]
@JLLeitschuh, it is ok tu use `'` for function, field or Kotlin extension names. It is not legal for a type name though.

This convoluted example works:
```kotlin
data class Foo(val `'baz'ar'`: String) {
    fun `''bar''`() {
        println(`'baz'ar'`)
    }
}

fun Foo.`'''baz'''`() {
    `''bar''`()
}

fun main(args: Array<String>) {
    Foo("cathedral").`'''baz'''`()
}
```

> Can you have the `'` character in an extension?

Yes you can!
