### ISSUE TITLE
Project::setDefaultTasks should take list of Object instead of string

### ISSUE THREAD

**Issue by JLLeitschuh** [gradle/kotlin-dsl#498]
### Expected Behavior
`setDefaultTasks` should have the same signature as `dependsOn` which takes a `Set<Object>`.

### Current Behavior
`setDefaultTasks` takes a `List<String>`

### Context
You can't pass references to `Task`s directly into `setDefaultTasks`, instead you must map to the tasks name.

### Your Environment

I'm looking at the line in the `fixures` subproject that is a part of this build.

```
------------------------------------------------------------
Gradle 4.3-20170914120502+0000
------------------------------------------------------------

Build time:   2017-09-14 12:05:02 UTC
Revision:     5defb547194cfc37c9a9663d868cafecb5729cb1

Groovy:       2.4.11
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_92 (Oracle Corporation 25.92-b14)
OS:           Mac OS X 10.12.6 x86_64
```

**Comment by bamboo** [comment]
This issue should be open against [gradle/gradle](https://github.com/gradle/gradle).

**Comment by bamboo** [comment]
Closing as Invalid.

**Comment by JLLeitschuh** [comment]
Fair enough.
