### ISSUE TITLE
Travis intermittently killing Gradle processes

### ISSUE THREAD

**Issue by eskatos** [gradle/kotlin-dsl#504]
### Expected Behavior
Travis CI is stable

### Current Behavior
On Travis, tests intermittently fail because the Travis machines are running out of memory and the OS is killing test workers, the Gradle daemons or Kotlin compiler daemon they start.

Here are some example failed builds:
- https://travis-ci.org/gradle/kotlin-dsl/jobs/275807645#L1188
- https://travis-ci.org/gradle/kotlin-dsl/builds/272899485#L1342
- https://travis-ci.org/gradle/kotlin-dsl/jobs/277863204#L2305

### Context
Github checks on PRs are 🔴 when they should not be. This is confusing.

**Comment by JLLeitschuh** [comment]
Are you sure? This looks like a compiler error:
https://travis-ci.org/gradle/kotlin-dsl/jobs/278180203#L954-L955

**Comment by eskatos** [comment]
You're right this one is! Fixed by baa22fe1f6526c40c587b83ed1da1b76f6fec3ce

I added some example builds to the description

**Comment by JLLeitschuh** [comment]
Would a solution simply be not to use the Gradle Daemon when running the integration tests on Travis CI?

**Comment by oehme** [comment]
I'd start by limiting memory for the [client VM](https://github.com/gradle/kotlin-dsl/blob/master/gradlew#L31). Without any bounds there, it'll just reserve whathever the default for that JDK is, which is *way* too much.

**Comment by oehme** [comment]
I'd start by limiting memory for the [client VM](https://github.com/gradle/kotlin-dsl/blob/master/gradlew#L31). Without any bounds there, it'll just reserve whathever the default for that JDK is, which is _way_ too much.

**Comment by oehme** [comment]
`gradle.properties` is for the daemon memory. The client VM is configured either via the script or using `GRADLE_OPTS`. 128m should be plenty for logging some stuff to the command line.

**Comment by eskatos** [comment]
We already do some process memory control, see:
- [gradle.properties](https://github.com/gradle/kotlin-dsl/blob/develop/gradle.properties#L1)
- [buildSrc/src/main/kotlin/build/Testing.kt](https://github.com/gradle/kotlin-dsl/blob/develop/buildSrc/src/main/kotlin/build/Testing.kt#L8)
- [test-fixtures/src/main/kotlin/org/gradle/kotlin/dsl/fixtures/AbstractIntegrationTest.kt](https://github.com/gradle/kotlin-dsl/blob/develop/test-fixtures/src/main/kotlin/org/gradle/kotlin/dsl/fixtures/AbstractIntegrationTest.kt#L131)

Thanks @oehme, I just added limits to the root `gradlew`, it should free up some room.

**Comment by JLLeitschuh** [comment]
@eskatos This probably requires a change to the `update-wrapper.sh` script so that these changes are preserved between gradle updates.

Every time gradle is updates it re-downloads the newest version of the `gradlew` and `gradlew.bat` meaning those limits will get blown away.

**Comment by eskatos** [comment]
@JLLeitschuh yes agreed. I confess I did bend the rules to try it out quickly. The build of `develop` just passed 2*3 times in a row: https://travis-ci.org/gradle/kotlin-dsl/builds/278258976. This looks promising, I guess we are very close to Travis limits ; thanks @oehme!

**Comment by eskatos** [comment]
We don't use regular Gradle distributions in the wrappers but snapshot distributions including a snapshot of the Kotlin DSL downloaded from a snapshot repository. We also have a lot of wrappers in the repository (e.g. in samples), all should be in sync.

That's why we can't use the Gradle `wrapper` task and we have this `update-wrapper.sh` script instead. It only changes all the `**/gradle/wrapper/gradle-wrapper.properties` files without having to configure the Gradle build and without touching the wrapper scripts and jar file. The downside is that we need to update these from time to time, carefully. So I guess I'll leave the memory limit hardcoded in `gradlew` for now, diffs will remind us about it.

@JLLeitschuh, let's see if Travis is still killing some processes, in that case, let's add links to such builds here so we can follow up.

**Comment by eskatos** [comment]
Another occurence after limiting client vm size: https://travis-ci.org/gradle/kotlin-dsl/jobs/278272752#L1166

**Comment by eskatos** [comment]
c41ca8f8489166e2b0b5f1685530e6e814d2ba2c should also help, thanks @mkobit

**Comment by eskatos** [comment]
https://travis-ci.org/gradle/kotlin-dsl/jobs/281314386#L1149

**Comment by JLLeitschuh** [comment]
Another one:
https://travis-ci.org/gradle/kotlin-dsl/jobs/286133671#L1078-L1084

**Comment by JLLeitschuh** [comment]
Would an adequate fix be to run the task three times so that if it fails once then there is a chance that it will pass on the subsequent run?

**Comment by eskatos** [comment]
Could be a way to work around the issue yes.

Gradle monitors the system for low memory and expire/kill idle daemons and worker processes to prevent memory starving. This do not apply to the KotlinCompiler daemon which is not managed by Gradle. See https://youtrack.jetbrains.com/issue/KT-21056

**Comment by eskatos** [comment]
Fixed in #953, closing
