### ISSUE TITLE
Update Android sample when AGP 3 is out

### ISSUE THREAD

**Issue by eskatos** [gradle/kotlin-dsl#505]
See https://developer.android.com/studio/build/gradle-plugin-3-0-0.html

**Comment by hzsweers** [comment]
FYI, with rc1 (possibly older ones, I haven't tried), the kotlin gradle plugin pulled in by kotlin-dsl crashes the build due to depending on a no-longer-there class `BaseVariant`

**Comment by jaredsburrows** [comment]
This can be closed. did this here:  @liutikas completed this here https://github.com/gradle/kotlin-dsl/blob/develop/samples/hello-android/build.gradle.kts#L2.

**Comment by eskatos** [comment]
Thanks for the heads up @jaredsburrows!
