### ISSUE TITLE
kotlin-dsl Gradle plugin declares redundant runtime Kotlin dependency

### ISSUE THREAD

**Issue by Minecrell** [gradle/kotlin-dsl#509]
Currently, the `kotlin-dsl` Gradle plugin adds `kotlin-stdlib` and `kotlin-reflect` twice to the compile classpath. Once from the `embedded-kotlin` plugin and once using `gradleKotlinDsl()`. This doesn't cause any problems, however, since the Kotlin dependency added by the `embedded-kotlin` is defined as regular `compile` dependency, it is also added to `pom.xml` of the new Gradle plugin:

```xml
<dependency>
  <groupId>org.jetbrains.kotlin</groupId>
  <artifactId>kotlin-stdlib</artifactId>
  <version>1.1.4-3</version>
  <scope>compile</scope>
</dependency>
<dependency>
  <groupId>org.jetbrains.kotlin</groupId>
  <artifactId>kotlin-reflect</artifactId>
  <version>1.1.4-3</version>
  <scope>compile</scope>
</dependency>
```

As a result, Gradle will now attempt to download `kotlin-stdlib` and `kotlin-reflect` when such a Gradle plugin is used in a project. This is redundant, because these are already provided by kotlin-dsl at runtime.

### Expected Behavior
Using `kotlin-dsl` should not trigger additional downloads of the Kotlin libraries when the newly created Gradle plugins are applied to a project.

### Current Behavior
Gradle downloads an unused copy of `kotlin-stdlib` and `kotlin-reflect` when Gradle plugins created with `kotlin-dsl` are applied to a project.

### Suggested Solution
Make `kotlin-stdlib` and `kotlin-reflect` provided/compile only when using the `gradle-dsl` plugin.

**Comment by eskatos** [comment]
Thanks for the report @Minecrell 

You're right, the `embedded-kotlin` plugin, applied by the `kotlin-dsl` plugin should add these dependencies to `compileOnly` and `testCompileOnly` instead of `compile`.
