### ISSUE TITLE
Change default koltin sourceSet srcDir

### ISSUE THREAD

**Issue by thergbway** [gradle/kotlin-dsl#515]
Currently I do not see any possibility to change srcDir for main kotlin sourceSet.
I do not want to use separate folder for kotlin src. Therefore I am going to change it to default java srcDir but I do not see the way to do it.
Fragment of Kotlin-Gradle setup taken from [here](http://kotlinlang.org/docs/reference/using-gradle.html):

```
The corresponding sourceSets property should be updated if not using the default convention:

sourceSets {
    main.kotlin.srcDirs += 'src/main/myKotlin'
    main.java.srcDirs += 'src/main/myJava'
}
```

This is because I cannot take sourceSets property for the 'kotlin' object in my build script.
I use kotlin("jvm") with the default version ("1.1.50") and kotlin std lib:  "org.jetbrains.kotlin:kotlin-stdlib-jre8:1.1.50")

**Comment by JLLeitschuh** [comment]
You can work around this with the logic here:
https://github.com/gradle/kotlin-dsl/blob/201534f53d93660c273e09f768557220d33810a9/buildSrc/src/main/kotlin/build/KotlinPluginExtensions.kt

**Comment by mkobit** [comment]
Also examples in https://github.com/gradle/kotlin-dsl/issues/343

**Comment by JLLeitschuh** [comment]
@bamboo Is there some way that we can work with the Kotlin or larger gradle team to make this API more friendly?
