### ISSUE TITLE
errors and unresolved symbols with hello-world.kts

### ISSUE THREAD

**Issue by mgroth0** [gradle/kotlin-dsl#518]
I am trying to use kotlin-dsl for the first time and getting this error.

### Expected Behavior
I am trying to run a simple build in the hello world.
### Current Behavior
I followed the instructions to clone kotlin-dsl/samples/hello-world. I tried building from the command line which results in
```
 "A problem occurred configuring root project 'hello-world'.
> Could not open cache directory" and "Unresolved reference: application"  
```
and IntelliJ which gives the same error. The IDE is also showing unresolved symbols for basically everything.
### Steps to Reproduce (for bugs)

https://github.com/gradle/kotlin-dsl/tree/master/samples#set-up-dev-environment

### Your Environment
IntelliJ 2017.2.5
Kotlin plugin 1.1.51
JDK 1.8.0_131

**Comment by bamboo** [comment]
Hi @mgroth0, 

From the error you are getting it seems you are not using the Gradle wrapper script to build the project from the command line, is that correct?

If you were not using the provided Gradle wrapper script (`./gradlew`) please try the following command `./gradlew run` in the `samples/hello-world` dir.

**Comment by appsolutegeek** [comment]
I am getting the same issue, I don't want to run gradle, i just wanted to edit the build.gradle.kts file in the latest intellij.

Intellij marks every line as being red, I didn't want to run any task at this stage so it appears I had to just run

`
./gradlew`

Now going back to intellij i could see all the kotlin types etc.

**Comment by mgroth0** [comment]
Whether I run  `gradle run` on the command line, `./gradlew run` on the command line, or I run any task from IntelliJ (on either the "use default gradle wrapper" preference or the "use gradle wrapper task configuration" preference), I always get the same error:

```
> Configure project :
e: /path/to/sample/hello-world/build.gradle.kts:5:5: Unresolved reference: application
e: Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class org.gradle.plugin.use.PluginDependenciesSpec, unresolved supertypes: Object



FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'hello-world'.
> Could not open cache directory am38i1kvrfhbsh5np2lcom49a (/Users/matt/.gradle/caches/4.2/gradle-kotlin-dsl/am38i1kvrfhbsh5np2lcom49a).
   > Internal error: unable to compile script, see log for details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org
```

There must be some step I am missing.

**Comment by mgroth0** [comment]
Just in case, heres a few other potential problems I can eliminate:

- I checked that my `hello-world/gradlew` is identical to `kotlin-dsl/samples/hello-world/gradlew`, and it is.
- I checked that  `/Users/matt/.gradle/caches/4.2/gradle-kotlin-dsl/am38i1kvrfhbsh5np2lcom49a` exsists, and it does. Inside are 2 files: 

**build.gradle.kts** full text
```kotlin


plugins {
    application
}
```

**am38i1kvrfhbsh5np2lcom49a.lock** full text (no idea what this file is)
```
~‰™ÎA®uè
```

**Comment by eskatos** [comment]
@mgroth0, the following error:
```
e: Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class org.gradle.plugin.use.PluginDependenciesSpec, unresolved supertypes: Object
```
Is expected if you run Gradle 4.2, or the `master` branch of the Gradle Kotlin DSL, on Java 9. This will be fixed in Gradle Kotlin DSL 0.12 that will ship with Gradle 4.3. See https://github.com/gradle/kotlin-dsl/pull/493

You can also test with the latest Gradle Kotlin DSL distribution snapshot by updating your Gradle wrapper in the following manner:

    ./gradlew --gradle-distribution-url https://repo.gradle.org/gradle/dist-snapshots/gradle-kotlin-dsl-4.3-20171004164220+0000-all.zip

Or by trying to run the samples from the `develop` branch of the `kotlin-dsl` repository.

BUT, your original report states that you are using JDK 1.8. Could you confirm?

@appsolutegeek, could you also report which Java version you were using?

**Comment by mgroth0** [comment]
@eskatos I can't be sure if I am running 1.8 or 9. I was originally on 9, but I _think_ I switched everything back to 1.8 so I can run this. I reset my JAVA_HOME env variable, changed project sdk and gradle settings in IntelliJ, and made sure any settings in my buildscript also were set up for 1.8. 

Does anyone know of a definitive way to see which java version is running the buildscript, like a runtime log or debug output?

After I can be sure about my java version I'll test the distribution snapshot/`develop` branch.

**Comment by eskatos** [comment]
@mgroth0 `./gradlew --version` will show the used java version

**Comment by JLLeitschuh** [comment]
Also, you can always switch really easily between JDK versions using this command:
```bash
JAVA_HOME=`/usr/libexec/java_home -v 1.8`
```
Or if you are using [Fish](https://fishshell.com/)
```
setenv -gx JAVA_HOME (/usr/libexec/java_home -v 1.8)
```

**Comment by crispinb** [comment]
I get the same as @appsolutegeek -- all symbols in build.gradle.kts are flagged with 'unresolved reference' errors.  hello-world builds and runs fine using gradlew, but the IDE is of less use than it is with groovy build scripts.

**Comment by crispinb** [comment]
OK having now scrutinised the entire README as logic might have dictated I do first, I see:
> Note: The very first time you do, IDEA might fail to recognise the classpath of the script, if that happens, simply restart IDEA. This is a known issue that will be fixed soon.

That indeed fixed the issue for me.

**Comment by eskatos** [comment]
Glad you found this @crispinb!

No answer from the op in almost 3 weeks, closing.

**Comment by mgroth0** [comment]
I'm very sorry for taking so long to respond. In the end, the problem for me was the same as for @crispinb . Restarting idea fixed it.

**Comment by hendrauzia** [comment]
FYI, the issue still exists as of this comment is written. People that faces this problem should just restart IDEA as @crispinb said and wait for a few moment. Yes, you have to wait just a few moment, because it doesn't recognise the script immediately, but it will eventually recognises the script.

**Comment by YoshiRulz** [comment]
This is *still* present in IDEA Ultimate 2019.1.3. Is there an issue on YouTrack?
