### ISSUE TITLE
Kotlin versions conflict 

### ISSUE THREAD

**Issue by ming13** [gradle/kotlin-dsl#519]
When updating to Kotlin `1.2-M1` → `1.2.0-beta-31` Kotlin DSL stops compiling. This can be reproduced this way.

1. Configure a Kotlin project (we have Android one, but use plain `kotlin` in one of the modules) using the `1.2-M1`. We have something like this in this module.

    ```kotlin
    apply {
        plugin("kotlin")

        from(rootProject.file("gradle/versions.gradle.kts"))
    }

    val libraries: Map<String, String> by extra

    dependencies {
        compile(libraries["kotlin-stdlib"]!!)
        compile(libraries["kotlin-reflect"]!!)
        compile(libraries["rx-java"]!!)
    }
    ```

2. `rm -rf ~/.gradle/caches`
3. Change Kotlin version to `1.2.0-beta-31`.
4. `./gradlew clean`

There is a Gradle output using the `--info`.

```
Evaluating project ':redacted-module' using build file '/home/artur_dryomov/mainframer/redacted-project/redacted-module/build.gradle.kts'.
w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    /home/artur_dryomov/.gradle/wrapper/dists/gradle-4.2-bin/cl9xe1l8k8ophj72k8rv6xbu7/gradle-4.2/lib/kotlin-reflect-1.1.4-3.jar (version 1.1)
    /home/artur_dryomov/.gradle/wrapper/dists/gradle-4.2-bin/cl9xe1l8k8ophj72k8rv6xbu7/gradle-4.2/lib/kotlin-stdlib-1.1.4-3.jar (version 1.1)
    /home/artur_dryomov/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.2.0-beta-31/aaf06727bfa71cc521be671d2642ffd75f32e8aa/kotlin-stdlib-1.2.0-beta-31.jar (version 1.2)
w: Consider providing an explicit dependency on kotlin-reflect 1.2 to prevent strange errors
w: Some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath or use '-Xskip-runtime-version-check' to suppress this warning
w: Some JAR files in the classpath have the Kotlin Runtime library bundled into them. This may cause difficult to debug problems if there's a different version of the Kotlin Runtime library in the classpath. Consider removing these libraries from the classpath or use '-Xskip-runtime-version-check' to suppress this warning
w: /home/artur_dryomov/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-compiler-embeddable/1.2.0-beta-31/40987e5fc92fdb841dd5ba3a6ee1b5245889120b/kotlin-compiler-embeddable-1.2.0-beta-31.jar: Library has Kotlin runtime bundled into it
w: /home/artur_dryomov/.gradle/wrapper/dists/gradle-4.2-bin/cl9xe1l8k8ophj72k8rv6xbu7/gradle-4.2/lib/kotlin-compiler-embeddable-1.1.4-3.jar: Library has Kotlin runtime bundled into it
e: /home/artur_dryomov/.gradle/caches/4.2/gradle-kotlin-dsl-accessors/ek4n6pm7alqo6ke3kdrhsyfuy/src/org/gradle/kotlin/dsl/accessors.kt:44:55: Class 'org.jetbrains.kotlin.gradle.dsl.KotlinProjectExtension' is compiled by a pre-release version of Kotlin and cannot be loaded by this version of the compiler
e: /home/artur_dryomov/.gradle/caches/4.2/gradle-kotlin-dsl-accessors/ek4n6pm7alqo6ke3kdrhsyfuy/src/org/gradle/kotlin/dsl/accessors.kt:45:71: Class 'org.jetbrains.kotlin.gradle.dsl.KotlinProjectExtension' is compiled by a pre-release version of Kotlin and cannot be loaded by this version of the compiler
e: /home/artur_dryomov/.gradle/caches/4.2/gradle-kotlin-dsl-accessors/ek4n6pm7alqo6ke3kdrhsyfuy/src/org/gradle/kotlin/dsl/accessors.kt:50:65: Class 'org.jetbrains.kotlin.gradle.dsl.KotlinProjectExtension' is compiled by a pre-release version of Kotlin and cannot be loaded by this version of the compiler
e: /home/artur_dryomov/.gradle/caches/4.2/gradle-kotlin-dsl-accessors/ek4n6pm7alqo6ke3kdrhsyfuy/src/org/gradle/kotlin/dsl/accessors.kt:56:56: Class 'org.jetbrains.kotlin.gradle.plugin.KaptExtension' is compiled by a pre-release version of Kotlin and cannot be loaded by this version of the compiler
e: /home/artur_dryomov/.gradle/caches/4.2/gradle-kotlin-dsl-accessors/ek4n6pm7alqo6ke3kdrhsyfuy/src/org/gradle/kotlin/dsl/accessors.kt:57:72: Class 'org.jetbrains.kotlin.gradle.plugin.KaptExtension' is compiled by a pre-release version of Kotlin and cannot be loaded by this version of the compiler
e: /home/artur_dryomov/.gradle/caches/4.2/gradle-kotlin-dsl-accessors/ek4n6pm7alqo6ke3kdrhsyfuy/src/org/gradle/kotlin/dsl/accessors.kt:62:66: Class 'org.jetbrains.kotlin.gradle.plugin.KaptExtension' is compiled by a pre-release version of Kotlin and cannot be loaded by this version of the compiler
e: Incompatible classes were found in dependencies. Remove them from the classpath or use '-Xskip-metadata-version-check' to suppress errors

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':redacted-project'.
> Could not resolve all dependencies for configuration ':redacted-project:_debugApk'.
   > A problem occurred configuring project ':redacted-module'.
      > Could not open cache directory ek4n6pm7alqo6ke3kdrhsyfuy (/home/artur_dryomov/.gradle/caches/4.2/gradle-kotlin-dsl-accessors/ek4n6pm7alqo6ke3kdrhsyfuy).
         > Failed to compile accessors.
           
               projectSchema: ProjectSchema(extensions={ext=org.gradle.api.plugins.ExtraPropertiesExtension, kotlin=org.jetbrains.kotlin.gradle.dsl.KotlinProjectExtension, kapt=org.jetbrains.kotlin.gradle.plugin.KaptExtension, defaultArtifacts=org.gradle.api.internal.plugins.DefaultArtifactPublicationSet, reporting=org.gradle.api.reporting.ReportingExtension}, conventions={base=org.gradle.api.plugins.BasePluginConvention, java=org.gradle.api.plugins.JavaPluginConvention}, configurations=[apiElements, archives, compile, compileClasspath, compileOnly, default, implementation, kapt, kaptTest, runtime, runtimeClasspath, runtimeElements, runtimeOnly, testCompile, testCompileClasspath, testCompileOnly, testImplementation, testRuntime, testRuntimeClasspath, testRuntimeOnly])
```

**Comment by ming13** [comment]
Actually I thought that Gradle uses an embedded Kotlin compiler, which is completely isolated from the project compiler. Is that not true?

**Comment by JLLeitschuh** [comment]
It should be true, yes. Shot in the dark, perhaps it's because you haven't also updated the version of the gradle kotlin plugin as well?
More specifically, you are adding a dependency on kotlin libraries built with the `1.2.0-beta-31` compiler but you are using the version of the compiler that
```kotlin
apply {
    plugin("kotlin")
}
```
downloads for you.

Might not be the case. But something you may want to check into.

**Comment by ming13** [comment]
Nope, the same version everywhere. You can see the version on top of the Gradle output actually with the message about different JAR files. That felt especially strange to me.

**Comment by bamboo** [comment]
Hi @ming13, 

> Actually I thought that Gradle uses an embedded Kotlin compiler, which is completely isolated from the project compiler. Is that not true?

The compiler is isolated but the Kotlin standard library is not which means only plugins and libraries compatible with the embedded Kotlin standard library version are supported and it seems Kotlin `1.2.0-beta-31` requires a newer one.

**Comment by ming13** [comment]
Hey @bamboo, thank you for your quick response!

That’s unfortunate :-( Is it possible to change it somehow, maybe from the Gradle side?

Please correct me if I’m wrong.

* Kotlin plugin `1.2.0-beta-31` provides Kotlin 1.2 and kind of uses it.
* Gradle Kotlin DSL from Gradle 4.2 provides Kotlin 1.1 and uses it.

Both of them use `stdlib` and `reflect` with different versions, i. e. 1.1 and 1.2. That’s why the error happens — basically it is a dependency clash.

Is it reasonable to execute each plugin in its own “sandbox” or something like that? I guess it will require multiple JVM processes to do that though, just to avoid the clash.

**Comment by JLLeitschuh** [comment]
It would probably require classloader goofiness, not quite separate processes. (I could be completely wrong here though).

**Comment by ming13** [comment]
I’m a bit worried about the development cadence. For example, we want to use some alpha or beta version of the language and use Gradle Kotlin DSL at the same time. It becomes kind of impossible in some cases like that when both of them should use the same language version under the hood.

**Comment by ming13** [comment]
@bamboo @eskatos Sorry for pinging you guys, but I’m still a bit confused about the situation I’ve described above when project Kotlin version differs from the Gradle’s one.

Actually I’ve found [a test regarding different (but compatible) versions](https://github.com/gradle/kotlin-dsl/blob/master/provider/src/test/kotlin/org/gradle/kotlin/dsl/integration/GradleKotlinDslIntegrationTest.kt#L154-L194), but not about not compatible ones. I’ve also tried to configure `embeddedKotlinVersion` for `GenerateKotlinDependencyExtensions` task, but seems like the task is not accessible.

It is possible to clarify the Kotlin version policies somewhere? Maybe in `/docs`?

Please correct me if I’m wrong.

* Gradle ships with Kotlin DSL support which uses embedded Kotlin compiler, plus fixed Kotlin `stdlib` and `reflect` dependencies. For example, Gradle 4.2 ships with Kotlin `1.1.4-3`, as well as `stdlib` and `reflect` with the same version.
* When the project uses Gradle Kotlin DSL and Kotlin `some-stable-version` everything should be fine. I. e. using Gradle 4.2 and Kotlin `1.1.50` or `1.1.3` or `1.0.0` or `1.2` is totally valid.
* When the project uses Gradle Kotlin DSL and Kotlin `some-beta-or-milestone-version` it is actually not quite possible, because stable (shipped with Gradle as part of DSL) and not stable (project one) Kotlin versions are not compatible. _That’s a huge bummer if that’s true._

**Comment by bamboo** [comment]
Hey @ming13,

Thanks for the opportunity to clarify some of these matters.

> * Gradle ships with Kotlin DSL support which uses embedded Kotlin compiler, plus fixed Kotlin stdlib and reflect dependencies. For example, Gradle 4.2 ships with Kotlin 1.1.4-3, as well as stdlib and reflect with the same version.

Correct. And the `kotlin` package from those modules is visible through the Gradle classpath.

> * When the project uses Gradle Kotlin DSL and Kotlin some-stable-version everything should be fine. I. e. using Gradle 4.2 and Kotlin 1.1.50 or 1.1.3 or 1.0.0 or 1.2 is totally valid.

> * When the project uses Gradle Kotlin DSL and Kotlin some-beta-or-milestone-version it is actually not quite possible, because stable (shipped with Gradle as part of DSL) and not stable (project one) Kotlin versions are not compatible. That’s a huge bummer if that’s true.

Some of those combinations will be compatible, some will not. The guarantees are those provided by Kotlin and documented [here](https://kotlinlang.org/docs/reference/compatibility.html).

The biggest issue is the compatibility between the external `kotlin-gradle-plugin` version and the `kotlin-stdlib` version shipped with Gradle or, more generally, between any plugin that transitively depends on `kotlin-stdlib` and its version shipped with Gradle. As long as the combination is compatible everything should work and the tendency is for this to become less of an issue overtime as the language matures.

And as for backward compatibility I'd like to finish by quoting the answer given by my colleague Stefan Oehme to a similar question recently:

> ... the issue is basically the same as we face with Groovy. Our approach is to only do backwards-breaking Groovy (or Kotlin) upgrades on a major Gradle release. We will always clearly document which Kotlin version we ship and announce upgrade plans before a major release. 
> Plugin authors who want to stay compatible with older versions need to limit their API usage to a subset that is compatible with these old versions. It’s not really different from any other new API in Gradle. E.g. if we introduce a new API for dependency resolution and a plugin wants to use that API, then they either need to drop support for older Gradle versions or they need to do some clever organization of their code to only execute the new code path on newer versions. Does that answer your question?

Does it?

**Comment by ming13** [comment]
@bamboo, thanks for the clarification!

Does it make sense to explore following areas?

* Use sandboxed classpath for Gradle plugins to avoid classpath issues.
* Ability to override `embeddedKotlinVersion` for Gradle Kotlin DSL to use.

Not really sure both of them are technically possible, but if it can be done, it would be great.

**Comment by sdeleuze** [comment]
I am working on my upcoming demos at Kotlinconf and Devoxx, and sadly this bug may prevent me to use Gradle Kotlin DSL since I would like to show backend + frontend leveraging Kotlin 1.2 multi-plaform capabilities + build in Kotlin. Any workaround before appreciated.

**Comment by sdeleuze** [comment]
Curiously, it seems to work again with [Kotlin beta 2](https://blog.jetbrains.com/kotlin/2017/10/kotlin-1-2-beta2-is-out/) (with Gradle `4.3-rc-1`).

**Comment by bamboo** [comment]
Thanks, @sdeleuze, that's good to hear. We're going to be checking compatibility with 1.2 on a more regular basis.

**Comment by bamboo** [comment]
Closing as answered. We'll be introducing a 1.2 branch for testing soon.

**Comment by Takhion** [comment]
I'm having a similar issue, when just by having a `buildSrc` the Kotlin DSL (v0.18.4 from Gradle 4.9) adds Kotlin 1.2.41 to the classpath, while everything else uses Kotlin 1.2.51! The code compiles, but the IDE warns about multiple runtimes and there's a few glitches resulting from it 😞.

I think what @ming13 suggested is a really good idea:
>Ability to override embeddedKotlinVersion for Gradle Kotlin DSL to use.

**Comment by ming13** [comment]
> Ability to override embeddedKotlinVersion for Gradle Kotlin DSL to use.

I think it would not work since it would basically mean swapping Kotlin runtime for the DSL which is an open window to essentially breaking it since there is no guarantee that the DSL will be compatible.

The proper way, as I see it, is isolating Gradle and project classpaths preventing such conflicts but it is so tricky I’m not sure it is even possible.

**Comment by Takhion** [comment]
@ming13 what about using a specific classloader for Gradle? Or, since in this case I'm reasonably sure that using Kotlin 1.2.51 would work with the current version of the DSL, if it was flagged as a "use at your own risk" option, I would definitely use it! :D

**Comment by oehme** [comment]
There is no way to use two different versions of Kotlin for Gradle and a plugin, because the plugin needs to be able to call Gradle's DSL (which includes the Kotlin library) and so the classes need to be the same.

**Comment by Takhion** [comment]
Then even more so: the only option would be to have an override for the version! Pleeeease :pray:

**Comment by oehme** [comment]
We have no plans to do that. It would be a costly change and would provide no guarantee of actually working.

**Comment by ming13** [comment]
@oehme, thanks for the clarification. What do you think about using Jar Jar before build scripts execution and change the Kotlin `stdlib` package? I think it would solve conflicts between Gradle Kotlin and Gradle plugin Kotlin versions. But I might not be thinking straight, sorry.

**Comment by MRezaNasirloo** [comment]
I'm using the `kotlin-dsl` for buildSrc modules which the latest kotlin version which has bundled with it is 1.2.41 and the latest android plugin only allows version 1.2.50 and higher
```
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.2.50 and higher. Project 'buildSrc' is using version 1.2.41.
```

**Comment by oehme** [comment]
Applying the Android plugin to `buildSrc` makes no sense.

**Comment by MRezaNasirloo** [comment]
@oehme I haven't applied it to `buildSrc`, if anything has it applied, it is Android Studio.

**Comment by oehme** [comment]
In that case please report a bug to the Android team.
