### ISSUE TITLE
TAPI model builders should support settings script and provide classpath to IDEs

### ISSUE THREAD

**Issue by eskatos** [gradle/kotlin-dsl#529]
This is a follow up to #528

The `KotlinBuildScriptModelBuilder` should provide a proper classpath model to TAPI clients, mostly IDEs, for `settings.gradle.kts` edition.

Currently it would treat such files as simple script plugins, that is `rootProject scope` + `kotlin-dsl` classpath. Meaning it potentially includes spurious dependencies from `rootProject` build script dependencies and lacks dependencies from Settings build script dependencies.

**Comment by eskatos** [comment]
First step as upstream PR https://github.com/gradle/gradle/pull/3172

**Comment by eskatos** [comment]
Second step as upstream PR https://github.com/gradle/gradle/pull/3233

**Comment by eskatos** [comment]
Last step PR #561

**Comment by JLLeitschuh** [comment]
TAPI?

**Comment by eskatos** [comment]
@JLLeitschuh The Kotlin DSL provides IDEs with build script dependencies to setup editors properly (classpath, sources, implicit imports etc...). Kotlin script templates provide a dependencies resolver that queries the build using the Tooling API, TAPI for short, see https://docs.gradle.org/current/userguide/embedding.html

**Comment by eskatos** [comment]
Closing as delivered in 2add1ab
