### ISSUE TITLE
Consider removing all Groovy Closure-accepting methods in Gradle proper

### ISSUE THREAD

**Issue by bamboo** [gradle/kotlin-dsl#53]
The benefit to users is less information overload when asking for code completion, reading the docs, etc.

**Comment by adammurdoch** [comment]
and replace with `Action` overloads (or whatever pattern works well for kotlin and for which we can mix-in the closure overload for Groovy).

**Comment by eskatos** [comment]
Closing in favor of upstream https://github.com/gradle/gradle/issues/4075
