### ISSUE TITLE
IntelliJ Kotlin support should handle Settings scripts 

### ISSUE THREAD

**Issue by eskatos** [gradle/kotlin-dsl#531]
#528 introduces a Kotlin script template provider for settings files.
This issue is about making IntelliJ aware of it and use it for `settings.gradle.kts` files.

See:
- [JetBrains/kotlin/idea/src/META-INF/gradle.xml](https://github.com/JetBrains/kotlin/blob/8e72a1211b79ade007042493c920f326d2c56a04/idea/src/META-INF/gradle.xml#L57-L58)
- [JetBrains/kotlin/idea/idea-gradle/src/org/jetbrains/kotlin/idea/core/script/GradleScriptTemplateProvider.kt](https://github.com/JetBrains/kotlin/blob/e3963fccf4d6db63a881cf2e5d60471df76b8ed7/idea/idea-gradle/src/org/jetbrains/kotlin/idea/core/script/GradleScriptTemplateProvider.kt#L91-L102)

**Comment by eskatos** [comment]
Upstream PR https://github.com/JetBrains/kotlin/pull/1339

**Comment by bamboo** [comment]
Depends on #551.

**Comment by eskatos** [comment]
Tested with Kotlin IntelliJ Plugin `1.1.60-eap-43` ✅

**Comment by eskatos** [comment]
Confirmed it works with Kotlin IntelliJ Plugin 1.1.60 ✅ 

Closing
