### ISSUE TITLE
Support concise and statically-typed configuration patterns

### ISSUE THREAD

**Issue by bamboo** [gradle/kotlin-dsl#54]

**Comment by oehme** [comment]
Do we know why this is not the default in Kotlin? Why is the single argument to the lambda not automatically the implicit receiver? That would make so many Java APIs easier to use with Kotlin without writing a bunch of overloads.

**Comment by melix** [comment]
This is an interesting discussion. I had the same issue when implementing the static Groovy DSL. Groovy does the same as Kotlin here: by default, you have to write `it.copy`. However, I'm generating extension methods (at build time) that create an overloaded `Closure` parameter and set the delegate appropriately. It works as a charm.

So either:
  * Kotlin needs to support the same pattern, and allow the extension method to be picked up first
  * Kotlin needs to allow the receiver to be the "delegate" implicitly

We have so many methods taking `Action<...>` which is both Java and Groovy friendly that it would be a pity to have to introduce a new one for Kotlin, especially if the methods have to be named differently.

**Comment by cbeams** [comment]
I've just updated the description with a section containing tasks that should be mapped to cards once we begin working on this epic. Namely, @bamboo had the idea of having Kotlin's `lazy`

**Comment by cbeams** [comment]
I've just updated the description with a section containing tasks that should be mapped to cards once we begin working on this epic. Namely, @bamboo had the idea of having Kotlin's `lazy` implement `Callable` so that deferred configuration can happen in Kotlin-friendly way, e.g.:

```kt
some.configuration(lazy {
    // expensive logic
})
```

**Comment by pioterj** [comment]
This is done, right?

**Comment by bamboo** [comment]
@pioterj, #47 and #53 are still open.

**Comment by pioterj** [comment]
Sorry, I missed that.
