### ISSUE TITLE
subprojects { subproject -> not working in build.gradle.kts

### ISSUE THREAD

**Issue by xmlking** [gradle/kotlin-dsl#546]
Not able to use following code in `build.gradle.kts`
```kotlin
subprojects { subproject ->

    if (subproject.name.startsWith("hello")) {
    apply plugin: 'org.gradle.sample.hello'
    }
    if (subproject.name.startsWith("goodbye")) {
        apply plugin: 'org.gradle.sample.goodbye'
    }
}
```

**Comment by mkobit** [comment]
`apply plugin: 'org.gradle.sample.hello'` is not valid Kotlin

**Comment by xmlking** [comment]
Following code also fail in build.gradle.kts but works in build.gradle 

```
subprojects { subproject ->
}
```

**Comment by mkobit** [comment]
https://docs.gradle.org/current/javadoc/org/gradle/api/Project.html#subprojects(org.gradle.api.Action)

Methods taking an `Action` are automatically turned into receivers by the SAM compiler plugin so you can not specify the parameter name.

This might be a more general issue with the SAM plugin but you can do this for now until a more concrete answer is given by somebody else:

```kotlin
subprojects {
  // The subproject is the receiver of the body
  dependences {
  }
}
```

**Comment by JLLeitschuh** [comment]
Simple workaround too if you really need it in a variable called `subproject`

```kotlin
subprojects { 
    val subproject = this
    // do whatever with the variable
}
```

**Comment by eskatos** [comment]
@xmlking, what @mkobit and @JLLeitschuh said is correct!

Here is your initial snippet converted to the Kotlin DSL:

```kotlin
subprojects {
    if (name.startsWith("hello")) {
        apply { plugin("org.gradle.sample.hello") }
    }
    if (name.startsWith("goodbye")) {
        apply { plugin("org.gradle.sample.goodbye") }
    }
}
```

I'm going to close this issue, feel free to comment further if things aren't clear.
