### ISSUE TITLE
Cannot use FQCN of java.* classes when 'java' plugin is applied in Kotlin DSL scripts

### ISSUE THREAD

**Issue by mkobit** [gradle/kotlin-dsl#548]
You can't refer to classes by their FQCN if the package namespace starts with an extension.
This holds for any top level class that has an extension with the same name.

I expect most collisions to occur with `java` and `kotlin` due to the standard libraries in both having collisions with the extension names in both plugins.

### Expected Behavior

I don't know what the expected behavior should be here.

### Current Behavior

* Requires an `import` of the class 

### Context

Auto-import in `build.gradle.kts` uses the FQCN so typing `ByteArrayOu`, hitting *CTRL* + *SPACE* and then selecting the class causes the FQCN to be used at the call site rather than being `import` for the script. It makes it cumbersome to use non-automatically imported JDK classes in the build script.

The same issue is also true when using `kotlin.*` types.

Here is an example of the IntelliJ behavior:

![Kotlin DSL autocomplete uses FQCN on import rather than ](https://user-images.githubusercontent.com/1447148/31625452-bf5f01f6-b26b-11e7-8968-43b597425e04.gif)

### Steps to Reproduce (for bugs)

```kotlin
import java.io.StringWriter

plugins {
  `java`
}

tasks {
  "wrapper"(Wrapper::class) {
    gradleVersion = "4.3-rc-1"
  }
}

// 👍
val typed: java.lang.Process? = null
// 👍 - from import
val imported: java.io.StringWriter = StringWriter()
// 👎 - Unresolved reference
val instantiateFQCN: java.io.ByteArrayOutputStream = java.io.ByteArrayOutputStream()
```

### Your Environment

* Gradle 4.3-rc-1 (and 4.2.*)

IntelliJ IDEA 2017.2.5
Build #IU-172.4343.14, built on September 26, 2017
Licensed to Mike Kobit
JRE: 1.8.0_152-release-915-b12 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.10.0-37-generic

**Comment by JLLeitschuh** [comment]
@mkobit and I were chatting with @ligee about this on slack last week.

This is probably a bug in the compiler. However, according to @ligee there really isn't an immediately apparent  simple solution to fix this one.

**Comment by eskatos** [comment]
Confirmed the problem still exists using Gradle 5.4:

```
FAILURE: Build failed with an exception.

* Where:
Build file '/path/to/some/gradle-build/build.gradle.kts' line: 11

* What went wrong:
Script compilation error:

  Line 11: val instantiateFQCN: java.io.ByteArrayOutputStream = java.io.ByteArrayOutputStream()
                                                                     ^ Unresolved reference: io

1 error
```

In IJ 2019.1 and its Kotlin plugin 1.3.30:

![image.png](https://images.zenhubusercontent.com/56fbbbe56caf56c9d38eef4c/5e66c7eb-d27c-4a0e-85ef-84812ed00368)

**Comment by bamboo** [comment]
I think that behaviour is expected. `java` in expression position within the script body is a reference to  the `java` project extension contributed by the `java` plugin.

The solution is to import `java.io.ByteArrayOutputStream` explicitly (until Kotlin provides a way to reference names starting from the global scope like C#'s `global::...` construct).

**Comment by JLLeitschuh** [comment]
@mkobit Do you want to open an official issue against the Kotlin compiler?

**Comment by mkobit** [comment]
@JLLeitschuh I wasn't planning on it, as I don't have a solid suggestion for the expected behavior. `java` is probably the most likely collision, but this could easily happen with other domain objects.
