### ISSUE TITLE
Update all samples to use settings.gradle.kts

### ISSUE THREAD

**Issue by eskatos** [gradle/kotlin-dsl#550]

**Comment by JLLeitschuh** [comment]
Do you want to wait until the kotlin plugin to be released as stable?

**Comment by eskatos** [comment]
Not necessarily, the Kotlin plugin update is about IntelliJ editing support only and we want to move forward with the samples on our `develop` branch.

Without Kotlin IntelliJ plugin 1.1.60 you can still edit the `settings.gradle.kts` files but they are "all red" because their base class and classpath are wrong (same as a `Project` script plugin).

And 1.1.60 is just around the corner anyway.

**Comment by eskatos** [comment]
Moreover, this will exercise the support for `settings.gradle.kts` earlier as we integration test all samples. In practice this may be done in several incremental steps following progress on #56.

**Comment by JLLeitschuh** [comment]
Sounds good. Given that master will keep the samples that use `settings.gradle` this makes sense.

**Comment by eskatos** [comment]
Closing as delivered in #555, #570, #571 and #572
