### ISSUE TITLE
Introduce CI job to check compatibility against Kotlin 1.2

### ISSUE THREAD

**Issue by bamboo** [gradle/kotlin-dsl#556]

**Comment by eskatos** [comment]
Step commits to upgrade to Kotlin 1.2 in `eskatos/kotlin/1.2` branch.

CI coverage: [TC](https://builds.gradle.org/project.html?projectId=GradleKotlinDSL&tab=projectOverview&branch_GradleKotlinDSL=kotlin%2F1.2), [Travis](https://travis-ci.org/gradle/kotlin-dsl/branches)
