### ISSUE TITLE
Ship `kotlin-stdlib-jre8`

### ISSUE THREAD

**Issue by bamboo** [gradle/kotlin-dsl#558]
It seems it should be safe to ship it as long as we don't directly use it but only expose the library to build scripts:

> There are now separate versions of the standard library supporting the new JDK APIs added in Java 7 and 8. If you need access to the new APIs, use kotlin-stdlib-jre7 and kotlin-stdlib-jre8 maven artifacts instead of the standard kotlin-stdlib. These artifacts are tiny extensions on top of kotlin-stdlib and they bring it to your project as a transitive dependency.
https://kotlinlang.org/docs/reference/whatsnew11.html#java-8-standard-library-support

**Comment by ilya-g** [comment]
Note that in Kotlin 1.2 these extension artifacts will be deprecated, so you might want to replace them with `-jdk7` and `-jdk8` versions then.

**Comment by bamboo** [comment]
Thanks for the heads-up, @ilya-g.
