### ISSUE TITLE
Multi Project Test Dependencies

### ISSUE THREAD

**Issue by NikolayMetchev** [gradle/kotlin-dsl#577]
I am trying to do in kotlin-dsl what is described here in groovy:
https://stackoverflow.com/questions/5644011/multi-project-test-dependencies-with-gradle
```
dependencies {
  ...
  testCompile project(':A').sourceSets.test.output
}
```

Is it possible in kotlin-dsl?

Many thanks

**Comment by JLLeitschuh** [comment]
That same code in the kotlin DSL would be something like this:
```
dependencies {
  ...
  testCompile(project(":A").java.sourceSets.test.output)
}
```

That being said, I think if you use the `java-library` plugin you automatically get the test source sets added when you add a dependency on the project (don't quote me).

Another better way to do this is to create a `configuration` that publishes the `test` class outputs as an artifact from the project.

Then you could depend upon it by doing something like this `project(":A", "test")`.

**Comment by NikolayMetchev** [comment]
Thanks. That works

**Comment by NetanelRabinowitz** [comment]
Having the same problem with the latest version. `.java` does not exist on the projectDependency object. any other workarounds?  @JLLeitschuh  suggest creating a configuration that publishes the test class outputs as an artifact from the project. are there any examples somewhere?

**Comment by JLLeitschuh** [comment]
The solution that I go with primarily is to create a separate project. For example, if my sub-project is called "core" then I make a second sub-project called "coreTestUtils" where I put the test utilities that I want to share with other projects.

This is by far the cleanest solution I have figured out so far.

**Comment by NetanelRabinowitz** [comment]
@JLLeitschuh Thanks! I found [this jartest plugin](https://github.com/hauner/gradle-plugins/tree/master/jartest)  which seems to work fine so far.
Any thoughts on this plugin?

**Comment by JLLeitschuh** [comment]
I don't really have any thoughts on it. If it works, awesome. Both seem to achieve the same goal.

**Comment by xbao** [comment]
For another option, I translated the jartest plugin logic to a kts snippet:
```
configurations.register(
    "testArchive"
) {
    extendsFrom(configurations.testCompile.get())
}
tasks.register<Jar>(
    name = "jarTest"
) {
    from(project.sourceSets.test.get().output)
    description = "create a jar from the test source set"
    archiveClassifier.set("test")
}

artifacts {
    add("testArchive", tasks.getByName("jarTest"))
}
```
with the other module depending on it like:
```
dependencies { testImplementation(project(":mysubproject", "testArchive")) }
```

Seems to work okay
