### ISSUE TITLE
Copy into multiple destDir

### ISSUE THREAD

**Issue by fanliming** [gradle/kotlin-dsl#578]
https://github.com/gradle/kotlin-dsl/blob/f5d09f7d0aa227f4cf6942ce89dab318020ef391/samples/copy/build.gradle.kts#L25

How can I copy into different multiple dest dir?

Thanks

**Comment by fanliming** [comment]
the source is same.
and Now I write two task to do this.
Is there a better way do this?

**Comment by eskatos** [comment]
Hi @fanliming,

You can use nested `CopySpec`s.
See the Gradle user guide section on working with files: https://docs.gradle.org/current/userguide/working_with_files.html#sec:using_the_copyspec_class

Here's an example using the Gradle Kotlin DSL:

```kotlin
tasks {
  "myCopyTask"(Copy::class) {
    from("source-1") {
      into("dest-1")
    }
    from("source-2") {
      into("dest-2")
    }
  }
}
```

**Comment by fanliming** [comment]
@eskatos Thanks!

actually I want this:  

```
tasks {
  "myCopyTask"(Copy::class) {
    from("source-1") {
      into("dest-1")
      into("dest-2")
    }
  }
}
```  
now it's like this:
```
tasks {
  "myCopyTask"(Copy::class) {
    from("source-1") {
      into("dest-1")
    }
    from("source-1") {
      into("dest-2")
    }
  }
}
```

**Comment by eskatos** [comment]
I see. Then you can do something along the lines of:

```kotlin
tasks {
  "myCopyTask"(Copy::class) {
    val sourceSpec = copySpec {
      from("source-1")
    }
    listOf("dest-1", "dest-2").forEach { dest ->
      into(dest) {
        with(sourceSpec)
      }
    }
  }
}
```

Such general questions are best asked on the Gradle forums at https://discuss.gradle.org/, you'll reach a wider audience there.
