### ISSUE TITLE
Editing Gradle Kotlin DSL build scripts in Android Studio 3 is broken

### ISSUE THREAD

**Issue by eskatos** [gradle/kotlin-dsl#584]
![android-studio-2-gradle-kotlin-dsl](https://user-images.githubusercontent.com/132773/32322540-22f15b72-bfc5-11e7-9dcd-402bb682ac19.png)

To reproduce, simply open the `hello-android` sample in Android Studio 3

See upstream issue: https://issuetracker.google.com/issues/68793090

**Comment by jaredsburrows** [comment]
Any update on this?

**Comment by jaredsburrows** [comment]
I am seeing the same thing in Intellij 2017.2.6.

**Comment by MonteCreasor** [comment]
I have the same problem in AndroidStudio 3.0 (android gradle version 3.0.0 and Kotlin 1.1.60).

**Comment by eskatos** [comment]
See the upstream issue at https://issuetracker.google.com/issues/68793090
Please up-vote there too!

**Comment by jaredsburrows** [comment]
@eskatos Done! Is there are way for Gradle developers to have direct contact with the Google AGP developers? This could help to better triage bugs.

**Comment by eskatos** [comment]
@jaredsburrows we do, this bug is already triaged, assigned and qualifed as P1

**Comment by Dkhusainov** [comment]
Any update on this? Android Studio build file editor is still broken.

Studio 3.0.1
revision a93da8024f8d83cf660c2e4b39256bf5cf32dc57


![error](https://user-images.githubusercontent.com/7382654/34265049-dfe2d8be-e685-11e7-827b-32d176bb550e.jpg)

**Comment by eskatos** [comment]
Just tried to reproduce with:

```
Android Studio 3.1.3
Build #AI-173.4819257, built on June 4, 2018
JRE: 1.8.0_152-release-1024-b01 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.4
```
and

```
Android Studio Kotlin Plugin 1.2.60-eap-44
```

Works for me!

![image](https://user-images.githubusercontent.com/132773/42932952-e9849dd6-8b43-11e8-9292-82752ace3ac9.png)
