### ISSUE TITLE
Fix FAQ section on roadmap

### ISSUE THREAD

**Issue by hansd** [gradle/kotlin-dsl#587]
It says that 1.0-M1 is out and mentions Gradle 3.0: https://github.com/gradle/kotlin-dsl/wiki/Frequently-Asked-Questions#whats-the-overall-roadmap

**Comment by bamboo** [comment]
Thanks, Hans. That's in reference to our [very first release](https://github.com/gradle/kotlin-dsl/releases/tag/v1.0.0-M1) originally named `1.0-M1` and later renamed to `v0.1.0`.

I've changed the answer to link directly to our ZenHub board.
