### ISSUE TITLE
Migrate `gradle/settings.gradle` and related files to Kotlin

### ISSUE THREAD

**Issue by bamboo** [gradle/kotlin-dsl#591]

**Comment by bamboo** [comment]
Putting on hold until we decide what to do about the Java 8 requirement: https://builds.gradle.org/viewLog.html?buildId=9451237&tab=buildResultsDiv&buildTypeId=Gradle_Check_Quick_Java7_Oracle_Windows_wrapper

**Comment by jaredsburrows** [comment]
I am excited for this but I cannot view the teamcity build.

**Comment by mkobit** [comment]
@jaredburrows there is a small link that says _Log in as guest_

**Comment by jaredsburrows** [comment]
@mkobit Thanks!

@bamboo Where are we targeting Java 8? I can't find via "JavaVersion" or "sourceCompatibility".

**Comment by bamboo** [comment]
@jaredsburrows The embedded Kotlin compiler requires Java 8.

**Comment by JLLeitschuh** [comment]
Is this about modifying the master project, not the `kotlin-dsl` project?

**Comment by bamboo** [comment]
@JLLeitschuh yes.

**Comment by eskatos** [comment]
Closing as delivered in https://github.com/gradle/gradle/commit/975e56a048a4aec626532205237da2339ef5934f
