### ISSUE TITLE
TeamCity Build Status on Pull Requests

### ISSUE THREAD

**Issue by JLLeitschuh** [gradle/kotlin-dsl#600]
TeamCity pass/fail results should be displayed as statuses on PR's and on commits.
This will help contributors see if things have failed TeamCity checks and that they need to update their PR's.

The configuration seems to be pretty easy to setup:
https://blog.jetbrains.com/teamcity/2016/10/teamcity-10-github-related-improvements/

**Comment by bamboo** [comment]
Thanks for the suggestion but for now we think Travis CI is good enough.
