### ISSUE TITLE
Migrate `gradle/gradle` to use a `-all` wrapper distribution

### ISSUE THREAD

**Issue by eskatos** [gradle/kotlin-dsl#602]

**Comment by eskatos** [comment]
Upstream PR https://github.com/gradle/gradle/pull/3572

**Comment by melix** [comment]
Please no. I really don't like `-all` distributions. It's way too fat, and it often leads to having to download both the fat (`-bin`) and extremely fat (`-all`) versions of Gradle, which is a non-sense. The sources should be downloadable separately, and downloaded on demand.

**Comment by bamboo** [comment]
> The sources should be downloadable separately, and downloaded on demand.
👍 
In the meantime, ~25% fat for source navigation on Gradle doesn't sound that bad.

**Comment by eskatos** [comment]
We decided not to do this, closing
