### ISSUE TITLE
Navigation to Gradle sources in IDEA should work with a `-bin` distribution

### ISSUE THREAD

**Issue by eskatos** [gradle/kotlin-dsl#604]
### Expected Behavior
Using a `-bin` Gradle distribution, I can navigate to Gradle sources from kotlin build scripts.

### Current Behavior
A `-all` Gradle distribution is required to get navigation to Gradle source from kotlin build scripts.

**Comment by wolfs** [comment]
We could publish the sources separately and then IDEA could download the sources as it does for other dependencies.

**Comment by eskatos** [comment]
It is the Kotlin DSL dependency resolver that resolves the sources and provide them to IDEA: https://github.com/gradle/kotlin-dsl/blob/2b8755669c27ec1343120445eff5818f574c74c8/provider/src/main/kotlin/org/gradle/kotlin/dsl/resolver/SourcePathProvider.kt#L52

If Gradle would publish a source jar that would be great, it could then be resolved on demand.

The support for resolving sources from a `-all` distribution if present should also be kept, it makes things much easier for Gradle & Kotlin DSL development.

**Comment by bamboo** [comment]
Closing as delivered. Thanks again, @melix!
