### ISSUE TITLE
Remove "Limitation" section from README.md

### ISSUE THREAD

**Issue by GFriedrich** [gradle/kotlin-dsl#614]
As said in the subject ...
It's not needed any longer, is it?
(Maybe leave a hint that at least Gradle 4.4 is needed?!)

By the way: Thanks for supporting settings.gradle.kts - makes the experience of Kotlin DSL so much nicer.

**Comment by gildor** [comment]
Fixed #619

**Comment by bamboo** [comment]
Closing as delivered.
