### ISSUE TITLE
Gradle should fail when the plugins {} block is used inside a sub-project configuration block

### ISSUE THREAD

**Issue by AlexCzar** [gradle/kotlin-dsl#625]
Consider following:
```
project(":child:grandchild") {
	plugins {
		id("war")
		id("org.springframework.boot")
	}
	dependencies {
		"providedRuntime"("org.springframework.boot:spring-boot-starter-tomcat")
		//...
	}
	//...
}
```

### Expected Behavior
Gradle should fail with something like `plugins {}` syntax is not supported in project("") configuration injection

### Current Behavior
Currently it will fail with `Configuration with name 'providedRuntime' not found.` Which is not very helpful.

### Context
It was very hard to find the reason for non-existent configuration when the plugins were seemingly properly applied.

### Steps to Reproduce (for bugs)
See example above. Create project and configure subproject as it is done in the example.

### Your Environment
Gradle `4.3.1`, Kotlin `1.1.61`

**Comment by Xerus2000** [comment]
I wanted to completely configure my subproject using such a block. Even after removing the plugins block it still gives me `org.gradle.api.artifacts.UnknownConfigurationException: Configuration with name 'compile' not found.` or alternatively a `java.lang.IllegalStateException: A convention named 'java' could not be found.` if I try to modify the `java.sourceSets`

Is this possible to fix? The subproject is in such a position that it would be inconvenient to put a separate build script there, nor a settings file...

**Comment by eskatos** [comment]
```kotlin
fun Project.plugins(block: PluginDependenciesSpecScope.() -> Unit): Unit =
    // throw explaining exception
```

**Comment by JLLeitschuh** [comment]
@eskatos Also, when this method is added, mark it as `@Depricated` so that users get a warning in their IDE visually that they are doing something wrong.

**Comment by eskatos** [comment]
Closing as delivered in 651248f00cd02b2ae0200b2ff1d5979e3e2de891
