### ISSUE TITLE
Allow typed Project delegated properties

### ISSUE THREAD

**Issue by AlexCzar** [gradle/kotlin-dsl#626]
currently I can do `val someValue: String by extra` and if I have a String named "someValue" my val is assigned extra["someValue"] with type String.
if I have `val someValue: String by project` it does not work, I get following error:
```
'getValue(Build_gradle, KProperty<*>)' function of property delegate is expected to return 'String', but returns 'Any?
```

**Comment by eskatos** [comment]
Closing as delivered in 4e8a53b

**Comment by Drjacky** [comment]
@AlexCzar Do you know what is difference between `by extra` and `by project` actually?

**Comment by AlexCzar** [comment]
> @AlexCzar Do you know what is difference between `by extra` and `by project` actually?
Yes, I think I do.
