### ISSUE TITLE
Task to generate configuration snippet for project model element addressed by name from the command line

### ISSUE THREAD

**Issue by bamboo** [gradle/kotlin-dsl#632]
A common question when migrating to the Kotlin DSL is how to express a given Groovy DSL snippet using the Kotlin DSL:

```groovy
fooBar {
   baz = gazonk
}
```

The answer will vary depending on what's behind the name `fooBar`. It could be a _task_, a _project property_, an _ext property_, a _convention property_ or a _project extension_. Each with its own configuration pattern.

A task could answer the question given it runs in the right build environment:

    $ ./gradlew ktsSnippet --for-name fooBar

    fooBar is a task of type my.tasks.FooBarTask, configure it using:

    tasks {
      "fooBar"<FooBarTask> {
        // configure fooBar here
      }
    }

**Comment by JLLeitschuh** [comment]
Is there a way to also get it to know that the task is added late in the lifecycle and will require something like this:
```
./gradlew ktsSnippet --for-name fooBar

fooBar is a task of type my.tasks.FooBarTask and added late in the gradle lifecycle, configure it using:

afterEvaluate {
  tasks {
    "fooBar"<FooBarTask> {
      // configure fooBar here
    }
  }
}
```

**Comment by bamboo** [comment]
Maybe better implemented as an IDE view that allows browsing the whole Gradle model and drag'n'drop into the editor to get the necessary configuration code.
