### ISSUE TITLE
Kotlin-based Gradle scripts fail to compile when using ::foo instead of this::foo

### ISSUE THREAD

**Issue by TheMrMilchmann** [gradle/kotlin-dsl#633]
Kotlin 1.2 added the possibility to use `::foo` as shorthand for `this::foo`. ([See the Kotlin 1.2 notes](https://kotlinlang.org/docs/reference/whatsnew12.html#support-for--foo-as-a-shorthand-for-thisfoo))

However, when using the shorter form Kotlin based Gradle scripts cannot be compiled.

While I expect this to be a bug in Kotlin rather than the DSL, I have not worked too much with Kotlin scripts yet to rule out the possibility and would rather have you report the issue upstream (if this is indeed external), since you probably have more knowledge of what is happening here.

### Expected Behavior

The expectation is that the following code works in Kotlin scripts.
```kotlin
fun foo(it: Any) = true

// The inline modifier is important. This does not fail when this is no inline function.
inline fun bar(f: (Any) -> Boolean) {}

bar(::foo)
```
### Current Behavior

It does not compile. (See the build scan linked below for more information.)

A possible workaround is using the "old way" of referencing a method. For example the following snippet does compile:
```kotlin
fun foo(it: Any) = true

inline fun bar(f: (Any) -> Boolean) {}

bar(this::foo)
```

### Your Environment

 * Gradle: `Gradle 4.5-20171208225052+0000`
 * Build scan URL: https://scans.gradle.com/s/nxtz3hlgpy6a2/

**Comment by TheMrMilchmann** [comment]
Looks like this was a known issue ([KT-20821](https://youtrack.jetbrains.com/issueMobile/KT-20821)) and has already been fixed in Kotlin 1.2.10.
I will leave this open for now and verify tomorrow whether or not this is now working as expected.

**Comment by bamboo** [comment]
Thanks for the report, @TheMrMilchmann!

**Comment by bamboo** [comment]
Depends on #634
