### ISSUE TITLE
Support accessing gradle properties from settings.gradle.kts

### ISSUE THREAD

**Issue by araqnid** [gradle/kotlin-dsl#635]
I want to be able to access the gradle.properties file (or -P command-line args) from inside `settings.gradle.kts` - in Groovy, they are available as dynamic properties on the Settings object, but they don't seem to be exposed via kotlin-dsl.

I was able to "support" this either by adding this to my `settings.gradle.kts` file:

```kotlin
fun Settings.property(key: String): String =
  javaClass.getMethod("getProperty", String::class.java).invoke(this, key) as String
fun Settings.hasProperty(key: String): Boolean =
  javaClass.getMethod("hasProperty", String::class.java).invoke(this, key) as Boolean
operator fun Settings.get(key: String) = if (hasProperty(key)) property(key) else null

val repoUrl = settings["repoUrl"]
```

or doing it like this:

```kotlin
operator fun Settings.getValue(any: Any?, property: KProperty<*>): String =
        this.javaClass.getMethod("getProperty", String::class.java).invoke(this, property.name) as String

val repoUrl: String by settings
```

Which works (yay Kotlin!) but it seems that something to provide this access would be suitable to provide as part of kotlin-dsl

**Comment by araqnid** [comment]
I found `startParameter.projectProperties`, but that *only* returns the `-P` args, not the merge of those and `gradle.properties`

**Comment by mat013** [comment]
Since you did the most of it already. Why don't you add that as a pull request. We may be lucky to get in one of the forthcoming releases. I would love to have it in.

I would imagine one place would seem reasonable is to add it to the provider/src/main/kotlin/org/gradle/kotlin/dsl/support/SettingsExtensions.kt

I think it would be in favor of the latter. 

Does your solution also works in the pluginManagement block?

**Comment by araqnid** [comment]
It's fine inside the pluginManagement block. The main issue I have with the latter solution is that it doesn't allow you to handle a property being missing, but it should be possible to make it provide a `String?` value instead. I'll grab the kotlin-dsl codebase and see about making this into a proper patch.

**Comment by mat013** [comment]
Thanks and looking forward to see it :)

**Comment by eskatos** [comment]
Thanks for the PR #653. We should enable access to Gradle properties without involving reflection though.

**Comment by bamboo** [comment]
Including support for delegated properties as in:

```kotlin
val myProperty by settings
```

**Comment by mkobit** [comment]
Related to https://github.com/gradle/gradle/issues/1697

**Comment by eskatos** [comment]
Closing as delivered in 4e8a53b

**Comment by lamba92** [comment]
> Closing as delivered in [4e8a53b](https://github.com/gradle/kotlin-dsl/commit/4e8a53b47c81af2996efdfecceb6a18b83ee65d5)

Is there an example?
