### ISSUE TITLE
Static accessors are missing from the classpath given to IntelliJ IDEA for `buildSrc/build.gradle.kts`

### ISSUE THREAD

**Issue by bamboo** [gradle/kotlin-dsl#640]
<img width="839" alt="screen shot 2017-12-21 at 18 06 39" src="https://user-images.githubusercontent.com/51689/34273011-bad4f0f4-e679-11e7-90c5-443a9293329b.png">

**Comment by JLLeitschuh** [comment]
Oh, I'm glad you're seeing this too. I was seeing this ~ a month ago but didn't open a bug. Sorry about that.
Thought it was just weirdness in IntelliJ and I didn't want to fight with it.

Any thoughts on the root cause?

**Comment by bamboo** [comment]
Hey, @JLLeitschuh. I think `buildSrc/build.gradle.kts` is being handled as a "script plugin" instead of a project script because [the code](https://github.com/gradle/kotlin-dsl/blob/develop/tooling-builders/src/main/kotlin/org/gradle/kotlin/dsl/tooling/builders/KotlinBuildScriptModelBuilder.kt#L94) is only looking for project scripts in `project.allprojects`, it needs to explicitly take `buildSrc` into account.

**Comment by eskatos** [comment]
This only happens when there's no `buildSrc/settings.gradle.kts`

**Comment by JLLeitschuh** [comment]
Was this resolved by Jetbrains?

**Comment by eskatos** [comment]
Sorry I thought the issue/pr association events coming from ZenHub were visible.
It was fixed in #715
