### ISSUE TITLE
settings.gradle.kts available?!

### ISSUE THREAD

**Issue by StefMa** [gradle/kotlin-dsl#641]
According to the readme settings.gradle in kotlin-dsl is not available.
But according to the [0.13.1 release](https://github.com/gradle/kotlin-dsl/releases/tag/v0.13.1) it is supported.

So my question.
Is it supported or not? 😅

**Comment by bamboo** [comment]
It is supported, @StefMa. I've updated the README to reflect that, thanks for the report!
