### ISSUE TITLE
project-schema (accessors) isn't inherited with project dependencies

### ISSUE THREAD

**Issue by Barteks2x** [gradle/kotlin-dsl#642]
I have a project that uses kotlin-dsl with generated accessors, that also has a project dependency on another project that uses kotlin-dsl, and some other projects already use that main project as a project dependency too. This is the version before I started using accessors, as it's not yet pushed to github.

The problem: when trying to use another gradle project as a project depencency, it's project-schema isn't used together with it, so `gskGenerateAccessors` has to be used again, which is very inconvinient as it requires first removing all the erroring code, and then running the task and reverting the code back, just to have a working project dependency.

**Comment by eskatos** [comment]
Closing, see #1195
