### ISSUE TITLE
KT-19025 - Gradle Kotlin script from file based project is all red

### ISSUE THREAD

**Issue by bamboo** [gradle/kotlin-dsl#643]
~https://youtrack.jetbrains.com/issue/KT-21985~ (a duplicate of https://youtrack.jetbrains.com/issue/KT-19025).

You can find a complete repro project [here](https://github.com/bamboo/kotlin-dsl-file-based-project-repro/).

In order to reproduce the problem

1. run `./gradlew idea`
2. open the generated `ipr` file with IntelliJ IDEA (dot not _Import_ the project but _Open_ the `ipr` instead)
3. open `build.gradle.kts` and notice it's all red
   ![all red](https://github.com/bamboo/kotlin-dsl-file-based-project-repro/raw/master/open-ipr-project.png)

Expected behaviour:

![not red](https://github.com/bamboo/kotlin-dsl-file-based-project-repro/raw/master/import-gradle-project.png)

**Comment by eskatos** [comment]
Marked as fixed upstream and targeted at Kotlin 1.2.40 \o/

**Comment by cstroe** [comment]
The "upstream" in this case is IntelliJ IDEA?

**Comment by eskatos** [comment]
@cstroe, correct.

Apparently it was marked as fixed by mistake and has been reopened.

**Comment by eskatos** [comment]
Confirmed as fixed in 1.2.40-eap-16:
- no syntax highlighting when no Gradle context available
- visible message explaining why
