### ISSUE TITLE
Gradle ChangingModules caching (with kotlin?) is not invalidating properly

### ISSUE THREAD

**Issue by xenoterracide** [gradle/kotlin-dsl#648]
I'm not sure if this is explicitly a kotlin-dsl bug or not, gradle 4.4.1

https://discuss.gradle.org/t/gradle-caching-with-kotlin-is-not-invalidating-properly/25249

### Expected Behavior

gradle should refetch changing modules when they're not set to be cached, every time, or if I have the expiration set to a minute, then after a minute.

### Current Behavior
gradle appears to be caching changing modules for the default? amount of time

### Steps to Reproduce (for bugs)

current partial config, more info in the discuss, though I can probably provide more if necessary

```
configurations.all({
    resolutionStrategy.cacheChangingModulesFor(0, TimeUnit.SECONDS)
})

...
    implementation("com.xenoterracide:util:0.1.4-SNAPSHOT", { isChanging = true })
    implementation("com.xenoterracide.entities:entities-api:0.2.0-SNAPSHOT", { isChanging = true })
    implementation("com.xenoterracide.entities:entities-jpa:0.2.0-SNAPSHOT", { isChanging = true })
    implementation("com.xenoterracide.rpf:sec:0.1.0-SNAPSHOT", { isChanging = true })
    implementation("com.xenoterracide.rpf:sec-dtos:0.1.0-SNAPSHOT", { isChanging = true })
    implementation("com.xenoterracide.rpf:constants:0.1.0-SNAPSHOT", { isChanging = true })
```

### Your Environment
```
------------------------------------------------------------
Gradle 4.4.1
------------------------------------------------------------

Build time:   2017-12-20 15:45:23 UTC
Revision:     10ed9dc355dc39f6307cc98fbd8cea314bdd381c

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_151 (Oracle Corporation 25.151-b12)
OS:           Linux 4.8.11-coreos-r2 amd64
```

**Comment by bamboo** [comment]
Thanks for the report. This seems to be a core Gradle issue though, would you mind posting this issue to `gradle/gradle`?

**Comment by xenoterracide** [comment]
I don't *think* I had this problem when I was using gradle without kotlin, I'd have to reverify though, why do you think it's a core issue?

**Comment by xenoterracide** [comment]
posted, if you have any further details to why you don't think it's explicitly kotlin, please comment there
