### ISSUE TITLE
Come up with a better filename extension than .gradle.kts

### ISSUE THREAD

**Issue by GrahamBorland** [gradle/kotlin-dsl#652]
The `.gradle.kts` filename extension for Gradle Kotlin DSL scripts is ugly and unwieldy.

### Expected Behavior

Build scripts should have user-friendly names. Filename extensions should be short.
A few suggestions off the top of my head:

- `.kradle`
- `.gradlek`
- `.kgradle`
- `.gradle` (use context or content to decide if it's Groovy or Kotlin)

### Current Behavior

`build.gradle.kts` is hard to read and unpleasant to look at.

### Context

I've been turned off from experimenting with the Kotlin DSL by the fact that the filenames are so darn ugly. It gives a feeling of unpolish.

**Comment by bamboo** [comment]
Thanks for the feedback and suggestions, @GrahamBorland but we are no longer considering changes to the file extension.
