### ISSUE TITLE
please add 0.14.2 to https://plugins.gradle.org/m2/org/gradle/kotlin/kotlin-dsl/org.gradle.kotlin.kotlin-dsl.gradle.plugin/

### ISSUE THREAD

**Issue by NikolayMetchev** [gradle/kotlin-dsl#654]
It seems the latest kotlin-dsl plugin hasn't been uploaded to gradle plugins portal:

https://plugins.gradle.org/m2/org/gradle/kotlin/kotlin-dsl/org.gradle.kotlin.kotlin-dsl.gradle.plugin/

**Comment by bamboo** [comment]
Hi @NikolayMetchev,

The version of the latest Kotlin DSL release (as in the latest _Kotlin language support for Gradle build scripts_) and the version of the latest [`org.gradle.kotlin.kotlin-dsl` plugin](https://plugins.gradle.org/plugin/org.gradle.kotlin.kotlin-dsl), which makes that DSL available to binary plugin projects, are not necessarily the same as they can evolve independently of each other.

That being said, we realize the potential for confusion and will assess how to best handle these releases in the future.

Thanks for bringing this up!

**Comment by eskatos** [comment]
Each Gradle release is meant to be used with a specific version of the `kotlin-dsl` plugin and compatibility between arbitrary Gradle releases and `kotlin-dsl` plugin versions is not guaranteed.

Using an unexpected version of the `kotlin-dsl` plugin in a build can cause hard to diagnose problems.

Starting with Gradle 5.4, a warning is emitted whenever an unexpected version of the `kotlin-dsl` plugin is detected.

See https://github.com/gradle/gradle/pull/8877
