### ISSUE TITLE
KT-21303: Kotlin isn't supported on jdk-10+ea-31

### ISSUE THREAD

**Issue by JLLeitschuh** [gradle/kotlin-dsl#657]
I haven't actually tried this myself but this is according to the Junit 5 team.

Just something I thought I should make everyone aware of. I know this issue isn't directly related to this project.

https://youtrack.jetbrains.com/issue/KT-21303

https://github.com/junit-team/junit5/issues/1169

**Comment by eskatos** [comment]
Apparently fixed in the upcoming `1.2.30`

**Comment by eskatos** [comment]
Fix [confirmed](https://builds.gradle.org/viewLog.html?buildId=11694475)
