### ISSUE TITLE
Guarantee `kotlin-dsl` API binary compatibility

### ISSUE THREAD

**Issue by bamboo** [gradle/kotlin-dsl#679]
Ensure that plugins compiled against `kotlin-dsl` 1.0 will remain compatible with future releases.

**Comment by eskatos** [comment]
Inlined functions usage by plugins should be considered.

**Comment by bamboo** [comment]
Consider https://github.com/Kotlin/kotlinx.coroutines/tree/master/binary-compatibility-validator

**Comment by JLLeitschuh** [comment]
Also relevant. See #1030 about exposing constructors.

**Comment by JLLeitschuh** [comment]
Another thing to consider is that `inline` functions can be called from java or other JVM languages. They just won't be inlined. This isn't true with inlined reified functions.

Just something to be aware of from an API compatibility standpoint.
