### ISSUE TITLE
.gradle.kts semantic highlighting lifecycle when introducing errors in plugins or buildscript blocks

### ISSUE THREAD

**Issue by eskatos** [gradle/kotlin-dsl#692]
Starting with an editor open on some `.gradle.kts` file, once it is ready for edition with proper semantic highlight, introducing some errors get the editor into a state where the whole file is red.

For example, a syntax error inside the `plugins {}` block gets the editor into a state where the whole file is annotated with errors.

The same happen when an error is inserted inside the `buildscript {}` block.

On large files, it looks like it takes quite some time to IntelliJ to highlight in red. Removing this state will probably also enhance the user experience by removing this lost processing.

Removing the offending code allows the editor to get back to a usable state.

This is most probably caused by how the TAPI model builders queried by the IDE are handling errors. This should be enhanced to e.g. provide the previous working classpath.

**Comment by JLLeitschuh** [comment]
> This should be enhanced to e.g. provide the previous working classpath.

This is one solution, but is this a feature that TAPI should have or should IDE's simply cash the last known "working" classpath? Whose role is it to keep track of this?

**Comment by eskatos** [comment]
The Gradle Kotlin DSL dependency resolver that queries the TAPI is running inside the IDE.
Caching at this level would make sense to me.

**Comment by eskatos** [comment]
@JLLeitschuh IntelliJ is doing the caching by providing us with the previous results.

https://github.com/gradle/kotlin-dsl/blob/ccf4cc599f9551b2f0ebb54c2f8d964e82004f39/provider/src/main/kotlin/org/gradle/kotlin/dsl/resolver/KotlinBuildScriptDependenciesResolver.kt#L48

**Comment by eskatos** [comment]
Turns out this two fold.

First aspect is #711, making it impossible to short circuit resolution when source hasn't changed nor to reuse better previous result when encountering errors.

The other one is related to the second point above, reusing previous results. We compile leniently and fail to detect any errors, returning a success response with a wrong classpath. These errors should be collected to allow the ide-side dependency resolver to reuse a better previous result.

I'll go ahead and fix this, we won't benefit from it until #711 is fixed but it might make fixing #711 easier.

**Comment by eskatos** [comment]
If #711 was fixed, current code as of Today would reuse the previous results in a single case: some compilation or configuration error happens in some applied script (as opposed to settings files and project build files).

**Comment by eskatos** [comment]
Closing as delivered in #714 
IntelliJ IDEA follow up in #711
