### ISSUE TITLE
Example of applying third-party plugin

### ISSUE THREAD

**Issue by iNikem** [gradle/kotlin-dsl#694]
I was unable to find an example of how to convert the following groovy dsl snippet to kotlin's one:

```
  apply plugin: 'org.springframework.boot'

```

**Comment by StefMa** [comment]
You can simply use:
```kotlin
apply {
    plugin("org.springframework.boot")
}
```

**Comment by eskatos** [comment]
Closing as answered, thanks @StefMa!

**Comment by iNikem** [comment]
Guys, my ticket was not about "how to do this". it was about "current samples don't show how to do this". ALL samples only demonstrate using gradle built-in plugins. How a John Doe developer should discover this syntax?
