### ISSUE TITLE
Move the kotlin-dsl folder from my home directory

### ISSUE THREAD

**Issue by Xerus2000** [gradle/kotlin-dsl#695]
There was a kotlin-dsl folder created in my home directory. I do not like clutter, so I would like to either have an option to move it, or why not simply put it into the `.gradle` folder? If none of that is possible, please at least add a dot before the folder name so it's hidden in Linux by default.

**Comment by eskatos** [comment]
Hi @Xerus2000, thanks for the report.

What system are you running on? What is the name of that directory? What's inside?

I suppose it is the `~/.gradle-kotlin-dsl` directory (on Linux) where interactions between IntelliJ and the Gradle Kotlin DSL Tooling API are logged.

https://github.com/gradle/kotlin-dsl/blob/2b8755669c27ec1343120445eff5818f574c74c8/provider/src/main/kotlin/org/gradle/kotlin/dsl/resolver/ResolverEventLogger.kt#L92-L100

The intent is to remove these log files once IntelliJ / Gradle Kotlin DSL interactions are ironed out.

**Comment by Xerus2000** [comment]
Oh sorry I just realised that it was a mistake on my side. Why though is the `.gradle-kotlin-dsl` not a subfolder of `.gradle`?

**Comment by eskatos** [comment]
The component that produces these logs runs inside IntelliJ IDEA, outside of Gradle.
