### ISSUE TITLE
Introduce cross-build in-memory compiled Kotlin script cache

### ISSUE THREAD

**Issue by eskatos** [gradle/kotlin-dsl#696]
Dogfooding the Kotlin DSL on the `gradle/gradle` build made apparent the fact that the Kotlin DSL provider doesn't have a cross-build in-memory compiled script cache and thus is slower than the Groovy DSL provider.

The regression can be seen [here](https://builds.gradle.org/viewLog.html?buildId=10626274&buildTypeId=Gradle_Check_PerformanceTestCoordinator&tab=buildResultsDiv) and the flamegraphs [here](https://builds.gradle.org/viewLog.html?buildId=10632445&buildTypeId=Gradle_Util_Performance_AdHocPerformanceScenarioLinux&tab=artifacts#!-1o4yfzkjpc80h,3grkdhtd6wwj).

We can clearly see that calculating the on-disk cache key is pretty expensive (`ClasspathUtil.getClasspath()` & hashing). This calculation wouldn't be needed with an in-memory cache built the same way as the Groovy DSL provider one.

A cross-build in-memory compiled script cache should be introduced in the Kotlin DSL provider. According to the flame graphs it may make the Kotlin DSL provider faster than the Groovy one.

**Comment by JLLeitschuh** [comment]
Just trying to understand, are you saying that the compiled Kotlin scripts don't get cached in memory in the daemon currently?

**Comment by bamboo** [comment]
Compiled Kotlin scripts don't get cached in memory currently.

**Comment by JLLeitschuh** [comment]
Okay, thanks for the clarification.

**Comment by JLLeitschuh** [comment]
Okay, thanks for the clarification.

**Comment by eskatos** [comment]
[Ad-hoc performance test build in `gradle/gradle`](https://builds.gradle.org/viewLog.html?buildId=10847127&buildTypeId=Gradle_Util_Performance_AdHocPerformanceScenarioLinux&tab=buildLog&_focus=2398#_state=84,2395,2397) shows a 3.4% speedup. Keep in mind that this test evaluates 12 Kotlin scripts and 111 Groovy scripts. The on-disk compilation cache disappeared from the [flame graphs](https://builds.gradle.org/viewLog.html?buildId=10847127&buildTypeId=Gradle_Util_Performance_AdHocPerformanceScenarioLinux&tab=artifacts#!-1o4yfzkjpc80h,3grkdhtd6wwj,-1o4yfzkjpc80h,3grkdhtd6wwj).

**Comment by eskatos** [comment]
Closing as delivered in https://github.com/gradle/kotlin-dsl/commit/a898ce1ee5c79c0913964a5d5520f86a46b2266b

**Comment by bamboo** [comment]
\o/
