### ISSUE TITLE
Ensure backwards compatibility of pluginManagement in settings.gradle.kts

### ISSUE THREAD

**Issue by eskatos** [gradle/kotlin-dsl#697]
The Groovy DSL provider checks that there's a single `pluginManagement {}` block and that it is the first expression in the script, just like with `buildscript {}`. But, the block is then evaluated as part of the settings script body with the whole script api available.

The Kotlin DSL provider evaluates `pluginManagement {}` block as part of the settings script body without any particular check.

We should introduce the same checks in order to guarantee backwards compatibility by preventing users from introducing backwards incompatible code in their build scripts.

**Comment by bamboo** [comment]
We can introduce a `fun pluginManagement(configure: PluginManagementScope.() -> Unit)` in the script template and mark `PluginManagementScope` `@GradleDsl`.

**Comment by eskatos** [comment]
And consider opening an upstream issue about corner cases like `settings.pluginManagement.*`

**Comment by eskatos** [comment]
Closing as delivered in 786d193
