### ISSUE TITLE
KT-22611 Precompiled `*.gradle.kts` scripts from regular Kotlin sourcesets are not in the test runtime classpath

### ISSUE THREAD

**Issue by bamboo** [gradle/kotlin-dsl#699]
https://youtrack.jetbrains.com/issue/KT-22611

**Comment by ligee** [comment]
The KT-22611 is fixed in 1.2.60, the sample project works as expected, as far as I can tell.

**Comment by bamboo** [comment]
Thanks, @ligee.

I've updated the [`kts-from-sourceset`](https://github.com/bamboo/kts-from-sourceset) repro project to the latest Gradle Kotlin DSL snapshot distro which includes 1.2.60-eap-44 and I can confirm that after importing the project I can successfully execute the unit tests from the IDE.

Debugging into the precompiled `.gradle.kts` script doesn't seem to work though. The debugger won't [step into the precompiled `.gradle.kts` script](https://github.com/bamboo/kts-from-sourceset/blob/47828eb2a7ed705ab43986c72d71a1e97aa35ca9/plugins/src/test/kotlin/plugins/MyGradlePluginTest.kt#L27) nor stop in breakpoints. Is that expected?

**Comment by ligee** [comment]
No, it is not expected, but wasn't tested either, so not really surprising. Please, create a separate issue for that.

**Comment by eskatos** [comment]
Closing

@bamboo please take care of creating a separate issue for debugging

**Comment by bamboo** [comment]
@ligee there was already a bug report about the debugger ignoring breakpoints in kts files: 

https://youtrack.jetbrains.com/issue/KT-23526

We're tracking it as #1040.
