### ISSUE TITLE
[ Suggest ] We'd better NOT set gradle and ONLY to use ~/.gradle ; Everything will be OK

### ISSUE THREAD

**Issue by zxj5470** [gradle/kotlin-dsl#701]
It takes me a whole night to set env.

:joy:

### Current Behavior
Everything is OK

### May be solve it
[#698][#692]

### Your Environment
Mac OS Sierra 10.12.6
Intellij Idea 18.1EAP

![qq20180201-084454](https://user-images.githubusercontent.com/20026798/35655323-4999fc1c-072c-11e8-87a1-4ff72c947da8.png)

**Comment by JLLeitschuh** [comment]
Not totally certain I understand what your problem is.

**Comment by eskatos** [comment]
Thank you for your feedback @zxj5470
