### ISSUE TITLE
How to overwrite a task?

### ISSUE THREAD

**Issue by Xerus2000** [gradle/kotlin-dsl#705]
I can't find any documentation or sample on how to overwrite a task.

**Comment by Xerus2000** [comment]
Would be good to add a sample for this

**Comment by StefMa** [comment]
As long as it isn't really supported it don't need a sample. Additionally
not everything needs a sample IMO.

**Comment by eskatos** [comment]
Closing as answered

**Comment by StefMa** [comment]
I don't think that it should be closed.
Better to keep it open to remind us to  to add the extension function...

**Comment by eskatos** [comment]
The Gradle API provides [TaskContainer#replace](https://docs.gradle.org/4.5/javadoc/org/gradle/api/tasks/TaskContainer.html#replace-java.lang.String-java.lang.Class-).

```java
// TaskContainer.java
Task replace(String name);
<T extends Task> T replace(String name, Class<T> type);
```

There's no need for an extension on the Gradle Kotlin DSL side to make this usable.

**Comment by Xerus2000** [comment]
But as it stands now, I can't find a way to override a task within a` tasks` block, but have to use a separate `tasks.replace` call, which is inconvenient

**Comment by eskatos** [comment]
Good point @Xerus2000!
`tasks {}` block receiver is a `NamedDomainObjectContainer<Task>`.
The `TaskContainer` methods aren't available in there.

I opened #716 to account for the more general issue.

**Comment by elect86** [comment]
> But as it stands now, I can't find a way to override a task within a` tasks` block, but have to use a separate `tasks.replace` call, which is inconvenient

Any news on this?
