### ISSUE TITLE
FileNotFoundException on Windows when applying kotlin-dsl script from dependency jar-file

### ISSUE THREAD

**Issue by Zeleboba9** [gradle/kotlin-dsl#706]
Build (build.gradle.kts) fails with FileNotFoundException when applying kotlin-dsl script (common.gradle.kts) from dependency (packed in jar) in Windows environment, works well on Unix and macOS.

A problem occurred evaluating root project 'my-project'.
> Could not open cache directory dob7tsrirpfp0vrg6lwa3o24w (C:\gradle\caches\4.4.1\gradle-kotlin-dsl\dob7tsrirpfp0vrg6lwa3o24w).
   > java.io.FileNotFoundException: C:\gradle\caches\4.4.1\gradle-kotlin-dsl\dob7tsrirpfp0vrg6lwa3o24w\jar:file:\C:\gradle\caches\modules-2\files-2.1\my.com\my-common\0.0.1\8e5f1054caa1e80a2047ec4f62e274ab33e17a53\my-common-0.0.1.jar!\common.gradle.kts (The filename, directory name, or volume label syntax is incorrect)

build.gradle.kts:
buildscript {
...
    dependencies {
        classpath "my.com:my-common:0.0.1"
    }
}

apply {
    from(project.buildscript.classLoader.getResource("common.gradle.kts").toURI())
}

common.gradle.kts:
tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
    options.compilerArgs.addAll(arrayOf("-Xlint:unchecked", "-Xlint:deprecation", "-Werror"))
}

tasks.withType<ProcessResources> {
    filesMatching("*.yml") {
        expand(project.properties)
    }
}

task<Wrapper>("wrapper") {
    gradleVersion = "4.4.1"
    distributionType = Wrapper.DistributionType.ALL
}

**Comment by bamboo** [comment]
Thanks for the report, @Zeleboba9.

This issue has been recently fixed (b9f4a5fe408fba1147988c1cf4a52415d00c76c2) and it will be available in the next Kotlin DSL release.

**Comment by bamboo** [comment]
Test case added in 4857bdd13ad956e4eb7c2ca04d4588ef56736873.
