### ISSUE TITLE
Extensions Arrays are imutable

### ISSUE THREAD

**Issue by StefMa** [gradle/kotlin-dsl#712]
In a project I want to use [this plugin](https://github.com/novoda/bintray-release).
Unfortunately I can't set/change the `licences` from their extension in a expected way.

[This is the extension from the plugin.](https://github.com/novoda/bintray-release/blob/847b34d0d65ae72282a3b63268e96f1d2229d1b0/core/src/main/groovy/com/novoda/gradle/release/PublishExtension.groovy)
As you see. `licenses` have a default value:
`String[] licences = ['Apache-2.0']`

### Expected Behavior
In the Groovy DLS I use the following code:
```groovy
publish {
//... Other code - ignore me
    licences = ["MIT"]
}
```
With that code the `license` array will be overwritten and it works.

I expect that I can set the `licenses` in kotlin similar to groovy:
```kotlin
publish {
//... Other code - ignore me
    licences = arrayOf("MIT")
}
```

### Current Behavior
If I use the same code in the Kotlin-DSL I get the error:
![bildschirmfoto 2018-02-08 um 15 33 22](https://user-images.githubusercontent.com/10229883/35978229-6c0b896e-0ce5-11e8-849f-3e74f9647a87.png)

I can't workaround it somehow.  First I thought I can use
```kotlin
licences.toMutableList().add("MIT")
```
but since the `toMutableList()` will return a **new** list I have to set the new list (which I have to convert to array first of course) to the licenses field of the extension. But since it is immutable I can't set it 😞 

### Context
N/A

### Steps to Reproduce (for bugs)
You could create a new project and add the following code:
settings.gradle
```gradle
pluginManagement {
    repositories {
        gradlePluginPortal()
    }
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == "com.novoda.bintray-release") {
                useModule("com.novoda:bintray-release:${requested.version}")
            }
        }
    }
}
```

build.gradle.kts
```kotlin
plugins {
    id("java-library")
    id("com.novoda.bintray-release") version "0.8.0"
}

publish {
    userOrg = "anyOrg"
    groupId = "aGroupdId"
    artifactId = "artifactId"
    uploadName = "name"
    version = "AVersion"
    description = "A descritpion"
    website = "https://github.com/gradle/kotlin-dsl"
    licences = arrayOf("MIT")
}
```

### Your Environment
 * ~Build scan URL:~
I think a build scan make no sense here

**Comment by mkobit** [comment]
Current workaround is to call the setter that uses `varargs` -> `setLicenses("MIT")`

**Comment by StefMa** [comment]
@mkobit hmm, I don't know what do you mean.
According to my build.script there is no `setLicenses`: 
![bildschirmfoto 2018-02-09 um 09 03 09](https://user-images.githubusercontent.com/10229883/36017462-1e87dc86-0d78-11e8-98a3-508aea90544e.png)

**Comment by eskatos** [comment]
That's causes by Groovy generating a property setter that takes a vararg for an array.
Plugin types should prefer collections.

Also note that #380 could help here.

Closing as answered
