### ISSUE TITLE
Compile failure in fresh clone?

### ISSUE THREAD

**Issue by coreybrenner** [gradle/kotlin-dsl#720]
$ gradle tasks
Parallel execution is an incubating feature.
e: /Users/corey/src/gradle/buildSrc/src/main/kotlin/org/gradle/plugins/testfixtures/TestFixturesPlugin.kt: (104, 21): Unresolved reference: because

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildSrc:compileKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

### Expected Behavior

$ gradle tasks

Should produce a list of tasks.  I am trying to compile Gradle from source, so I can begin
working on the native toolchain support that is inadequate to our needs.

### Current Behavior

Current behavior is as described above.  Failure to generate a list of tasks, because
"because" cannot be resolved within the Kotlin build.  Is this the Kotlin DSL?  Can it be disabled so I can focus on something I am using?

### Context

Our needs for better native toolchain support at work have caused me to need to tackle the problem.  My intent is to create a more generic toolchain configuration that can be used to more easily adapt Gradle to using toolchains which don't conform to Gradle's current ideas of the way the world works.  I would like to upstream this work, so that we can more easily fit it into our build environment dependencies, and because more flexibility is needed in this area generally.

In general, Gradle's toolchain support is too closely geared to Gcc (Clang) or MSVC.  When trying to adapt these toolchain templates to, for instance, the QNX SDP's "qcc" and "QCC" compiler drivers, the metadata gathering phase determines that there is no toolchain available for the QNX target platform.  The "tell me your version" flag isn't the same for "qcc" as for gcc.

In a related issue, it is difficult to build binaries for the iPhoneOS platform using Xcode 9.2 and Gradle post-4.4, because there is no way to provide target platform info to the compiler metadata gathering step.  Gradle ends up injecting -I/usr/include into the compile options, with seemingly no way to remove it.  This causes code which might otherwise compile, to fail because of "Unsupported architecture" in /usr/include/sys/cdefs.h.

Gradle is trying to be too smart by about half, when configuring toolchains.  It either needs to become omniscient, knowing how to configure every compiler for every target platform, or it needs to become slightly less smart, or at least more willing to trust the rote configuration.  If the issue is gathering information about header file usage, it might be better to use the compilers' mechanism for dumping this information, then parsing afterward.

### Steps to Reproduce (for bugs)

Clone my fork of Gradle, then try to list tasks:

$ git clone https://github.com/coreybrenner/gradle
Cloning into 'gradle'...
[...]

$ gradle tasks
Parallel execution is an incubating feature.
e: /Users/corey/src/gradle/buildSrc/src/main/kotlin/org/gradle/plugins/testfixtures/TestFixturesPlugin.kt: (104, 21): Unresolved reference: because

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildSrc:compileKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

### Your Environment

Mac OSX, latest git available from homebrew, Xcode 9.2.

**Comment by eskatos** [comment]
In order to build `gradle/gradle` you shall use the [Gradle wrapper](https://docs.gradle.org/current/userguide/gradle_wrapper.html), not a Gradle version you have installed:

```
./gradlew tasks
```

The `gradle/gradle` wrapper is a snapshot of the upcoming Gradle 4.6-rc-1 and its build makes use of features that are only available in this version, hence the failure you get using a previous Gradle version.

**Comment by coreybrenner** [comment]
Thank you.  I had figured that out independently, and had come here to close the ticket. :-)
