### ISSUE TITLE
IDE support for non-Java builds

### ISSUE THREAD

**Issue by big-guy** [gradle/kotlin-dsl#730]
The underlying thing built by the project should not matter when it comes to syntax highlighting/autocompletion/general IDE integration.  I may be doing something wrong.

### Expected Behavior
I can use an IDE that supports Kotlin to edit a Kotlin DSL build script regardless of the type of thing built by the project.

### Current Behavior
The IDE integration seems to require that you apply the Java (or one of the other JVM language) plugins.

### Context
I tried importing https://github.com/gradle/native-samples/tree/master/cpp/application into IntelliJ and converting the `build.gradle` to a `build.gradle.kts`.

With the build script:
```
plugins {
    `cpp-application`
    `xcode`
    `visual-studio`
}
```
Everything is red.  When I switch `cpp-application` for `java`, auto-completion and syntax highlighting start to work.  I verified that these built-in plugin ids show up in the Kotlin extension.

If I try this instead:
```
plugins {
    id("cpp-application")
    id("xcode")
    id("visual-studio")
}
```
Nothing is red, but I can't access any types or DSL as I would expect.  Switching "cpp-application" for "java" again and things start working. 

I also tried creating a multi-project build where the root most project applied the Java plugin and a subproject applied the `cpp-application` plugin, but the behavior seemed the same.

**Comment by eskatos** [comment]
I was unable to reproduce using IntelliJ 2018.1.3, Kotlin IntelliJ Plugin 1.2.41 and a Gradle 4.8 nightly.

![image](https://user-images.githubusercontent.com/132773/39919490-15905c0a-5514-11e8-8d88-27c1e3ab3467.png)

**Comment by eskatos** [comment]
@big-guy could you confirm it now works for you?

**Comment by big-guy** [comment]
Yep, this seems to work now.  Any idea what changed?

**Comment by eskatos** [comment]
Thanks for confirming @big-guy!

IIUC your original report, you imported the project and then converted `build.gradle` to `build.gradle.kts`, I assume you re-synched the Gradle project in IntelliJ. The issue was about highlighting in the IDE and I don't see why it wouldn't have worked from the command line. So, I guess all the improvements made to the IDE in Kotlin 1.2.4x fixed the UX behavior you were seeing.
