### ISSUE TITLE
Lack of `open` task class causes strange failures

### ISSUE THREAD

**Issue by big-guy** [gradle/kotlin-dsl#731]
Given this task class in a `build.gradle.kts`:
```
class SomeTask : DefaultTask() {
    @TaskAction
    fun myAction() {
        print("Hello, world")
    }
}
```

If I try creating the task with any of these options:
```
 val myTask: SomeTask = tasks.create("myTask", SomeTask::class.java)
 val myTask: SomeTask = project.task<SomeTask>("myTask")
 val myTask: SomeTask = project.createTask("myTask", SomeTask::class, {})
```
the build fails with:
> Could not generate a proxy class for class Build_gradle$SomeTask.

If I instead try to create the task this way:
```
tasks {
     val myTask: SomeTask by creating
 }
```
It seems to work, except it doesn't.  The build succeeds and Gradle reports that `myTask` has no actions.

If I try adding the task's action manually:
```
tasks {
     val myTask: SomeTask by creating
     myTask.doLast {
         print("do something")
     }
 }
```

This fails during configuration time with the error:
> Element 'myTask' of type 'org.gradle.api.DefaultTask_Decorated' from container 'org.gradle.kotlin.dsl.NamedDomainObjectContainerScope@50397db8' cannot be cast to 'Build_gradle.SomeTask'.

If I try the equivalent kind of task in Groovy (`final class SomeTask extends DefaultTask ...`), I get a similar "Could not generate a proxy class" error. 

I think there are three facets to this problem:
- Since final classes are the default in Kotlin, are there any additional diagnostics we can add to kts compilation or can we influence the openness of a type to make this kind of problem more obvious or preventable?
- If we do nothing, I think it's mostly OK if we behave similar to a final task class in the Groovy DSL.  But it's very bad that we silently create a seemingly valid task that does nothing. I'm not sure if there's a way to do this from the Groovy DSL.
- The cast failure is very cryptic and should be avoided if possible.

**Comment by StefMa** [comment]
From my point of view this is not a issue of the Kotlin-DSL or of the Groovy-DSL.
It is more or less a language decided how they handle classes/finals.

Fact is that Gradle have to create - for whatever reasons - a "proxy class" of some classes. For that they need non final classes. That is just one requirement of Gradle if you develop something for/with Gradle. Maybe that should be just better documented in the Gradle docs. 

We could implement the `all-open` Kotlin-Gradle-Plugin which opens all Kotlin classes. But from my point of view we should do that in the Groovy version as well.
But - as I already said - I would do nothing here 😃

The only issue I see here is the fact that a `tasks {}` block works somehow (or not really).
That is the only issue I see here which should be fixed.

**Comment by big-guy** [comment]
@StefMa I agree that we don't have to fix the issue with `final` classes.  I [pushed a change](https://github.com/gradle/gradle/commit/19cb9d54edf44b020bcf2d756cab960567ac65f4) to improve the error message by checking explicitly for `final` classes.

The main problem is the weirdness around `tasks {}`.

**Comment by JLLeitschuh** [comment]
@bamboo This could be resolved by using the Kotlin Compiler for the script files with the "All Open" plugin.

**Comment by bamboo** [comment]
Indeed: https://github.com/gradle/kotlin-dsl/issues/378 ;)

**Comment by StefMa** [comment]
As I already said I wouldn't do that.
There a different reasons why Kotlin have decided to make all classes by default `final`.
Beside of that (also already mentioned above):
If you change it in the Kotlin DSL you should change it also in the Groovy DSL.
You should also changed that for plugin developers which may choose Kotlin as their plugin language of choice.
This gives you much more overhead that just document somewhere "Gradle needs non final classes for X, Y, and Z to create proxy classes".
This is in my opinion the better solution...

**Comment by eskatos** [comment]
Thanks to @big-guy, Gradle, starting with 4.7-rc-1, emits better error messages when a task class is final. And there is #378.

This issue also contains other aspects that were extracted as a separate one: #805

Closing this one as delivered in https://github.com/gradle/gradle/commit/19cb9d54edf44b020bcf2d756cab960567ac65f4
