### ISSUE TITLE
Handle scripts with name ending with`.settings.gradle.kts` as `Settings` scripts

### ISSUE THREAD

**Issue by bamboo** [gradle/kotlin-dsl#735]
Currently only `settings.gradle.kts` itself as treated as a `Settings` script.

**Comment by JLLeitschuh** [comment]
That is a gnarly and long extension. But it makes sense.

**Comment by bamboo** [comment]
Closing as delivered.

**Comment by JLLeitschuh** [comment]
Is this a documented feature anywhere? Should a follow-on task be opened to actually document somewhere that this behaviour exists? The only reason I know it exists is because I follow every PR and have chatted with you @bamboo about this directly.
