### ISSUE TITLE
buildscript.sourceFile in applied scripts should return the applied script file

### ISSUE THREAD

**Issue by eskatos** [gradle/kotlin-dsl#736]
it currently returns the applying script file.

```kotlin
// other.gradle.kts
println("other: ${buildscript.sourceFile}")

// build.gradle.kts
println("main: ${buildscript.sourceFile}")
apply { from("other.gradle.kts") }
```

outputs:
```
main: /path/to/build.gradle.kts
other: /path/to/build.gradle.kts 
```

it should output this instead:
```
main: /path/to/build.gradle.kts
other: /path/to/other.gradle.kts 
```

**Comment by JLLeitschuh** [comment]
Is this an issue specific to the Kotlin DSL or all applied scripts?

**Comment by eskatos** [comment]
@JLLeitschuh it is specific to Kotlin DSL scripts.

**Comment by eskatos** [comment]
It happens because `buildscript` returns the script target `ScriptHandler`.
It should return the script `ScriptHandler` instead.

**Comment by bamboo** [comment]
Closing as delivered.
