### ISSUE TITLE
Script named init.gradle.kts is exposed as a project script instead of as an initialization script to IDE editors

### ISSUE THREAD

**Issue by GFriedrich** [gradle/kotlin-dsl#741]
With #684 ".init.gradle.kts" support was added to Kotlin DSL.
Via #717 the support of "init.gradle.kts" files within the Gradle home directories was added.
Unfortunately the latter one doesn't give proper context support within IntelliJ as the KotlinInitScript class only recognizes ".init.gradle.kts" (so only the ones which have a "init.gradle.kts" suffix) which was implemented with the mentioned #684 

Not sure why it was decided to only recognize files with a suffix, but changing the pattern at [KotlinInitScript.kt Line 56](https://github.com/gradle/kotlin-dsl/blob/c17a316b11976377050947265d08c7e58fce5d36/provider/src/main/kotlin/org/gradle/kotlin/dsl/KotlinInitScript.kt#L56) should let IntelliJ recognize the "init.gradle.kts" files correctly.

**Comment by rgoldberg** [comment]
Are there any objections to making this change?

**Comment by JLLeitschuh** [comment]
@eskatos Why is this in the icebox? Too much work? Are `init` scripts too underused?

**Comment by eskatos** [comment]
The problem is the ambiguity of an arbitrary file named `init.gradle.kts` sitting in a project directory, it could be a project script plugin.

`init.gradle.kts` is only ever an init script when it’s found in the Gradle home or when explicitly configured as so via `-I`.

It’s a tradeoff, either we lose support for project scripts named `init.gradle.kts`,
or we lose support for the one init script named `init.gradle.kts`.
the pattern based selection is not capable of handling both

**Comment by JLLeitschuh** [comment]
This breaks the paradigm of how the rest of these scripts work, but what about using a file annotation?
```kotlin
@file:GradleInitScript
```

That way, with this annotation the TAPI can know how to render the file.

**Comment by eskatos** [comment]
We decided that it's more important to preserve the flexibility to have project scripts named `init.gradle.kts` over providing IDE support for the single case where this name represents an initialization script: `USER_HOME/.gradle/init.gradle.kts`.

The workaround is simple, create a file named `<something>.init.gradle.kts` and put it into the `USER_HOME/.gradle/init.d/` or `GRADLE_HOME/init.d/` directory.

See https://docs.gradle.org/current/userguide/init_scripts.html#sec:using_an_init_script
