### ISSUE TITLE
How can I use `from { blabla }` in kotlin gradle dsl

### ISSUE THREAD

**Issue by ice1000** [gradle/kotlin-dsl#748]
In a Groovy build script, we have this code

```gradle
jar { from { configurations.compile.collect { it.isDirectory() ? it : zipTree(it) } } }
```

To copy all `compile` dependencies to the jar, but `from`'s all overloaded functions' first param is not a `Closure`, but an object.

```java
public AbstractCopyTask from(Object... sourcePaths)
public AbstractCopyTask from(Object sourcePath, Closure c)
public AbstractCopyTask from(Object sourcePath, Action<? super CopySpec> configureAction)
```

What's the equivalant code of `from {}` in kts? Or is there any other way that allows me to copy dependencies into jars?

P.S. tried

```kotlin
from(configurations.compile.allDependencies)
```

But failed.

**Comment by JLLeitschuh** [comment]
```kotlin
from (Callable{ configurations.compile.collect { it.isDirectory() ? it : zipTree(it) } })
```

You may or may not need the generic type parameter on `Callable` I'm not certain.

**Comment by ice1000** [comment]
Let me test

**Comment by ice1000** [comment]
Are you sure? @JLLeitschuh 
![image](https://user-images.githubusercontent.com/16398479/37255007-1f19c152-2581-11e8-9eeb-4e6a65f186a4.png)

**Comment by ice1000** [comment]
After importing `import java.util.concurrent.Callable`, the left one of the two errors above disappears. But what's `collect`? I can't find this method.

**Comment by StefMa** [comment]
Not sure if collect is only available in groovy. But try 'forEach {} '
instead...

**Comment by ice1000** [comment]
Do you mean `map`？

**Comment by ice1000** [comment]
```kotlin
from(Callable { configurations.compile.map { if (it.isDirectory) listOf(it) else zipTree(it) } })
```

This code works. Thanks you all @JLLeitschuh  @StefMa

**Comment by mreichelt** [comment]
The code by @ice1000 didn't compile for me in the latest Gradle Kotlin DSL 1.1 (using Gradle 5.1.1).
It took me some time to figure it out: we have to convert the configuration to a FileTree and then modify that (keep directories, but extract JAR files). Here's a functional way to do it:

```kotlin
tasks.jar {
    from(configurations.compile.map { configuration ->
        configuration.asFileTree.fold(files().asFileTree) { collection, file ->
            if (file.isDirectory) collection else collection.plus(zipTree(file))
        }
    })
}
```

This will copy all JAR contents (classes etc.) into the final JAR.

I am sure there is a better way to write this, but as of now this is a solution that works.

**Comment by StefMa** [comment]
Just wanted to let you know that there is an "official" example how to to
this: https://docs.gradle.org/current/userguide/working_with_files.html

**Comment by StefMa** [comment]
The signature of the method is `from(Object...)`.
And you can't pass a single lambda into the an vararg parameter...
![bildschirmfoto 2019-01-29 um 16 33 24](https://user-images.githubusercontent.com/10229883/51919458-bef84200-23e3-11e9-9068-79a311e77fe7.png)

**Comment by ice1000** [comment]
Thanks for the explanation, although this looks like a design flaw to me.

**Comment by FranklinYu** [comment]
@StefMa Any detail about the reason? Or is there any discussion about this rule?
