### ISSUE TITLE
How can I use `artifacts.add` in kts?

### ISSUE THREAD

**Issue by ice1000** [gradle/kotlin-dsl#749]
In groovy we can have

```kotlin
artifacts {
  archive jar
  archive sourcesJar
}
```

But when I clicked `archive`, IntelliJ jumps to `artifacts.add`.  
`artifacts.add` requires two params while `archive` only passes one.

How can I achive `artifacts.archive jar` in kts?

**Comment by JLLeitschuh** [comment]
I think it's:
```kotlin
artifacts {
 "archive"(jar)
 "archive"(sourcesJar)
}
```

**Comment by ice1000** [comment]
It doesn't work, saying that there's no `invoke` for strings -- but you've inspired me, `add("archives", jar)` works.

gradle 4.6, kotlin 1.2.30, maybe your solution is only available in a preview version?

**Comment by ice1000** [comment]
Thanks

**Comment by mkobit** [comment]
This might be a valid request for DSL generation.

**Comment by ice1000** [comment]
Also please generate `val NamedDomainObjectCollection<Configuration>.library get() = this["library"]` for `configurations { creating("library") }`

And please add

```kotlin
val SourceSet.kotlin
  get() = (this as HasConvention)
    .convention
    .getPlugin(KotlinSourceSet::class.java)
    .kotlin
```
