### ISSUE TITLE
Use metadata sources API to define the embedded-kotlin-repo as artifact-only repository

### ISSUE THREAD

**Issue by jjohannes** [gradle/kotlin-dsl#754]
There is no need to check for metadata files, as they never exist. Also we will no longer check for `jars` at all in Gradle 5.0 which will break the repository (can be tested already with `enableFeaturePreview('GRADLE_METADATA')`).

The fix is to add
```
  repo.metadataSources {
    it.artifact()
  }
```

here
https://github.com/gradle/kotlin-dsl/blob/develop/provider/src/main/kotlin/org/gradle/kotlin/dsl/support/EmbeddedKotlinProvider.kt#L85-L88

**Comment by bamboo** [comment]
Closing as delivered in b70ab790770752297a48eddffc585d8101111d2b.
