### ISSUE TITLE
Compilation failure when using the org.hidetake.ssh plugin

### ISSUE THREAD

**Issue by ingokegel** [gradle/kotlin-dsl#763]
The compilation of the following build file fails with Gradle 4.6:

	import org.hidetake.groovy.ssh.core.Remote
	import org.hidetake.groovy.ssh.core.RunHandler
	import org.hidetake.groovy.ssh.session.SessionHandler

	plugins {
		id("org.hidetake.ssh") version "2.9.0"
	}

	ssh.run(delegateClosureOf<RunHandler> {
		session((ssh.remotes as Map<*, *>)["server"]!! as Remote, delegateClosureOf<SessionHandler> {
			get(hashMapOf("from" to "remoteFile.txt", "into" to "localFile.txt"))
		})
	})

with the error message:

	 Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
		class org.hidetake.groovy.ssh.core.Remote, unresolved supertypes: org.hidetake.groovy.ssh.session.transfer.FileTransferSettings.Trait.FieldHelper, org.hidetake.groovy.ssh.session.execution.SudoSettings.Trait.FieldHelper, org.hidetake.groovy.ssh.operation.ShellSettings.Trait.FieldHelper, org.hidetake.groovy.ssh.operation.CommandSettings.Trait.FieldHelper, org.hidetake.groovy.ssh.session.SessionSettings.Trait.FieldHelper, org.hidetake.groovy.ssh.connection.ConnectionSettings.Trait.FieldHelper, org.hidetake.groovy.ssh.connection.ProxyConnectionSettings.Trait.FieldHelper, org.hidetake.groovy.ssh.connection.HostAuthenticationSettings.Trait.FieldHelper, org.hidetake.groovy.ssh.connection.UserAuthenticationSettings.Trait.FieldHelper

**Comment by JLLeitschuh** [comment]
Is this an issue with the Kotlin compiler or Gradle not correctly resolving dependencies?
A good way to figure this out would be to try to use that plugin as a dependency in some project and try to use those types.

**Comment by weitjong** [comment]
Using kotlin-dsl 0.16.3.

```
plugins {
    id("org.hidetake.ssh") version "2.9.0"
}
remotes {
    create("webServer") {
        host = "192.168.1.101"
    }
}
```

As soon as the 'host' or any property from the `Remote` class is used, the script compilation failed with the similar error message.

FWIW, currently I workaround the issue by writing the remotes configuration and custom SSH task using a separate Groovy script, and then apply the groovy script in my module's build.gradle.kts (similar to https://github.com/gradle/kotlin-dsl/blob/master/samples/groovy-interop/build.gradle.kts).

**Comment by calvertdw** [comment]
@weitjong Is it possible for you to share some example code for doing that?

**Comment by rnett** [comment]
I still get `Duplicate method name "getExt" with signature "(Lorg.gradle.api.NamedDomainObjectContainer;)Lorg.gradle.api.plugins.ExtraPropertiesExtension;" in class file org/gradle/kotlin/dsl/AccessorsKt` when using a separate file.

Not sure if this is the same issue, should I make a new one?

**Comment by eskatos** [comment]
This is a Groovy/Kotlin interoperability problem. The `Remote` type makes use of Groovy traits that confuse the Kotlin compiler. Latest 2.10.1 version of that plugin is also affected.

**Comment by eskatos** [comment]
Here is how to work around the plugin interoperability issue using `withGroovyBuilder {}`:

```kotlin
plugins {
    id("org.hidetake.ssh") version "2.10.1"
}

remotes {
    withGroovyBuilder {
        "create"("webServer") {
            setProperty("host", "127.0.0.1")
        }
    }
}
```

**Comment by calvertdw** [comment]
@eskatos Struggling to use your workaround in practice. I have:

```
var myRemote: Any? = null
remotes {
   myRemote= withGroovyBuilder {
      "create"("remoteName") {
         setProperty("host", "127.0.0.1")
         setProperty("user", "username")
         setProperty("password", properties["password"]!!)
         setProperty("knownHosts", AllowAnyHosts.instance)
      }
   }
}

val deploy by tasks.registering {
   dependsOn(":installDist")

   doLast {
      ssh.run {
         delegateClosureOf<RunHandler> {
            session(myRemote, withGroovyBuilder {
                  "execute"("mkdir -p /remote/dir")
...
```
Currently stuck on the error: `Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
      class org.hidetake.groovy.ssh.core.Remote, unresolved supertypes: FieldHelper, FieldHelper, FieldHelper...`

**Comment by eskatos** [comment]
As long as you need to reference the `Remote` type or an instance from Kotlin it won't work.
Did you try `val remote: Any = withGroovyBuilder { ... }` ?

The real fix would be that https://github.com/int128/gradle-ssh-plugin/issues/317 be addressed by the plugin author or the community.
