### ISSUE TITLE
Tasks for Simple Kotlin/Java Classes

### ISSUE THREAD

**Issue by ConnectionistSystems** [gradle/kotlin-dsl#764]
I'm trying to create tasks for simple kotlin/java classes. I followed something similar to the helloworld example. I know for example in groovy you can do something  "project.task("my Task").

So I need to add a task that would enable the kotlin file to be executed.

Thank you in advance!

**Comment by ConnectionistSystems** [comment]
This is closer to what I'm looking for. But instead of doing gradle run task, I want my own custom task. 

Example

I have kotlin or java file called. PrintToolsList.kt

I want a task to click on or run in terminal to run this PrintToolsList.

What code should I put in the gradle.build to run a similar file above? 

Would I have to run this in JVM?

Thanks!

**Comment by ConnectionistSystems** [comment]
When I put application is build.gradle.kts

It says Expression 'application' cannot be invoked as a function. This function 'invoke()' is not found.

This example also doesn't create a custom/name task. 

In the build.gradle file.
When I add application it says it can't resolve application

I'm looking to do something like this below.

task("SomeTaskName") {
    run HelloKotlin.kt
    }
}

**Comment by JLLeitschuh** [comment]
I think you're looking for the [JavaExec](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.JavaExec.html) task.

**Comment by ConnectionistSystems** [comment]
Thank you, that's what I was looking for. Also, I resolved the issue by creating an actual kotlin gradle file. It doesn't work if you just add the extension.

**Comment by eskatos** [comment]
Closing as answered
