### ISSUE TITLE
Android-related dependencies methods could not be resolved properly

### ISSUE THREAD

**Issue by Archinamon** [gradle/kotlin-dsl#770]
I'm migrating simple gradle project to kotlin-dsl and faced a problem:
methods `api`, `implementation`, `compileOnly`, related to gradle 3.0.0+ api is not properly handling by kotlin-dsl even if AccessorsKt was generated well.

Screenshot illustrating my problem.
<img width="1193" alt="2018-03-21 18 49 02" src="https://user-images.githubusercontent.com/6616695/37721164-e0a357ba-2d39-11e8-9cc2-4b20375cc86a.png">

As well, these methods not always even has been generated. As a workaround I can use `add("api", "dependency:notation:...")` or `"api"("dependency:notation:...")`.

I have tried also launching gradle from command line with `--recompile-scripts` and no positive changes.

### Expected Behavior
Proper handling android-related generated methods for `DependencyHandlerScope`.

### Current Behavior
As I have been described above — these methods not always has been generated at all, or kts file simply not compiling nor from IDEA either from command line.

### Context
Simple Android project generated by IDEA/Android Studio.

### Steps to Reproduce (for bugs)
1. Create new android-project
2. Provide "com.android.tools.build:gradle:3.0.1" classpath dependency
3. Try to use and `api` or `implementation` methods within `dependencies` closure block inside default app module.

### Your Environment
 * Build scan URL: https://gradle.com/s/65y3u4ci3qaiw

**Comment by eskatos** [comment]
Hi @Archinamon,
Thanks for the report.
The availability of Kotlin extensions for dynamic parts of the Gradle model depend on how you apply your Gradle plugins. See https://github.com/gradle/kotlin-dsl/blob/master/doc/getting-started/Configuring-Plugins.md
How are your plugin applied?

**Comment by Archinamon** [comment]
Hello!
I'm using `apply { plugin(<T>::class.java) }` style. Does dsl stricts methods generating upon the way of declaring plugins? I'd found it a bit unobvoius =/

**Comment by eskatos** [comment]
For Kotlin  extensions for dynamic parts of the Gradle model to be available your plugins must be either already applied (e.g. by a parent project) or applied using the `plugins {}` block. That's a known limitation. Please read the documentation linked above ☝️

**Comment by Archinamon** [comment]
Great, thanks!

Does it planning to be fixed? I'm glad you have point me my mistake, but I'd prefer using static types for plugin apply block. Which is not available for `plugins {}` block.

**Comment by eskatos** [comment]
You're welcome!

We can't fix this, `apply {}` is imperative, and could very well be nested in conditionals and such, so we just can't know what plugins would be applied before compiling/evaluating the scripts. The `plugins {}` block on the other hand is declarative, and allow us to provide those extensions. Some more background is available in Gradle's documentation: https://docs.gradle.org/current/userguide/plugins.html
