### ISSUE TITLE
Unable to convert the official KotlinJS example to a multi-project setup

### ISSUE THREAD

**Issue by czyzby** [gradle/kotlin-dsl#792]
Given this setup based on official `hello-js` example:

* `settings.gradle.kts`:

```kotlin
include("a", "b")

pluginManagement {
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == "kotlin2js") {
                useModule("org.jetbrains.kotlin:kotlin-gradle-plugin:${requested.version}")
            }
        }
    }
}
```

* `build.gradle.kts`:
```kotlin
subprojects {
    plugins {
        id("kotlin2js") version "1.2.31"
    }

    dependencies {
        compile(kotlin("stdlib-js"))
    }

    repositories {
        jcenter()
    }
}
```

* empty `a/build.gradle.kts`, `b/build.gradle.kts`,

I'm unable to build the project. It seems that the plugin is not applied properly.

### Expected Behavior
Multi-project setup builds without any errors. (It should be noted that the project builds correctly if the contents of the `subprojects` block is copied to `a`'s and `b`'s `build.gradle.kts` files, but I'd like to avoid that and extract as much shared config as possible.)

### Current Behavior
I'm getting the following script compilation error:

```bash
$ gradle build

> Configure project : 
e: /mnt/workspace/gradle-bug/build.gradle.kts:7:9: Unresolved reference: compile


FAILURE: Build failed with an exception.

* Where:
Build file '/mnt/workspace/gradle-bug/build.gradle.kts' line: 7

* What went wrong:
Script compilation error:

  Line 7:         compile(kotlin("stdlib-js"))
                  ^ Unresolved reference: compile

1 error
```

### Context
Struggling to setup a multi-project setup with 2 KotlinJS modules based on `hello-js` example.

### Steps to Reproduce (for bugs)
Convert `hello-js` into a multi-project setup by wrapping some parts of the script into `subprojects ` or `allprojects` blocks.

### Your Environment
Gradle 4.6, Java 1.8, Kotlin 1.2.31.

**Comment by JLLeitschuh** [comment]
This syntax isn't allowed in your build:
```
subprojects {
    plugins {
        id("kotlin2js") version "1.2.31"
    }
}
```
`plugins` is only valid on the project that the `build.gradle.kts` is configuring, not it's children.

Additionally, static accessors for dependencies aren't generated for child projects, you need to change your code to something like:

```
subprojects {
    apply {
        plugin("kotlin2js") version "1.2.31"
    }

    dependencies {
       "compile"(kotlin("stdlib-js"))
    }

    repositories {
        jcenter()
    }
}
```

**Comment by czyzby** [comment]
The `apply` syntax causes the following error:

```
Script compilation error:

  Line 6:         plugin("kotlin2js") version "1.2.31"
                                      ^ Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
                                          public infix fun PluginDependencySpec.version(version: String?): PluginDependencySpec defined in org.gradle.kotlin.dsl
```

**Comment by JLLeitschuh** [comment]
My bad. Try this:
```kotlin
plugins {
    id("kotlin2js") version "1.2.31" apply false
}

subprojects {
    apply {
        plugin("kotlin2js")
    }

    dependencies {
       "compile"(kotlin("stdlib-js"))
    }

    repositories {
        jcenter()
    }
}
```

**Comment by czyzby** [comment]
Thanks, the last one worked. I still think `"compile"` is a bit tedious - it would have worked in Groovy.
