### ISSUE TITLE
How to avoid avoid Repeated repositories Configuration

### ISSUE THREAD

**Issue by hanct** [gradle/kotlin-dsl#799]
Hi, 
     Me struggle for a day but could not make out anything, hence would like to seek for help
     IDE: Android Studio 3.1

Current Situation
===========

buildscript {
    **repositories {
        google()
        jcenter()
    }**
    dependencies {
        classpath("com.android.tools.build:gradle:3.1.0")
        classpath ("org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.30")
    }
}

allprojects {
    **repositories {
        google()
        jcenter()
}**
}

Query
===========
In the above build.gradle,  is there any way not to repeat the repositories configuration (indicated in bold) in kotlin dsl?

**Comment by bamboo** [comment]
Hi @hanct,

Something like this should do:

```kotlin
buildscript {

  fun RepositoryHandler.configure() {
    google()
    jcenter()
  }

  repositories.configure()

  allprojects {
    repositories.configure()
  }

  dependencies {
    classpath("com.android.tools.build:gradle:3.1.0")
    classpath ("org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.30")
  }
}
```

Alternatively, the extracted function could be moved to `buildSrc`.

**Comment by hanct** [comment]
Thanks. Its working!!!! Finally!
Look like I need to study kotlin syntax a bit more, as the **fun RepositoryHandler.configure** is a bit special syntax. (me coming from java background)
