### ISSUE TITLE
all samples: change to use explicit version

### ISSUE THREAD

**Issue by cvmocanu** [gradle/kotlin-dsl#801]
It is a really bad practice to not specify plugin and dependency versions.
This makes the build very brittle (today it works, tomorrow it doesn't).
It's really unacceptable even for a HelloWorld, if it's going to be used in production.

Since the samples will be the place from where most people will copy/paste, they should not contain any bad practice. This is true, even if changing them makes the samples more complicated. Comments that explain the complexity will help.

In particular, all samples need to be modified to add versions:
- for each plugin. This includes ALL plugins (even core ones) if they need to be downloaded separately from a remote repository (this is the case for maven).
- for each library dependency

An alternative is to place at the beginning of each ".kts" file a big "WARNING: this script is just a sample and is unfit for production. Read more about how to make it production ready at http://...."

**Comment by eskatos** [comment]
Hi @cvmocanu,
Thanks for the concern.

Starting with `kotlin-gradle-plugin` 1.1.1, it is recommended to omit the version of Kotlin dependencies, the plugin manages it. See https://kotlinlang.org/docs/reference/using-gradle.html#plugin-and-versions

For core Gradle plugins that are part of the Gradle distribution, version is simply disallowed, it simply is the Gradle version.

If you find a specific sample where a version is missing, please open an issue for it.

**Comment by eskatos** [comment]
Closing as answered

**Comment by cvmocanu** [comment]
Thanks for the response.
It wasn't clear for me that the version of the plugin is the same version of the Kotlin runtime.

Thanks again and sorry not doing my homework.
