### ISSUE TITLE
New configurations (implementation, testImplementation, etc) do not work in the dependencies block for an Android project

### ISSUE THREAD

**Issue by netvl** [gradle/kotlin-dsl#803]
### Expected Behavior

`implementation`, `testImplementation` etc methods in the `dependencies` block should work correctly.

### Current Behavior

`implementation`, `testImplementation` etc methods give the "unresolved reference" errors:

```
Script compilation errors:

  Line 49:     implementation("org.jetbrains.kotlin:kotlin-stdlib:1.2.31")
               ^ Unresolved reference: implementation

  Line 50:     implementation("org.jetbrains.kotlin:kotlin-reflect:1.2.31")
               ^ Unresolved reference: implementation
```

### Context

I'm migrating my Android project to use the Kotlin Gradle DSL for the build description. It went mostly smoothly, however, it seems that I can't use the `implementation`, `testImplementation` and other new configurations for some reason in Kotlin DSL. It was possible in the regular Groovy DSL, however.

### Steps to Reproduce (for bugs)

I'm not sure how to reproduce it. Apparently, the example project "hello-android" works correctly when `compile` is changed to `implementation`.

### Your Environment

I'm using Gradle 4.6 (also tried with 4.5.1), and I have the following `plugins` section:

```kotlin
plugins {
    id("com.android.application").version("3.0.1")  // also tried with 3.1.0
    kotlin("android").version("1.2.31")
    kotlin("android.extensions").version("1.2.31")
    kotlin("kapt").version("1.2.31")
}
```

The first plugin is made possible to be enabled by additional configuration in `settings.gradle.kts`:

```kotlin
pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
    }
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == "com.android.application") {
                useModule("com.android.tools.build:gradle:${requested.version}")
            }
        }
    }
}
```

**Comment by JLLeitschuh** [comment]
## Solution

I think you need to explicitly add `java-library` to your `plugins` block like so for `implementation` and  `testImplementation` to automatically get generated for you:

```kotlin
plugins {
    `java-library`
}
```

An alternative you can use is this:
```
dependencies {
    "implementation"("org.jetbrains.kotlin:kotlin-stdlib:1.2.31")
    "implementation"("org.jetbrains.kotlin:kotlin-reflect:1.2.31")
}
```

## Question for the Gradle Team
@bamboo @eskatos @eriwen:

Is there any way that we can make this error clearer to users that the problem they are experiencing originates from Gradle not knowing about the configuration?

I think that Gradle needs to provide more useful information when the compiler can't find things like `implementation` or  `testImplementation`. What are your thoughts on this?

**Comment by StefMa** [comment]
I don't think that this is the a official solution.
The android plugin provides already the implementation/api configuration
(however how). It works with groovy. So why doesn't it work with kotlin?

Seems more a like issue from my side...

**Comment by JLLeitschuh** [comment]
Taking a second look at this it might be because the android plugin isn't designed to create the configurations up front and instead adds them later in the plugin lifecycle than the `kotlin-dsl` project evaluates to when generating the accessors.

**Comment by eskatos** [comment]
Hi @netvl,
Thanks for the report.

If you look at the [`hello-android`](https://github.com/gradle/kotlin-dsl/blob/master/samples/hello-android/build.gradle.kts#L28) sample, accessors to `compile`, `implementation` and other configurations are available.

Could you provide a reproducer build or all your build scripts?
Could it be that you were trying to cross-configure projects in a multi-project build?

**Comment by eskatos** [comment]
@netvl thanks for the reproducer, much easier to know exactly what is happening.

I noticed that you use the `gradle/project-schema.json` snapshot. Meaning there's no automatic discovery of the project schema and that you must manage it yourself (using tasks, not editing it by hand). And, your snapshot file was actually outdated. Removing that file fixed the build. This `gradle/project-schema.json` snapshot has been helpful in the early Kotlin DSL days but you should not need it anymore in the general case.
