### ISSUE TITLE
Browser UI component for displaying DSL snippets in both Groovy and Kotlin

### ISSUE THREAD

**Issue by eskatos** [gradle/kotlin-dsl#812]
This browser component should:
- display DSL snippets with e.g. tabs
- rewrite links to DSL references
- rewrite script file names in prose
- switching DSL should switch all snippets
- DSL choice should persist during navigation

Given it will be used in various places using different documentation toolchains, the design of this component should define what all documentation toolchains should generate in order to integrate.

**Comment by StefMa** [comment]
Just wanted to say that I really like the solution of the Google Cloud documentation:
<img width="875" alt="bildschirmfoto 2018-04-07 um 08 45 59" src="https://user-images.githubusercontent.com/10229883/38452230-367f2cd2-3a40-11e8-9bb1-87965922137c.png">
<img width="872" alt="bildschirmfoto 2018-04-07 um 08 46 06" src="https://user-images.githubusercontent.com/10229883/38452231-3698fbb2-3a40-11e8-8245-11be61a897de.png">

**Comment by eriwen** [comment]
I have a first draft of this functionality for Gradle guides here: https://github.com/gradle-guides/gradle-guides-plugin/pull/23 — Gradle docs to follow. Here's what it looks like:

![multi-lang-sample](https://user-images.githubusercontent.com/51534/38645164-e9fed21c-3d97-11e8-9acb-e7700e085ff2.gif)

**Comment by StefMa** [comment]
Don't know where to comment. Here or at https://github.com/gradle-guides/gradle-guides-plugin/pull/23 😓 

Can't say something about the code but the optic.
I don't like:
* That the titles have no "full width" background. I would like it to have the selection is as wide as the source code.
* According to your PR in the other repository we can define the titles (build.gradle, build.gradle.kts). I wouldn't do that. I would force to use always the same title. That leads just to typos or inscosistant in the future. Personally I would "hard code" the titles. 

Other than that:
Good job. I really like it 👍 😄

**Comment by eskatos** [comment]
Closing as delivered

See #880 for a list of guides already making use of the browser ui component.

**Comment by eriwen** [comment]
I'm going to improve this a little bit more, but I won't track that work here.
