### ISSUE TITLE
Translate key Groovy DSL snippets to Kotlin DSL snippets in Gradle user manual

### ISSUE THREAD

**Issue by eskatos** [gradle/kotlin-dsl#813]
#811 will answer #818 and give the tone for the translations.

The plan is to:
- make sure all existing samples have a settings script
- unify the sample directories naming convention as described below
- call the Gradle teams and the community for action

```
.
└── buildCache
    ├── buildSrc-groovy
    └── buildSrc-kotlin
```

**Comment by StefMa** [comment]
The documentation lives in the gradle repository. Shouldn't it be a issue
there? 🤔

**Comment by eskatos** [comment]
Chapters considered as part of this issue:
- Authoring Maintainable Build Scripts
- Organizing Gradle Projects
- Build Script Basics
- Using Gradle Plugins

**Comment by JLLeitschuh** [comment]
@eskatos @eriwen 

Should you consider changing all of the plugin documentation to recommend using the `plugin` syntax instead?

![screen shot 2018-05-24 at 10 38 52 am](https://user-images.githubusercontent.com/1323708/40492599-d3e46816-5f3e-11e8-9c33-457533842b05.png)

Currently every documentation page starts with something like this but I think we'd rather have users using the `plugin` syntax instead correct?

**Comment by eskatos** [comment]
@JLLeitschuh yes! 💯

**Comment by eskatos** [comment]
Key chapters have been translated except one that a community member took over in https://github.com/gradle/gradle/pull/6621
Closing as delivered
