### ISSUE TITLE
unable to apply gradle/kotlin script

### ISSUE THREAD

**Issue by abendt** [gradle/kotlin-dsl#814]
### Expected Behavior
I want to import (apply) a gradle/kotlin script that contains shared logic into a given gradle/kotlin script.
 
### Current Behavior
works, if the imported script is groovy

fails after i migrated the imported script to kotlin
the imported script works standalone 

### Context
in a multimodule build I have some shared logic to configure/start/stop some docker containers.
some of the modules apply the shared script.

### Steps to Reproduce (for bugs)
I setup a stripped down example
https://github.com/abendt/gradle-docker-modularity

`cd module1; gw dockerVersion`

_module1_ uses the groovy version of the script _../docker.gradle_. the task _dockerVersion_ comes from the shared script.

`cd module2; gw dockerVersion`

_module2_ uses the kotlin version of the script _../docker2.gradle.kts_

module2 fails with:

```
> Configure project :
e: /Users/alphonse.bendt/Projects/gradle-docker-modularity/docker2.gradle.kts:1:12: Unresolved reference: bmuschko
e: /Users/alphonse.bendt/Projects/gradle-docker-modularity/docker2.gradle.kts:2:12: Unresolved reference: bmuschko
e: /Users/alphonse.bendt/Projects/gradle-docker-modularity/docker2.gradle.kts:13:11: Unresolved reference: bmuschko
e: /Users/alphonse.bendt/Projects/gradle-docker-modularity/docker2.gradle.kts:15:26: Unresolved reference: DockerInfo
e: /Users/alphonse.bendt/Projects/gradle-docker-modularity/docker2.gradle.kts:18:29: Unresolved reference: DockerVersion


FAILURE: Build failed with an exception.

* Where:
Script '/Users/alphonse.bendt/Projects/gradle-docker-modularity/docker2.gradle.kts' line: 1

* What went wrong:
Script compilation errors:

  Line 01: import com.bmuschko.gradle.docker.tasks.container.*
                      ^ Unresolved reference: bmuschko

  Line 02: import com.bmuschko.gradle.docker.tasks.*
                      ^ Unresolved reference: bmuschko

  Line 13: apply<com.bmuschko.gradle.docker.DockerRemoteApiPlugin>()
                     ^ Unresolved reference: bmuschko

  Line 15: createTask("dockerInfo", DockerInfo::class) {
                                    ^ Unresolved reference: DockerInfo

  Line 18: createTask("dockerVersion", DockerVersion::class) {
                                       ^ Unresolved reference: DockerVersion

5 errors
```

However its possible to invoke the included script directly so it seems to be correct:

`gw -b ../docker2.gradle.kts dockerVersion`
```
> Task :dockerVersion
Retrieving Docker version.
...
```
 
Also the script is shown to be faulty in IntelliJ
![bildschirmfoto 2018-04-09 um 10 49 05](https://user-images.githubusercontent.com/370821/38488446-bf347fc4-3be3-11e8-9243-11b302e383b9.png)

### Your Environment
Gradle:

`gw --version`
```
------------------------------------------------------------
Gradle 4.6
------------------------------------------------------------

Build time:   2018-02-28 13:36:36 UTC
Revision:     8fa6ce7945b640e6168488e4417f9bb96e4ab46c

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_152 (Oracle Corporation 25.152-b16)
OS:           Mac OS X 10.12.6 x86_64
```

IntelliJ:
```
IntelliJ IDEA 2018.1 (Ultimate Edition)
Build #IU-181.4203.550, built on March 26, 2018
Licensed to ...

JRE: 1.8.0_152-release-1136-b20 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.12.6
```

**Comment by Archinamon** [comment]
The same thing even without inter-modules file linking. Just have a main `build.gradle.kts` and some folder, let's name it `scripts` on the same level with build file:
• any kts file within the `scripts` folder won't see imports from outer plugins applied in main build file
• but all files will see imports from buildSrc

Any ETA or workaround on this?

**Comment by Archinamon** [comment]
#601 more about syntax highlight and IDE support, in this case gradle not even builds these scripts :(

**Comment by abendt** [comment]
IntelliJ marks the file as faulty:
![bildschirmfoto 2018-04-16 um 15 32 01](https://user-images.githubusercontent.com/370821/38811986-57ff7068-418b-11e8-8554-694e1f314f3c.png)

I can use the file standalone using the shell: `gw -b ../docker2.gradle.kts tasks`

However when including it exception seems to be the same:

```
> Configure project :module1
e: /Users/alphonse.bendt/Projects/gradle-docker-modularity/docker2.gradle.kts:1:12: Unresolved reference: bmuschko
e: /Users/alphonse.bendt/Projects/gradle-docker-modularity/docker2.gradle.kts:2:12: Unresolved reference: bmuschko
e: /Users/alphonse.bendt/Projects/gradle-docker-modularity/docker2.gradle.kts:17:26: Unresolved reference: DockerInfo
e: /Users/alphonse.bendt/Projects/gradle-docker-modularity/docker2.gradle.kts:20:29: Unresolved reference: DockerVersion


FAILURE: Build failed with an exception.

* Where:
Script '/Users/alphonse.bendt/Projects/gradle-docker-modularity/docker2.gradle.kts' line: 1

* What went wrong:
Script compilation errors:

  Line 01: import com.bmuschko.gradle.docker.tasks.container.*
                      ^ Unresolved reference: bmuschko

  Line 02: import com.bmuschko.gradle.docker.tasks.*
                      ^ Unresolved reference: bmuschko

  Line 17: createTask("dockerInfo", DockerInfo::class) {
                                    ^ Unresolved reference: DockerInfo

  Line 20: createTask("dockerVersion", DockerVersion::class) {
                                       ^ Unresolved reference: DockerVersion

4 errors

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
```

**Comment by JLLeitschuh** [comment]
For sanity's sake, can you do me a favor and try with version `3.2.0` of the plugin?

**Comment by abendt** [comment]
sure.

again the script works standalone but cannot be imported into another script ...

**Comment by JLLeitschuh** [comment]
Ah. Okay, I understand now.
@bamboo & @eskatos Does the

**Comment by JLLeitschuh** [comment]
@abendt 
In `build.gradle.kts` you have:
```kotlin
buildscript {
    dependencies {
        classpath("com.bmuschko:gradle-docker-plugin:3.2.0")
    }
}
apply {
    from("docker2.gradle.kts")
}
```
And in your `docker2.gradle.kts` you have:
```kotlin
// Some imports
apply {
    // some plugin
}
```
And you still get compilation issues?

**Comment by abendt** [comment]
@JLLeitschuh yes, i still get compilation issues.

I updated my demo project: https://github.com/abendt/gradle-docker-modularity

apply-groovy includes a groovy version of the script
apply-kotlin includes the kotlin version (failing)
apply-kotlin-with-classpath additionally sets the build script class path as you suggested (also failing)

**Comment by bamboo** [comment]
@JLLeitschuh, no, the `buildscript` block is not supported in applied scripts, see #180.

**Comment by Archinamon** [comment]
Any ETA on this? Groovy scripts allows using imports from plugins that applies in main build.gradle, but kts not. That's causes a lot of problems migrating groovy scripts to kts.

**Comment by eskatos** [comment]
The `buildscript {}` block in applied scripts is now supported, see #180, but IDE support is not there yet, see #110.

Closing as a duplicate
