### ISSUE TITLE
Consider optimizing code generation and its compilation

### ISSUE THREAD

**Issue by eskatos** [gradle/kotlin-dsl#817]
The Gradle Kotlin DSL generates Kotlin code in various places.

Code generation emits source code and uses the Kotlin compiler to produce the corresponding bytecode. Some of this happens on critical paths and can be slow.

If we generated Kotlin AST and then emitted both source and bytecode we could remove the cost of Kotlin compilation. In all cases observed so far we know exactly what bytecode to generate.

One evidence is described in #815 where Kotlin compilation taking several seconds could be cut down.

**Comment by bamboo** [comment]
Closing as implemented in 370f268fc8462ec8710e17c04408757e346c764a.
