### ISSUE TITLE
Make preferred syntax for common build script configuration as clear as possible

### ISSUE THREAD

**Issue by eriwen** [gradle/kotlin-dsl#818]
### Expected Behavior
In order to provide consistent samples and avoid user confusion, we need  be clear to users how they should declare and configure tasks and other common build script configuration.

Provide a prominent piece of documentation that explains preferred ways to do these things.

### Current Behavior
We have samples, but we vary ways that we achieve common things.

### Context
I argue this is a blocker to converting samples from Groovy => Kotlin in our docs

**Comment by JLLeitschuh** [comment]
Some Examples (certainly not extensive):

## Assignment VS Calling Setters
```kotlin
tasks {
    "copy"(Copy::class) {
        group = "Custom"
        description = "Copies the source to the destination directory"
    }
}
```
VS
```kotlin
tasks {
    "copy"(Copy::class) {
        setGroup("Custom")
        setDescription ("Copies the source to the destination directory")
    }
}
```

## Creation of Tasks
```kotlin
tasks {
    "copy"(Copy::class) {
        // Ect..
    }
}
```
VS
```
val copy = task<Copy>("copy") {
   // Ect...
}
```
VS
```
val copy by tasks.creating(Copy::class) {
   // Ect...
}
```

**Comment by mkobit** [comment]
This is one of the biggest issues I have seen from others I have worked with Gradle and may be unfamiliar with Groovy, and I think with some of the DSL additions to Kotlin might make these even more ambiguous. The "how am I supposed to do this" is a reason some others I work with aren't ready to try and switch.

For example, handling tasks:

```groovy
// what is type: MyTask ? what is 'task'? where is the javadoc?
task myTask(type: MyTask)
// What is 'MyTask'? Oh, at least I can Ctrl + Click in IDEA to go to the method
tasks.create('myTask', MyTask)
// what is myTask? how does this work?
def myTask = tasks.myTask
// ok, that looks like a method
def myTask = tasks.getByName('myTask')
```

```kotlin
// does this create a task? retrieve it? I can CTRL + Click in IDEA to go to the method to figure it out
task<MyTask>("myTask")
// ok looks like I can get a project property by its name
val myProp: String by project
// how come I can't don't that for the tasks?
val myTask: MyTask by tasks
// oh, I guess I need getting
val myTask: MyTask by tasks.getting
// how come this works in Groovy but not Kotlin?
val myTask = tasks.myTask
```

I think the `java` plugin shows a bunch of things that are just "different" that I have seen others struggle to understand.

```groovy
sourceCompatibility = 1.6
targetCompatibility = 1.6
sourceSets {
    main {
        groovy {
            srcDirs = ['src/groovy']
        }
    }
}
```

compared to

```kotlin
java {
    setSourceCompatibility(1.8)
    //sourceCompatibility = JavaVersion.VERSION_1_8
    sourceSets {
        "main" {
            withConvention(GroovySourceSet::class) {
                groovy.setSrcDirs(listOf("src/groovy"))
            }
        }
    }
}
```

* top-level convention properties
* convention extensions/plugins `withConvention(GroovySourceSet::class)`
* automatic setter conversion, especially with methods that take `Object`

Some other areas I can think of:

* A bunch of people don't realize that something like `group 'Welcome'` is actually the method call `group('Welcome')`. The translation between Groovy and Kotlin needs to be clear especially with the often API combination of both methods for both setter style and the method invocation style `group(String group)` and `setGroup(String group)`
* _"This documentation from a public OSS plugin I'm using says to configure it with this Groovy DSL, and copy pasting it to Kotlin doesn't work. I don't know why, so I'm just going to use Groovy"_
* _"What the hell is a `Closure`? I used to just do `protobuf {}` and things worked, and now the `kotlin-dsl` I need to put in some `delegateClosureOf<> {}`?!? or `closureOf<> {}`? What the hell goes in as the generic parameter"?_ (see https://github.com/google/protobuf-gradle-plugin/issues/219#issuecomment-376179475 for an example of how difficult it would be for somebody to try and use that plugin who did not have a knowledge base of Gradle and the Kotlin DSL)
* `buildscript` versus `plugins` - playing the _Accessors - Where Are They Now?_ game
* Dealing with plugins that are not designed in a way to allow for simple integration with the `kotlin-dsl`. See this [SO question/answer](https://stackoverflow.com/questions/48502220/how-to-configure-appengine-gradle-plugin-using-kotlin-dsl/48510049#48510049) for an example.

**Comment by JLLeitschuh** [comment]
I can 100% agree with @mkobit's above post. (Man, this very eloquently captures some of my pains, nice job!)

Part of my "What the hell" interaction with groovy `Closure`s in plugins is part of why I wrote up this [Colosure getting started](https://github.com/gradle/kotlin-dsl/blob/master/doc/getting-started/Closures.md) page.

The solutions I've had to resort to mostly include rooting through the source code of the plugin that I'm trying to integrate my build with.
This was particularly annoying when trying to interact with gradle plugins where you can't find the source code for them (eg. The [com.gradle.plugin-publish](https://plugins.gradle.org/docs/publish-plugin) where the source code [isn't available](https://discuss.gradle.org/t/source-code-for-com-gradle-plugin-publish/24711) (I had a chat with @eriwen about this, I know it will be remeded soon, but it was still painful as an early adopter)).

**Comment by mkobit** [comment]
Another one I want to bring up is the consistency of certain APIs and expectations with regards to reified APIs. I know there is some work to deal with the `Class<T>` accepting APIs to make them work with `KClass<T>`.

```kotlin
// #1
val hey: Jar by tasks.creating {
    // scoped to Task type
}

// #2
val hey: Jar by tasks.getting {
  // compiler fails
  // ^ Type parameter bound for U in fun <T : Any, U : NamedDomainObjectCollection<T>> U.getting(configuration: T.() -> Unit): NamedDomainObjectCollectionDelegateProvider<T>         
  //                                     is not satisfied: inferred type TaskContainer is not a subtype of NamedDomainObjectCollection<Jar> 
}
```

**Comment by JLLeitschuh** [comment]
@mkobit Regarding your last point.
The `java` accessor is an extension function on `Project` so it would get invoked on the "subproject"
but I agree that it's weird that the `java` accessor exists only because of the:
```
plugins {
  java
}
```
Not because of the `apply(plugin = "java")`

**Comment by eskatos** [comment]
Thanks to a great help from the community, the [Gradle User Manual](https://docs.gradle.org/release-nightly/userguide/userguide.html) now contains samples for both the Groovy and Kotlin DSLs. This is now the best place to find information on how
 to use the Gradle Kotlin DSL as it covers all Gradle features from [using plugins](https://docs.gradle.org/release-nightly/userguide/plugins.html) to [customizing the dependency resolution behavior](https://docs.gradle.org/release-nightly/userguide/customizing_dependency_resolution_behavior.html).

A new user manual chapter dedicated to the [Gradle Kotlin DSL](https://docs.gradle.org/release-nightly/userguide/kotlin_dsl.html) has also been added.

The [Gradle Plugin Portal](https://plugins.gradle.org/) now displays Kotlin DSL snippets for easy copy and paste.

The sum of the above makes preferred syntax for common build script configuration as clear as possible, closing this issue. Please direct any more discussion to the documentation properties.
