### ISSUE TITLE
Configuration for Kotlin-Kapt 

### ISSUE THREAD

**Issue by hanct** [gradle/kotlin-dsl#820]
I have 2 build.gradle.kts. One is at top level, the other is inside the src folder. This is the default organization that android studio v3.1 generates for me when i create an android application.
For some unknown reason, when i run my android app, i got the error: 
**org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:compileDebugJavaWithJavac'**

When i remove the  id("kotlin-kapt")  in the plugins section, such error disappear. 
So my query is how to use the kotlin-kapt without any error? Did i miss anything in my configuration?

In the top-level gradle.build.kts, i have this
```
buildscript {
         ........
    dependencies {
        classpath("com.android.tools.build:gradle:3.1.0")
        classpath ("org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.30")
    }
{
```
In the src folder's gradle.build.kts, i have the below
```
plugins{
    id("com.android.application")
    id("kotlin-android")
    id("kotlin-kapt")
    id("kotlin-android-extensions")
   
}
```

**Comment by StefMa** [comment]
From my point of view it doesn't look like a Kotlin DSL issue. Your
configuration looks correct so far.
The error says that you have compile time issue in your code. kapt
generates source files for your. Maybe these generated files are wrong?!
For what are you using kapt? You can take a look into the
build/generated/source/kapt directory for your generated source files...

**Comment by hanct** [comment]
Hi,
Thanks for the reply. I will take a look at the generated files. 
As for your question, i am using it to support annotation (specifically @BindingAdapter) in my android applicaton (develop using kotlin). Currently my @BindingAdapter does not seem to work hence I suspect i need to include kotlin-kapt, and that is when i met this error message

**Comment by hanct** [comment]
Hi, the problem has been solved. I forgot to import a class in my source code, hence indirectly lead to the above error. My above configuration is actually correct.  Thanks
