### ISSUE TITLE
Classpath discovery at configuration time should be reduced

### ISSUE THREAD

**Issue by eskatos** [gradle/kotlin-dsl#824]
Looking at graphs produced by our performance testing infrastructure we can see that it consumes a lot of memory and does way too much classpath discovery.

See this [`help on the gradle build comparing gradle` build](https://builds.gradle.org/viewLog.html?buildId=12298211&buildTypeId=Gradle_Util_Performance_AdHocPerformanceScenarioLinux&tab=artifacts#!-1o4yfzkjpc80h,3grkdhtd6wwj,-1s2moyreduysh,rytasyhp789m,1q2aagnoqbt3n,vl1shhj2eps8,-17oefv4rm4ozr,-1o4yfzkjpc80h,3grkdhtd6wwj,-1s2moyreduysh,1xmmaovlcsviz,-8p8na8w36obu,rytasyhp789m,1q2aagnoqbt3n).

Especially [this `allocation-tlab` graph](https://builds.gradle.org/repository/download/Gradle_Util_Performance_AdHocPerformanceScenarioLinux/12298211:id/results/performance/build/test-results-performanceAdhocTest.zip%21/flames/4.8-20180417160908-0200/allocation-tlab/simplified/icicles.svg). Search for `KotlinBuildScriptCompiler`, you'll see it accounts for 30% of memory allocations, `KotlinBuildScriptCompiler.<init>` for 20%.

It appears that we visit too much classloaders to infer their classpath, too many times. A lot of this should be avoidable to make configuration time faster. It is definitely the case when one script has no dependencies, parent scope classpath could be reused directly. Something along the lines of [this logic](https://github.com/gradle/gradle/blob/8263f4640e65201eb2a12ee549da311cf34f7547/subprojects/core/src/main/java/org/gradle/api/internal/initialization/DefaultClassLoaderScope.java#L99-L115) that does the exact same thing reusing classpaths would help.

**Comment by oehme** [comment]
Caching the [classpath computation](https://github.com/gradle/kotlin-dsl/blob/2b8755669c27ec1343120445eff5818f574c74c8/provider/src/main/kotlin/org/gradle/kotlin/dsl/support/ClassLoaderScopeExtensions.kt#L26) should do the trick. Right now it walks the very same class loaders again and again.

**Comment by bamboo** [comment]
Closing as delivered, new version is ~6% faster.

**Comment by oehme** [comment]
And 25% leaner, nice work!

**Comment by bamboo** [comment]
The performance test infrastructure makes it a joy.
