### ISSUE TITLE
Plugins should be defined in the plugins classloader

### ISSUE THREAD

**Issue by oehme** [gradle/kotlin-dsl#833]
The KotlinScriptBasePlugin and KotlinScriptRootPlugin (and maybe others I have missed) are currently part of Gradle's runtime classloader (because they are packed up in the `lib` directory), but should instead be part of the plugins classloader (packaged up in the `plugins` directory). This is important for the performance of plugin registry lookups. Basically to our plugin registry it looks like a plugin from an "unknown" location, triggering a slower lookup code path.

**Comment by oehme** [comment]
The same is true for model builders btw, although they don't lead to performance problems, they still conceptually belong into the plugins directory, not the runtime.

**Comment by eskatos** [comment]
Closing as delivered in #869 followed up by #871
