### ISSUE TITLE
Should not require lexing to determine the script hash

### ISSUE THREAD

**Issue by oehme** [gradle/kotlin-dsl#834]
See this [flame graph](https://builds.gradle.org/repository/download/Gradle_Util_Performance_AdHocPerformanceScenarioLinux/12410884:id/results/performance/build/test-results-performanceAdhocTest.zip%21/flames/4.8-20180423072656-0000/cpu/simplified/flames.svg) of a warm daemon calling `gradle help` on our own build. We shouldn't need to lex the Kotlin script just to look up the cached script classes. The lexing should only be done the first time the script is compiled.

**Comment by bamboo** [comment]
The lexing of the script happens because we cache and evaluate the `buildscript` and `plugins` blocks separately from the main script.

**Comment by oehme** [comment]
That's alright, but there's no need to make the cache key depend on the separate script parts. You can just add in a qualifier into the hash. We do the same for Groovy. I.e. if the script changes in any way, all parts of the script are "out of date". The lexing should only happen if we actually knows something changed.

**Comment by bamboo** [comment]
Superseded by #897, the new script execution strategy doesn't lex unless strictly necessary.
