### ISSUE TITLE
Users should be able to configure test logging using Kotlin DSL

### ISSUE THREAD

**Issue by eriwen** [gradle/kotlin-dsl#836]
It looks like we don't have `Action` accepting overloads for [AbstractTestTask](https://github.com/gradle/gradle/blob/master/subprojects/testing-base/src/main/java/org/gradle/api/tasks/testing/AbstractTestTask.java) beforeSuite, afterSuite, beforeTest, afterTest, and onOutput methods.  

### Expected Behavior
I should be able to configure test logging using the Kotlin DSL without creating extension functions.

### Current Behavior
There is no easy equivalent to something like this in Kotlin:

```
afterSuite { desc, result ->
    if (!desc.parent) {
        println "\nTest result: ${result.resultType}"
        println "Test summary: ${result.testCount} tests, " +
        "${result.successfulTestCount} succeeded, " +
            "${result.failedTestCount} failed, " +
            "${result.skippedTestCount} skipped"
    }
}
```

The only Kotlin solution I could find is creating something [like this in buildSrc](https://github.com/orange-buffalo/hoopoe-profiler/blob/e53610b65006a7d09d87067545eabf1261aefa3d/buildSrc/src/main/kotlin/hoopoe/gradle/buildscript/BuildScripting.kt).

### Context
Looks like [over 1000 GitHub projects](https://github.com/search?utf8=%E2%9C%93&q=afterSuite+extension%3Agradle&type=Code&ref=advsearch&l=&l=) call `afterSuite` in their test config. These projects will be harder to migrate to Kotlin DSL.

### Your Environment
Kotlin DSL 0.16.3 in Gradle 4.7

**Comment by eskatos** [comment]
This also applies to plugins implemented in Java, they would have to import `groovy.lang.Closure` and fiddle with the untyped Closure parameters.

**Comment by eskatos** [comment]
One workaround is to use a typed `TestListener` instead, it is more verbose because you need to implement its 4 functions though, an adapter would help:

```kotlin
tasks.withType<Test> {
    addTestListener(object : TestListener {
        override fun beforeSuite(suite: TestDescriptor) {}
        override fun beforeTest(testDescriptor: TestDescriptor) {}
        override fun afterTest(testDescriptor: TestDescriptor, result: TestResult) {}
        override fun afterSuite(suite: TestDescriptor, result: TestResult) {}
    })
}
```

**Comment by eskatos** [comment]
There's also `void onOutput(Closure closure)` in `AbstractTestTask` that needs an  `Action` taking counterpart.

**Comment by eskatos** [comment]
All those methods, except `beforeSuite()` takes two parameters. So `Action` is out of question.
Note that `BiAction` is currently internal.

**Comment by eskatos** [comment]
Another potential approach without `BiAction`:
```java
interface TestDescriptorEvent<T> {
    TestDescriptor getDescriptor();
    T getEvent();
}
```
```java
class AbstractTestTask {
    void onOutput(Action<TestDescriptorEvent<TestOutputEvent>> action);
}
```
```kotlin
tasks.withType<Test> {
    onOutput {
        println("$descriptor -> $event")
    }
}
```

**Comment by eriwen** [comment]
This last solution came to my mind as well, and seems more forward-compatible as it guards against the TestListener interface getting more methods.

**Comment by eriwen** [comment]
One last idea that came to my mind is `Action<Pair<TestDescriptor, TestResult>> action` — is that possible?

**Comment by bamboo** [comment]
@eriwen Yes. It would imply usage similar to the following though:

```kotlin
tasks.withType<Test> {
    onOutput { 
        println("$first -> $second")
    }
}
```

**Comment by eskatos** [comment]
Moreover, the changes need to happen in the Gradle Java API where we don't have a public `Pair` type. So far my preference goes to https://github.com/gradle/kotlin-dsl/issues/836#issuecomment-384333766

**Comment by eriwen** [comment]
Agreed @eskatos. Should we solicit community help to address this?

**Comment by eskatos** [comment]
Issue moved to [gradle/gradle #5431](https://github.com/gradle/gradle/issues/5431) via [**ZenHub**](https://www.zenhub.com/)
