### ISSUE TITLE
Capture essential performance scenarios

### ISSUE THREAD

**Issue by eskatos** [gradle/kotlin-dsl#840]
In order to gain confidence in the Kotlin DSL performance as compared with the Groovy DSL we should select a set of performance tests from the existing `gradle/gradle` performance test suite.

Once identified the chosen performance tests should be converted to the Gradle Kotlin DSL and run as part of the regression test suite.

**Comment by eskatos** [comment]
[configure largeJavaMultiProject](https://github.com/gradle/gradle/blob/c4a184957074ac83a52797a48caec594b9b8694c/subprojects/performance/src/performanceTest/groovy/org/gradle/performance/regression/java/JavaConfigurationPerformanceTest.groovy#L44) is probably the best test we have that exercise scripting.

We could try convert [perf-android-large](https://github.com/gradle/perf-android-large) to Kotlin, but that’s a lot more work and we don't suspect big new insights from it.

**Comment by eskatos** [comment]
PR on `gradle/gradle` adding the performance tests: https://github.com/gradle/gradle/pull/5441

**Comment by eskatos** [comment]
We now have regression coverage for:
- large multi project hot daemon configuration time
- large multi project cold daemon configuration time
- large multi project first use configuration time

And a comparison of the Groovy DSL and the Kotlin DSL for large multi project hot daemon configuration time.

See the [Performance Test Coordinator](https://builds.gradle.org/viewType.html?buildTypeId=Gradle_Check_PerformanceTestCoordinator&tab=buildTypeStatusDiv&branch_Gradle_Check_Stage_BranchBuildAccept=master) and [Performance Experiment Coordinator](https://builds.gradle.org/viewType.html?buildTypeId=Gradle_Check_PerformanceExperimentCoordinator&branch_Gradle_Check_Stage_ReleaseAccept=master&tab=buildTypeStatusDiv) CI jobs for the `master` branch of `gradle/gradle`.

Closing as delivered.

**Comment by bamboo** [comment]
\o/
