### ISSUE TITLE
Expose enclosing project accessors to project Kotlin DSL script plugin

### ISSUE THREAD

**Issue by bamboo** [gradle/kotlin-dsl#846]
So as to allow the factoring out of build logic into colocated project scripts.

A common pattern is to keep the dependency declarations in a separate `dependencies.gradle.kts` script which gets applied from the main script.

```kotlin
plugins {
    kotlin("jvm") version "1.2.40"
}

apply(from = "dependencies.gradle.kts")
```

Today, because configuration accessors are not exposed to script plugins, `dependencies.gradle.kts` must use the stringly typed `dependencies` DSL:

```kotlin
dependencies {
    "implementation"(kotlin("stdlib"))
}
```

Exposing the accessors would enable the strongly typed DSL and its accompanying IDE support:

```kotlin
dependencies {
    implementation(kotlin("stdlib"))
}
```

## Limitations

Due to how script plugin `ClassLoader`s are setup, only those types coming from `buildSrc` (and its transitive closure) can be properly shared between top level project scripts and script plugins.

**Comment by JLLeitschuh** [comment]
If you do this, you'll have to make an assumption about which project's accessors you are going to generate for. Should you do it for all projects and all of the subprojects or only for the root project?

Do you make it dependent upon where the file is declared in the project (probably not a good idea as it ties what code is generated to where it is in the directory structure.

**Comment by bamboo** [comment]
> Do you make it dependent upon where the file is declared in the project

That's the proposition.

**Comment by JLLeitschuh** [comment]
That seems kinda counterintuitive.

So, if people have all of their files in a directory in their project called `projectScripts/` and that isn't a Gradle subproject, your not going to get these accessors generated for you?

Also, what is the plan for IDE support for all these rules?

**Comment by bamboo** [comment]
> So, if people have all of their files in a directory in their project called projectScripts/ and that isn't a Gradle subproject, your not going to get these accessors generated for you?

Assuming:

    /root-project/
        /build.gradle.kts
        /projectScripts/
            /script.gradle.kts 

`script.gradle.kts` would get the root project accessors. 

> Also, what is the plan for IDE support for all these rules?

There's only one rule being proposed here and it is with the intent of providing IDE support.

**Comment by JLLeitschuh** [comment]
So, in this case:
```
/root-project/
    /build.gradle.kts
    /subproject/
        /script.gradle.kts
        /build.gradle.kts
```
Then the `script.gradle.kts` would get the accessors for `subproject/build.gradle.kts`
Also, the same would be true for this setup?
```
/root-project/
    /build.gradle.kts
    /subproject/
        /build.gradle.kts
        /projectScripts/
            /script.gradle.kts
```

**Comment by bamboo** [comment]
Exactly.

**Comment by JLLeitschuh** [comment]
I can see the value in this idea, but I can also see potential user confusion that could arise from this feature.
