### ISSUE TITLE
Top-level statically typed extra properties

### ISSUE THREAD

**Issue by ilya-g** [gradle/kotlin-dsl#85]
Currently extra properties defined in buildScript are as dynamically typed as in groovy script and even less convenient to use. For example, look how `kotlinVersion` defined and used in this sample: https://github.com/gradle/gradle-script-kotlin/blob/master/samples/hello-kotlin/build.gradle.kts

Is it possible to declare extra properties on top-level with the help of delegation? something like this:

```
val kotlinVersion by extra("1.1.0-dev-998")
val repo by extra("https://repo.gradle.org/gradle/repo")
```

and then use them as plain variables inside build script:

```
buildscript {
    dependencies {
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion")
    }
}
dependencies {
    compile("org.jetbrains.kotlin:kotlin-stdlib:$kotlinVersion")
}
```

**Comment by jaredsburrows** [comment]
@ilya-g See https://github.com/gradle/kotlin-dsl/issues/485

**Comment by eskatos** [comment]
> Currently extra properties defined in buildScript are as dynamically typed as in groovy script and even less convenient to use.

Extra properties are dynamic by nature. In the dynamic typing world of Groovy you just refer to them by name and they get resolved at runtime. In the static typing world of Kotlin you need to refer to them by both name and type before being able to use them.

> Is it possible to declare extra properties on top-level with the help of delegation and then use them as plain variables inside `buildscript {}`?

The `buildscript {}` block is evaluated before the script body ; top-level members can't be used inside it. So, no, it is not possible.
