### ISSUE TITLE
Add sample with kotlin-dsl for distribution plugin

### ISSUE THREAD

**Issue by alexandrenavarro** [gradle/kotlin-dsl#851]
Add sample with kotlin-dsl for distribution plugin

I tried to use the distribution plugin with the kotlin dsl but I failed.
Can you add a sample or add in the official documentation with a snippet kotlin in addition of the one in groovy, please?

**Comment by StefMa** [comment]
Which distribution plugin do you mean?

**Comment by alexandrenavarro** [comment]
This one https://docs.gradle.org/current/userguide/distribution_plugin.html

**Comment by alexandrenavarro** [comment]
Anyone has config to use the distributions plugin with kotlin, my problem is how to declare the second level with main / custom or what ever

distributions {
    main {
        baseName = 'someName'
        contents {
            from { 'src/readme' }
        }
    }
}

The main is not accepted by kotlin dsl, I tried a string like "main" { but does not work.
If someone has a solution or any comment to help me, I'm really interested, it is the only plugin I can't succeed to use with kotlin-dsl.

**Comment by bamboo** [comment]
Hi @alexandrenavarro, here's how you would translate that snippet to Kotlin at the moment, including the required plugin application:

```kotlin
plugins {
    distribution
}

distributions {
    getByName("main") {
        baseName = "someName"
        contents {
            from("src/readme")
        }
    }
}
```

I hope that helps.

**Comment by alexandrenavarro** [comment]
Thanks a lot, it works. I let the issue open, just to improve samples with the distribution plugin. I'm also interested if it is possible to have some documentation to migrate from groovy -> kotin  dsl. For instance, how can I know I have to change from "main" to getByName("main) by my self without any sample.

**Comment by StefMa** [comment]
You know that by reading the documentation 😉
As you see in this docu (
https://docs.gradle.org/current/userguide/distribution_plugin.html):
> The plugin adds an extension named “distributions” of type
DistributionContainer
<https://docs.gradle.org/current/dsl/org.gradle.api.distribution.DistributionContainer.html>
to
the project.

If you follow the DistributionContainer link you got redirected to this
site:
https://docs.gradle.org/current/dsl/org.gradle.api.distribution.DistributionContainer.html

And there stands "everything" what is possible with the extension.

**Comment by alexandrenavarro** [comment]
Thanks for the different answers, I understand better now, and sorry I'm a newbie in gradle, I want to migrate from maven to gradle kotlin-dsl.

**Comment by bamboo** [comment]
Nothing to be sorry for, @alexandrenavarro. Documentation is lacking at this point but we're working on it. Please keep the feedback coming!

**Comment by alexandrenavarro** [comment]
I think it should be very useful to have at least for official gradle plugins document snippet in groovy-dsl but also in kotlin-dsl.

**Comment by eskatos** [comment]
Closing as superseded by #813
