### ISSUE TITLE
Project schema entries type should take part in script compilation cache keys

### ISSUE THREAD

**Issue by eskatos** [gradle/kotlin-dsl#854]
Let's say you apply the `build-scan` plugin from some init script.
You'll then get a `buildScan {}` accessor, typed `Any` because the plugin classes are inaccessible (see https://github.com/gradle/gradle/issues/4078).
Then, remove the init script and add the `build-scan` plugin directly to your build script `plugins {}` block.
Run the build again, now the `buildScan {}` accessor should be properly typed, but it still is typed `Any`.

If you kill the daemon (in-memory cache) and remove the on-disk caches, then the accessor gets generated correctly.

Scripts and accessors cache keys don't take the init scripts classloader into account.
But, init scripts can influence the set of applied plugins and their "accessibility", hence influence the set of generated accessors.

This can lead to situations where accessors aren't re-generated despite the accessibility of plugin types having changed.

**Comment by bamboo** [comment]
Maybe the`Class<*>` of every extension/convention should be part of the cache key?

**Comment by oehme** [comment]
I think instead we should ignore any classes coming from classloaders outside the project's hierarchy. I.e. the buildscan extension should not be there at all, because for all intents and purposes it is not configurable by the build script.

**Comment by melix** [comment]
I agree it's probably better to ignore types from init scripts: by definition they are not shared, so I would understand that you don't get accessors from plugins applied in an init script.

**Comment by eskatos** [comment]
This was the same as #844, fixed in  eb05db1.
