### ISSUE TITLE
TestKit: Custom Plugin imports unresolved in `build.gradle.kts` scripts

### ISSUE THREAD

**Issue by Mauin** [gradle/kotlin-dsl#862]
While trying to write tests for a custom Gradle Plugin I ran into the issue that importing classes from said Gradle Plugin does not seem to be possible when defining a `build.gradle.kts` file. The same does work without issue when testing `build.gradle` files. When defining the same `build.gradle.kts` (not in a test) with the same import it will work just fine for regular builds.

### Expected Behavior
Tests should be able to resolve imports in `build.gradle.kts` files.

### Current Behavior
Imports for custom plugin classes in `build.gradle.kts` files cannot be resolved.

### Context
I am trying to test the Kotlin DSL integration of a custom Gradle Plugin. Testing the DSL from a `build.gradle` file in Groovy works fine. But importing extension functions or classes of the Plugin in the `build.gradle.kts` file does not work and marks the import as an `Unresolved reference`.

### Steps to Reproduce (for bugs)
See the following test class: https://github.com/Mauin/detekt/blob/mr/gradle_testkit_issue/detekt-gradle-plugin/src/test/kotlin/io/gitlab/arturbosch/detekt/KotlinPluginTest.kt

Running the test via `./gradlew :detekt-gradle-plugin:test` will result in the `KotlinPluginTest` failing.
It reports 

```
FAILURE: Build failed with an exception.
│
│                 * Where:
│                 Build file '/private/var/folders/m0/d3jp10jx3nj99jq5r5xdzjfh0000gp/T/applyPlugin2915895765937588209.tmp/build.gradle.kts' line: 1
│
│                 * What went wrong:
│                 Script compilation errors:
│
│                   Line 01: import io.gitlab.arturbosch.detekt.detekt
│                                   ^ Unresolved reference: io
│
│                   Line 14:      toolVersion = "1.0.0.RC6-MARVIN2"
│                             ^ Unresolved reference: toolVersion
│
│                 2 errors
│
│                 * Try:
│                 Run with --debug option to get more log output. Run with --scan to get full insights.
│
│                 * Exception is:
│                 ScriptCompilationException(errors=[ScriptCompilationError(message=Unresolved reference: io, location=/private/var/folders/m0/d3jp10jx3nj99jq5r5xdzjfh0000gp/T/.gradle-test-kit-marvinramin/caches/4.7/gradle-kotlin-dsl/e22d2lfbtp2ucnnng6l3us1pk/build.gradle.kts (1:8)), ScriptCompilationError(message=Unresolved reference: toolVersion, location=/private/var/folders/m0/d3jp10jx3nj99jq5r5xdzjfh0000gp/T/.gradle-test-kit-marvinramin/caches/4.7/gradle-kotlin-dsl/e22d2lfbtp2ucnnng6l3us1pk/build.gradle.kts (14:2))])
```

Running the following Test: https://github.com/Mauin/detekt/blob/mr/gradle_testkit_issue/detekt-gradle-plugin/src/test/kotlin/io/gitlab/arturbosch/detekt/GroovyPluginTest.kt doesn't show any issues with importing classes from the plugin (it currently fails for other reasons).

### Your Environment
```
nfrastructure
Operating system	Mac OS X 10.12.6
CPU cores	8 cores
Max Gradle workers	8 workers
Java runtime	Oracle Java(TM) SE Runtime Environment 1.8.0_171-b11
Java VM	Oracle Java HotSpot(TM) 64-Bit Server VM 25.171-b11 (mixed mode)
Max JVM memory heap size	4294 MB
```

**Comment by StefMa** [comment]
Sounds for me similar to https://github.com/gradle/kotlin-dsl/issues/492

Maybe give https://github.com/gradle/kotlin-dsl/issues/492#issuecomment-386826527 this a try?

**Comment by Mauin** [comment]
@StefMa is correct. Using the snapshot build from https://github.com/gradle/kotlin-dsl/issues/492#issuecomment-386826527 fixes this and lets the tests run correctly. 

Didn't make that connection, sorry for the noise. I'll wait for the next Gradle release to proceed with the Tests.
