### ISSUE TITLE
Make the Kotlin DSL extensions API jar unique per source classpath

### ISSUE THREAD

**Issue by bamboo** [gradle/kotlin-dsl#868]
So Gradle integration tests that use the Kotlin DSL don't have to `requireOwnGradleUserHomeDir()`.

> We can (and should) simply include the hash of the classpath from which the jar was generated in the name of the generated jar

**Comment by JLLeitschuh** [comment]
Is this something that would impact plugin developers or just the integration tests for this project?

**Comment by eskatos** [comment]
@JLLeitschuh it's specific to integration tests in `gradle/gradle`

**Comment by bamboo** [comment]
No longer needed after gradle/gradle@9bf5f294294b576b293cf0a01eed5026afb0ba3f.
