### ISSUE TITLE
Support test block alias for val test by tasks.getting(Test::class)

### ISSUE THREAD

**Issue by sdeleuze** [gradle/kotlin-dsl#872]
Currently we need to write the following non-obvious code to enable JUnit 5 support:
```
val test by tasks.getting(Test::class) {
	useJUnitPlatform()
}
```
It would be much easier and consistent with Gradle Groovy DSL to be able to write:
```
test {
	useJUnitPlatform()
}
```

**Comment by eskatos** [comment]
With #873 it'll be possible to express the same as:
```kotlin
tasks.getByName<Test>("test") {
    useJUnitPlatform()
}
```
for cases where you don't need to bring the `test` val in scope for later reference.

You may also consider configuring all `Test` tasks instead of just the `"test"` task:
```kotlin
tasks.withType<Test> {
    useJUnitPlatform()
}
```

**Comment by bamboo** [comment]
Superseded by #879.
