### ISSUE TITLE
KT-24588 - Multiple Gradle Kotlin DSL script files dependencies lifecycle is flawed

### ISSUE THREAD

**Issue by eskatos** [gradle/kotlin-dsl#895]
See https://youtrack.jetbrains.com/issue/KT-24588

**Comment by JLLeitschuh** [comment]
This could have serious impacts on people who are switching git branches and have different code per-branch.

**Comment by eskatos** [comment]
@JLLeitschuh, mind commenting on the upstream issue?

**Comment by JLLeitschuh** [comment]
Done

**Comment by eskatos** [comment]
Works fine with `gradle/kotlin-dsl` `develop` branch and 1.2.6-eap-75
