### ISSUE TITLE
Substituting a dependency module with a compatible replacement

### ISSUE THREAD

**Issue by rahulkhimasia** [gradle/kotlin-dsl#898]
In Gradle Groovy DSL you can easily [substitute a dependency module with a compatible replacement](https://docs.gradle.org/current/userguide/customizing_dependency_resolution_behavior.html#sec:module_substitution) as explained in the Gradle user manual. How do you do the same in Gradle Kotlin DSL? I did go thru all the sample scripts, but did not find any thing helpful.

**Comment by eskatos** [comment]
@rahulkhimasia no sample yet for this, in the meantime the following should do, it's a translation of the sample you linked:
```kotlin
configurations.all {
    resolutionStrategy.eachDependency {
        if (requested.name == "groovy-all") {
            useTarget("${requested.group}:groovy:${requested.version}")
            because("prefer 'groovy' over 'groovy-all'")
        }
        if (requested.name == "log4j") {
            useTarget("org.slf4j:log4j-over-slf4j:1.7.10")
            because("prefer 'log4j-over-slf4j' 1.7.10 over any version of 'log4j'")
        }
    }
}
```

HTH
