### ISSUE TITLE
KotlinLexerException on Windows

### ISSUE THREAD

**Issue by blindpirate** [gradle/kotlin-dsl#900]
Recently I encountered an issue with `gradle/gradle` repository on my local Windows VM. Whatever build I was trying to run, I got the following error:

![image](https://user-images.githubusercontent.com/12689835/40534114-7e12dad6-6037-11e8-9aa8-ff89267bd36b.png)

At last, it would fail with:

![image](https://user-images.githubusercontent.com/12689835/40534647-506420c0-6039-11e8-824a-4b75f40e24c7.png)

I thought it was a cache issue, so I deleted my `~/.gradle` and cloned a clean `gradle/gradle` repository and this issue still occurs.

I also tried to change my system locale to `en_US` but still no luck.

Here's my locale and line sepearator:

![image](https://user-images.githubusercontent.com/12689835/40534134-96c29a76-6037-11e8-8617-d47632ae34d5.png)

![image](https://user-images.githubusercontent.com/12689835/40534149-a03481b4-6037-11e8-8613-175390658280.png)

OS: Windows 7
JVM: JDK 1.8.0_121

P.S. sorry for the images.

**Comment by bamboo** [comment]
Thanks for the report, @blindpirate. Can you reproduce it on the latest Gradle master?

**Comment by blindpirate** [comment]
After running `git bisect` on `gradle/gradle`, I found this commit is the first bad commit:

https://github.com/gradle/gradle/commit/bc90b90

![image](https://user-images.githubusercontent.com/12689835/40572043-a2ed43de-60d5-11e8-9c1d-2f28e99766f4.png)

**Comment by nskvortsov** [comment]
Same issue here. 
output of same script is

    ru_RU
    13
    10

and git newline is set as follows:

    >git config --global core.autocrlf
    true

**Comment by nskvortsov** [comment]
works if `kotlin-dsl`  is updated to "0.18.0"  in `buildSrc\build.gradle.kts:32` (thanks to @eskatos )

**Comment by eskatos** [comment]
Thank you for testing and confirming the fix @nskvortsov!

**Comment by eskatos** [comment]
The `gradle/gradle` build was still using 0.17.2, fix in https://github.com/gradle/gradle/pull/5670

After more scrutiny, it is the same as #858 that was fixed in 0.17.5 in 88d3836b2963bb38448e2c1046f2acf97848454d

Closing as fixed
