### ISSUE TITLE
Kotlin DSL sugar uses the lazy configuration APIs

### ISSUE THREAD

**Issue by eskatos** [gradle/kotlin-dsl#917]
This epic is about changing the Kotlin DSL sugar to use the Gradle API for lazy configuration of container elements.

**Comment by SUPERCILEX** [comment]
These APIs will use `register` for 1.0, right? https://github.com/gradle/kotlin-dsl/blob/0eccacca4c9f87be19dd88045c2007ae3ee58f2f/subprojects/provider/src/main/kotlin/org/gradle/kotlin/dsl/ProjectExtensions.kt#L118-L150

**Comment by eskatos** [comment]
@SUPERCILEX nope, these simply map methods from the Gradle API, the behavior will stay the same as the underlying API to prevent any confusion.

**Comment by SUPERCILEX** [comment]
Aw, dang! 😊 So what's this issue about? And will the be a sexier way to lazily create tasks? (Currently having to use `tasks.register<Type>(name) { doStuff }`. I mean, TBH it's not that bad, but I don't get what this issue would be about then.)

**Comment by eskatos** [comment]
It is mostly about delegated properties #918 and string invoke #907.

This issue is a Zenhub Epic. If you install the Zenhub Chrome extension you'll see the attached issues.

**Comment by SUPERCILEX** [comment]
@eskatos Gotya, thanks for the hints here and in the Android issue. ❤️
