### ISSUE TITLE
gradle/kotlin-dsl and gradle/gradle should use the same branching scheme

### ISSUE THREAD

**Issue by adammurdoch** [gradle/kotlin-dsl#921]
Using different approaches and conventions for a common problem in each of our repositories means extra friction for developers moving between these repositories, particularly on the first use of a given repo. It also means more cost in whatever automation we use as this automation has to account for these differences. And so, the differences have to be justified by some strong benefit that outweighs the costs. I can't see any real benefit in this case (branching scheme) so we should get rid of the differences.

### Expected Behavior

`gradle/gradle` and `gradle/kotlin-dsl` (and `gradle/gradle-native` and the guides infrastructure and ...) all use the same branching scheme. I don't particularly care which scheme that happens to be, but I do care that it's the same everywhere.

### Current Behavior

Branching schemes are different.

**Comment by JLLeitschuh** [comment]
This should also be documented if us outside the company want to contribute something and it needs to span 2 repositories.

**Comment by eskatos** [comment]
Superseded by #1232
