### ISSUE TITLE
Import java.net.URI in buildscript block - need to use fully qualified name?

### ISSUE THREAD

**Issue by DavidMihola** [gradle/kotlin-dsl#925]
Just a quick question- this is my (top-level) build.gradle:

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.
import java.net.URI

buildscript {
    repositories {
        maven { url = java.net.URI("https://maven.fabric.io/public") } // 1
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.1.3")
        classpath(kotlin("gradle-plugin", version = "1.2.41"))

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        maven { url = URI("https://maven.fabric.io/public") } // 2
        google()
        jcenter()
    }
}

task<Delete>("clean") {
    delete(rootProject.buildDir)
}
```

And my only question is: Why do I need to use the fully qualified name `java.net.URI` in the line marked `1`, while I don't have to in the line marked `2`?

**Comment by bamboo** [comment]
Hi @DavidMihola,

The function `uri(uri: String): java.net.URI` is available within the `buildscript` block and the script body for that purpose:

```kotlin
     maven { url = uri("https://maven.fabric.io/public") }
```

There's also a `maven(url: String)` overload you might want to use:

```kotlin
     maven(url = "https://maven.fabric.io/public")
```

Does that help?

**Comment by bamboo** [comment]
> Is there an easy explanation as to why the buildscript block works differently in this regard than, say, the allprojects block? Is it resolved before the import statements at the top are applied?

Yes, the optional `plugins` block together with the optional `buildscript` block are evaluated first and separately from the rest of the script.

**Comment by bamboo** [comment]
Closing as answered.

**Comment by DavidMihola** [comment]
Thanks a lot - this explains everything!

**Comment by sabberworm** [comment]
> Thanks a lot - this explains everything!

Doesn’t explain why kotlin doesn’t fall back on the `void setUrl(Object var1);` overload when a `url = somestring` is used…
