### ISSUE TITLE
Provide a task<FooTask> {} utility function by default

### ISSUE THREAD

**Issue by sdeleuze** [gradle/kotlin-dsl#930]
Could it be possible to bundle  `inline fun <reified T : Task> task(noinline configuration: T.() -> Unit) = tasks.creating(T::class, configuration)` by default? (from https://github.com/gradle/kotlin-dsl/blob/master/build.gradle.kts#L149 and found in various projects since it is super useful)

**Comment by eskatos** [comment]
It's a nice shortcut but we don't want to add another way to create tasks.
Closing as won't fix
Also see https://github.com/gradle/kotlin-dsl/issues/605
