### ISSUE TITLE
Incorrect dependency version with Configuration.copyRecursive()

### ISSUE THREAD

**Issue by ben-manes** [gradle/kotlin-dsl#934]
Investigating https://github.com/ben-manes/gradle-versions-plugin/issues/244 showed that the behavior of dependency resolution behaves oddly when the Kotlin plugin is applied. In the plugin, I can get the correct result when not touching the transitive setting. When trying to isolate it into a reproducible bug, I instead see `copyRecursive()` return different results.

The expected behavior is that the kotlin version is applied to `kotlin-stdlib-jdk8` automagically. However, the version resolved may be either the plugin's or transitively from the dependency's. It seems that copying a configuration breaks an internal assumption and the incorrect version is resolved. 

```gradle
plugins {
  id 'org.jetbrains.kotlin.jvm' version '1.2.50'
}

repositories {
  jcenter()
}

dependencies {
  compile "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
  compile "com.serebit:loggerkt:0.2.0"
}

task printVersions() {
  doLast {
    def config = configurations.compile
    def copy = config.copyRecursive()
    config.resolvedConfiguration.firstLevelModuleDependencies.each { println "${config.name}: $it" }
    copy.resolvedConfiguration.firstLevelModuleDependencies.each { println "copy: $it" }
  }
}
```

```
$ gradle printVersions

> Task :printVersions
compile: org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.2.50;runtime
compile: com.serebit:loggerkt:0.2.0;runtime
copy: com.serebit:loggerkt:0.2.0;runtime
copy: org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.2.21;runtime
```

**Comment by eskatos** [comment]
It is expected that `configuration.copyRecursive()` doesn't copy over resolution rules. One should instead create a new configuration that `.extendsFrom()` the other configuration.

If you think this behavior should be changed, please open an issue on `gradle/gradle`.

**Comment by ben-manes** [comment]
Except Gradle’s DefaultConfiguration works exactly as I said and kotlin dsl behaves differently. I see nothing in the documentation to support your claim.

https://github.com/gradle/gradle/blob/929a2663e16343ecf0f38ac559c69a8028228f27/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfiguration.java#L928

**Comment by eskatos** [comment]
Taking another look 👀 

The snippet in the issue, using a Groovy script, fails to resolve dependencies 
https://scans.gradle.com/s/vjpsyapxhf3ow

It seems the `loggerkt` artifacts got removed ...

I replaced it with some other dependency for the example:
```groovy
// build.gradle
plugins {
    id("org.jetbrains.kotlin.jvm") version "1.2.50"
}

repositories {
    jcenter()
}

dependencies {
    compile("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    compile("org.apache.commons:commons-math:2.2")
}

task printVersions() {
    doLast {
        def config = configurations.compile
        def copy = config.copyRecursive()
        config.resolvedConfiguration.firstLevelModuleDependencies.--
each { println("${config.name}: $it") }
        copy.resolvedConfiguration.firstLevelModuleDependencies.each { println("copy: $it") }
    }
}
```

Success
https://scans.gradle.com/s/ddoappaucwnfc/console-log?task=:printVersions

```
:printVersions
compile: org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.2.50;runtime
compile: org.apache.commons:commons-math:2.2;runtime
copy: org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.2.50;runtime
copy: org.apache.commons:commons-math:2.2;runtime
```

Then, using a Kotlin script:
```kotlin
// build.gradle.kts
plugins {
    id("org.jetbrains.kotlin.jvm") version "1.2.50"
}

repositories {
    jcenter()
}

dependencies {
    compile("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    compile("org.apache.commons:commons-math:2.2")
}

task("printVersions") {
    doLast {
        val config = configurations.compile.get()
        val copy = config.copyRecursive()
        config.resolvedConfiguration.firstLevelModuleDependencies.forEach { 
println("${confi--
g.name}: $it") }
        copy.resolvedConfiguration.firstLevelModuleDependencies.forEach { println("copy: $it") }
    }
}
```

Same behavior as I expected
https://scans.gradle.com/s/r6fdrfwtaxfrm/console-log?task=:printVersions

```
:printVersions
compile: org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.2.50;runtime
compile: org.apache.commons:commons-math:2.2;runtime
copy: org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.2.50;runtime
copy: org.apache.commons:commons-math:2.2;runtime
```

There must be something else going on on your end.
