### ISSUE TITLE
Native binaries build support?

### ISSUE THREAD

**Issue by crashtua** [gradle/kotlin-dsl#935]
Does kotlin-dsl supports 'cpp' plugin? Like in this tutorial - https://guides.gradle.org/building-cpp-libraries/ ?
I am unable to find a way of defining NativeLibrarySpec.
Thanks in advance.

**Comment by eskatos** [comment]
Hi @crashtua,

The DSL of the [discontinued Gradle Software Model](https://blog.gradle.org/state-and-future-of-the-gradle-software-model) is not supported in Gradle Kotlin DSL scripts.
However, declaring and using a `RuleSource` is supported, see the [model-rules](https://github.com/gradle/kotlin-dsl/tree/master/samples/model-rules) sample that demonstrates how to write rules in Kotlin and how to use them from a Gradle Kotlin DSL script.

The [new native plugins](https://blog.gradle.org/introducing-the-new-cpp-plugins) that don't rely on the software model should work out of the box.

**Comment by eskatos** [comment]
Closing as answered
