### ISSUE TITLE
Provide a way to configure the Kotlin build script compiler so as to allow using the 1.3.x compiler with libraries compiled by the 1.2.x compiler

### ISSUE THREAD

**Issue by bamboo** [gradle/kotlin-dsl#938]
There is a problem with using the 1.3 milestone builds of the Kotlin Gradle plugins with current gradle versions. There are special checks in the compiler that generate the following error during buildscript compilation:

>`org.jetbrains.kotlin.gradle.tasks.KotlinCompile`is compiled by a pre-release version of Kotlin and cannot be loaded by this version of the compiler

To overcome this we need to be able to pass an option to the compiler that compiles buildscripts: `-Xskip-metadata-version-check` in this case.

**Comment by eskatos** [comment]
Superseded by using Kotlin 1.3
