### ISSUE TITLE
Make changes in release notes linkable

### ISSUE THREAD

**Issue by pledbrook** [gradle/kotlin-dsl#941]
Please make it possible to link directly to individual changes listed in your release notes. To understand why, see [this section](https://docs.gradle.org/4.8/release-notes.html#changes-to-the-gradle-kotlin-dsl) of the Gradle 4.8 release notes, which direct the reader to the Kotlin DSL release notes. The link in that section is virtually useless as it doesn't even go to the right release version! Even then, there appears to be no way to take the user directly to the relevant section of the correct release notes.

**Comment by eskatos** [comment]
Subsequent release notes got linkable breaking changes section, e.g. https://github.com/gradle/kotlin-dsl/releases/tag/v1.0-RC14#breaking-changes
For future releases, this will be superseded by #1232, closing
