### ISSUE TITLE
kotlin-dsl plugin forces configuration of tasks unnecessarily in afterEvaluate

### ISSUE THREAD

**Issue by ldaley** [gradle/kotlin-dsl#943]
You can see the effect of this here: https://e.grdev.net/s/4k4trfgvt2tda/performance/configuration?focused=185&openScriptsAndPlugins=WzEwXQ

I know it's this plugin because this went away for us after making this change: https://github.com/gradle/dotcom/commit/a524a2fdbb94ba5ba62d91fb0d2d3460c2c566fe

I had a quick look at the source and could not see why this was happening.

**Comment by JLLeitschuh** [comment]
This link is broken:
https://github.com/gradle/dotcom/commit/a524a2fdbb94ba5ba62d91fb0d2d3460c2c566fe

**Comment by ldaley** [comment]
Here's a screenshot of what is pertinent:

![image](https://user-images.githubusercontent.com/17825/42017677-3b8ae20e-7af3-11e8-99fc-8227e54b4333.png)

**Comment by eskatos** [comment]
There's no task creation nor `afterEvaluate` hook usage in this plugin.
However, this plugin applies the Kotlin Gradle Plugin which is most probably the offender.

**Comment by ldaley** [comment]
That would explain why I couldn't find it in the kotlin-dsl code.

Unfortunately, scans don't yet associate `afterEvaluate` to the callback owner so scans don't reveal that. My only data point is that not applying the plugin avoids the tasks being created.

**Comment by eskatos** [comment]
Makes sense. Once Gradle 4.9 is out we can open an issue upstream pushing for the Kotlin Gradle Plugin to leverage lazy task configuration.

**Comment by ldaley** [comment]
Would also be good to audit there use of afterEvaluate generally and see if it can be avoided if we can manage it.

**Comment by eskatos** [comment]
We recently introduced a forced realization of `KotlinCompile` tasks in the `kotlin-dsl` plugin in 0b374f297ae9d3c13cf25962168a5d0ef143a20c. Fixed by 89a81e7

**Comment by eskatos** [comment]
Closing as superseded by https://github.com/gradle/gradle-native/issues/732
