### ISSUE TITLE
org.jetbrains.kotlin.lexer.KotlinLexerException: Error: could not match input

### ISSUE THREAD

**Issue by zosrothko** [gradle/kotlin-dsl#945]
On branch v4.8.1 of the gradle project, running: `gradlew eclipse` is production this `KotlinLexerException` on some files. See the build.log attached?

### Expected Behavior
No exception

### Current Behavior
Self Identified Issue

### Context
Windows 10, git **core.autocrlr = true**
C:\Users\fandre\Documents\git\gradle-4.8.1>gradlew -version

------------------------------------------------------------
Gradle 4.8-rc-3
------------------------------------------------------------

Build time:   2018-05-31 14:04:36 UTC
Revision:     9803e11cf1218511e0fd1595bdc66e0a6210a0b6

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_141 (Oracle Corporation 25.141-b15)
OS:           Windows 10 10.0 amd64

C:\Users\fandre\Documents\git\gradle-4.8.1>git config --global -l
user.name=Francis ANDRE
user.email=francis.andre.kampbell@orange.fr
core.autocrlf=true
credential.helper=manager

### Steps to Reproduce (for bugs)
On a Windows system
1. git config --global core.autocrlf true
2. git clone -b v4.8.1 git@github.com:gradle/gradle.git gradle-4.8.1
3. cd gradle-4.8.1
4. gradlew eclipse

### Your Environment
Please notice that replacing all `CRLF` by `LF` on `*.kt` and `*.kts` avoids all the execptions

 * Build scan URL:

**Comment by zosrothko** [comment]
[build.log](https://github.com/gradle/kotlin-dsl/files/2153809/build.log)

**Comment by eskatos** [comment]
Hi @zosrothko,

You are hitting #858 that was fixed in `kotlin-dsl` 0.17.5. The wrapper version present at the `v4.8.1` tag in `gradle/gradle` repository is `4.8-rc-3` which include the fix to #858. But the `gradle/gradle` build was still using 0.17.2, fixed in gradle/gradle#5670 after 4.8.1. The `v4.9` tag should be buildable on Windows.
