### ISSUE TITLE
Unused method 

### ISSUE THREAD

**Issue by AregevDev** [gradle/kotlin-dsl#948]
When creating a function in build.gradle.kts file and not using it, it does not put the "unused method" markdown

**Comment by StefMa** [comment]
I think that is a Kotlin, Kotlin Plugin or IDE issue 🤔

May be better to report there.

**Comment by eskatos** [comment]
Top level members of scripts are not subject to the "unused member" IntelliJ suggestion.
Please report a bug on https://youtrack.jetbrains.com/ if you thing this should be changed.
