### ISSUE TITLE
Can't use kotlin java8 inline-only methods

### ISSUE THREAD

**Issue by Barteks2x** [gradle/kotlin-dsl#955]
When trying to use inlineonly java8 kotlin methods, it fails to compile with the following error:
```
 Cannot inline bytecode built with JVM target 1.8 into bytecode that is being built with JVM target 1.6. Please specify proper '-jvm-target' option
```
Example of such method is `Map.getOrDefault`.

### Expected Behavior
The code using inlineonly java 8 methods should compile and run

### Current Behavior
It fails to compile

### Context
I was trying to use `project.properties.getOrDefault` instead of explicit if..else to make the code less verbose, but that doesn't seem to be possible.

### Steps to Reproduce (for bugs)
include `project.properties.getOrDefault("something", "default")` somewhere in the buildscript.

**Comment by bamboo** [comment]
Fixed in 1e739759a7449e239f1f4b048f1cbc1f23d8d393.

Thanks for the report!
