### ISSUE TITLE
Soften `SamConversionForKotlinFunctions` warning, provide a way to opt-out and silence the warning

### ISSUE THREAD

**Issue by eskatos** [gradle/kotlin-dsl#971]
### Current Behavior (`develop` only)

Since #957 and #960, applying the `kotlin-dsl` plugin and running `KotlinCompile` tasks outputs the following warning on the console:

```
w: ATTENTION!
This build uses internal compiler arguments:

-XXLanguage:+NewInference
-XXLanguage:+SamConversionForKotlinFunctions

This mode is strictly prohibited for production use,
as no stability/compatibility guarantees are given on
compiler or generated code. Use it at your own risk!
```

### Context

These Kotlin compiler features are required to fix #522 and enable #221.

### Expected Behavior

- [x] enable `-Xprogressive`, `-XXLanguage:+NewInference` and `-XXLanguage:+SamConversionForKotlinFunctions` by default
- [x] translate the related `w: ATTENTION!` message to be clearer about the implications for `kotlin-dsl` users
- [x] describe and implement opt-out and warning silencing

Warning proposal (to be completed/refined):
```
WARNING
The `kotlin-dsl` plugin relies on Kotlin compiler's progressive mode and experimental features to enable among other things SAM conversion for Kotlin functions.

Once built and published, artifacts produced by this project will continue to work on future Gradle versions.
However, you may have to fix the sources of this project after upgrading the Gradle wrapper of this build.

To silence this warning add the following to this project's build script:

    kotlinDslPluginOptions.progressive.set(true)

To disable Gradle Kotlin DSL progressive mode and give up SAM conversion for Kotlin functions add the following to this project's build script:

    kotlinDslPluginOptions.progressive.set(false)

See the `progressive` property documentation for more information.
```

**Comment by JLLeitschuh** [comment]
I suspected that this would start happening with these new flags

A few things:
1. Won't IntelliJ also give this warning to users? What is the mitigation for that?
2. Why is this in the project's build script? Wouldn't `settings.gradle.kts` be more relevant? Or perhaps a `gradle.properties` flag?

**Comment by eskatos** [comment]
1. Good question. IntelliJ respects the configured compiler arguments and warn always when building with JPS and respect `kotlinDslPluginOptions.progressive` when delegating to Gradle.
2. The option is for the `kotlin-dsl` plugin applied to a project and impact the compilation of the project sources.

**Comment by eskatos** [comment]
Closing as delivered
