### ISSUE TITLE
android-kotlin-extensions does not compile in multi-module Gradle project after migrating to KTS while using ViewBinding

### ISSUE THREAD

**Issue by dudududi** [gradle/kotlin-dsl#974]
After migrating from Groovy Gradle scirpts to KTS, multi-module project is failing to compile, saying that it is unable to resolve references generated by ViewBinding.

Project is multi-module, so its structure is a bit different that standard Android project - it co-resides with another non-Android modules. Whats more interesting, Android Studio is not highlighting any errors - everything looks and works as usual (code completion, linking)

### Expected Behavior
Project should compile without any errors after migrating to KTS from Groovy.

### Current Behavior
Project compilation is failing with following error:
> e: kts-nested-android/nested/core-lib/src/main/java/com/kts/android/test/corelib/LibActivity.kt: (5, 8): Unresolved reference: kotlinx
e: kts-nested-android/nested/core-lib/src/main/java/com/kts/android/test/corelib/LibActivity.kt: (12, 9): Unresolved reference: myTestTextView
> Task :nested:core-lib:compileDebugKotlin FAILED
FAILURE: Build failed with an exception.

### Context
In our project, we would like to move entirely to kotlin-dsl syntax from Groovy. The project is held as one multi-platform project (with separate modules for iOS, Android, JS and JVM) and almost all modules are already migrated to KTS - only Android module is still written Groovy because of above-mentioned compilation error. When we will remove usage of ViewBinding from the project, everything compiles perfectly. It does not matter where the `kotlin-android-extenstions` plugin was used: in such project it is failing in both android-library and android-application modules.

### Steps to Reproduce
- clone the repo which imitates multi-module Gradle project: [kts-nested-android](https://github.com/dudududi/kts-nested-android)
- import it to AndroidStudio 3.2-beta4 by pointing to root build.gradle.kts- notice that it will import without any errors
- run _./gradlew nested:assemble_ or try to run the app from IDE to see compilation errors.

**Comment by JLLeitschuh** [comment]
Using the `--stacktrace` flag might give you more insights into your issue.

**Comment by eskatos** [comment]
The build scripts do compile, the compilation failure is from your production code. It must be a missing dependency or something along those lines.

I see that your module `:nested:core-lib` applies the `kotlin-android-extensions` plugin, so, according to its documentation the dependency should be present.

**Comment by ppamorim** [comment]
is there any way to suppress this?
