### ISSUE TITLE
Adding suggested config about progressive compiler mode results in error

### ISSUE THREAD

**Issue by tomdcc** [gradle/kotlin-dsl#984]
On using a gradle build branched from master recently, I got this warning:

```
WARNING
The `kotlin-dsl` plugin relies on Kotlin compiler's progressive mode and experimental features to enable among other things SAM conversion for Kotlin functions.

Once built and published, artifacts produced by this project will continue to work on future Gradle versions.
However, you may have to fix the sources of this project after upgrading the Gradle wrapper of this build.

To silence this warning add the following to this project's build script:

    kotlinDslPluginOptions.progressive.set(ProgressiveModeState.ENABLED)

To disable Gradle Kotlin DSL progressive mode and give up SAM conversion for Kotlin functions add the following to this project's build script:

    kotlinDslPluginOptions.progressive.set(ProgressiveModeState.DISABLED)

See the `progressive` property documentation for more information.
```

But adding either of those lines gave me this:

```
Script compilation errors:

  Line 8: kotlinDslPluginOptions.progressive.set(ProgressiveModeState.DISABLED)
                                             ^ Overload resolution ambiguity: 
                                                 public abstract fun set(p0: Provider<out ProgressiveModeState!>!): Unit defined in org.gradle.api.provider.Property
                                                 public abstract fun set(@Nullable p0: ProgressiveModeState?): Unit defined in org.gradle.api.provider.Property

  Line 8: kotlinDslPluginOptions.progressive.set(ProgressiveModeState.DISABLED)
                                                 ^ Unresolved reference: ProgressiveModeState

```

Basically ProgressiveModeState is not visible without an import, but it's not clear what the import should be. At this point, I also couldn't get the IDE to tell me what the package for the class was, as the gradle build script was broken. I had to comment it out, import into the IDE, then add it. 

### Expected Behavior
Provided import snippet should have a fully-qualified path or an import statement, or the class in question should be imported automatically, either by moving it into `org.gradle.kotlin.dsl`, or automatically importing it from somewhere else.

### Current Behavior
Cut'n'pasting the snippet results in a compiler error.

### Context
Using Kotlin-DSL in our buildSrc project.

### Steps to Reproduce (for bugs)
This was made worse due to me adding the line before successfully importing the model into the IDE. If I had already done that, I presume that the IDE would have been able to automatically find the class for me.

**Comment by eskatos** [comment]
Thank you @tomdcc, fixed with #985
