### ISSUE TITLE
forkEvery in tests is not working

### ISSUE THREAD

**Issue by otros-systems** [gradle/kotlin-dsl#995]
I'm trying to fork JVM in test for every test.

### Expected Behavior

I have configured test task in following way
```
tasks {
    "test"(Test::class) {
        useTestNG {
            maxHeapSize = "200m"
            testLogging { showStandardStreams = true }
            setForkEvery(1)
            addTestListener(utils.MyTestListener())
        }
    }
}
```

Test listener:
```
public class MyTestListener implements TestListener {
  static AtomicInteger atomicInteger = new AtomicInteger();
  @Override
  public void beforeTest(TestDescriptor testDescriptor) {
    System.out.println(testDescriptor.getName()+ " " + atomicInteger.incrementAndGet());
  }
///....
}
```

### Current Behavior

All tests are run in single JVM. I expected. As result of my test I have:
```
> Task :bluewhale:test
shouldTest2_1 1
....
shouldTest2_2 2
....
shouldTest1_1 3
....
shouldTest1_2 4
....
```

If every test would be run in separate JVM I would have:

```
> Task :bluewhale:test
shouldTest2_1 1
....
shouldTest2_2 1
....
shouldTest1_1 1
....
shouldTest1_2 1
....
```

### Context

I'm trying to validate if I can migrate my project from groovy to kotlin-dsl. This feature is required for scenario test. I have to restart application for every test to get a clean state.

### Steps to Reproduce (for bugs)

Try to set ` setForkEvery(1)` and check if JVM was forked for evert test.

### Your Environment

 * Build scan URL:

**Comment by eskatos** [comment]
Hi @otros-systems,

`forkEvery` is about "test classes" not individual tests
See the [`forkEvery` documentation](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.testing.Test.html#org.gradle.api.tasks.testing.Test:forkEvery).

The Gradle forums at https://discuss.gradle.org/ are a better fit for usage questions.

Closing as answered
