### ISSUE TITLE
Circular dependency error with kotlin plugin when using several modules with same name

### ISSUE THREAD

**Issue by xhanin** [gradle/kotlin-dsl#999]
In a multi project build with a deep structure where several projects have the same short name (in different paths), if one kotlin project depends on another kotlin project you get a circular dependency error.

### Expected Behavior

Build should be performed without error

### Current Behavior

You get this kind of error:
```
* What went wrong:
Circular dependency between the following tasks:
:sub:core:classes
\--- :sub:core:compileJava
     +--- :sub:core:compileKotlin
     |    \--- :sub:core:jar
     |         +--- :sub:core:classes (*)
     |         \--- :sub:core:compileKotlin (*)
     \--- :sub:core:jar (*)
```

### Steps to Reproduce 

In the `samples/multi-kotlin-project` do the following:
mkdir sub
mv cli sub/core

modify settings.gradle.kts:
include("sub:core", "core")

run ./gradlew run

### Environment

 * Build scan URL: 
https://gradle.com/s/l3sdkoofvdgak

**Comment by eskatos** [comment]
Hi @xhanin,
This seems to be an issue with the `kotlin-gradle-plugin`, not with `gradle/kotlin-dsl`.
Please open an issue on the [Kotlin Issue Tracker](https://youtrack.jetbrains.com/issues/KT).

**Comment by xhanin** [comment]
Hi,

Thanks for your quick reply, I've submitted the issue here:
https://youtrack.jetbrains.com/issue/KT-25872

**Comment by h0tk3y** [comment]
@eskatos Please see the comment by our QA team under the [issue reported to the Kotlin YouTrack](https://youtrack.jetbrains.com/issue/KT-25872): we can reproduce it with pure Java as well. Should I report this issue to the core Gradle repository?

**Comment by eskatos** [comment]
@h0tk3y got it, thanks for the heads up! Yes please, this should be reported on `gradle/gradle`.
Looks like somehow the `":core"` project path in the dependency declaration present in `:sub:core` build script resolves to the `:sub:core` project instead of the expected `:core` creating the circular dependency.
